### ISSUE TITLE
[argo-cd] argo-cd-3.26.6 missing from index

### ISSUE THREAD

**Issue by hairmare** [argoproj/argo-helm#1007]
### Describe the bug

The argo-cd-3.26.6 chart from #1006 is missing from index.yaml on the GitHub page.

### Related helm chart

argo-cd

### To Reproduce

1. Download [index.yaml](https://argoproj.github.io/argo-helm/index.yaml)
2. Search for argo-cd 3.26.6 in index.yaml, no results
3. Look at [index.yaml on gh-pages branch](https://github.com/argoproj/argo-helm/blob/gh-pages/index.yaml#L1589-L1617),  argo-cd 3.26.6 is available
4. Check [github-pages environment](https://github.com/argoproj/argo-helm/deployments/activity_log?environment=github-pages), be surprised that the last update is way longer ago than the last merge to the branch

### Expected behavior

The GitHub Pages site should have been updated to publish argo-cd 3.26.6

### Additional context

Without intervention it is highly likely that this will be fixed as soon as any new chart is pushed.

**Comment by mkilchhofer** [comment]
Hi @hairmare You are right, thanks for bringing that onto the table 👍 
![image](https://user-images.githubusercontent.com/7290987/141009282-726068d6-80cd-401e-a3c0-1601b9a76273.png)
Seems like the page build is stuck: https://github.com/argoproj/argo-helm/runs/4124955162

This is something for the core Argoproj team, could you please have a look @jessesuen , @alexec  or @alexmt ?

**Comment by hairmare** [comment]
3.26.7 and 3.26.8 have been tagged and added to the index. 3.26.6 is still missing, but I think we can close this and live with the fact that 3.26.6 isn't available
