### ISSUE TITLE
[argo-cd] Support using secrets in the .Values.configs

### ISSUE THREAD

**Issue by cyrilcros** [argoproj/argo-helm#1022]
### Is your feature request related to a problem?

The current `configs:` stanza has a lot of credentials that mustn't be spread around. It would be nice to be able to add secret names instead of values.

This is a regression, for example see https://github.com/argoproj/argo-helm/blob/26d0a54345c8b80e60e63cf08dd6723b35098db5/charts/argo-cd/values.yaml#L1027

### Related helm chart

argo-cd

### Describe the solution you'd like

Restore the ability to access tokens and private keys via secrets. Notably:
 
1.  `configs.credentialTemplates`: Introduce `sshPrivateKeySecret` `githubAppPrivateKeySecret` `httpCredsSecret` opaque secrets
2.  `configs.clusterCredentials`: `bearerTokenSecret` opaque secret
3. `argocdServerTlsConfig`: use a tls secret

The `configs.secret` is not so important, you can just not set it.

### Describe alternatives you've considered

Improve documentation. For example,  it seems possbile to replace `configs.credentialTemplates` with a pre-existing secret, with the label   `argocd.argoproj.io/secret-type: repo-creds`

### Additional context

I want to keep the Argo-cd config itself in Gitops with the `sealedSecrets` Bitnami controller, to make bootstrapping clusters easy.

- a  `sealedSecret` for `argocd-secret` _and ideally I need a `my-repo-ssh-cred` secret as well_
-  `helm install argo-cd argo/argo-cd --version 3.26.9 --namespace argocd`
- Apply a beefier `argo-cd-application.yaml`  file with a `configs.repositories` and `configs.credentialTemplates` 

I can set ` configs.secret.createSecret=false` and the pre-existing secret `argocd-secret`  will be picked up, _ideally I need a `configs.credentialTemplates`  that point to `my-repo-ssh-cred` secret rather than putting a private git key in my  `argo-cd-application.yaml`_

### **EDIT: this looks possible but not clearly documented**
See:
- https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-repo-creds.yaml
- https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-repositories.yaml

You add separate SealedSecrets for repositories and credentials. They need specific labels, they get matched by the url...
Currently this is seen here: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#atomic-configuration

**Comment by LiorLieberman** [comment]
Hi guys, i am facing the same issue and did not completely understand if I have a way i can use a predefined secret without putting it in the files explicitly (like i had in `config.repositories.sshPrivateKeySecret`)
Appreciate your help

**Comment by cyrilcros** [comment]
@LiorLieberman  that's my case, note that now this uses `configs.repositories` with `s`.
In the chart (V3.26.9), I have:
```
configs: 
  repositories:
    my-repo-name:
       url: your-url
```
That creates a secret with the url, `argocd-repo-my-repo-name`, with a label `argocd.argoproj.io/secret-type: repository`. I end up with the URL in version control, but that's not so bad.
You then add the credentials directly by creating a secret (via a SealedSecret for me):

```
apiVersion: v1
kind: Secret  
type: Opaque
name: argocd-repo-creds-ssh-creds
namespace: argocd
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds 
data:
  sshPrivateKey: <your-key>
  url: <your-url>
```

**Comment by cyrilcros** [comment]
https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories ok so this is documented, but that's not been super clear

**Comment by LiorLieberman** [comment]
@cyrilcros Thank you very much for the clarification.
I still think it would be better if this can be a reference to a secret like before
One more question I still have, how is `configs.secret.createSecret` is related to this issue? As far as I see this value has a different purpose

**Comment by behniafb** [comment]
But still, we can't use secrets for other resources like "clusterCredentials"
