### ISSUE TITLE
Helm Versions

### ISSUE THREAD

**Issue by Matt-Dee** [argoproj/argo-helm#103]
**Is your feature request related to a problem? Please describe.**
Things break for our development team when helm chart version increases.

**Describe the solution you'd like**
Create multiple versions of the chart that one can choose to install.

**Describe alternatives you've considered**
Upgrading every time the helm chart version increases.

**Additional context**
We have a fairly decent sized development team and everyone has their own special snowflake environment.  Some use docker for desktop, some use micro k8s.  Whenever there is an upgrade to Argo, it's hit or miss whether the workflow engine will work for everyone on the team.  It'd be nice to downgrade and not lose velocity if the latest doesn't work.  Then upgrade when we get a chance.

**Comment by alexec** [comment]
This seems like a good idea. Need to understand how we might do this. Any suggestions?

**Comment by Matt-Dee** [comment]
Hey Alex.  Thanks for the response.  Argo is an awesome tool.  The helm install has also made my life a lot easier(and is also awesome)!

The way that we do our helm versioning on our project is that we have a separate folder for each version of our helm install.

foo-project
  v0.0.1
    Chart.yml
    configs
    templates
    values.yml
  v0.0.2
    Chart.yml
    configs
    templates
    values.yml
  latest
    Chart.yml
    configs
    templates
    values.yml
  stable
    Chart.yml
    configs
    templates
    values.yml

I don't know if this would work for you guys.  It does appear that you pull from github when your containers are spinning up.  Could you also pull from a branch in github?  Argo seems to have branches for all it's releases.

Thanks for the speedy reply,
Matt

**Comment by alexec** [comment]
Do you know how to do this? It'd be awesome if you could even just draft the changes!

**Comment by Matt-Dee** [comment]
Let me look at what you guys have going on.  Do you have a developer wiki/documentation for the project?

**Comment by jdeprin** [comment]
Perhaps I don't understand the initial requirement but why not use either `helm install --version` or semantic versioning in a requirements.yaml file (https://helm.sh/docs/chart_best_practices/#requirements-files) to pin a specific chart version?
Helm repositories already keep a version list, no need to complicate the repo with additional branches.

**Comment by jbehling** [comment]
Yeah, I don't believe any change is needed to this chart for you to pin versions (or run multiple versions). You can install different versions into different namespaces, using `--version` along with a different `--name` for each release

**Comment by jbehling** [comment]
I'm closing this as I haven't heard any follow-up from the reporter
