### ISSUE TITLE
How namespace install will work ? - Argo workflow 

### ISSUE THREAD

**Issue by tiwarisanjay** [argoproj/argo-helm#1033]
### Describe the bug

I would like to understand as there is some contradiction where argo-workflow get installed in namespaced. 
According to following documentation I should be able to mentioned number of namespace I would like to mange for namespaced : 
https://argoproj.github.io/argo-workflows/managed-namespace/
But here you are restricting the number namespace I can enabled for managed namespace : 
 [   # be created. Only valid when singleNamespace is false. ](https://github.com/argoproj/argo-helm/blob/f9b2f22203be35382219d06a0e90f148b609dc8b/charts/argo-workflows/values.yaml#L161)

If I would like to have the workflows running in a separated namespace, I will have to add --managed-namespace as well, which is not possible with current helm chart. 

### Related helm chart

argo-workflows

### To Reproduce

1. Install argo workflow by changing following 
2. workflowNamespaces:
       - workflow
 3. singleNamespace: true

This one should create a workflow-sa.yaml in workflow namespace and installed namespace but it will not. 

### Expected behavior

I would like to create service account in workflow namespace along with role and role-binding for namespace install. 
Following command should be showing for namespace install for file workflow-controller-deployment.yaml:

- "--namespaced" 
 - --managed-namespace
        - workflow

**Comment by vladlosev** [comment]
Can you provide the complete set of values that can reproduce the issue?
