### ISSUE TITLE
argocd namespace install

### ISSUE THREAD

**Issue by waheedshahani** [argoproj/argo-helm#1054]
### Is your feature request related to a problem?

argocd provides two ways to install argocd instances.
https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml
https://github.com/argoproj/argo-cd/blob/master/manifests/namespace-install.yaml

It looks like helm is using only install.yaml which means we can not have multi-tenancy as provided by namespace-install.yaml. 
Can this be taken into account so that helm way also supports same features as manifest way? 

### Related helm chart

argo-cd

### Describe the solution you'd like

A helm chart allowing to choose multi-tenancy vs single tenancy.

### Describe alternatives you've considered

Using raw mainfests provided by argocd

**Comment by olevitt** [comment]
Hi,

Not sure if that corresponds to what you are trying to achieve but at my organization we deploy argoCD in single namespace by explicitly adding --namespace option to the command line. See https://github.com/InseeFrLab/helm-charts-datascience/blob/5f88b0ef0990c48537aa793dc1edfc551ddd3dc0/charts/argo-cd/values.yaml#L52

Except from CRD (which are cluster wide) management, we succed in allowing multiple argoCD installs in the same cluster
