### ISSUE TITLE
unable to promote rollouts from argocd console 

### ISSUE THREAD

**Issue by bhupenderS012** [argoproj/argo-helm#1078]
### Describe the bug

Hi Team,

I am facing issue to promote argo rollouts from argocd console. 

I have allowed default access as read-only under argocd RBAC for developers group.  
But at project level I have allowed below access to developers group.  
**Actions**: get, create, update, delete, sync, override, action

still facing issue to do promote argo rollouts from argocd console.

_Only possible solution i see is to allow admin access to group and they will be able to promote argo rollouts from argocd console.
We don't want to allow admin access to developers group. Is there any RBAC policy or workaround for this issue ?_ 

### Related helm chart

argo-cd

### To Reproduce

I have allowed default access as read-only under argocd RBAC for developers group.  
But at project level I have allowed below access to developers group.  
**Actions**: get, create, update, delete, sync, override, action

### Expected behavior

_Only possible solution i see is to allow admin access to group and they will be able to promote argo rollouts from argocd console.

**Comment by mkilchhofer** [comment]
I think you need to file an issue in the upstream repo over there: https://github.com/argoproj/argo-cd
