### ISSUE TITLE
Question: upgrade argocd using helm and/or kubectl 

### ISSUE THREAD

**Issue by guy-frontegg** [argoproj/argo-helm#1091]
Hello All,

We have multiple clusters with argocd. One was installed using kubectl and it's version 2.1.0 and the others were installed via helm and the version is 2.1.16.

We would like to upgrade all servers to 2.2.2 and we are a little concern with the process. AS we understand the CRD were changed. 

What are the best practice to upgrade argocd in production environment without the risk of deleting or damaging "live" applications.

**Comment by mkilchhofer** [comment]
Is downtime of ArgoCD allowed?
If so I'd remove all manifests except the CRDs by using 
```console
kustomize build https://github.com/argoproj/argo-cd/manifests/base?ref=v2.1.0  | kubectl delete -f -
kustomize build https://github.com/argoproj/argo-cd/manifests/cluster-rbac?ref=v2.1.0  | kubectl delete -f -
```
After that you could install the helm chart.

As the current state is stored in the CRDs the new instance should pick up the existing CRDs.

**Comment by guy-frontegg** [comment]
THank you,
We've upgraded Argo using help and then kubectl the CRD
