### ISSUE TITLE
Repo-server for Argo-CD 1.2 and newer is incomplete

### ISSUE THREAD

**Issue by carsonoid** [argoproj/argo-helm#111]
The repo server now -has- to have volume mounts for the ssh known hosts and tls certs: https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml#L2832

The current charts do not include these mounts by default.

**Comment by alexec** [comment]
Would you fancy updating this and submitting a PR?

**Comment by carsonoid** [comment]
@alexec done. It would be awsome if someone could merge both #112 and #109 then cut a release to get us back to a working chart.

**Comment by carsonoid** [comment]
Actually, hold up, it looks like the cm mounts need to be in the server deployment as well.

**Comment by carsonoid** [comment]
Ok. Added to both the server and repo-server deployments.
