### ISSUE TITLE
Argo-Rollouts: Unknown flag: --leader-elect

### ISSUE THREAD

**Issue by mjhuber** [argoproj/argo-helm#1112]
### Describe the bug

when setting `controller.replicas` to a value > 1, controller replicas will not start and return the error `Error: unknown flag: --leader-elect`.

Helm Chart version: `2.9.3`

```
❯ k get po/argo-rollouts-d5cd7fd8-rhdh5 -o json | jq -r '.spec.containers[0].image'
quay.io/argoproj/argo-rollouts:v1.1.1
```

### Related helm chart

argo-rollouts

### To Reproduce

1.  Deploy chart version 2.9.3 with the value `controller.replicas` set to 2.
2.  Observe the controller pods enter CrashLoopBackoff

### Expected behavior

controller pods work correctly

**Comment by huikang** [comment]
Hi, @mjhuber , I think argo-rollouts v1.1.1 does not support leader-elect yet. Could you try `quay.io/argoproj/argo-rollouts:latest`?

**Comment by mkilchhofer** [comment]
Already observed it as a comment (https://github.com/argoproj/argo-helm/pull/1016#issuecomment-1015364514) in the PR introduced this feature:
- https://github.com/argoproj/argo-helm/pull/1016

I think reverting the PR does not makes too much sense, but the feature is not yet released.
