### ISSUE TITLE
argo-cd (v2.3.x): Integrate ApplicationSets / Notifications in ArgoCD helm chart

### ISSUE THREAD

**Issue by reiniertimmer** [argoproj/argo-helm#1115]
### Is your feature request related to a problem?

In the upcoming ArgoCD 2.3 release (see https://github.com/argoproj/argo-cd/releases/tag/v2.3.0-rc1) both the Notifications and ApplicationSets controllers will come bundled with ArgoCD.

Looking at the plain kubernetes manifests from [argo-cd/manifests](https://github.com/argoproj/argo-cd/tree/release-2.3/manifests), the CRDs and controllers for both notifications and applicationsets are now shipped by default (as separate deployments).

Has it already been considered to include this in the argo-cd helm chart?

### Related helm chart

argo-cd

### Describe the solution you'd like

Allow for an option to install ArgoCD Notification controller and ApplicationSets controller as part of the ArgoCD helm chart.

### Describe alternatives you've considered

I have considered using the old helm charts for installing the controllers. However, I'm not sure this will lead to inconsistencies with the integrated code vs the code from the external repository

### Additional context

* According to https://github.com/argoproj/argo-cd/pull/7744 the entire codebase of notifications has been moved to ArgoCD
* However, for ApplicationSets, it seems that only CRDs have been moved to the ArgoCD repository (but the controller code still lives in its own repository) (https://github.com/argoproj/argo-cd/pull/8148)

This means that for notifications, the image that will be used is the same as the ArgoCD app version that is being installed. However, for ApplicationSets, this does not seem to be the case, and the image version should be a different (release) version of the application sets controller.

Would it make sense to install both notifications and appsets as part of the helm chart?

**Comment by reiniertimmer** [comment]
@mkilchhofer do yo have any idea how to proceed here, or who to contact?

It seems that we can use various approaches, at least:

* keep using the existing helm charts (also keep installation completely separate)
* use the (separate) helm charts but use them as dependencies from the main `argo-cd` chart
* completely integrate the helm templates into the `argo-cd` chart

For notifications, it probably makes most sense to completely merge the notifications chart with `argo-cd`, but for application sets, I'm not so sure what would make the most sense.

If possible, we could consider contributing (I would have to check if we can & have the appropriate skills) but maybe it's best to first get some idea what approach would be preferred.

As soon as ArgoCD 2.3 is release, I'm not sure there's a proper way to install these additional controllers through helm anymore.

**Comment by hbakkerit** [comment]
Please provide us with the preferred approach, such that we do not expend time and energy trying to contribute to the non-preferred approach(es).

**Comment by mkilchhofer** [comment]
Hmm I am unsure if we should integrate the existing addons as subcharts into the ArgoCD chart or deprecate the existing addons and directly integrate the templates into the ArgoCD chart.

Opinions @davidkarlsen @mbevc1 @oliverbaehler ?

**Comment by reiniertimmer** [comment]
The most important thing is compatibility I guess.

If it's possible to roll out the newer 2.3+ versions of both controllers using the old helm charts, then that's probably the easiest solution. It would mean there's no rush to patch up things because of things breaking on newer ArgoCD versions.

In that case, it's just a matter of updating the charts with the latest AppVersion (if needed) and checking the compatibility. It doesn't look like much of the code has changed on both controllers after the integration effort.

**Comment by mbevc1** [comment]
I haven't had time to dive into all the details of upcoming ArgoCD 2.3, but seems like safest and most straightforward approach would be to cut a new major release and follow upstream direction with integrating templates into Helm chart. Not sure keeping it backwards compatible makes sense unless we have use cases where people need to interchange using same chart without following upgrade path?

**Comment by tooptoop4** [comment]
2.3 is out

**Comment by pdrastil** [comment]
I would like to upvote integrating these into the argo-cd chart with new major version because these two add-ons are typically installed in most of the production grade deployments. Also this might provide good opportunity to cleanup some deprecated configuration options from 3.x chart if new major version would be released.

**Comment by wd** [comment]
If we integrate the notifications chart into the argo-cd chart, we may also need a migration guide about how to migrate from the current setup to the new one. 

I agree with @reiniertimmer that continue using the current setup for the new version so that people can use the latest version very soon. Also, start the progress about integrating them into one chart.

**Comment by BeyerJC** [comment]
I agree with @pdrastil and think its a good oppertunity to cleanup and have one, clean chart for the new release including all needed resources.

**Comment by jasonmacdonald** [comment]
Just want to jump in and let you know that there's [a bug](https://github.com/argoproj/argo-cd/issues/8716) that is part of 2.3.0 with the current 0.4.0 release of the applicationset CRDs, which was patched in t[his ticket](https://github.com/argoproj/applicationset/pull/535). You may want to use the 0.4.1 release of the cards once it's released.

If you were already aware, feel free to ignore this :)
