### ISSUE TITLE
[argo-workflows] artifactRepository.archiveLogs setting ignored

### ISSUE THREAD

**Issue by jze2** [argoproj/argo-helm#1140]
### Describe the bug

I installed argo-workflows via `helm upgrade --install argo-workflows argo/argo-workflows --values values.yaml`.
I have values like:
```
version: 0.9.2
appVersion: v3.2.4
artifactRepository:
  archiveLogs: true
  s3:
...
...
```
but no logs of cron workflows are saved to the S3 bucket.
I haven't used helm chart for installation before, argo workflows were installed in kubernetes via install manifest at first and archiving of logs was working. Switched to helm chart then and no logs are now archived (no changes to cron workflows configuration).

### Related helm chart

argo-workflows

### To Reproduce

1. setup S3 bucket
2. install argo-workflows via helm chart with artifactRepository section enabling archiving of logs accordingly.

### Expected behavior

Logs of cron workflows stored in S3 bucket.

**Comment by TimSchSkaylink** [comment]
Hi, i had the same problem when i switch to helm deployment for the Logs.
In our case the artifactRepository didnt got set on the configmap not sure if this is the same case here.

But we fixed it by adding the value for "useDefaultArtifactRepo" to true as default is false. But it's only getting set when the value is true.

have a look on the values here: https://github.com/argoproj/argo-helm/tree/master/charts/argo-workflows#artifact-repository
and here: https://github.com/argoproj/argo-helm/blob/3befa82210ea2c77dcc722c1582503700f66ae4c/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml#L46

Couldn't find anything on why there is an extra value to activate this. But this is currently the case

**Comment by jze2** [comment]
Yes, that helped. Thanks!

**Comment by jze2** [comment]
This should be documented if it is expected behavior.

**Comment by mkilchhofer** [comment]
WDYT @VaibhavPage @stefansedich @yann-soubeyrand ? In my opinion this `{{- if .Values.useDefaultArtifactRepo }}` could be deleted

**Comment by maxisam** [comment]
this useDefaultArtifactRepo should be removed. IMHO, it is sort of misleading

**Comment by nmatare** [comment]
Came here for same reason. I don't think this should be closed, it still exists in the main branch.

https://github.com/argoproj/argo-helm/blob/bb4d3154e63c89939c732ef89e404f2cba2f03e9/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml#L58

**Comment by jmeridth** [comment]
I'm getting a PR up for this shortly to remove that flag.
