### ISSUE TITLE
Add deployment annotations to the argocd-applicationset helm chart

### ISSUE THREAD

**Issue by voidlily** [argoproj/argo-helm#1151]
### Is your feature request related to a problem?

My cluster has a workflow that checks annotations on deployments for security/compliance scanning and exemptions for third party tools, but since there's no deployment annotations available to set for the argocd-applicationset helm chart, I can't use my tooling for this chart.

### Related helm chart

argocd-applicationset

### Describe the solution you'd like

Expose a deploymentAnnotations value for the argocd-applicationset helm chart so I can put annotations on the applicationset deployment.

**Comment by mkilchhofer** [comment]
So you need an annotation to be set on the `deployment.metadata.annotations`?

Or on the pods the Deployment resource creates for you? Pod annotations inside the Deployment can be done via the `podAnnotations` parameter.

**Comment by voidlily** [comment]
Annotations on `deployment.metadata.annotations`

**Comment by pratiyushpushkar05** [comment]
Any follow up for this ?

**Comment by mkilchhofer** [comment]
@pratiyushpushkar05 can you file a new issue for your desired helm chart?
This issue here is related argocd-applicationset helm chart, which no longer exists.

**Comment by pratiyushpushkar05** [comment]
Hi @mkilchhofer , our use case is to add an annotation to deployment kind present in all the applications in Argocd . We have lots of application and some synchronisation , common annotation , is required in all of them. ArgoCD is the place where they all come together . So functionality like being able to add a custom annotation to specific kind of k8 resource would full fill .
