### ISSUE TITLE
Argocd Notifications in Helm Chart

### ISSUE THREAD

**Issue by NishikaDeSilva** [argoproj/argo-helm#1168]
### Related helm chart

argo-cd

### Describe the solution you'd like

As per [ArgoCD notifications repository]( https://github.com/argoproj-labs/argocd-notifications#argo-cd-notifications-is-now-part-of-argo-cd), notifications are a part of argocd. But couldn't find it in the official helm chart `argo-cd`. It'd be great if it can be added to the helm chart as well.

**Comment by mkilchhofer** [comment]
There is already an issue open for this: #1115.

Closing as duplicate
