### ISSUE TITLE
[ArgoCD] server.config.url is not optional and must be configured when exposed and SSO is enabled.

### ISSUE THREAD

**Issue by fungiboletus** [argoproj/argo-helm#1169]
### Describe the bug

The `server.config.url` is described as optional but it is not optional when SSO is enabled. ArgoCD will redirect to the URL when you logout. The default `argocd.example.com` is therefore not valid.

### Related helm chart

argo-cd

### To Reproduce

Deploy CargoCD with the default settings and SSO configured, login as admin and logout.

### Expected behavior

CargoCD should redirect to the correct URL.

### Additional context

I started to write a pull request but I gave up when I found the list of requirements.

Here is my patch to illustrate my willingness to help:

```patch
From f6fc1640e71082cf665b72d106c1772b2cd692e2 Mon Sep 17 00:00:00 2001
From: Antoine Pultier <45740+fungiboletus@users.noreply.github.com>
Date: Fri, 11 Mar 2022 09:45:49 +0100
Subject: [PATCH 1/1] The server.config.url is not optional

CargoCD will redirect to this URL when you logout.
---
 charts/argo-cd/values.yaml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/charts/argo-cd/values.yaml b/charts/argo-cd/values.yaml
index fcd2a3d..710a901 100755
--- a/charts/argo-cd/values.yaml
+++ b/charts/argo-cd/values.yaml
@@ -1140,7 +1140,7 @@ server:
   # -- [General Argo CD configuration]
   # @default -- See [values.yaml]
   config:
-    # Argo CD's externally facing base URL (optional). Required when configuring SSO
+    # Argo CD's externally facing base URL
     url: https://argocd.example.com
     # Argo CD instance label key
     application.instanceLabelKey: argocd.argoproj.io/instance
-- 
2.35.1
```

**Comment by mkilchhofer** [comment]
Maybe we better set it to empty string?

This setting is required when SSO is configured.

Ref: https://github.com/argoproj/argo-cd/blob/v2.2.7/util/settings/settings.go#L45-L47

**Comment by fungiboletus** [comment]
It looks like my report is wrong, it's optional when SSO is not enabled. Leaving it empty sounds good from my point of view.
