### ISSUE TITLE
[argo-cd] Upgrading from v2.2 to 2.3 using Helm, an error occurs because the Applicationset CRD does not exist.

### ISSUE THREAD

**Issue by chattytak** [argoproj/argo-helm#1180]
### Describe the bug

Since v2.3, the Applicationset has been built in, so the argocd-applicationset-controller pod is now deployed.
However, it is repeatedly CrashLoopBackOff with an error that seems to be caused by the CRD not being present.
I have checked api-resources and indeed the CRD does not seem to exist.

`kubectl logs -n argocd argo-cd-argocd-applicationset-controller-df5d88bc8-zgnb8 | grep ERROR `
```
1.6475935455924516e+09 ERROR controller-runtime.source if kind is a CRD, it should be installed before calling Start{"kind": "ApplicationSet.argoproj.io", "error": "failed to get restmapping: no matches for kind \"ApplicationSet\" in group \"argoproj.io\""}
```

`kubectl api-resources | grep argo`
```
applications                        app,apps                               argoproj.io/v1alpha1                   true         Application
appprojects                         appproj,appprojs                       argoproj.io/v1alpha1                   true         AppProject
argocdextensions                                                           argoproj.io/v1alpha1                   true         ArgoCDExtension
```

I have come up with several avenues as workarounds, but is this a bug to begin with?
Or are the means I consider workarounds the legitimate way?

`kubectl apply -k https://github.com/argoproj-labs/applicationset.git/manifests/crds?ref=<appVersion>`
 or
`helm install --name my-release argo/argocd-applicationset -n argocd`

### Related helm chart

argo-cd, argocd-applicationset

### To Reproduce

Upgrade "argo-cd-3.35.4" to "argo-cd-4.0.0", which has never used "applicationset".

### Expected behavior

The chart will install the CRD of the "applicationset".

**Comment by BryanStenson-okta** [comment]
I've been able to work around this by disabling the `applicationSet` controller via values (https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L1866):

```
applicationSet:
  enabled: false
```

**Comment by chattytak** [comment]
Hello @BryanStenson-okta 
Since v2.3 incorporated ApplicationSet into the standard, I think it is just a work-around.
argocd will be developed under the assumption that ApplicationSet can be used, and of course the documentation will follow suit.
The path of deviating from the standard only when installed with helm is not the high road.

**Comment by ricardojdsilva87** [comment]
Hello all, 
the application set is part of argocd by default starting from version 2.3.
It happened to me also the issue with the CRD, maybe the helm chart is not installing it for now, I just applied it directly to test:
```
https://argocd-applicationset.readthedocs.io/en/stable/Getting-Started/#a-install-applicationset-as-part-of-argo-cd
```

**Comment by seddarj** [comment]
We're having the same issue with version `4.2.2` of the helm chart (already had the issue in version `4.0.0`) although we can see that the CRD for ApplicationSets exists [here](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/crds/crd-applicationset.yaml).

So it seems it could be a helm issue where it's not creating the new CRDs during an upgrade 🤔

**Comment by cgroschupp** [comment]
Helm does not support adding/deleting or updating crds, the directory `crds` is only used during `helm install`. https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

The best solution right now is to note this in the migration documentation and include the manual kubectl apply commands in the documentation.

**Comment by seddarj** [comment]
Thanks @cgroschupp for your input! I had looked at the page you mention but didn't understand  _There is no support at this time for upgrading or deleting CRDs using Helm_ as not being able to create new CRDs...

**Comment by cgroschupp** [comment]
Helm applies the `crds` directory only on the initial run(helm install).

**Comment by mkilchhofer** [comment]
Resolved via documentation inside README. PR #1180
