### ISSUE TITLE
v1.0.0 release removed support for controlling anonymous access

### ISSUE THREAD

**Issue by chrisjohnson** [argoproj/argo-helm#1190]
### Describe the bug

I am deploying argocd into ephemeral k8s clusters that I want to eliminate access barriers for, so I want argo to allow anonymous admin access. I have set policy.default but I can't enable anonymous access.

I found [this PR](https://github.com/argoproj/argo-helm/pull/117/files) that added support for enabling it and then I found [this PR](https://github.com/argoproj/argo-helm/pull/129) that removed it (with no justification given)

How can I control this config when deploying argocd via helm chart?

### Related helm chart

argo-cd

### To Reproduce

1. Deploy argocd via helm chart

### Expected behavior

The ability to enable anonymous login

**Comment by mkilchhofer** [comment]
The field `users.anonymous.enabled` lives in the ConfigMap `argocd-cm` [upstream docs](https://github.com/argoproj/argo-cd/blob/v2.3.3/docs/operator-manual/rbac.md#anonymous-access).

The content of this ConfigMap can be controlled via

```yaml
server:
  config:
    <your-key>: <your-value>
```

> README: 
> | Key | Type | Default | Description |
> |-----|------|---------|-------------|
> | server.config | object | See [values.yaml] | [General Argo CD configuration] |

**Comment by chrisjohnson** [comment]
Thanks for the clarification!! Looks like I just overlooked this info, I'm able to make it work with this value :)

**Comment by mkilchhofer** [comment]
> Thanks for the clarification!! Looks like I just overlooked this info, I'm able to make it work with this value :)

You are welcome. I'm glad that it works as designed 👍
