### ISSUE TITLE
Chore: Renaming default branch

### ISSUE THREAD

**Issue by mbevc1** [argoproj/argo-helm#1194]
### Is your feature request related to a problem?

Let's align naming of the default branch to something better and align with upstream naming: https://github.com/github/renaming

### Related helm chart

other

### Describe the solution you'd like

Let's go with `main`

**Comment by mkilchhofer** [comment]
I already wanted to implement this. But argoproj (all other repos) still uses "master". In my opinion I'd use the org default. 

Maybe we could ask @jessesuen, @alexmt or @crenshaw-dev if they plan to change to "main" or still want to use "master".
