### ISSUE TITLE
[charts/argo-cd] Enable override of tls.crt and tls.key

### ISSUE THREAD

**Issue by jl431** [argoproj/argo-helm#123]
The tls.crt and tls.key appear to be autogenerating in the argocd-secret secret. It would be great if we could override this from the values.yaml.

**Comment by jdeprin** [comment]
This is still an open issue in v1.0.0 for argo-cd.  These values in addition to the admin.password / mtime can be added in.  Initially I kept these values out of the config to prevent people commiting secrets into git but based on this comment https://github.com/argoproj/argo-helm/pull/129#pullrequestreview-301409563 and with the waiver of personal responsibility I can work on adding them in.
