### ISSUE TITLE
Use Helm's htpasswd function to encrypt configs.secret.argocdServerAdminPassword

### ISSUE THREAD

**Issue by jwilkicki** [argoproj/argo-helm#1233]
### Is your feature request related to a problem?

I am putting together a Terraform module for installing ArgoCD on my cluster.  In the process, I am setting argocdServerAdminPassword to a bcrypted value so that I can perform some other operations on ArgoCD after I provision it.  I am using Terraform's random string provider to create a stable random string for the password but because bcrypt doesn't generate the same hash every time for the same string my Terraform is constantly reapplying the Helm chart when it shouldn't be.

### Related helm chart

argo-cd

### Describe the solution you'd like

I think the issue might be fixed if I can pass something stable to Helm and possibly have the Helm chart do the encrypting within the template.  Then Terraform will not need to reapply the chart every time.  Is there some way to make this possible?

Alternatively, it would be good to know if there is some way to generate a token during provisioning that I can use for performing additional operations without needing to have the admin account enabled and then later having to disable it.

### Additional context

I need to provision ArgoCD at the time that I am creating my cluster and then 'bootstrap' the cluster with some ArgoCD applications.  Unfortunately, using the additonalApplications parameter in this chart in combination doesn't work with autosync on the Applications due to a race condition.  At the time my chart is applied the application controller tries to contact the repo server to synchronize the application but the repo server isn't receiving requests yet.  The application controller considers that a sync failure and refuses to try to synchronize the application again.

My workaround was to use the additionalApplications parameter to put in a manual syncing project, enable the admin account, wait for ArgoCD to fully deploy with helm wait, trigger the application with the admin account, and then disable the admin account (we have single sign on enabled for normal usage).

If there's another way to do this besides using the admin account, then I don't need this feature because I can just have Terraform disable the admin account and not need to generate a random password while provisioning.

**Comment by mkilchhofer** [comment]
I think this is more a TF problem. We have the same issue with TF and we workarounded it like this:

```hcl
// Workaround for bcrypt non-idempotence
// > Since a bcrypt hash value includes a randomly selected salt, each call to this function will return a different value,
// > even if the given string and cost are the same. (..)
// > HashiCorp recommends using this function only in provisioner blocks, or in data resources whose results are only used in provisioner blocks.
// Workaround source: https://github.com/hashicorp/terraform-provider-random/issues/102#issuecomment-698980286
resource "null_resource" "argocd_password" {
  triggers = {
    plain    = var.argocd_password
    hash     = bcrypt(var.argocd_password)
    modified = timestamp()
  }

  lifecycle {
    ignore_changes = [
      triggers["hash"],
      triggers["modified"]
    ]
  }
}
```

Then we can inject the cached password like this

```hcl
  set_sensitive {
    name  = "configs.secret.argocdServerAdminPassword"
    value = null_resource.argocd_password.triggers.hash
  }

  set {
    name  = "configs.secret.argocdServerAdminPasswordMtime"
    value = null_resource.argocd_password.triggers.modified
  }
```

Would that also work for you?

**Comment by jwilkicki** [comment]
I'll give it a try and see if it does.

**Comment by jwilkicki** [comment]
That seemed to do the trick.  Thank you!
