### ISSUE TITLE
 quay.io/bitnami/redis-exporter returning 401

### ISSUE THREAD

**Issue by jasonmacdonald** [argoproj/argo-helm#1234]
### Describe the bug

Trying to install the argoCD helm chart and getting the following error.

> Failed to pull image "quay.io/bitnami/redis-exporter:1.26.0-debian-10-r2": rpc error: code = Unknown desc = failed to pull and unpack image "quay.io/bitnami/redis-exporter:1.26.0-debian-10-r2": failed to resolve reference "quay.io/bitnami/redis-exporter:1.26.0-debian-10-r2": pulling from host quay.io failed with status code [manifests 1.26.0-debian-10-r2]: 401 UNAUTHORIZED

I'm not sure why an opensource chart would be requiring an authorized login. Perhaps this is something on my end but I cannot seem to find the cause. Perhaps it's just on their end but figured it was worth posting here.

### Related helm chart

argo-cd

### To Reproduce

Install the most recent chart version.

### Expected behavior

It should install without issue

**Comment by cfarrend** [comment]
I have this issue too. If you see [here](https://bitnami.com/stack/redis-exporter/containers), there is no reference to quay.io. So possibly it's no longer supported?

This shows no repositories either
https://quay.io/organization/bitnami

There are still DockerHub images for it
https://hub.docker.com/r/bitnami/redis-exporter

**Comment by joeunlog** [comment]
I had the same problem. I solved the problem by changing the image of the redis metric setting in the `values.yaml` file.
![image](https://user-images.githubusercontent.com/78069372/164456430-c082c47f-cf7b-42c6-8b55-e07f8f02c2d4.png)
It has been confirmed that the pod is properly created and that it is caught as a target in Prometheus. However, I did not check whether redis itself works normally.

**Comment by crabique** [comment]
Fixed in 4.5.5 as of #1235

Here's the screenshot from their Slack with more details as to "why":
![image](https://user-images.githubusercontent.com/6256096/164630364-48f8dfa6-d2ea-4fb3-a379-b83a5333cedc.png)

**Comment by joeunlog** [comment]
> Fixed in 4.5.5 as of #1235
> 
> Here's the screenshot from their Slack with more details as to "why": ![image](https://user-images.githubusercontent.com/6256096/164630364-48f8dfa6-d2ea-4fb3-a379-b83a5333cedc.png)

Where did you find this announcement?

**Comment by crabique** [comment]
> Where did you find this announcement?

[#sealed-secrets on Kubernetes Slack](https://kubernetes.slack.com/archives/CM0H415UG/p1650471042760389)

**Comment by mkilchhofer** [comment]
Fixed with PR https://github.com/argoproj/argo-helm/pull/1235 and chart version 4.5.5
