### ISSUE TITLE
Clarify and resolve CODEOWNER errors for user paguos

### ISSUE THREAD

**Issue by mkilchhofer** [argoproj/argo-helm#1239]
Hi @paguos

Your name in the CODEOWNERS file https://github.com/argoproj/argo-helm/blob/master/CODEOWNERS is highlighted with an error (already mentioned that in your initial PR here #331):

> Hi @paguos
> 
> Are you still active in this repository? Github now parses the CODEOWNERS file and displays errors if there are any: ![image](https://user-images.githubusercontent.com/7290987/164699050-365385d3-aad8-447d-985d-1f15117a285b.png)

Shall we remove you or can we try to solve this (maybe invite you again)?

**Comment by jmeridth** [comment]
@paguos you need the invite reset, correct?  /cc @alexec

**Comment by paguos** [comment]
> @paguos you need the invite reset, correct? /cc @alexec

Thanks! Is done!
