### ISSUE TITLE
Clarify and resolve CODEOWNER errors for user mr-sour

### ISSUE THREAD

**Issue by mkilchhofer** [argoproj/argo-helm#1240]
Hi @mr-sour

Your name in the CODEOWNERS file https://github.com/argoproj/argo-helm/blob/master/CODEOWNERS is highlighted with an error.

It seems that your feedback in PR #551 is still open and the invitation process is also open.

How shall we proceed? Do you want to act as a maintainer here? I'd love to have more maintainers on board.

**Comment by mr-sour** [comment]
Id love to be a maintainer! If I recall I found myself chomping at the bit for some scalability features for running a large instance, while that feature was upstreamed awhile ago. I'd be happy to help keep the chart healthy from my enterprise scale mindset.

**Comment by mkilchhofer** [comment]
@alexec can you send an invitation for this project to @mr-sour ?

**Comment by alexec** [comment]
@mr-sour was added to the CODEOWNERS file 1y5m ago. If this was a problem, then I would expect we should have know by now.

**Comment by mkilchhofer** [comment]
@alexec you added mr-sour back then, but as he did not gave feedback if this is okay, you did not invite him.
Now as Github introduced a validation feature for the CODEOWNERS file, we see this error:
<img width="946" alt="Screenshot of CODEOWNERS file" src="https://user-images.githubusercontent.com/7290987/166632044-194e33e8-2592-45e4-beea-1c6607b9d1b4.png">

**Comment by jmeridth** [comment]
@alexec could we resend the invite to @mr-sour to try to rectify the issue with our CODEOWNERS file?

@mr-sour you need it reset, correct?

**Comment by alexec** [comment]
Done.
