### ISSUE TITLE
"applicationsets" resource for "argoproj.io" apiGroups is missing in "argo-helm/charts/argo-cd/templates/argocd-server/role.yaml"

### ISSUE THREAD

**Issue by unixmind** [argoproj/argo-helm#1244]
### Describe the bug

We got this error message while running "argocd admin export" command inside the pod:

``
WARN[0000] applicationsets.argoproj.io is forbidden: User "system:serviceaccount:argocd:argocd-server" cannot list resource "applicationsets" in API group "argoproj.io" in the namespace "argocd"
``

We should have:

``` sh
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  - applicationsets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch
```

### Related helm chart

argo-cd

### To Reproduce

``` sh
POD=$(kubectl -n argocd get pod -l app.kubernetes.io/component=server -o jsonpath="{$.items[0].metadata.name}")
```

``` sh
kubectl -n argocd exec -ti $POD -- argocd admin export
```

### Expected behavior

No WARN[0000] message

**Comment by mkilchhofer** [comment]
It looks like the upstream manifests also doesn't include `applicationsets`:
https://github.com/argoproj/argo-cd/blob/v2.3.3/manifests/base/server/argocd-server-role.yaml#L25

Maybe we should discuss this also in the upstream repo?

**Comment by dbaltor** [comment]
Hi @mkilchhofer. I'm getting the same error message with AgoCD `2.11.0` deployed using helm chart `3.35.4`. Have you got any news on this error?

**Comment by mkilchhofer** [comment]
@dbaltor do you have a reference why do yo want to run the export command within the argocd-server pod?
I think the export functionality is designed to run it as a cluster admin from where you also run kubectl.

**Comment by dbaltor** [comment]
Hi @mkilchhofer thanks for coming back. I've completely missed the context of this question. I'm actually getting this error message in the `argocd-server` pod logs after upgrading to ArgoCD `2.11.0` whilst keeping using my original helm chart (`3.35.4`) to deploy it on EKS. It's most likely due to some misconfiguration caused by the old helm chart.

I'll redeploy everything using the latest helm chart: `7.0.0`
