### ISSUE TITLE
Argo Events improvements

### ISSUE THREAD

**Issue by pdrastil** [argoproj/argo-helm#1249]
### Is your feature request related to a problem?

I would like to align Argo Events Helm chart closer to Argo CD structure. Namely user experience isn't great in following areas:

- Redefining image on 3 places when behind corporate proxy
- Redefining image pull secrets on multiple places
- Redefining pod labels on a multiple places
- Redefining host aliases on a multiple places
- Running controllers with restricted / namespaced installation by default that quickly pollutes the namespace with deployments created from CRDs
- Service account creation / configuration is not exactly typical nowadays
- Core RBAC is exposed in values.yaml instead placed into Role / ClusterRole

### Related helm chart

argo-events

### Describe the solution you'd like

Argo Events 1.7.0 will introduce different EventBus and configuration of multiple versions for bus controllers via ConfigMap. What do you think @mkilchhofer about refactoring / cleaning up this chart a little bit and aligning it closer how Argo CD chart looks like.

**Comment by mkilchhofer** [comment]
Yes aligning all charts to follow one structure is great. As I am not one of the CODEOWNERS of that repo I act a bit passive here :-) But lets proceed and push your PR forward 👍
