### ISSUE TITLE
Add badge support

### ISSUE THREAD

**Issue by jl431** [argoproj/argo-helm#125]
**Is your feature request related to a problem? Please describe.**
Editing the argocd-cm post deployment and adding the additional data field:
statusbadge.enabled: "true"

allows us to access badge status via
https://argourl/api/badge?name=foobar

It would be neat if we could do this via a values flag instead of post deployment.

**Describe the solution you'd like**
We could add a boolean value that adds statusbadge.enabled to the underlying cm.

**Comment by seanson** [comment]
Badge support now configurable as of freeform config in 1.0.0 chart.
``` yaml
server:
  config:
    statusbadge.enabled: "true"
```
