### ISSUE TITLE
argo helm upgrade from 4.2.1 to 4.5.8

### ISSUE THREAD

**Issue by srinireddya** [argoproj/argo-helm#1259]
### Describe the bug

This is one of the basic question.

We are updating the argo helm chart from 4.2.1 to 4.5.8, when we look at the document provided at https://artifacthub.io/packages/helm/argo/argo-cd, its been mentioned as CRD's are not going to upgraded.
 
When we tried to run the upgrade by kubectl commands provided (kubectl apply -k https://github.com/argoproj/argo-cd.git/manifests/crds?ref=v2.3.3), we get the error "no matches found", the url points to non existing file. 

### Related helm chart

argo-cd

### To Reproduce

Update the helm chart from 4.2.1 to 4.5.8

### Expected behavior

is there any documentation available to update the CRD's, when we update the argocd using Helm.  Also any impacts and best practices around them.

**Comment by yu-croco** [comment]
Probably [upstream's doc](https://github.com/argoproj/argo-cd/tree/master/manifests#normal-installation) is correct. 👀 
Please try  like this `kubectl apply -k https://github.com/argoproj/argo-cd/manifests/crds\?ref\=v2.3.3` . 🙋 

<img width="1135" alt="Screen Shot 2022-06-25 at 10 03 03" src="https://user-images.githubusercontent.com/30188755/175752387-a4befe2a-dfcd-4716-b5b3-14da648472a5.png">

It worked on my local environment.

```
 $ kubectl apply -k https://github.com/argoproj/argo-cd/manifests/crds\?ref\=v2.4.2
customresourcedefinition.apiextensions.k8s.io/applications.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/applicationsets.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/appprojects.argoproj.io created
```
