### ISSUE TITLE
Disable default admin user helm chart value

### ISSUE THREAD

**Issue by ErwinJapie** [argoproj/argo-helm#1261]
### Is your feature request related to a problem?

I am installing argocd on my clusters using an infrastructure as code approach by adding the argo helm chart to my terraform code with the necessary values (including dex github oauth config)

However I now have to manually update the config map argocd-cm to disable the default admin as described here (https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#disable-admin-user)

I have skimmed through the values file but could not find an option to accomplish this in code.

### Related helm chart

argo-cd

### Describe the solution you'd like

I'd like a value to be added to the values.yaml such that I can specify to disable the default admin

**Comment by tuananh** [comment]
alternatively, this can be achieved by managing `argocd-cm` by argocd itself

**Comment by pdrastil** [comment]
Use following section in your values.yaml:

```
server:
  config:
    admin.enabled: false
```

**Comment by ErwinJapie** [comment]
Thanks @pdrastil that did the trick!
