### ISSUE TITLE
Deprecation warnings on Kubernetes resource PodSecurityPolicy

### ISSUE THREAD

**Issue by ingmars1709** [argoproj/argo-helm#1263]
### Describe the bug

In the gitops-argocd-application-controller I receive the warning:

`warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+`

### Related helm chart

argo-cd

### To Reproduce

Open logs of gitops-argocd-application-controller and observe the warning.

### Expected behavior

If in the future I will upgrade to Kubernetes 1.25 I do not want this to turn into an error.

Are these warning generated because of Argo?  Or because I use deprecated resources inside my cluster?

**Comment by rassie** [comment]
@mkilchhofer this issue still exists, as far as I'm aware. Could you re-open this please?

**Comment by rassie** [comment]
Thanks, I have indeed misunderstood the output of `kubectl get apirequestcounts podsecuritypolicies.v1beta1.policy`.

**Comment by mkilchhofer** [comment]
Never seen this command 😄 is it a kubectl plugin, @rassie?

**Comment by rassie** [comment]
Yes, I'm spoiled with OpenShift and never know which commands exist in original kubectl :)

**Comment by drozd-A** [comment]
These deprecation warnings were from redis-ha and were resolved in https://github.com/argoproj/argo-helm/pull/1421

**Comment by mkilchhofer** [comment]
> These deprecation warnings were from redis-ha and were resolved in https://github.com/argoproj/argo-helm/pull/1421

No, they actually comes from the application controller if users deploy apps with deprecated resources.
Will be suppressed with upcoming Argo CD releases:
- https://github.com/argoproj/argo-cd/pull/12067
