### ISSUE TITLE
[Documentation] Add some examples about how to configure things like configmaps via Helm

### ISSUE THREAD

**Issue by spkane** [argoproj/argo-helm#1264]
### Is your feature request related to a problem?

If you are trying to do something like add configuration to the `argo-cd` ConfigMap via helm, looking at the templates and `values.yaml` file only gets you so far.

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-configs/argocd-cm.yaml#L14-L15

```
data: {{- include "argo-cd.config" $ | nindent 4 }}
{{- end }}
```

Where does this come from? 

Github search and [artifacthub](https://artifacthub.io/packages/helm/argo/argo-cd) aren't very helpful, as the search returns **nothing** for `"argo-cd.config"` or `argo-cd.config` and artifacthub does not show the `_helpers.tpl`.

In the end, it basically required cloning the repo and prepping through things to find the relevant code:

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/_helpers.tpl#L236-L243

### Related helm chart

argo-cd

### Describe the solution you'd like

Please add some documentation and examples to the top-level README in this repo (or in a README in each project's helm chart root) for setting these config maps.

This was way more work than it should have been to track down, and for some folks, this would likely end up being a hard blocker, as reading helm templating code should not be required to do something this standard.

### Additional context

Although I selected the `argo-cd` chart, this likely applies to all the charts here.

**Comment by bukowa** [comment]
@spkane Hey would you mind sharing how it works?
