### ISSUE TITLE
Add support for nginx-ingress-classes flag on argo rollout chart to support multiple ingresses

### ISSUE THREAD

**Issue by pragmaticivan** [argoproj/argo-helm#1274]
### Is your feature request related to a problem?

> As a default, the Argo Rollouts controller only operates on ingresses with the kubernetes.io/ingress.class annotation set to nginx. A user can configure the controller to operate on Ingresses with different kubernetes.io/ingress.class values by specifying the --nginx-ingress-classes flag. A user can list the --nginx-ingress-classes flag multiple times if the Argo Rollouts controller should operate on multiple values.

The controller should have a new array property to support multiple ingress classes and perhaps just have a default value to `nginx` which is the current default.

### Related helm chart

argo-rollouts

### Describe the solution you'd like

Add `controller.nginxIngressClasses = []`

defaults to `['nginx']`

### Describe alternatives you've considered

I'm aware of the field `extraArgs`. But, because that has its own section in the docs it could do with being a dedicated field with proper documentation.

**Comment by flyingsaucerer** [comment]
The existing ingress spec only mimics nginx and traefikv1. I agree that new ingress specs should be supported. For e.g. the traefikv2 ingress spec is completely different and uses routers, middleware and services instead of simple front and backends.
