### ISSUE TITLE
Support for Traefikv2 ingress spec

### ISSUE THREAD

**Issue by flyingsaucerer** [argoproj/argo-helm#1287]
### Is your feature request related to a problem?

Anyone wanting to use an ingress other than Nginx is severely limited in the use of this chart. It seems that the template supports only nginx and traefikv1 specs. Traefikv2 has a completely different spec as can be seen here: https://doc.traefik.io/traefik/migration/v1-to-v2/. So far it seems that nginx and traefik have nearly the same spec which is why the existing template works.

### Related helm chart

argo-cd

### Describe the solution you'd like

Please support multiple ingress class specs in the ingress template: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/ingress.yaml

**Comment by ronaldmiranda** [comment]
i think that you can use the extraObjects for that.
