### ISSUE TITLE
failed to install CRD crds/cluster-workflow-template-crd.yaml

### ISSUE THREAD

**Issue by asafyish** [argoproj/argo-helm#1305]
### Describe the bug

I am getting:
```
Error: failed to install CRD crds/cluster-workflow-template-crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```
when trying to install on k8s version 1.23 since "apiextensions.k8s.io/v1beta1" was disabled in https://github.com/kubernetes/kubernetes/issues/82022. Can also be seeing at https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22#customresourcedefinition-v122

### Related helm chart

argo-cd

### To Reproduce

Try to deploy on k8s version 1.23

### Expected behavior

Should work on versions below 1.22 and above.

**Comment by vladlosev** [comment]
What version of the chart are you using? In the current one, all the CRDs are already at the version `apiextensions.k8s.io/v1`.
