### ISSUE TITLE
ClusterRole argo-workflows-workflow-controller  is missing get secrets

### ISSUE THREAD

**Issue by ntdt** [argoproj/argo-helm#1324]
### Describe the bug

The error is

`Warning  WorkflowFailed         10m   workflow-controller  failed to check if secret argo-workflows-agent-ca-certificates exists: secrets "argo-workflows-agent-ca-certificates" is forbidden: User "system:serviceaccount:argo-workflows:argo-workflows-workflow-controller" cannot get resource "secrets" in API group "" in the namespace "opsys"`

### Related helm chart

argo-workflows

### Helm chart version

0.16.3

### To Reproduce

Run a workflow with http template, e.g. https://github.com/argoproj/argo-workflows/blob/master/examples/http-hello-world.yaml

### Expected behavior

The error shoud not be there.

**Comment by hbrewster-splunk** [comment]
+1

**Comment by wesleyscholl** [comment]
I'm also receiving a similar error when running this http template (local instance of argo) :

https://argoproj.github.io/argo-workflows/http-template/

**Comment by phanindraramesh-a10** [comment]
I have the same problem. Is there any fix/workaround for this?

**Comment by joebowbeer** [comment]
@wesleyscholl @phanindraramesh-a10 Open a new issue with repro steps?

You need to make sure there is a secret, associated either by naming convention or annotation, for the service account that runs the workflow:

https://argoproj.github.io/argo-workflows/manually-create-secrets/
