### ISSUE TITLE
With Kubernetes 1.24, argo-workflows-server SA is no longer created with a secret token

### ISSUE THREAD

**Issue by sharangb** [argoproj/argo-helm#1345]
### Describe the bug

With the release of Kubernetes 1.24, service accounts are no longer created with a corresponding secret token ([ref](https://github.com/kubernetes/kubernetes/pull/108309)). For argo-workflows, this means that the `argo-workflows-server` service account no longer comes with an out-of-the-box secret that can be used to access the REST API.

For now, we have to work around this by [manually creating a secret](https://stackoverflow.com/a/72258300) that has to be managed separately from the helm release. It would be great to have this as a part of the helm installation. 

### Related helm chart

argo-workflows

### Helm chart version

0.16.3

### To Reproduce

1. Use Kubernetes version 1.24
2. Install the argo-workflows helm chart
3. Note that argo-workflows-server service account no longer has an associated secret

### Expected behavior

The `argo-workflows-server` service account should have an associated secret.

**Comment by vladlosev** [comment]
AFAIU, with the new feature the service accounts are no longer required. When creating the pod, the Kubernetes will generate a token for it and map that token into a projected volume. The token will be periodically renewed and will expire automatically when the pod is deleted. But it will still be mapped into the same path as the secret token before. So from the perspective of the code in the pod nothing changes, except for the need to periodically re-read the token when it's renewed.

All fairly recent Kubernetes SDKs have been updated to do that. So if you run a version of Argo Workflows that's less than 6 month old (and maybe older, you can check that the Go SDK it's built with must be 0.15.7 or newer). You can read more about this at the AWS [page](https://docs.aws.amazon.com/eks/latest/userguide/service-accounts.html#identify-pods-using-stale-tokens) devoted to the matter.

**Comment by sharangb** [comment]
@vladlosev You are right, this seems to be the case. How would I go about exposing the service account token from the projected volume so that other pods can use it to access the argo-workflows REST API? I tried to exec into the argo-workflows container to read it, but for any shell command I always get:
```OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown```

**Comment by vladlosev** [comment]
The new bound tokens are bound to a given pod. They cannot be used from any other pod. IMHO you best approach should be to give your other pod's a service account of their own so they can access the API server.
