### ISSUE TITLE
Project admin

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-helm#1354]
### Is your feature request related to a problem?

Argo Helm is a community maintained Git repo. I don't really want to be involved in the day-to-day admin of it. How do I avoid that?

### Related helm chart

other

### Describe the solution you'd like

This can only be either be addressed by either 

(a) promoting 2 or 3 of the current "write" members to "admin", or 
(b) by other project leads (such as @jessesuen @alexmt @sarabala1979 @whynowy) taking an active role.

I don't think (b) will happen.

**Comment by jmeridth** [comment]
I volunteer as tribute. I imagine @mkilchhofer would also and would have precedence over me.

**Comment by mkilchhofer** [comment]
> I volunteer as tribute. I imagine @mkilchhofer would also and would have precedence over me.

Sure, I am also happy with that role 👍

**Comment by jmeridth** [comment]
> > I volunteer as tribute. I imagine @mkilchhofer would also and would have precedence over me.
> 
> 
> 
> Sure, I am also happy with that role 👍

He was here first (maintaining this repo). @mkilchhofer  should have it IMO.

**Comment by jmeridth** [comment]
@alexec bump this.  Can you please make @mkilchhofer an admin?  Thank you.

**Comment by mkilchhofer** [comment]
Hi @alexec, unfortunately "Access > Collaborators and Teams" is not visible to us with that privilege level:
![grafik](https://user-images.githubusercontent.com/7290987/184238920-abe7f8c1-f8f1-4241-8080-05329259256c.png)

At least I am unable to invite/manage members inside the repository.

**Comment by alexec** [comment]
Try now?

**Comment by mkilchhofer** [comment]
Looks good 🚀 thank you
