### ISSUE TITLE
openssh-server 8.9 Azure DevOps ssh connectivity issues

### ISSUE THREAD

**Issue by dtotopus** [argoproj/argo-helm#1359]
### Describe the bug

Argocd version 4.9.11 cannot establish connection to Azure DevOps git repositories over ssh.
The issue seems to be related to the usage of openssh-server 8.9 in the never versions.
Older Argocd version 4.8.2 does work fine as it's using openssh-server 8.4.

Following error appears when connection is being established
```
Unable to negotiate with 40.74.28.9 port 22: no matching host key type found. Their offer: ssh-rsa
fatal: Could not read from remote repository.
```

### Related helm chart

argo-cd

### Helm chart version

4.9.11

### To Reproduce

Add ssh connection configuration to Azure Devops.
Open Argocd dashboard.
Following error dialog will appear over applications `Unable to negotiate with 40.74.28.9 port 22: no matching host key type found. Their offer: ssh-rsa
fatal: Could not read from remote repository.`

### Expected behavior

Application connects succesfully

### Screenshots

![image](https://user-images.githubusercontent.com/9915827/177169055-e054bd08-2155-4f37-90ae-51c28c83939e.png)

## EDIT

Apparently this seems to be an issue from openssh-server version 8.8 and technically this is an issue from Azure DevOps side as they do not support any other ssh keys except for ssh-rsa ones and are incompatible with newer openssh-server versions. 
In any case - everyone using Argocd version while using Azure DevOps repositories should be aware of this 

https://www.openssh.com/txt/release-8.8
```
This release disables RSA signatures using the SHA-1 hash algorithm
by default. This change has been made as the SHA-1 hash algorithm is
cryptographically broken, and it is possible to create chosen-prefix
hash collisions for <USD$50K [1]

For most users, this change should be invisible and there is
no need to replace ssh-rsa keys. OpenSSH has supported RFC8332
RSA/SHA-256/512 signatures since release 7.2 and existing ssh-rsa keys
will automatically use the stronger algorithm where possible.

Incompatibility is more likely when connecting to older SSH
implementations that have not been upgraded or have not closely tracked
improvements in the SSH protocol. For these cases, it may be necessary
to selectively re-enable RSA/SHA1 to allow connection and/or user
authentication via the HostkeyAlgorithms and PubkeyAcceptedAlgorithms
options. For example, the following stanza in ~/.ssh/config will enable
RSA/SHA1 for host and user authentication for a single destination host:

    Host old-host
        HostkeyAlgorithms +ssh-rsa
	PubkeyAcceptedAlgorithms +ssh-rsa

We recommend enabling RSA/SHA1 only as a stopgap measure until legacy
implementations can be upgraded or reconfigured with another key type
(such as ECDSA or Ed25519).

[1] "SHA-1 is a Shambles: First Chosen-Prefix Collision on SHA-1 and
    Application to the PGP Web of Trust" Leurent, G and Peyrin, T
    (2020) https://eprint.iacr.org/2020/014.pdf
```

**Comment by mkilchhofer** [comment]
It's not a bug. Did you read the upstream upgrading guide? :-)

https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.3-2.4/#support-for-private-repo-ssh-keys-using-the-sha-1-signature-hash-algorithm-is-removed
