### ISSUE TITLE
Can we copy the LICENSE file into each of the helm charts?

### ISSUE THREAD

**Issue by eyal-lantzman** [argoproj/argo-helm#1364]
### Is your feature request related to a problem?

Enterprise helm-chart procurement tools fails to identify the license for each of the helm charts

### Related helm chart

argo-cd, argo-events, argo-rollouts, argo-workflows, argocd-image-updater

### Describe the solution you'd like

Copy the file into each of the charts.

### Describe alternatives you've considered

manual procurement which is very slow and creates a lot of friction point

**Comment by mkilchhofer** [comment]
I don't think that this makes sense for us. We want to follow the DRY principle. Are there other options for you? Maybe a chart annotation (https://artifacthub.io/docs/topics/annotations/helm/)?

**Comment by eyal-lantzman** [comment]
The ideal outcome I’m looking for is that there’s a license file per chart.

A chart is an independent deployable unit, and the convention is to have LICENSE file at that unit level.

If the annotation will do just that, great.
Otherwise, if there’s a way to copy the file during build/publishing to artifacthub, that should work as well.

Third option, to avoid DRY, is to possible
symlink the file to the LICENSE file at root.
https://stackoverflow.com/questions/954560/how-does-git-handle-symbolic-links

Thanks


On 9 Jul 2022, at 23:40, Marco Kilchhofer ***@***.***> wrote:

﻿

I don't think that this makes sense for us. We want to follow the DRY principle. Are there other options for you? Maybe a chart annotation (https://artifacthub.io/docs/topics/annotations/helm/)?
