### ISSUE TITLE
workflow-controller fails to obtain v1alpha1.WorkflowTemplate resource

### ISSUE THREAD

**Issue by l15k4** [argoproj/argo-helm#137]
**Describe the bug**
Deploying argo 0.6.1 using this chart boots up workflow controller that immediately fails.

**To Reproduce**
1. deploy argo with default values
2. `kubectl logs -f pod/workflow-controller-5994bd4bbd-jx7zk`

**Expected behavior**
workflow controller should boot up properly but instead following happens : 
```
time="2019-10-25T13:56:54Z" level=info msg="workflow controller configuration from argo-staging-workflow-controller-configmap:\ncontainerRuntimeExecutor: docker\nartifactRepository:\n"
time="2019-10-25T13:56:54Z" level=info msg="Persistence configuration disabled"
time="2019-10-25T13:56:54Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2019-10-25T13:56:54Z" level=info msg="Workflow Controller (version: v2.4.2) starting"
time="2019-10-25T13:56:54Z" level=info msg="Workers: workflow: 8, pod: 8"
time="2019-10-25T13:56:54Z" level=info msg="Watch Workflow controller config map updates"
time="2019-10-25T13:56:54Z" level=info msg="Detected ConfigMap update. Updating the controller config."
time="2019-10-25T13:56:54Z" level=info msg="workflow controller configuration from argo-staging-workflow-controller-configmap:\ncontainerRuntimeExecutor: docker\nartifactRepository:\n"
time="2019-10-25T13:56:54Z" level=info msg="Persistence configuration disabled"
E1025 13:56:54.844483       1 reflector.go:126] github.com/argoproj/argo/workflow/controller/controller.go:157: Failed to list *v1alpha1.WorkflowTemplate: the server could not find the requested resource (get workflowtemplates.argoproj.io)
E1025 13:56:54.844483       1 reflector.go:126] github.com/argoproj/argo/workflow/controller/controller.go:157: Failed to list *v1alpha1.WorkflowTemplate: the server could not find the requested resource (get workflowtemplates.argoproj.io)

```

**Comment by jbehling** [comment]
Did you install the CRDs? (via the chart or otherwise?) if you do `kubectl get crds` do you see `workflowtemplates.argoproj.io`

**Comment by l15k4** [comment]
both `true/false` in : 
```
argo:
  installCRD: true/false
```
has the same outcome. I thought that if that is `true`, the CRDs would be installed, but my `kubectl get crds` does not list `workflowtemplates.argoproj.io`

**Comment by l15k4** [comment]
We use k8s `1.13.7-gke.24` so these `apiextensions.k8s.io/v1beta1` should all work in there :-/

**Comment by l15k4** [comment]
I found the reason https://github.com/argoproj/argo/issues/1609

**Comment by l15k4** [comment]
If I run `helm install --debug`, those argo CRDs are not included :woman_shrugging:  in there. However they are included for `argo-events`

**Comment by l15k4** [comment]
got it, compare these that are not installed : 
https://github.com/argoproj/argo-helm/blob/master/charts/argo/templates/workflow-crd.yaml#L1
https://github.com/argoproj/argo-helm/blob/master/charts/argo/templates/workflow-template-crd.yaml#L1
with those that are installed : 
https://github.com/argoproj/argo-helm/blob/master/charts/argo-events/templates/sensor-crd.yaml#L1
https://github.com/argoproj/argo-helm/blob/master/charts/argo-events/templates/gateway-crd.yaml#L1
