### ISSUE TITLE
opt-out of the creation of cluster roles when deploying argo-rollouts with 'clusterInstall: true'

### ISSUE THREAD

**Issue by jphelton** [argoproj/argo-helm#1384]
### Is your feature request related to a problem?

I work for a large enterprise, which has strict controls around the governance of cluster-roles.  As such we've found it necessary to pull our cluster-roles and cluster-rolebindings into a separate helm chart.  This works well for the argo-cd helm chart, but with argo-rollouts we've been forced to fork the helm chart.  This makes it hard to stay up to date with argo-rollouts because we have to keep merging from upstream.

### Related helm chart

argo-rollouts

### Describe the solution you'd like

I would like to able to the deploy the argo-rollouts helm chart with "clusterInstall: true", but I don't want argo-rollouts to get deployed with the clusterRoles in the helm chart.  I instead want to be able to bring my own.

### Describe alternatives you've considered

Right now we fork the the argo-rollouts helm chart, but this makes it hard to stay up to date on important features.

### Additional context

My forked version of the helm chart have relatively minor changes.  I simply update the first line on all of the cluster role templates

from
```
{{- if .Values.clusterInstall }}
```
to
```
{{- if and .Values.clusterInstall .Values.installClusterRoles }}
```

If there are no objects I can open a PR for this, but I wasn't sure if the decision to not allow the ability to override the cluster-roles was intentional.

**Comment by jmeridth** [comment]
Closed by #1388
