### ISSUE TITLE
Enable livenessProbe for dex connectivity issue that prevents oauth login

### ISSUE THREAD

**Issue by NishikaDeSilva** [argoproj/argo-helm#1385]
### Is your feature request related to a problem?

Sometimes, dex server connection is failed and thus unable to authenticate with google groups. Server restart fixes this.

### Related helm chart

argo-cd

### Describe the solution you'd like

This bug was reported in https://github.com/redhat-developer/gitops-operator/issues/263 and has fixed with adding a livenessProbe in **kubernetes operator**.  It would be nice to have this enabled in the helm chart as well.

### Describe alternatives you've considered

Helm chart could have the ability to override *.Values.dex.livenessProbe.httpGet*.

**Comment by pdrastil** [comment]
@NishikaDeSilva Check `dex.livenessProbe.enabled` and `dex.readinessProbe.enabled` to get what you want. Currently probes are not enabled by default due to compatibility reasons.
