### ISSUE TITLE
argo workflows: missing permissions

### ISSUE THREAD

**Issue by trondhindenes** [argoproj/argo-helm#1391]
### Describe the bug

After upgrading to helm chart 0.16.8, I'm getting this error:

```
ingest-recording-id-5601-1659527325-1340600742-agent main time="2022-08-03T12:04:34.721Z" level=error msg="TaskSet Patch Failed" error="workflowtasksets.argoproj.io \"ingest-recording-id-5601-1659527325\" is forbidden: User \"system:serviceaccount:workflows-staging:oort-cloud-workflow-staging\" cannot patch resource \"workflowtasksets/status\" in API group \"argoproj.io\" in the namespace \"workflows-staging\"" workflow=ingest-recording-id-5601-1659527325
```
It seems to me that the role definition is missing some permissions.

Any workflow steps using the http template are hanging, and the agent pod is logging the able error.

### Related helm chart

argo-workflows

### Helm chart version

0.16.8

### To Reproduce

use a namespaced install with `serviceAccount.create=true`

### Expected behavior

workflows should succeed

**Comment by trinhpham** [comment]
Sorry for bringing this up, @trondhindenes 
I got the same error when using HTTP template, may I know why did you close this as not planned?

**Comment by trondhindenes** [comment]
I'm afraid I don't remember :-(
