### ISSUE TITLE
argocd-applicationset-controller CrashLoopBackOff

### ISSUE THREAD

**Issue by holooloo** [argoproj/argo-helm#1402]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

i`ve installed a argo-cd-3.26.3 helm chart and got argocd-applicationset-controller CrashLoopBackOff:
```
[FATAL tini (8)] exec argocd-applicationset-controller failed: No such file or directory
```

try to install argo-cd-3.26.3 helm chart

**Expected behavior**

working chart

**Screenshots**

**Version**

```shell
argo-cd-3.26.3 helm chart
```

**Logs**

```
[FATAL tini (8)] exec argocd-applicationset-controller failed: No such file or directory
```

**Comment by pdrastil** [comment]
Most likely you are still using old image for applicationset that is no longer maintained. Binary was moved into same image as Argo CD.

**Comment by pdrastil** [comment]
@holooloo Is this still an issue or can we close this?

**Comment by holooloo** [comment]
close it please cause no error with the same version on another cluster
