### ISSUE TITLE
[ArgoCD][FR] Upgrade redis-ha chart to the latest version (4.22.1)

### ISSUE THREAD

**Issue by pierluigilenoci** [argoproj/argo-helm#1428]
### Is your feature request related to a problem?

New version of `redis-ha` chart is released with a major upgrade of `redis` (to 7.0.4) `ha-proxy` to (2.6.4)

Ref: https://github.com/DandyDeveloper/charts/pull/226

### Related helm chart

argo-cd

### Describe the solution you'd like

Upgrade the chart of `redis-ha` to version [4.22.1](https://artifacthub.io/packages/helm/dandydev-charts/redis-ha).

### Describe alternatives you've considered

None

### Additional context

Nothing to add

**Comment by jmeridth** [comment]
Was resolved by #1428
