### ISSUE TITLE
Allow setting log format of deployments

### ISSUE THREAD

**Issue by ni-todo-spot** [argoproj/argo-helm#1438]
### Is your feature request related to a problem?

I'd like my GCP logging (stackdriver) to successfully parse logs printed to pod's console by different argo components, otherwise it considers most massages as ERROR

### Related helm chart

argo-cd, argo-events, argo-workflows

### Describe the solution you'd like

Add additional setting in helm chart to set the log format 

### Describe alternatives you've considered

Edit the deployment of manually, for instance for argo-workflows (what I did manually):

`workflow-controller --configmap workflow-controller-configmap --executor-image quay.io/argoproj/argoexec:v3.2.9 --namespaced --log-format=json`

### Additional context

I think this feature can be helpful for all other argo charts, though I'm not sure which components support it

**Comment by jmeridth** [comment]
@ni-todo-spot this already exists in argo-cd chart:

- [controller logFormat](https://github.com/argoproj/argo-helm/blob/db0957d3cbae617b72995ee3db8790081f2095ef/charts/argo-cd/values.yaml#L142)
- [server logFormat](https://github.com/argoproj/argo-helm/blob/db0957d3cbae617b72995ee3db8790081f2095ef/charts/argo-cd/values.yaml#L919)
- [repo server logFormat](https://github.com/argoproj/argo-helm/blob/db0957d3cbae617b72995ee3db8790081f2095ef/charts/argo-cd/values.yaml#L1498)
- [notifications logFormat](https://github.com/argoproj/argo-helm/blob/db0957d3cbae617b72995ee3db8790081f2095ef/charts/argo-cd/values.yaml#L2211)


We'd have to extend the templates and values.yaml for argo-workflows to take advantage of the `log-format` argument [here](https://github.com/argoproj/argo-workflows/blob/e31ffcd339370d6000f86d552845d7d378620d29/cmd/argoexec/commands/root.go#L39) like we did in argo-cd [here](https://github.com/argoproj/argo-helm/blob/db0957d3cbae617b72995ee3db8790081f2095ef/charts/argo-cd/templates/argocd-notifications/deployment.yaml#L43)
