### ISSUE TITLE
[argo-cd] Allow for specifying Certificate Authority as Secret and have it be trusted by the installation

### ISSUE THREAD

**Issue by rgarcia6520** [argoproj/argo-helm#1443]
### Is your feature request related to a problem?

When setting up SSO pointing to an internal OIDC host the pods state they cannot complete the connection and do not trust the certificate. 

We are currently performing this [workaround showed here](https://github.com/argoproj/argo-cd/issues/4344#issuecomment-890382825) however several of the other helm-charts we deploy and configure allow for specifying a certificate authority as a secret and getting auto-mounted into the pods.

### Related helm chart

argo-cd

### Describe the solution you'd like

The ability to have a value (global or otherwise) to list an array of kubernetes secrets which get mounted into `/etc/ssl/certs/` on the pods and therefore trusted by the installation.

### Describe alternatives you've considered

Currently using this [workaround showed here](https://github.com/argoproj/argo-cd/issues/4344#issuecomment-890382825) but would be nice for the chart to handle these on the backend

**Comment by pdrastil** [comment]
Hi @rgarcia6520 - See following in documentation: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#configuring-a-custom-root-ca-certificate-for-communicating-with-the-oidc-provider . This should be supported via `rootCA` in oidc.config section.

```yml
  oidc.config: |
    ...
    rootCA: |
      -----BEGIN CERTIFICATE-----
      ... encoded certificate data here ...
      -----END CERTIFICATE-----
```

**Comment by rgarcia6520** [comment]
Look like support for this was added in recent versions

https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#configuring-a-custom-root-ca-certificate-for-communicating-with-the-oidc-provider

Though pointing to an existing certificate in the namespace doesn't get loaded properly.

**Comment by zillani** [comment]
from which version is this added @rgarcia6520
