### ISSUE TITLE
[argo-events] Is deploying 1.7.x supported with this chart?

### ISSUE THREAD

**Issue by dave08** [argoproj/argo-helm#1458]
### Describe the bug

It seems like appVersion is holding by 1.6.0, and there are major changes in 1.7.x (migrating to jetstream)...

### Related helm chart

argo-events

### Helm chart version

latest

### To Reproduce

...

### Expected behavior

...

**Comment by pdrastil** [comment]
Hi @dave08,
the version 1.7.x of the controller is supported by 2.x version of the chart. Main difference is that 3 controllers were merged into 1 and there is now configuration for JetStream as you mentioned.

**Comment by dave08** [comment]
Thanks @pdrastil! I just noticed the argo-events-2.x tags... I thought that was only on the master branch... Until this day helm versioning is quite confusing...
