### ISSUE TITLE
Ingress for argocd not working with new helm chart

### ISSUE THREAD

**Issue by bnouvelbmll** [argoproj/argo-helm#148]
**Describe the bug**
When enabling ingress it maps to port "server" and ingress-controller in our case traefik, doesn't resolve anymore link to service. Ports on service are named "http" and "https". We use http intracluster as we are using a secure CNI network. We would expect ingress to point to "http" port.
Changing ingress from port "server" to port "http" fixes the bug.

**Expected behavior**
The ingress generated by the chart should enable connectivity to the UI without having to be fixed manually.

**Comment by jdeprin** [comment]
The port names are dynamic based on the server name:
https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/ingress.yaml#L3
https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/deployment.yaml#L78

Are you sure your server deployment is updating?

**Comment by bnouvelbmll** [comment]
I have used helm update and helm upgrade now.
Nowe the name of the port on the service port are hard-coded  on the
service:

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/service.yaml

**Comment by jdeprin** [comment]
What should the functionality be here?  The raw manifests do have two service ports 80/443.  The deployment only has one container port.  If a user is terminating SSL at their ingress should we route traffic to the http service port?  That seems like a complex setup.

The existing setup works for nginx ingress but I am thinking that is because it may not recognize named ports like other ingresses do. 

I think we'll need input from the developers on this one.

**Comment by bnouvelbmll** [comment]
The fix is not that complex: it is just that the ingress refers to a
serviceport name and not to the containerport name, the parameter is called
servicePort. The fact that the service offers two ports that connect to the
same containerport is not the concern.  We have traefik as ingress manager
terminating ssl for the entire domain, the CNI is weave encrypts traffic on
transit inside the cluster,  so to expose argocd normally we just enable
the ingress in the maifest, and indeed we expect to connect to an http port
inside the cluster, it saves us having to set up certificates directly on
argo and all other services. The problem here was that traefik was not
saying that there was no pod behind the ingress because it could not
resolve the servicePort. Changing the ingress to point a specific port name
on the SERVICE did the fix. In some other cluster where we can't use weave
CNI, we are using istio, I haven't tested argocd in that framework too but
here too I would expect similarly the http ingress to point to the http
port of the service in the manifest.

**Comment by jdeprin** [comment]
I understand that you may terminate ssl at the ingress layer but that is not the case for everyone and ArgoCD supports (and defaults to) terminating SSL in the server pod.  I want to make sure that both use cases are supported.  If a user is allowing SSL traffic to flow into the service and then terminate at the pod level, making your suggested change may introduce a breaking change.

**Comment by rojopolis** [comment]
I have the same issue when using `aws-alb-ingress-controller`  I didn't have this issue with the 0.7 version of the chart so I'm abandoning my effort to upgrade for now.

**Comment by valerauko** [comment]
>ArgoCD supports (and defaults to) terminating SSL in the server pod

@jdeprin could you please point me to the configuration documentation about how to change that default? I've been struggling with getting Argo to work because it either goes into a redirect loop or "internal server error"s on me. I already have working TLS termination set up on my ingress controller. How do I get ArgoCD to work with that?

**Comment by seanson** [comment]
Configuration for terminating TLS at the ingress, configuring Traefik or using the AWS ALB configuration is available here: https://argoproj.github.io/argo-cd/operator-manual/ingress/

If there is any configuration in the Helm chart for enabling these patterns please raise a specific Issue for that type and we'll be glad to help get a PR up and going.
