### ISSUE TITLE
[argo-cd]User info in UI not displaying the currently logged in user after integration with keycloak

### ISSUE THREAD

**Issue by preethignanesh** [argoproj/argo-helm#1486]
### Describe the bug

On login to the Argo CD UI, if the user needs to know the name of the logged in user, then he has to click on the User Info tab on the left panel. If the user is logged in via keycloak to the UI, then the username field is empty. But if the user logs in via normal login, we do see the username of the logged in user.

### Related helm chart

argo-cd

### Helm chart version

5.4.7

### To Reproduce

1. Install Argo CD helm charts - version 5.4.7
2. Integrate Argo CD with keycloak provider following the steps mentioned in docs - https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/
3. In the Argo CD UI, login to the user via button 'Login via Keycloak'
4. Click on the User Info tab on the left panel.
5. Username field is empty but it does populate the other fields like Issuer and Groups

### Expected behavior

When the user logs into the Argo CD UI via normal login and clicks on the User Info section, it clearly displays the name of the logged in user and the Issuer as Argo CD but when the user tries to login to the UI via keycloak, then the username field is empty but the other fields like Issuer and GroupName is pre-populated.

### Screenshots

<img width="1440" alt="Screen Shot 2022-09-22 at 6 37 31 AM" src="https://user-images.githubusercontent.com/79624602/191951618-16fe58d9-0a8a-41a6-ba1f-a4ba60aae4c5.png">

Attached the screenshot of the Argo CD UI with the missing username field

**Comment by pdrastil** [comment]
Hi,
there is nothing we can do about Keycloak integration. I've seen this issue with a different SSO provider that did not had user info endpoint configured or not all scopes were requested. If you are sure that this is working properly please raise an issue in upstream repository: https://github.com/argoproj/argo-cd
