### ISSUE TITLE
most recent version of helm chart is not on https://argoproj.github.io/argo-helm

### ISSUE THREAD

**Issue by louis-murray** [argoproj/argo-helm#15]
most recent chart up is from june

**Comment by louis-murray** [comment]
@jessesuen fyi. not sure who else to tag for this

**Comment by jessesuen** [comment]
Thanks @louis-murray. @alexmt was handling this but I'm unsure of the new process now that the site has been redone. Will work with him.

**Comment by alexmt** [comment]
Fixed. I've documented steps to update https://argoproj.github.io/argo-helm here: https://github.com/argoproj/argo-helm#publishing-changes
