### ISSUE TITLE
Cannot install extensions along with Argo CD

### ISSUE THREAD

**Issue by krancour** [argoproj/argo-helm#1501]
### Describe the bug

Ever since https://github.com/argoproj/argo-helm/pull/1342 it is not possible to include extensions in your initial installation of Argo CD.

### Related helm chart

argo-cd

### Helm chart version

Every version since #1342 was merged

### To Reproduce

```shell
helm install argo-cd argo-cd \
  --repo https://argoproj.github.io/argo-helm \
  --version 5.5.6 \
  --create-namespace \
  --namespace argo-cd \
  --set server.extensions.enabled=true \
  --set server.extensions.contents[0].name=argo-rollouts \
  --set server.extensions.contents[0].url=https://github.com/argoproj-labs/rollout-extension/releases/download/v0.2.0/extension.tar
```

### Expected behavior

One should be able to include extensions in their installation of Argo CD.

### Additional context

I understand what some of the motivations for the change were, but I humbly propose that this also is a pretty significant problem. The only workaround I know of currently is to leave extensions out of the initial installation and _immediately_ do an upgrade to add in the extensions.

**Comment by krancour** [comment]
@pdrastil does your PR really fix this? It looks like it provides an alternative way to install extensions using a different chart, but it doesn't fix the broken feature of _this_ chart.

**Comment by pdrastil** [comment]
@krancour Yes that's completely correct and content was removed from the chart because it will never work. Same was done for applications and project in https://github.com/argoproj/argo-helm/pull/1356
