### ISSUE TITLE
Migration from 4.X to 5.X chart and Helm custom plugin breaking change

### ISSUE THREAD

**Issue by pnowy** [argoproj/argo-helm#1520]
### Describe the bug

Hi,

I would say that this is not typical bug but more documentation update suggestion/question.

I was migrating from 4.X chart version to 5.X. In my setup there was used Helm init container to setup Helm plugins according to ArgoCD documentation (https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#using-initcontainers).

In Helm chart 4.X the repos server didn't have any Helm environment variables. In chart 5.X I noticed by default the following env variables:

```
- name: HELM_CACHE_HOME
  value: /helm-working-dir
- name: HELM_CONFIG_HOME
  value: /helm-working-dir
- name: HELM_DATA_HOME
  value: /helm-working-dir
```

Above cause some issues:

- error in ArgoCD comparison process
- stopped working authentication

To make it working again some adjustment were needed to provided chart Helm settings:

```
    volumes:
      - name: gcp-credentials
        secret:
          secretName: my-gcp-credentials
    volumeMounts:
      - name: gcp-credentials
        mountPath: /gcp
    env:
    initContainers:
      - name: helm-gcp-authentication
        image: alpine/helm:3.8.1
        volumeMounts:
          - name: helm-working-dir
            mountPath: /helm-working-dir
          - name: gcp-credentials
            mountPath: /gcp
        env:
          - name: HELM_CACHE_HOME
            value: /helm-working-dir
          - name: HELM_CONFIG_HOME
            value: /helm-working-dir
          - name: HELM_DATA_HOME
            value: /helm-working-dir
        command: [ "/bin/sh", "-c" ]
        args:
          - apk --no-cache add curl;
            helm plugin install https://github.com/hayorov/helm-gcs.git;
            helm repo add my-gcs-repo gs://my-private-helm-gcs-repository;
            chmod -R 777 $HELM_DATA_HOME;
```

### Related helm chart

argo-cd

### Helm chart version

5.5.9

### To Reproduce

1. Setup init containers according to ArgoCD documentation with 4.X Helm chart
2. Upgrade chart to 5.X version
3. Helm custom config stopped working (see bug description)

### Expected behavior

I think maybe it's worth to mention about this breaking changes in documentation or maybe the ArgoCD documentation part should be updated (?). I didn't check whether new env HELM settings is also in kustomize (then probably ArgoCD docs should be updated) or it is only Helm chart change (then probably should be pointed in upgrade docs).

Hope that maintainers could point the right direction. Thanks!

**Comment by pdrastil** [comment]
Hi @pnowy - the Helm env values are actually in base manifests [here](https://github.com/argoproj/argo-cd/blob/2fc7c7da733cc5782ccaabf0ef288f00dd2e6638/manifests/base/repo-server/argocd-repo-server-deployment.yaml#L140) and volume is actually `helm-working-dir` not `helm` so examples / upstream doc should be updated.

**Comment by mkilchhofer** [comment]
There was already an issue for that case:
- #1118

But as you can see in this PR, we introduced it in 3.32.1 not 4.x:
- https://github.com/argoproj/argo-helm/pull/1103

4.0.0 is like this: https://github.com/argoproj/argo-helm/blob/argo-cd-4.0.0/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L62-L67

And as @pdrastil mentioned, we just followed upstream manifests.
