### ISSUE TITLE
Use https for dex server

### ISSUE THREAD

**Issue by psimms-r7** [argoproj/argo-helm#1537]
### Is your feature request related to a problem?

Should we be using https for the dex server?

As per this issue
https://github.com/argoproj/argo-cd/issues/10841

### Related helm chart

argo-cd

### Describe the solution you'd like

By default use https for the dex server

**Comment by pdrastil** [comment]
This will be relevant in 2.5 and there is already some initial implementation. 

- https://github.com/argoproj/argo-helm/pull/1477
- https://github.com/argoproj/argo-helm/pull/1474 - most of it is here and I will be pulling it out into separate PR

**Comment by pdrastil** [comment]
Update - I've added support for Dex using HTTPS/TLS directly for 2.5.0 release. I will add support for custom Dex certs after that because it's not clear to me if these should be just internally facing certs using K8s endpoints or there is also need for externally facing certs.

**Comment by mkilchhofer** [comment]
Resolved via #1568
