### ISSUE TITLE
Access app resource from repo-server -> add RBAC to the repo-server

### ISSUE THREAD

**Issue by fiftoine** [argoproj/argo-helm#154]
**Is your feature request related to a problem? Please describe.**
I'm writing a plugin for argocd config management. That plugin needs to read the argo app details (like destination namespace, annotations, labels,...) and I don't want to put those values as env for each of the apps that will use that plugin. 

**Describe the solution you'd like**
Adding configurable RBAC for the repo-server component would allow to execute `kubectl` commands and read the app manifest.

**Describe alternatives you've considered**
I forked the chart to add the SA and associated RBAC and put it into a private helm chart repo.

**Additional context**

**Comment by seanson** [comment]
Is this a common enough use case that we should be providing a service account template in the Helm chart itself, or would it be enough to allow a single Helm value pointing to an externally created serviceAccount as is a common pattern in other charts?

**Comment by seanson** [comment]
Tested and merged, thanks for raising the issue!
