### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by hernanpl** [argoproj/argo-helm#1557]
### Is your feature request related to a problem?

KubeCon [Security Slam](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam)

### Related helm chart

other

### Describe the solution you'd like

This repo is signed up as part of the KubeCon [Security Slam](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam). I'm bringing to your attention the checklist from the official [CLOMonitor page for Argo](https://clomonitor.io/projects/cncf/argo#argo-helm) -- it refreshes every hour, so it should be up-to-date.

### Summary

**Repository**: argo-helm
**URL**: https://github.com/argoproj/argo-helm
**Checks sets**:  `CODE`
**Score**: 74

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  100%  |
|  License  |  75%  |
|  Best Practices  |  38%  |
|  Security  |  80%  |
|  Legal  |  n/a  |

### Documentation [100%]

  - [x] Changelog ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Contributing](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Maintainers](https://github.com/argoproj/argo-helm/blob/main/OWNERS) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/argoproj/argo-helm/blob/main/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [38%]

  - [x] [Artifact Hub badge](https://artifacthub.io/packages/search?repo=argo) ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [ ] OpenSSF badge ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/argoproj/argo-helm/releases/tag/argo-cd-5.5.20) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  
### Security [80%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool)) `EXEMPT`
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [x] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom)) `EXEMPT`
  - [x] Security policy ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [ ] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by eddie-knight** [comment]
whoops-- duplicate of #1508
