### ISSUE TITLE
Eventbus failed to get nats streaming version

### ISSUE THREAD

**Issue by pockyhe** [argoproj/argo-helm#1558]
### Describe the bug

I tried to update version of Argo helm chart. I used the Argo Workflow(Version 0.20.1) and Argo Event(Version 2.0.6).
After updating them successfully, I kubectl apply native event bus that caused error:
error":"failed to get nats streaming version, err: unsupported version \"0.22.1\", supported versions: \"latest\"","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:56\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227

And kubectl describe eventbus. It indicates that:
Status:
  Conditions:
    Last Transition Time:  2022-10-17T10:28:59Z
    Status:                True
    Type:                  Configured
    Last Transition Time:  2022-10-17T10:28:59Z
    Message:               Failed to build a statefulset spec
    Reason:                BuildStatefulSetFailed
    Status:                False
    Type:                  Deployed

It seems that there is gap between latest version of Argo workflow and latest version of Argo Event

### Related helm chart

argo-events, argo-workflows

### Helm chart version

2.0.6 0.20.1

### To Reproduce

***

### Expected behavior

***

**Comment by pdrastil** [comment]
Hi @pockyhe, thanks for mentioning this. I don't use Argo Workflows so I'm not sure what is causing the gap.

For events you can check [here](https://github.com/argoproj/argo-helm/blob/17e601148f0325d196e55a77a1b9577c8bbd926d/charts/argo-events/values.yaml#L65) to see that chart by default provides only the `latest` version and user is expected to create / pin his own versions. Would this help to fix your issue?

**Comment by pockyhe** [comment]
The problem is that you changed the version of nats as latest. However, Argo Event still use 0.22.1 to check version
![image](https://user-images.githubusercontent.com/64390829/196189660-341a1ce7-9094-484e-8f9f-03381f57109b.png)
which caused this mistake

**Comment by pockyhe** [comment]
I tried to install argo-event with customized value yml insteads of default 
![image](https://user-images.githubusercontent.com/64390829/196194456-b9f7b239-2bd9-4ecb-9ead-e7520d0eafa8.png)
 It worked successfully.

**Comment by pdrastil** [comment]
@pockyhe Glad to hear that.
