### ISSUE TITLE
[argocd-redis-ha] seccompProfile is forbidden on k8s version 1.21

### ISSUE THREAD

**Issue by ayoub-elbachiri** [argoproj/argo-helm#1560]
### Describe the bug

k8s version: 1.21
argocd helm chart version: 5.6.0

After deploying the latest chart of argocd, redis-ha-server statefulset and redis-ha-proxy are not deploying cause of the seccompProfile injected by default from the argocd chart,

I tried to edit the statefulset manually and delete the seccompProfile from the specs, the pods poped up

### Related helm chart

argo-cd

### Helm chart version

5.6.0

### To Reproduce

1. deploy argocd helm chart on k8s

### Expected behavior

  kubectl describe sts
  Warning  FailedCreate  16s (x13 over 36s)  statefulset-controller  create Pod argocd-redis-ha-server-0 in StatefulSet argocd-redis-ha-server failed error: pods "argocd-redis-ha-server-0" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/config-init]: Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/redis]: Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/sentinel]: Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/split-brain-fix]: Forbidden: seccomp may not be set]

**Comment by pdrastil** [comment]
Hi @ayoub-elbachiri - this is actually part of redis-ha subchart [here](https://github.com/DandyDeveloper/charts/blob/30611121e114fea4eebf1202021fbcc6bd1ee1ef/charts/redis-ha/values.yaml#L169) that is used by argo-cd.

You can try to unset the value like this:

```yaml
redis-ha:
  containerSecurityContext:
    seccompProfile: null
```

**Comment by ayoub-elbachiri** [comment]
> 


> Hi @ayoub-elbachiri - this is actually part of redis-ha subchart [here](https://github.com/DandyDeveloper/charts/blob/30611121e114fea4eebf1202021fbcc6bd1ee1ef/charts/redis-ha/values.yaml#L169) that is used by argo-cd.
> 
> You can try to unset the value like this:
> 
> ```yaml
> redis-ha:
>   containerSecurityContext:
>     seccompProfile: null
> ```

Hi @pdrastil i have just tried it and it doesn't work, outputs the same results :(

**Comment by pdrastil** [comment]
Hi @ayoub-elbachiri after testing this it seems that `null` value works only with `--set` argument for helm. Only way that worked for me to clear this argument was to use following command.

```sh
helm install argocd argocd/argo-cd -f my-values.yaml \
  --set redis-ha.containerSecurityContext.seccompProfile=null \
  --set redis-ha.haproxy.containerSecurityContext.seccompProfile=null
```

**Comment by mkilchhofer** [comment]
> Hi @ayoub-elbachiri after testing this it seems that `null` value works only with `--set` argument for helm. Only way that worked for me to clear this argument was to use following command.
> 
> ```shell
> helm install argocd argocd/argo-cd -f my-values.yaml \
>   --set redis-ha.containerSecurityContext.seccompProfile=null \
>   --set redis-ha.haproxy.containerSecurityContext.seccompProfile=null
> ```

Yup, this is a helm bug:
- https://github.com/helm/helm/issues/9136
- https://github.com/helm/helm/issues/9027

😢

**Comment by pdrastil** [comment]
As we are following upstream whole chart will have seccomp profile enabled by default after PR above is merged.

**Comment by pdrastil** [comment]
Cloased as https://github.com/argoproj/argo-helm/pull/1579 now enforces 1.22
