### ISSUE TITLE
Metrics - Enable argocd-metrics alongside argocd-server-metrics

### ISSUE THREAD

**Issue by Lobosque** [argoproj/argo-helm#1561]
### Is your feature request related to a problem?

https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/ describes two metrics services, one for application controller (port 8082) and another for API server (port 8083)
Enabling metrics on the helm creates the `argocd-server-metrics` which correctly exposes metrics from the API Server.
However, no service is created for the Application Controller Metrics

### Related helm chart

argo-cd

### Describe the solution you'd like

a similar service for exposing application controller metrics

**Comment by pdrastil** [comment]
Hi @Lobosque - I believe this is already present via `controller.metrics.enabled` (port 8082) and `server.metrics.enabled` (port 8083) feature toggles.

**Comment by Lobosque** [comment]
@pdrastil you are correct - this worked as expected. thanks!
