### ISSUE TITLE
Add license scan badge to the README

### ISSUE THREAD

**Issue by eddie-knight** [argoproj/argo-helm#1562]
Part of #1508.

It's not a security item, but maintainers should be able to generate a license scan badge really easily using FOSSA (the alternative is a paid Snyk tool). Once a license scan badge is in the repo, that license scanning check should go green.

1. Maintainer should sign in to https://fossa.com using GitHub auth
2. Authorize connectivity, add/import this repo, and begin the scan
3. After the import is completed, a license badge will be generated, see image below (click badge to open modal)
4. Add scan to CI ([ref](https://github.com/artifacthub/hub/blob/860e933d116da8ab57e58a6e5527a566537900d8/.github/workflows/fossa.yml))
<img width="1234" alt="Screen Shot 2022-10-17 at 9 45 28 PM" src="https://user-images.githubusercontent.com/21176439/196325530-88170eaf-2814-404e-88be-986ef779acef.png">

**Comment by pdrastil** [comment]
@mkilchhofer Can you take a look into this?

**Comment by mkilchhofer** [comment]
@crenshaw-dev 
Can we use snyk as well? I see that in our (community) repository we inherit the token for Snyk. Can we try the workflow of argo-cd?

https://github.com/argoproj/argo-cd/blob/776d8f97ccc95584b7ac586f0e7091819e39f583/.github/workflows/update-snyk.yaml#L1-L36

**Comment by eddie-knight** [comment]
@mkilchhofer Argo CD doesn't currently have License Scanning identified by CLOMonitor.

ref: https://clomonitor.io/projects/cncf/argo#argo-cd_license

**Comment by mkilchhofer** [comment]
not stale
