### ISSUE TITLE
Ingress not creating

### ISSUE THREAD

**Issue by holotrack** [argoproj/argo-helm#1565]
### Describe the bug

When i enable ingress it is not created from template:

![image](https://user-images.githubusercontent.com/100580892/196793304-6c2b10ed-a041-452d-9d95-45fbf6388024.png)

![image](https://user-images.githubusercontent.com/100580892/196793404-224fb0eb-83d3-45c3-94ff-2b337cbefe3d.png)

### Related helm chart

argo-workflows

### Helm chart version

0.20.1

### To Reproduce

download helm chart, update values files to enable ingress, try to deploy or create template eg:

```
helm template argo-workflows argo/argo-workflows -n values.yaml -n argocd|grep Ingress 
```

### Expected behavior

Ingress will be created

### Screenshots

![image](https://user-images.githubusercontent.com/100580892/196793879-c9e2231a-5bbc-4e09-8ef2-d29d4f485f49.png)

**Comment by drimailorr** [comment]
the same with argo-cd
