### ISSUE TITLE
ApplicationSet CRD update for Gitlab Pull request generator

### ISSUE THREAD

**Issue by nbjohnson** [argoproj/argo-helm#1567]
### Is your feature request related to a problem?

In Argocd v2.5.0 Gitlab was added to the Pull request generator. Currently the CRD does not have support for Gitlab in the matrix pull request generator, and it looks like none of the other pull request generator locations either.

### Related helm chart

argo-cd

### Describe the solution you'd like

For the matrix Gitlab pull request generator https://github.com/argoproj/argo-cd/blob/v2.5.0-rc3/manifests/crds/applicationset-crd.yaml#L2399 needs to be added at https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/crds/crd-applicationset.yaml#L2406

Looks like there are two other locations that need to have the Gitlab pull request generator added as well:

- https://github.com/argoproj/argo-cd/blob/v2.5.0-rc3/manifests/crds/applicationset-crd.yaml#L4629 -> https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/crds/crd-applicationset.yaml#L4558
- https://github.com/argoproj/argo-cd/blob/v2.5.0-rc3/manifests/crds/applicationset-crd.yaml#L5724 -> https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/crds/crd-applicationset.yaml#L5576

All instances of `pullRequest` in https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/crds/crd-applicationset.yaml should have Gitlab as an option

**Comment by pdrastil** [comment]
@nbjohnson We do not create Helm charts with release candidate versions right now. This will be present when stable version 2.5.0 is officially released.

**Comment by mkilchhofer** [comment]
Resolved via #1568
