### ISSUE TITLE
Argo CD will not work with redis.enabled: false

### ISSUE THREAD

**Issue by disposab1e** [argoproj/argo-helm#157]
**Describe the bug**
With redis to false syncing of apps is not possible. 

**To Reproduce**
1. Install Argo CD with latest Helm Chart Version
2. Install guestbook-helm example
3. See errors
Unable to load data: dial tcp: lookup argocd-redis on XX.XX.XX.XX:53: no such host

**Expected behavior**
Syncing of apps is possible.

**Additional context**
Reproducable behaviour on OpenShift and Minikube. With redis enabled all is fine! I used the defaults from values.yaml

![2019-11-07_08-44-11](https://user-images.githubusercontent.com/48065501/68369613-0104a000-013b-11ea-8214-d4a47a32325c.png)
![2019-11-07_08-44-36](https://user-images.githubusercontent.com/48065501/68369614-0104a000-013b-11ea-83e8-d9b53526883e.png)

**Comment by jdeprin** [comment]
@alexec this was discussed in the PR: https://github.com/argoproj/argo-helm/pull/129#pullrequestreview-301053976.  Should it be changed back to default `enabled: true` or remove the ability to disable it?

**Comment by disposab1e** [comment]
Well done!
