### ISSUE TITLE
Argocd-cm improvement

### ISSUE THREAD

**Issue by Gianluca755** [argoproj/argo-helm#1580]
### Related helm chart

argo-cd

### Describe the solution you'd like

Hello people,
there is some stuff missing in the `values.yaml` for the configmap, such as `users.session.duration`, `passwordPattern` and others.
If not a fix, add at least a reference to https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml

Bye

**Comment by pdrastil** [comment]
It's referened on the first line above `configs.cm` [here](https://github.com/argoproj/argo-helm/blob/77de11bcab8622002bf9595ffb16a705aec5a96e/charts/argo-cd/values.yaml#L89). Stuff is missing intentionally as it's optional.
