### ISSUE TITLE
Azure OIDC login fails after 5.8.0 upgrade

### ISSUE THREAD

**Issue by agentq15** [argoproj/argo-helm#1583]
### Describe the bug

After upgrading to 5.8.0 we can't login using Azure anymore.

In the console it shows

`Uncaught (in promise) Error: {"error":"invalid session: Failed to query provider \"https://login.microsoftonline.com/<tenant-ID>/v2.0\": Get \"https://login.microsoftonline.com/<tenant-ID>/v2.0/.well-known/openid-configuration\": x509: certificate signed by unknown authority","code":16,"message":"invalid session: Failed to query provider \"https://login.microsoftonline.com/<tenant-ID>/v2.0\": Get \"https://login.microsoftonline.com/<tenant-ID>/v2.0/.well-known/openid-configuration\": x509: certificate signed by unknown authority"}
    at x.<anonymous> (main.b061a2c16573e4046c76.js:2:1010482)
    at t.emit (main.b061a2c16573e4046c76.js:2:151144)
    at XMLHttpRequest.<anonymous> (main.b061a2c16573e4046c76.js:2:1014306)`
    
   In the network tab it doesn't even get a request to microsoft anymore. Just returns us back to the login screen with this error in the console.

### Related helm chart

argo-cd

### Helm chart version

5.8.0

### To Reproduce

Log in via Azure

### Expected behavior

To be logged in using Azure AD account

### Screenshots

Request flow
 ![image](https://user-images.githubusercontent.com/10948042/198032622-26b7b6fc-a5e6-48c3-a009-27cf348337c4.png)

**Comment by pdrastil** [comment]
@agentq15 Maybe this relates to https://github.com/argoproj/argo-helm/issues/1443

**Comment by agentq15** [comment]
But this is for Azure and not something hosted by us. Also it is still working in our production environment which is running chart version 5.6.0

**Comment by pdrastil** [comment]
There is no mention about OIDC change in 2.5 release notes. Maybe this would be question for upstream project https://github.com/argoproj/argo-cd

Only thing I've found is this bypass you can also try to use:

```yml
configs:
  cm:
    oidc.tls.insecure.skip.verify: "true"
```

**Comment by agentq15** [comment]
Hmm, that fixed the issue after a restart of the pods.
But tried removing it and restarted again and it is still working now. Weird!

**Comment by pdrastil** [comment]
Really weird - I've seen that upstream have mostly issues related to Dex after upgrade. If you see this again it might be worth a while to ping them.

**Comment by crenshaw-dev** [comment]
@agentq15 what chart version are you upgrading from? Want to compare Argo CD versions and see if I can find any interesting differences.

**Comment by robbert229** [comment]
When doing a fresh deploy of argo-cd at 5.8.0 to a new cluster I am encountering this same issue.

**Comment by agentq15** [comment]
@crenshaw-dev It was from v5.6.0

**Comment by crenshaw-dev** [comment]
> Hmm, that fixed the issue after a restart of the pods.
> But tried removing it and restarted again and it is still working now. Weird!

@agentq15 have you been able to continue with 5.8.0 and verification enabled?

**Comment by agentq15** [comment]
Yeah no issues after that

**Comment by Tizull** [comment]
The chart fundamentally changed after 5.8.0. The configs section is completely different. I had the same problem until comparing the chart to my values file.

**Comment by pdrastil** [comment]
Hi @Tizull - config sections are exactly same with backward compatibility `server.configs` moved to `configs.cm` and `server.rbacConfig` moved to `configs.rbac` without changing any fields inside. If you leave previous configuration section as they were you will get a deprecation warning but data are still loaded from original place (there were few hiccups for which I'm sorry). The upgrade path for configs was fully fixed from chart version >= 5.12.3.

What really changed in 5.8.0 is Argo CD image that was upgraded to 2.5.0 + Dex that runs on https by default instead of http + new configuration options in configs.params.

**Comment by el-aasi** [comment]
We are observing the same issue in chart 5.34.6 app version 2.7.3. Basically as described by the OP as well as posted workaround still works. Any suggestions?

**Comment by Dominic1DL** [comment]
This issue should my be re-opened if there is no follow up Issue.
I had the same Issue Today in Version v2.10.6+d504d2b
