### ISSUE TITLE
Dex TLS volume is always enabled

### ISSUE THREAD

**Issue by johgoe** [argoproj/argo-helm#1588]
### Describe the bug

volume argocd-dex-server-tls should not exists when dex is disabled

https://github.com/argoproj/argo-helm/blob/7e30521dd28ae52c04e0576fb390fd3be49f2bdc/charts/argo-cd/templates/argocd-server/deployment.yaml

### Related helm chart

argo-cd

### Helm chart version

5.8.2

### To Reproduce

Install  helm chart with value `dex: enabled: false`

### Expected behavior

No dex related content (volumes, config etc) are generated.

**Comment by pdrastil** [comment]
The volume is optional - see here https://github.com/argoproj/argo-helm/blob/7e30521dd28ae52c04e0576fb390fd3be49f2bdc/charts/argo-cd/templates/argocd-server/deployment.yaml#L401

**Comment by pdrastil** [comment]
After discussion with @mkilchhofer  we decided to keep it as-is for now because this optional volume is defined in upstream manifests.
