### ISSUE TITLE
New aws-config volume always enabled

### ISSUE THREAD

**Issue by johgoe** [argoproj/argo-helm#1589]
### Describe the bug

The new version 5.8.2 has a volume for AWS even if it's not a aws cluster at all.

```
- mountPath: /home/argocd/.aws
  name: aws-config
```

### Related helm chart

argo-cd

### Helm chart version

5.8.2

### To Reproduce

Install 5.8.2

### Expected behavior

No aws configuration if it's not installed on AWS

**Comment by pdrastil** [comment]
Hi @johgoe - this was intentional change because of security contexts that will be enabled in this PR https://github.com/argoproj/argo-helm/pull/1579 . All Argo containers will enforce read only filesystem so keeping this volume always on ensures compatibility.

**Comment by pdrastil** [comment]
I would test if the volume is actually needed at all with 2.5.0 release or if `/home/argocd/.aws` path have problems and needs this extra mount.

**Comment by pdrastil** [comment]
This was reason why it was added in the first place: https://github.com/argoproj/argo-helm/pull/1006
