### ISSUE TITLE
argocd extraArgs works only with hashes despite stating otherwise

### ISSUE THREAD

**Issue by mckjhd** [argoproj/argo-helm#159]
**Describe the bug**
By looking at https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L199 one can assume that extraArgs expects a list, but, in fact, it works only with hashes, because of: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/deployment.yaml#L60.

If a list of options is provided then it becomes --0=option, and argocd server pod fails to start.

**Comment by jdeprin** [comment]
you would need to specify a key and value such as:
```yaml
extraArgs:
  insecure: ""
```
to produce a key with no value: `--insecure`.  I think this is the only way to accommodate command line flags with and without values.

**Comment by mckjhd** [comment]
@jdeprin `insecure: true` works as well, thanks to golang, but imo template code needs to change too, as it produces unrunnable configuration if array is provided.

**Comment by rojopolis** [comment]
> you would need to specify a key and value such as:
> 
> ```yaml
> extraArgs:
>   insecure: ""
> ```
> 
> to produce a key with no value: `--insecure`. I think this is the only way to accommodate command line flags with and without values.
> 
> The values comment should be updated to reflect this.

This definitely is not the only way to accommodate both use cases:  simply accept a list of extrArgs verbatim:
```yaml
server:
  extraArgs:
  - --flag
  - --key=value
```
I don't see the value in adding the `--` in the template.

**Comment by jdeprin** [comment]
Seems like a stylistic choice.  You could pass in plan strings to a list but then you could also pass in yaml key value pairs.  In my experience the later has been the acceptable method.  I'll update the value file to be more clear.

**Comment by rojopolis** [comment]
@jdeprin of course it is...  I was just responding to this part of your comment:

>I think this is the **only way** to accommodate command line flags with and without values.

I don't have a strong opinion about it, but in a previous version of this chart it was the way I described and the change broke my config in a really confusing way.

**Comment by seanson** [comment]
Looking through the Helm stable charts and its about a 60/40 split between args as an array vs args as a hash. I'd go for the list of arguments for the following reasons:
- Seeing a list with flags like `--foo` is easier to interpret as a command line argument
- People coming from other systems like docker-compose will be familiar with the syntax
- The target in k8s yaml is a list so the Helm templating itself is a simple toYaml call

**Comment by seanson** [comment]
Closing for now, will open a new issue in the future if this comes up again enough to merit a change for version 2.x.
