### ISSUE TITLE
Add argo-helm argo-cd implementation of namespace-install.yaml

### ISSUE THREAD

**Issue by racker7** [argoproj/argo-helm#1592]
### Is your feature request related to a problem?

no

### Related helm chart

argo-cd

### Describe the solution you'd like

argo-helm/argo-cd uses this to create full implementation of ArgoCD:
https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml

I would like to be able to create additional ArgoCD instances on same cluster using this with helm:
https://github.com/argoproj/argo-cd/blob/master/manifests/namespace-install.yaml

The main differentiators of this alternate install method are skipping setup of 3 CRDs and 2 Cluster Roles.  This is dependent on having a full install paired alongside it.

The goal is to have multiple ArgoCD instances to separate admin usage from application teams, for security and performance isolation.

Thank you for your consideration.

### Describe alternatives you've considered

Alternative is using non-helm method to install the namespace-install.  This means we don't have all the objects managed by helm, and its less consistent/supportable.

**Comment by racker7** [comment]
Update: I see the latest version of argo-helm has this option: crds.install
Perhaps this accomplishes the goal.  I'll check with the team about upgrading to latest.

**Comment by pdrastil** [comment]
For cluster roles thare are these two switches:

```yam
controller:
  clusterAdminAccess:
    enabled: false

server:
  clusterAdminAccess:
    enabled: false
```

**Comment by pdrastil** [comment]
Mentioned PR above will change the config on all components to single key.

```yaml
global:
  rbac:
    clusterRoles: true
```

**Comment by racker7** [comment]
Thank you very much.  I'll give this a try, hopefully in the next week or so.

**Comment by racker7** [comment]
hi @pdrastil   can I ask another question please?
I am not sure what roles this creates exactly.
Do I want to enable this on the primary admin argo instance or the secondary application argo instance, or both?
global.rbac.aggregatedRoles / createAggregateRoles

**Comment by racker7** [comment]
ok i figured out that you enable aggregate roles in the secondary application argo instance and not the main primary admin argo instance.

the result is you get CRDs and ClusterRoles in the main instance (app-controller,server)
in the secondary instances you do not get CRDs, you get ClusterRoles that are 'aggregated' (admin/edit/view)

the CRDs appear to be accessible to the secondary instance from initial testing.

ty for your help.

**Comment by racker7** [comment]
update.  we decided one argocd per cluster is simpler to support as the multiple is not well documented.  ty for all your help.
