### ISSUE TITLE
PR #1549 causes Prometheus serviceMonitor to be unable to collect metrics

### ISSUE THREAD

**Issue by cimin0** [argoproj/argo-helm#1601]
### Describe the bug

#1549 failed to update port name for argocd-application-controller network policy which causes prometheus to fail to connect since the previous port no longer exists.

Will file PR to fix shortly.

### Related helm chart

argo-cd

### Helm chart version

5.12.1

### To Reproduce

deploy argocd chart 5.12.1 with prometheus enabled

check statefulset/service/servicemonitor port names, should be 'metrics'

check network policy port name, reads 'controller'

### Expected behavior

prometheus should be able to scrape on port metrics

### Screenshots

![Screen Shot 2022-10-31 at 11 51 09 AM](https://user-images.githubusercontent.com/58572548/199063782-e60d5939-aadf-4a9d-a260-6d9af442f9b4.png)

**Comment by pdrastil** [comment]
Hi @cimin0 - thanks for catching this. Fix is on the way.
