### ISSUE TITLE
[argo-cd] Add ability to annotate Deployments and StatefulSets

### ISSUE THREAD

**Issue by jstewart612** [argoproj/argo-helm#1604]
### Is your feature request related to a problem?

I have third party systems which need to annotate these objects as to interact with them.  I cannot do so with your helm chart.

### Related helm chart

argo-cd

### Describe the solution you'd like

Helm chart values be added allowing the Deployments and Statefulsets to themselves have annotations added by the helm chart.

**Comment by pdrastil** [comment]
Isn't already implemented `podLabels` and `podAnnotations` option in every component enough?

**Comment by jstewart612** [comment]
A PR is being submitted shortly.

**Comment by jstewart612** [comment]
PR now up to address and in need of review: https://github.com/argoproj/argo-helm/pull/1605

**Comment by jstewart612** [comment]
PR posted to address this: https://github.com/argoproj/argo-helm/pull/1608

**Comment by pdrastil** [comment]
Closing as resolved via https://github.com/argoproj/argo-helm/pull/1608
