### ISSUE TITLE
Breaking change when specifying server.config value keys

### ISSUE THREAD

**Issue by dowlingw** [argoproj/argo-helm#1611]
### Describe the bug

When upgrading to version `5.7.0` of the `argo-cd` chart, users will experience a breaking change if they are providing _any_ chart values under the `server.config` key.

### Related helm chart

argo-cd

### Helm chart version

5.7.0

### To Reproduce

Deploy 5.6.8 of the argo-cd chart whilst specifying any chart values under `server.config` key.

Update to version 5.7.0 or newer of the chart (retaining the `server.config` chart values), and observe that all the default values previously provided by this chart are no longer present in the argo config map.

An example is the `instanceLabelKey` - following the upgrade, all applications will show a diff to update the instance label from `argocd.argoproj.io/instance` to `app.kubernetes.io/instance`

### Expected behavior

ArgoCD to continue to provide default values following the upgrade.

### Additional context

In previous versions of this chart, users are able to relay on behaviour that is a combination of:
* Configuration specified by the `server.config` keys
* Configuration provided by `server.config` defaults in the chart provided values.yaml

#1528 (released in version 5.7.0 of this chart) moves to use `coalesce` with the intent of providing backwards compatible changes.

Because the default values have been moved to `configs.cm`, this means that users already providing `server.config` chart values will lose any default values (as `coalesce` will only choose the entire non-empty value).

The correct implementation of #1528 should use `merge` in favour of `coalesce` to provide the intended behaviour.

I believe this is the root cause of #1587.

**Comment by pdrastil** [comment]
Hi @dowlingw I've tested with current version 5.12.2? I've used following sample with commands to test the upgrade.

```sh
helm install argocd argo/argo-cd -n argocd -f extra.yaml --version 5.6.8
helm upgrade argocd argo/argo-cd -n argocd -f extra.yaml
cat extra.yaml
   1   │ server:
   2   │   config:
   3   │     application.instanceLabelKey: argocd.argoproj.io/instance
```

**Comment by pdrastil** [comment]
I see and agree with your point about `coalesce` vs `merge` behaviour and this can be improved.

**Comment by dowlingw** [comment]
@pdrastil Thanks, that was super quick - I was going to raise a PR on this just now (start of my day) but looks like you beat me to it.

I'll have the team re-test our upgrade (I think I missed some repro detail on this) with the new version without our workaround.

Thx again :)

**Comment by pdrastil** [comment]
@dowlingw You are welcome. I thank you for the pointing out the gap for migration / consolidation of configs :)
