### ISSUE TITLE
Disable auth via helm set doesnt work

### ISSUE THREAD

**Issue by tanmay-bhat** [argoproj/argo-helm#1613]
### Describe the bug

When installing the the helm chart with overriding variables via helm `--set`, the parameters are not taken into consideration.

### Related helm chart

argo-cd

### Helm chart version

5.12.2

### To Reproduce

1. Install the helm chart using the below command : 
```
helm upgrade --install argocd argo/argo-cd --set configs.params."server.disable.auth"=true --version 5.12.2 --create-namespace -n argocd
```
2. Inspect the configmap : `argocd-cmd-params-cm` to check the values : 
```
kubectl get cm argocd-cmd-params-cm -n argocd -o yaml | grep server.disable.auth
  server.disable.auth: "false"
```

### Expected behavior

Auth disable key value should be set to `true`.

### Additional context

Workaround : 
```
helm upgrade --install argocd argo/argo-cd --set-string configs.params."server\.disable\.auth"=true --version 5.12.0 --create-namespace -n argocd
```

**Comment by pdrastil** [comment]
This is not a bug - we cannot fix incorrectly done shell escapes that will build different structure:

```sh
helm upgrade --install argocd argo/argo-cd --set-string configs.params."server\.disable\.auth"=tru
```
produces:
```yml
configs:
  params:
    server:
      disable:
        auth: true      
```

expected is following structure

```yml
configs:
  params:
    "server.disable.auth": true
```

Ref:
- https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
- https://github.com/helm/helm/issues/5027

**Comment by tanmay-bhat** [comment]
What's the better way to set `server.disable.auth` via `helm --set` ?
Is it using shell escape only as mentioned above ?

**Comment by pdrastil** [comment]
Yes if the value is string it needs to be escaped otherwise the dot signifies the map.

**Comment by tanmay-bhat** [comment]
Got it, thanks !!
