### ISSUE TITLE
Upgrade fails for chart version 5.14.1 on GKE with non-root error

### ISSUE THREAD

**Issue by cydergoth** [argoproj/argo-helm#1616]
### Describe the bug

```
Error: container has runAsNonRoot and image has non-numeric user (argocd), cannot verify user is non-root (pod: "argocd-dex-server-c89f47b79-9kkz2_argocd(dfaceb25-9024-4dc4-900c-6b9c1e8c8430)", container: copyutil)
```

### Related helm chart

argo-cd

### Helm chart version

5.13.1

### To Reproduce

Attempt to apply chart version 5.13.1 onto a Google cloud GKE cluster 

### Expected behavior

Chart deploys containers successfully

### Additional context

Applying using ArgoCD to update itself for [CVE ](https://www.openssl.org/news/secadv/20221101.txt)

This is blocking our ability to mitigate this CVE

Thanks!

**Comment by pdrastil** [comment]
Hi @cydergoth - do you have some custom overrides of the image? The init container for Dex is using same image as other Argo CD components:

```yaml
initContainers:
      - name: copyutil
        image: quay.io/argoproj/argocd:v2.5.1
```

This image have numeric user ID defined [here](https://github.com/argoproj/argo-cd/blob/21731c9c2d01994303c3f58935964aae6cfd6b7f/Dockerfile#L132)

**Comment by cydergoth** [comment]
I will check, thank you for the fast response

**Comment by cydergoth** [comment]
Yes, we are using a custom image for SOPS.

**Comment by cydergoth** [comment]
This as an error on our side in our custom additions Dockerfile
