### ISSUE TITLE
PR #1586 broke SSO RBAC in Argo Workflows

### ISSUE THREAD

**Issue by elemental-lf** [argoproj/argo-helm#1638]
### Describe the bug

PR #1586 removed the `sso.rbac.enabled` stanza from the controller config map and so made it impossible to activate SSO RBAC. Another user also noticed this and commented on the PR in question. SSO RBAC and its activation is covered in the [documentation](https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac).

### Related helm chart

argo-workflows

### Helm chart version

0.20.5 and above

### To Reproduce

* Deploy Argo Workflows chart with SSO and `server.sso.rbac.enabled` set to `true`
* Inspect config map and note that  `sso.rbac.enabled` stanza is missing

### Expected behavior

Setting `server.sso.rbac.enabled` to `true` should activate SSO RBAC.

**Comment by elemental-lf** [comment]
Note: From my tests it seems that SSO RBAC is broken in the latest version of Argo Workflows at the moment. I've noticed the same behavior described in https://github.com/argoproj/argo-workflows/issues/9989. But this is unrelated to this bug report as this bug is about not being able to activate SSO RBAC at all.

**Comment by yu-croco** [comment]
Hi @nxf5025 ,
as @elemental-lf mentioned, according to the [documentation](https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac), I think we need to keep the stanza for configmap by reverting https://github.com/argoproj/argo-helm/pull/1586 . WDYT? 🤔 

cc: @vladlosev

**Comment by vladlosev** [comment]
Yep it looks like I erred in suggesting the solution in https://github.com/argoproj/argo-helm/pull/1586. Unfortunately I cannot review the original changes there to suggest a better one, as they were force pushed over. It makes sense to revert it and we can discuss a better solution to the original issue. If the problem in question is https://github.com/argoproj/argo-helm/issues/1572, that appears to be a benign log entry, which can be taken care of by guarding [these lines](https://github.com/argoproj/argo-workflows/blob/55ad68022b17763e9265da10fa74d1c26031660d/server/apiserver/argoserver.go#L145-L146) with `if ssoIf.IsRBACEnabled()`.

**Comment by yu-croco** [comment]
Thank you for checking, @vladlosev !
I will make PR for fixing this current one. 🙋 

Regarding https://github.com/argoproj/argo-helm/issues/1572, I wonder if `.server.sso.rbac.enabled` was missing. 🤔
I will ask about the situation of values.yaml on original issue.

**Comment by simox-83** [comment]
Will this fix also [#9989](https://github.com/argoproj/argo-workflows/issues/9989) please? Thank you.
