### ISSUE TITLE
argocd-rbac-cm replaced when deploying 5.13.8

### ISSUE THREAD

**Issue by RicardoAlvialANS** [argoproj/argo-helm#1644]
### Describe the bug

argocd-rbac-cm get replaced when deploying or upgrading,  is this intended ? 
previous: 
apiVersion: v1
data:
  policy.default: role:admin
kind: ConfigMap

new one 

apiVersion: v1
data:
  policy.csv: ""
  policy.default: ""
  scopes: '[groups]'

Sorry if this is intended and i should place this config on the chart now , someone sayd 5 hours of debugging can save you 5 mins of reading the docs :(

maybe this should be added like a warn in the chart page when upgrading

### Related helm chart

argo-cd

### Helm chart version

5.13.8

### To Reproduce

helm install my-argo-cd argo/argo-cd --version 5.13.8

### Expected behavior

to not replace edited cm because im lazy and  i dont want to mess with dex with  azure groups , rbac again .

**Comment by pdrastil** [comment]
Hi - see docs here - https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-rbac-cm.yaml

The stuff inside are just defaults for visibility if you don't configure anything else.

**Comment by RicardoAlvialANS** [comment]
thank you! i was wondering if the configmap replacement is intended
the reason i ask is because i upgraded from chart version 3.2 to 4.0 and the config map did not get replaced , then i upgraded to version 4.3 no issues, the cm still functioning, then i upgraded to version 4.9 and then the configmap still working, then i upgraded to version 5.0!!! and the cm still works!!! then the issue, i upgraded the chart to version 5.13.8 and puff my configmap get replaced , that is why i was wondering if this is intended, and if it is intended then this should be added to the chart page docs so people upgrading can have a backup of the cm getting replaced

**Comment by pdrastil** [comment]
Thanks for pointing this out. It's possible it's a unexpected side-effect - whole RBAC code was commented out in values.yaml which means it was never used unless it was provided by the user. By uncommenting defaults the code suddenly started to work / template the values.

**Comment by pdrastil** [comment]
Resolved via https://github.com/argoproj/argo-helm/pull/1652
