### ISSUE TITLE
Enabling serviceaccounts watch list permissions for argo workflow cluster role

### ISSUE THREAD

**Issue by AndriySidliarskiy** [argoproj/argo-helm#1658]
### Is your feature request related to a problem?

When i configure sso for argo workflow i have an error wich contains next 

E1121 09:46:13.616793 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.ServiceAccount: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:argocd:argo-workflow-argo-workflows-server" cannot list resource "serviceaccounts" in API group "" at the cluster scope
W1121 09:46:23.449686 1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:argocd:argo-workflow-argo-workflows-server" cannot list resource "serviceaccounts" in API group "" at the cluster scope

So I need to create a new cluster role in with this permissions.

### Related helm chart

argo-workflows

### Describe the solution you'd like

add by defeult watch/list permissions for cluster role argo workflow server

**Comment by vladlosev** [comment]
This looks suspiciously similar to #1624. Are you also using RBAC authorization along with the SSO authentication?
