### ISSUE TITLE
Not able to deploy your chart with certificate that contain subject identifier at the top of the file

### ISSUE THREAD

**Issue by Whisper40** [argoproj/argo-helm#1661]
### Describe the bug

You should let us encode in base64 on our side and not on your side :
https://github.com/argoproj/argo-helm/blob/7105de193a4cc349bb22da9ee960dba7a93510a0/charts/argo-cd/templates/argocd-configs/argocd-server-tls.yaml#L19

Actually, i'm having trouble because, my certificate contains subject identifier into a file before the ----BEGIN CERTIFICATE---...

And while using helm to deploy it seems to cause trouble to ArgoCD to use the certificate.

### Related helm chart

argo-cd

### Helm chart version

5.14.1

### To Reproduce

Use custom certificate and key that contains subject identifier into values.yaml

### Expected behavior

We should encode the cert on our side and define a variable that contain the cert.
It will solve any indentation problem and make it work

**Comment by mkilchhofer** [comment]
Why you cannot trim your inputs? You could also manage the Secret externally if you want. Only requirement is to name it `argocd-server-tls` and place it in the namespace where Argo CD is installed to.
