### ISSUE TITLE
argo-rollouts: allow custom spec.strategy for the apps/ve

### ISSUE THREAD

**Issue by dsaintilma-flinks** [argoproj/argo-helm#1666]
### Is your feature request related to a problem?

Restarting the deployment recreates all the replicas. Pulling metrics is not possible while the recreation of pods in on-going.

### Related helm chart

argo-rollouts

### Describe the solution you'd like

 I would like to be able to use rollingUpdate instead with the ability to setup maxSurge & maxUnavailable parameters so that the pods would be replaced one after the other.

**Comment by mkilchhofer** [comment]
@huikang does this it make sense? This would require leader election but what happens when the leader goes down, does the other pod serves the metrics?

I ask you as you implemented leader election for rollouts here: https://github.com/argoproj/argo-rollouts/pull/1519
