### ISSUE TITLE
How to disable tls for the purpose of own ingress ?

### ISSUE THREAD

**Issue by sokoow** [argoproj/argo-helm#168]
**Describe the bug**
I'm missing an option to completely disable slf signed tls in argo, in order for it to be usable by ingress controllers that terminate tls on ingress. Is there any reliable way to do it ? Thanks

**Comment by sokoow** [comment]
anybody ?

**Comment by jdeprin** [comment]
`--insecure` https://argoproj.github.io/argo-cd/operator-manual/ingress/

**Comment by sokoow** [comment]
yep, that was it, thanks
