### ISSUE TITLE
Cannot upgrade an existing argo installation

### ISSUE THREAD

**Issue by amateope** [argoproj/argo-helm#1683]
### Describe the bug

Hi, I have argocd 4.10.3 running on my cluster and want to upgrade to the latest release but I get the error below. I tested other versions and saw that the issue started on chart version 5.1.1 so I could upgrade to 5.1.0 at least.

`Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "applications.argoproj.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "argocd"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "argocd"`

### Related helm chart

argo-cd

### Helm chart version

5.1.1 to 5.16.0

### To Reproduce

Install argocd 4.10.3 and then upgrade to the latest version.

### Expected behavior

No errors

**Comment by yu-croco** [comment]
Hi @amateope , did you check changelog ?
https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#520

I think https://github.com/argoproj/argo-helm/discussions/1476 will also help you.
