### ISSUE TITLE
cannot delete workflow with artifacts

### ISSUE THREAD

**Issue by pockyhe** [argoproj/argo-helm#1690]
### Describe the bug

I enable Artifacts with Azure Storage Blob as artifactory. And I wrote workflow with artifacts for passing parameters. However, I found some of these workflows cannot be deleted. Whatever from Argo UI or command argo delete. Even I update Argo Workflow, all workflow records are clean except these workflows because I found crd workflows.argoproj.io keep Terminating status in k8s.
I don't know how to delete them.

### Related helm chart

argo-workflows

### Helm chart version

0.20.0

### To Reproduce

none

### Expected behavior

none

**Comment by yu-croco** [comment]
This GitHub Repository manages Helm Chart, not Argo Workflows itself.
So, regarding the specific feature, let's follow https://github.com/argoproj/argo-workflows/issues/10192 .
