### ISSUE TITLE
argo-cd: 'operation' fiels in ApplicationSets

### ISSUE THREAD

**Issue by leotomas837** [argoproj/argo-helm#1699]
### Is your feature request related to a problem?

ApplicationSets need addition `spec.template.operation` fields to then inject it within the created Applications. Currently, in the `spec.template` of an ApplicationSet, `operation` is not available as for Applications (check CRD).

These `operation` fields are used for a range of things, as for force syncing for example, see the following [issue](https://github.com/argoproj/argo-cd/discussions/5172). I currently have to duplicate my Application manifests for different clusters instead of using ApplicationSets when I need this field.

### Related helm chart

argo-cd

### Describe the solution you'd like

ApplicationSets need addition `spec.template.operation` fields to then inject it within the created Applications. Currently, in the `spec.template` of an ApplicationSet, `operation` is not available as for Applications (check CRD).

Solution: adding the said `operation` fields in the ApplicationSet CRD and adapt the `applicationset-controller` consequently.

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by pdrastil** [comment]
Hi @leotomas837, this is a feature request for upstream repository https://github.com/argoproj/argo-cd as we don't build Argo CD controllers / generate CRDs. If the upstream does such change it will be included in the Helm chart.
