### ISSUE TITLE
[charts/argo-cd] Invalid certificate config reference

### ISSUE THREAD

**Issue by masondaven** [argoproj/argo-helm#170]
**Describe the bug**
Helm chart references certificate config at the top level when it has been moved under the server config. The chart will not deploy unless you add duplicate certificate config to your values file.

**To Reproduce**
1. Enable certificates in `values.yaml` file:
```
server:
...
  certificate:
    enabled: true
...
```
2. Deploy helm chart.

**Expected behavior**
The chart should deploy if you have cert-manager configured in the cluster.

**Additional context**
The helm chart template file is looking for the certificate issuer config in the wrong place:

https://github.com/argoproj/argo-helm/blob/30889df4767f9f15c41eb228090307b43acf046c/charts/argo-cd/templates/argocd-server/certificate.yaml#L20-L22

It should read:

```
  issuerRef:
    kind: {{ .Values.server.certificate.issuer.kind | quote }}
    name: {{ .Values.server.certificate.issuer.name | quote }}
```

**Comment by seanson** [comment]
Resolved by #170
