### ISSUE TITLE
ArgoCD session expiration

### ISSUE THREAD

**Issue by wadhekarp** [argoproj/argo-helm#1717]
### Describe the bug

We have setup of ArgoCD running on EKS cluster.

For SSO login I use the keycloak as an identity provider in my organisation.
Whenever I choose keycloak option for login (keycloak credentials) the session get expired in about 5min. I would like this to get extended to a minimum of 1hr.
One thing to note here, If I choose the local user for login the same issue does not happen.

### Related helm chart

argo-cd

### Helm chart version

4.9.1

### To Reproduce

Deploy argocd using helm chart.

Parameters used in sso config-

server:
    config:
      url: https://argocd.xyz.com
      users.anonymous.enabled: "true"
      accounts.ci: apiKey
      oidc.config: |
        name: Keycloak
        issuer: https://sso.xyz.com/auth/realms/xyz
        clientID: k-core.xyz.com
        clientSecret: ${Secret}
        requestedScopes:
          - openid
          - profile
          - email
    clusterAdminAccess:
      enabled: true
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, htg-k8s-admins, role:admin

### Expected behavior

After login with keycloak option, the session should not be expired after 5min

**Comment by pdrastil** [comment]
Plase check configuration of your Keycloak instance (see https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/sessions/timeouts.html). Argo CD by default have 24h session expiration.
