### ISSUE TITLE
[argo-helm/argo-cd] add HA functionality

### ISSUE THREAD

**Issue by jdeprin** [argoproj/argo-helm#172]
**Is your feature request related to a problem? Please describe.**
Currently there exists good documentation for how to run ArgoCD in HA mode but the existing chart does not support it.

**Describe the solution you'd like**
Add in HA functionality.  I believe this can be done while keeping backwards compatibility with the v1.*.* chart version. 

**Describe alternatives you've considered**
N/A

**Additional context**
I'll probably work on this over the next couple weeks.

**Comment by nouseforaname** [comment]
Hello,

did you do anything on that story already? Our team currently has the same thing on the roadmap and we could take over if you did not have time to work on this yet.
Let me know if you'd like some support

**Comment by papanito** [comment]
The docu helm chart of Argo-CD currently states
> This chart currently installs the non-HA version of ArgoCD.

So is this statement still true? If yes, what is missing? Glad to help though

**Comment by spencergilbert** [comment]
I suspect this is just an issue with the documentation - the chart can currently deploy HA redis and HA for the rest of the components can just be controlled via the replica values
