### ISSUE TITLE
Set resource tracking method via helm chart

### ISSUE THREAD

**Issue by crimbler2** [argoproj/argo-helm#1722]
### Is your feature request related to a problem?

Hello everybody:)

For integration with another tool I would like ArgoCD to use the resource tracking method "Annotation".
To achieve this the [docs](https://argo-cd.readthedocs.io/en/latest/user-guide/resource_tracking/) say I have to add this to the ArgoCD Config Map:
```
apiVersion: v1
data:
  application.resourceTrackingMethod: annotation
kind: ConfigMap
```

### Related helm chart

argo-cd

### Describe the solution you'd like

As far as I can tell, a parameter called `configs.cm."application.resourceTrackingMethod"` may be appropriate. 

Allowed values:
- label (default)
- annotation+label
- annotation

### Describe alternatives you've considered

There was no arbitrary way to add properties to the data-section of the ArgoCD config map, maybe I'm missing something.

Thank you very much for your work:)

**Comment by crimbler2** [comment]
If I'm right and it's 'only' this one new parameter, this seems doable for a newbie. I'd be willing to add it:)

**Comment by crimbler2** [comment]
So, after reading the docs again, my use case (resourceTrackingMethod: annotation) is covered by setting `configs.cm."application.instanceLabelKey"` to `argocd.argoproj.io/tracking-id`. The use case of the method "annotation+label" does not seem to be supported. I'll keep this open in case you want to support this. Otherwise, this issue can be closed.

**Comment by toyamagu-2021** [comment]
@crimbler2 
I think you can use `application.resourceTrackingMethod: annotation` already, even if it is not explicitly shown in `values.yaml` example.
For reference: https://github.com/argoproj/argo-helm/blob/c4d8b37fe49cfcfd09cbd693032ba54a0bc21403/charts/argo-cd/templates/_helpers.tpl#L185

E.g.) 
```yaml:values.yaml
configs:
  cm:
    application.resourceTrackingMethod: annotation+label
```

**Comment by pdrastil** [comment]
Answer from @toyamagu-2021 is right. There is reference in values.yaml to upstream configuration. Present configuration just includes few defaults / features that are commonly used when deploying the chart. Please refer to operation manual for full list of options.

**Comment by crimbler2** [comment]
Alright, thanks 👍
I'll close this, then.
