### ISSUE TITLE
Getting err: unsupported version "0.22.1" when deploying an `EventBus`

### ISSUE THREAD

**Issue by rakhbari** [argoproj/argo-helm#1724]
### Describe the bug

Right after deploying the `argo-events` chart, when you attempt to deploy an `EventBus`, no matter the name or namespace, you'll get the following error in the argo-events controller logs:
```
{"level":"error","ts":1665255012.769629,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:56","msg":"reconcile error","namespace":"default","eventbus":"default","error":"failed to get nats streaming version, err: unsupported version \"0.22.1\", supported versions: \"latest\""
```
I'm not the first one to run into this issue as it's been reported a few times in `argo-events` channel on CNCF Slack. This is just one of the threads:
https://cloud-native.slack.com/archives/C01TNKD6KL6/p1665255315412619

### Related helm chart

argo-events

### Helm chart version

2.0.8

### To Reproduce

1. Deploy the `argo-events` chart as per [the instructions](https://argoproj.github.io/argo-events/installation/#using-helm-chart)
2. Install the `default` native `EventBus` [in argo-events examples](https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml)
3. Tail the `argo-events-controller-manager` pod logs and you'll see the above error.

### Expected behavior

Installation of the `default` native `EventBus` [in argo-events examples](https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml) works fine with no errors in the `argo-events-controller-manager` pod logs.

### Additional context

This has also been reported as [an issue in the main `argo-events` repo](https://github.com/argoproj/argo-events/issues/2261), but the issue has been closed citing the fact that it's the Helm chart that's missing a crucial configuration.

The problem is that the chart's default `values.yaml` is missing the actual NATS version used in the [`argo-events` controller config](https://github.com/argoproj/argo-events/blob/master/manifests/base/controller-manager/controller-config.yaml#L10-L12).

The fix is quite simple: Add the expected NATS version to the `configs.nats.versions` in the chart's `values.yaml`.

**Comment by pdrastil** [comment]
Resolved via https://github.com/argoproj/argo-helm/pull/1735
