### ISSUE TITLE
apiKey capability for oidc users like localuser accounts

### ISSUE THREAD

**Issue by samba1112** [argoproj/argo-helm#1733]
### Is your feature request related to a problem?

Currently apiKey capability generation is possible for local user accounts by adding `accounts.<user>: apiKey`
Same way it will be helpful if apiKey generation privileges can be added to particular users of Oidc, So this way a new policy can be added in rbac config

### Related helm chart

argo-cd

### Describe the solution you'd like

Adding new resource can be used in policy as below
`p, role:sre, apikey, *, *, allow` 
sre role is the one we create in SSO so that we can assign that role to particular users

**Comment by pdrastil** [comment]
Hi @samba1112 , this is feature that should be requested in upstream repository https://github.com/argoproj/argo-cd

FYI: @crenshaw-dev

**Comment by samba1112** [comment]
@pdrastil Thanks for the revert 
Raised here https://github.com/argoproj/argo-cd/issues/11835

**Comment by pdrastil** [comment]
@samba1112 You are welcome. Closing this as solved.
