### ISSUE TITLE
Add SealedSecret template to helm chart

### ISSUE THREAD

**Issue by maciejmazur10c** [argoproj/argo-helm#1734]
### Is your feature request related to a problem?

When you deploy ArgoCD using helm chart and you want the secrets to be managed by Argo, it's much safer to keep them sealed, but they have to be stored as separate files. 

### Related helm chart

argo-cd

### Describe the solution you'd like

I would like you to add SealedSecret template to ArgoCD Helm chart, so additional secrets (like repository key, github oauth key, etc) could be managed using some entry in values.yaml file.
This part could be disabled by default. 
It would be nice to be able to create multiple secrets using this template.

Example usage:

```apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.13.6
    chart: argo-cd
    helm:
      version: v3
      values: |
        configs:
          sealedSecrets: 
            enabled: true
            repo-secret1:
              labels:
                argocd.argoproj.io/secret-type: repository
              foo: <sealed-secret-value>
            new-secret-2:
              bar: <some-other-sealed-secret-value>
 ```
 
it would create 2 sealed secret objects named "repo-secret1" and "new-secret-2", with the values added in that values entries.
Optionally it could create one secret for repository credentials and one secrets name "additional-secrets" or something like that.

**Comment by pdrastil** [comment]
Hi @maciejmazur10c this is already supported via `extraObjects`. The chart in intentionally un-opinionated about secrets same as Argo CD. See https://argo-cd.readthedocs.io/en/stable/operator-manual/secret-management/

**Comment by maciejmazur10c** [comment]
Thanks a lot @pdrastil! This is exactly what I was looking for.
