### ISSUE TITLE
Add: Helm Chart for argo-rollouts Release Version 1.4.0

### ISSUE THREAD

**Issue by saurabhvagrawal** [argoproj/argo-helm#1763]
### Is your feature request related to a problem?

Hi,

We are periodically upgrading our Infrastructure component to latest version -1. We can see that a new release of argo-rollouts for version 1.4.0 is released [here](https://github.com/argoproj/argo-rollouts/releases/tag/v1.4.0)

Requesting a feature to upgrade the chart to version 1.4.0.

### Related helm chart

argo-rollouts

### Describe the solution you'd like

A new chart for version 1.4.0

**Comment by alonbehaim** [comment]
+1

**Comment by jmeridth** [comment]
@saurabhvagrawal @alonbehaim Please be aware that https://github.com/argoproj/argo-helm/pull/1777 is a quick follow PR that needs to happen to toggle providers in the RBAC setup.  Current release should be good but if you see anything weird, you may want to wait for that to merge.  Cheers.
