### ISSUE TITLE
Distribute Charts in OCI format

### ISSUE THREAD

**Issue by sabre1041** [argoproj/argo-helm#1768]
### Is your feature request related to a problem?

No

### Related helm chart

argo-cd, argo-events, argo-rollouts, argo-workflows, argocd-image-updater, argocd-apps

### Describe the solution you'd like

Helm supports multiple distribution methods, traditional Helm repositories (http based) and the newer [OCI Registry](https://helm.sh/docs/topics/registries/).

Provide support for distributing charts as OCI artifacts within an OCI registry

**Comment by pdrastil** [comment]
Maybe this https://github.com/appany/helm-oci-chart-releaser can be used to support this

**Comment by geowalrus4gh** [comment]
we are moving to OCI registries for both images and helm charts. So it would be super easy if argo charts are published to registries in OCI format along with the respective images.
