### ISSUE TITLE
`See Upgrade` link is broken

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-helm#1781]
### Describe the bug

`See Upgrade` doesn't go anywhere.

### Related helm chart

other

### Helm chart version

N/A

### To Reproduce

1. Go to https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning
2. Click ([See Upgrade](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#upgrades))

### Expected behavior

Links to anchors should be to anchors that exist

### Screenshots

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/2119212/213612020-bab06ba2-8734-41ab-8361-5d2a0e496d32.png">

### Additional context

I'm trying to understand how to contribute to this repository.

Specifically, it appears that there are pairs of files, e.g. `charts/argo-cd/README.md` and `charts/argo-cd/README.md.gotmpl`. This file did not clarify that.

**Comment by jmeridth** [comment]
@jsoref Nice catch.  Even when this change was [added](https://github.com/argoproj/argo-helm/pull/750/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R17) it was a broken link.  The author may have had intention for it to go somewhere else but forgot.  That happens.

re: `README.md` and `README.md.gotmpl` files:
We use [helm-docs](https://github.com/norwoodj/helm-docs) in our linting GitHub action [here](https://github.com/argoproj/argo-helm/blob/main/.github/workflows/lint-and-test.yml#L48-L58) to call our [script](https://github.com/argoproj/argo-helm/blob/main/scripts/helm-docs.sh) to ensure the README.md file is generated and matches what is being checked-in.  There is always room for improvement but we could definitely notate this better in docs.

I look forward to your pull request fixing this. 😉
