### ISSUE TITLE
feat: Add Helm tests to ArgoCD build process

### ISSUE THREAD

**Issue by seanson** [argoproj/argo-helm#179]
**Is your feature request related to a problem? Please describe.**
As a maintainer it can be difficult to manage chart values and mappings to their target values. We have seen a few pull requests where the source values are not correctly mapped or larger reworks where some previously working functionality is missed.

**Describe the solution you'd like**
I'd like a simple way to run unit tests against our Helm charts so we can create test cases for regressions and prove new features are functional. The unit test framework should be portable and standard and leverage a common standard for discovery and test output.

I'd initially like to propose using Terratest's Helm chart testing.

**Describe alternatives you've considered**
I haven't seen any alternatives for Helm chart testing. There is also the possibility of spinning up our own testing framework, such as leveraging PyTest's custom file support.

**Comment by davidkarlsen** [comment]
How about using https://github.com/helm/charts/tree/master/test.
You can do CI in githuib with github-actions like this: https://github.com/evryfs/helm-charts/commit/2f9e105450aebbaa886b399010290e97338dd7c1/checks?check_suite_id=351194410

**Comment by seanson** [comment]
We currently already use helm-test but it is more of a linting system than a testing tool.

**Comment by seanson** [comment]
The current workflow in #183 has been really helpful so far and the CircleCI pipeline is configured and working. It would be very nice if I could get some eyes on it to see if it's fit for purpose.

**Comment by sudermanjr** [comment]
> We currently already use helm-test but it is more of a linting system than a testing tool.

Is that based on https://github.com/helm/chart-testing ?

If so, then it can do more than lint. There's end-to-end testing built-in as well.
We use it for running tests on our charts repo against a kind cluster.

**Comment by seanson** [comment]
> > We currently already use helm-test but it is more of a linting system than a testing tool.
> 
> Is that based on https://github.com/helm/chart-testing ?
> 
> If so, then it can do more than lint. There's end-to-end testing built-in as well.
> We use it for running tests on our charts repo against a kind cluster.

Sorry, yes, it does integration testing via installations, which would definitely be another nice feature. This issue is intended to raise a feature for unit testing the Helm charts.

**Comment by cmaster11** [comment]
I feel this issue should get more +1s !

This, using Helm tests, or some generic test hooks, which are not supported at the moment.

Sure, you can "emulate" testing with sync waves, but an ideal situation would see a deployment, testing and potential rollback on error 🤔

**Comment by phoenix1480** [comment]
FluxCD has built-in support for this via their helm controller; we use ArgoCD though -- would love to see helm tests built in as it allows us to keep the tests local to the chart and not put some other process in place

**Comment by pdrastil** [comment]
@phoenix1480 - depends what type of tests you have in mind. Helm tests via `helm.hook/test` are not supported via Argo CD controller as stated in [documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/). If you have in mind unit tests to verify that templating works as expected I can recommend https://github.com/quintush/helm-unittest plugin or running https://github.com/helm/chart-testing to do smoke test deployment for each PR you do. If you are more inclined to E2E tests of your service I would consider Argo Rollouts with blue-green / canary deployments.

**Comment by laurentiusoica** [comment]
Did anyone here manage to execute the helm tests of a helm chart by remapping the helm annotations to argo sync wave annotations ? Or through any other mechanism ?

**Comment by pradeepnnv** [comment]
I'm also interested to learn more about how this requirement is being managed if ArgoCD does not support helm tests.
