### ISSUE TITLE
argocd chart: redis metrics exporter sidecar not running on ARM

### ISSUE THREAD

**Issue by klauss42** [argoproj/argo-helm#1796]
### Describe the bug

Since chart version 5.19.0 an additional sidecar container redis-exporter gets deployed, but it is not compatible with ARM architecture and crashes immediately.

As a workaround you can disable the metrics exporter in values.yaml:
`redis:
  exporter:
    enabled: false`

### Related helm chart

argo-cd

### Helm chart version

5.19.0

### To Reproduce

Deploy argo-cd chart on ARM cluster

### Expected behavior

New chart versions should also work on ARM architecture

**Comment by pdrastil** [comment]
Hi @klauss42 - can you take a look which image would work for you on DockerHub? I don't see difference between architecture in older version 1.23.0 and 1.45.0.

Ref: https://hub.docker.com/r/bitnami/redis-exporter/tags

**Comment by klauss42** [comment]
Look at this commit: https://github.com/argoproj/argo-helm/commit/b4de202859d65343dc32d88364aa3dd368ba7d27
Before metrics sidecar was disabled by default, now the metrics exporter is enabled. This breaks existing deployments

**Comment by pdrastil** [comment]
@klauss42 Yes it was, and it can be disabled again. However I would rather make it working for everyone out of the box (make it same with redis-ha deployment where it's enabled by default) and same applies to upstream PR https://github.com/argoproj/argo-cd/pull/12102 .

**Comment by klauss42** [comment]
I am fine with the workaround of disabling the exporter in my values.yaml. But I was a little bit annoyed by the crash-looping redis pod this morning :-)

**Comment by pdrastil** [comment]
I'm sorry for that. If oliver image works for you I could create PR and push this to upstream as well.

**Comment by christian-schlichtherle** [comment]
To add some context: We are also deploying ArgoCD on ARM. It used to work until 5.19.3. When changing from 5.19.3 to 5.19.6, it stopped working because the image `public.ecr.aws/bitnami/redis-exporter:1.45.0` does not support ARM ISA. On 5.19.3, the container `metrics` wasn't enabled and I did not change the config.

BTW: Bitnami images generally do not support ARM. You will need to find an image from another publisher.

**Comment by pdrastil** [comment]
After discussion with @mkilchhofer this will be disabled by default as we prefer to use image geared towards enterprise environment from bitnami. Thank you for patience.

**Comment by pdrastil** [comment]
Closed via https://github.com/argoproj/argo-helm/pull/1799
