### ISSUE TITLE
"dex is not configured" in dex server output even though I have dex config in `dex.config`

### ISSUE THREAD

**Issue by WesselAtWork** [argoproj/argo-helm#1801]
### Describe the bug

```logfmt
time="TZ" level=info msg="ArgoCD Dex Server is starting" built="2023-01-25T16:17:49Z" commit=bbe870ff5904dd1cebeba6c5dcb7129ce7c2b5e2 namespace=x version=v2.5.8+bbe870f
time="TZ" level=info msg="Generating self-signed TLS certificate for this session"
time="TZ" level=info msg="Starting configmap/secret informers"
time="TZ" level=info msg="Configmap/secret informer synced"
time="TZ" level=info msg="0xc00031a9c0 subscribed to settings updates"
time="TZ" level=info msg="dex is not configured"
```

I have no idea what I am setting up wrong and looking at the helm chart I can't tell how we are loading the CM into the application!
Looks to be via the `argocd-dex` sub application...

I am definitely configuring something wrong...

### Related helm chart

argo-cd

### Helm chart version

5.19.8

### To Reproduce

Configure Dex under the `config.dex` field and then deploy the application

You should see this output.

### Expected behavior

Clear log output to what I did wrong.

I have no idea where to even begin looking.

**Comment by WesselAtWork** [comment]
Figured it out.

I was looking at the code for the `argocd-dex` sub-app to try and follow what needs to happen for it to print "dex is not configured".

Following from where it apeared first:

https://github.com/argoproj/argo-cd/blob/61f6530e8ab5d6816099edbbb2b555540a9eeda4/cmd/argocd-dex/commands/argocd_dex.go#L100-L103

I found this section:

https://github.com/argoproj/argo-cd/blob/61f6530e8ab5d6816099edbbb2b555540a9eeda4/util/dex/config.go#L13-L15

Which is defined like so:

https://github.com/argoproj/argo-cd/blob/61f6530e8ab5d6816099edbbb2b555540a9eeda4/util/settings/settings.go#L1648-L1651

Looking at the `values.yaml` I see that I missed configuring the URL parameter:

https://github.com/argoproj/argo-helm/blob/5335a75fbcbb8bdd87d19fa088c9420a0ea8f990/charts/argo-cd/values.yaml#L112-L113


I probably saw the "optional", then when I later realized I needed to configure SSO via dex I forgot I needed to define it.

Hope I can spare someone a few hours ⌛

**Comment by Anghille** [comment]
Thank you for this ! 
I have been trying to figure out why I had this error as well. The `url: ""` in my git repo was provided but I didnt commit this change "just for an optional url" that would definitely not solve my problem.... I was wrong
