### ISSUE TITLE
argo-cd Helm chart changelog at artifacthub stopped working

### ISSUE THREAD

**Issue by nicl09** [argoproj/argo-helm#1808]
### Describe the bug

Since v5.19.7 of the argo-cd Helm chart the changelog generation at artifacthub seems to be broken. This is what it looks like now:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/75254846/215296697-c645587d-989f-498f-8654-b8a945d5f7d8.png">

### Related helm chart

argo-cd

### Helm chart version

5.19.7

### To Reproduce

1. Go to https://artifacthub.io/packages/helm/argo/argo-cd/5.19.11?modal=changelog&version=5.19.11
2. Check changelog
3. No changes to be found

### Expected behavior

1. Go to https://artifacthub.io/packages/helm/argo/argo-cd/5.19.11?modal=changelog&version=5.19.11
2. Check changelog
3. See changes

**Comment by yu-croco** [comment]
Thanks for reporting!

It happens from argo-cd v5.19.7 (diff: https://github.com/argoproj/argo-helm/compare/argo-cd-5.19.6...argo-cd-5.19.7 ), though the diff does not have any configuration changes.... 🤔

**Comment by yu-croco** [comment]
Hi @mkilchhofer @pdrastil @jmeridth ,
do you have any ideas about this issue...? 🤔

**Comment by pdrastil** [comment]
I first thought that something changed in [ArtifactHub annotations](https://artifacthub.io/docs/topics/annotations/helm/) but it doesn't seem so. So only likely explanation is that there is some change in parsing of content. See official [Chart.yaml](https://github.com/artifacthub/hub/blob/master/charts/artifact-hub/Chart.yaml) where structure below is used for generating changelog. Maybe we should align this as well?

```yaml
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Experimental support for Kyverno policies
```

**Comment by yu-croco** [comment]
I think so too, it's worth to try the latest structure.

FYI, the new style shows nicely UI at artifact hub. 👀 
https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=changelog

<img width="993" alt="image" src="https://user-images.githubusercontent.com/30188755/215334920-21257f2b-2e63-40e7-87bd-97b0e0808471.png">

**Comment by pdrastil** [comment]
@yu-croco - If you compare with Argo changelog you can see that color is not picked as we have `[Added]` etc in plain text instead. Supported kinds should be: `added`, `changed`, `deprecated`, `removed`, `fixed` and `security`. For security there is also extra annotation that shows `Contains security updates` on top.

**Comment by yu-croco** [comment]
@pdrastil 
Ahh, that's why. 😇 Thank you for explaining!

I made PR to argo-cd Helm Chart. https://github.com/argoproj/argo-helm/pull/1810
If this works well, I will update other projects' changelog structure and [here](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog). 🙋

**Comment by nicl09** [comment]
Damn you guys are fast. I was about to say I could make the necessary changes if you want, would've been great practice as a first time contributor, but your pace is too much for me. 😄 Thank you for the quick fix!

**Comment by yu-croco** [comment]
PR is merged but not yet updated...
Does it take time...? 🤔 

index.yaml: https://github.com/argoproj/argo-helm/blob/gh-pages/index.yaml#L1589-L1595

artifact hub: https://artifacthub.io/packages/helm/argo/argo-cd/
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/30188755/215336531-fe2f6fcf-132f-4d6d-9573-1065eecee616.png">

**Comment by pdrastil** [comment]
@yu-croco - It showed up and is working

**Comment by yu-croco** [comment]
Ohhhhhh 🎉 
https://artifacthub.io/packages/helm/argo/argo-cd/5.19.12?modal=changelog&version=5.19.12

<img width="1881" alt="image" src="https://user-images.githubusercontent.com/30188755/215337314-0461a3e1-6eb3-4249-ae16-9ec1e363dff4.png">

**Comment by yu-croco** [comment]
I will update the rest of projects (argo-events, argo-rollouts, argocd-apps, argocd-image-updater) tomorrow. 😴 
*Of course, anyone can make PR for them. 🙋

**Comment by jmeridth** [comment]
[argo-events PR](https://github.com/argoproj/argo-helm/pull/1813)

**Comment by jmeridth** [comment]
[argo-rollouts PR](https://github.com/argoproj/argo-helm/pull/1814)

**Comment by jmeridth** [comment]
@yu-croco all PRs up for review

**Comment by mkilchhofer** [comment]
Does someone also update the CONTRIBUTION.md? :)

**Comment by jmeridth** [comment]
@mkilchhofer yep, already updated [here](https://github.com/argoproj/argo-helm/pull/1811)

**Comment by mkilchhofer** [comment]
> @mkilchhofer yep, already updated [here](https://github.com/argoproj/argo-helm/pull/1811)
> 
> 
> 
> [great minds think alike](https://github.com/argoproj/argo-helm/pull/1810#issuecomment-1407692063) 😄 

🚀 superfast. Thank you guys 🙏

**Comment by pdrastil** [comment]
I believe we are done - all projects updated together with CONTRIBUTING.md
