### ISSUE TITLE
Can not install argo-workflows in two different namespaces

### ISSUE THREAD

**Issue by Freia3** [argoproj/argo-helm#1818]
### Describe the bug

When I want to namespace-install argo workflows in two different namespaces, I get the following error message:

Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "clusterworkflowtemplates.argoproj.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "test-namespace-argo2": current value is "test-namespace-argo"

I know I can use `--no-crd-hook`, but I don't want to do this. Using the official release, I can install argo workflows in two different namespaces, I guess it does not check this owernship metadata in this case.

### Related helm chart

argo-workflows

### Helm chart version

argo-workflows-0.22.9

### To Reproduce

1.  helm upgrade --install argo-workflows argo/argo-workflows --set singleNamespace=true -n test-namespace-argo
2.  helm upgrade --install argo-workflows argo/argo-workflows --set singleNamespace=true -n test-namespace-argo2

### Expected behavior

I want to namespace-install argo workflows in two different namespaces without getting an error message.

**Comment by yu-croco** [comment]
CRD itself exists cluster wide, not namespace, so I think it's suspicious to establish the use case even you set `singleNamespace=true` . 🤔 

```
$ k get crd
NAME                                   CREATED AT
clusterworkflowtemplates.argoproj.io   2023-01-30T14:33:46Z
cronworkflows.argoproj.io              2023-01-30T14:33:46Z
workflowartifactgctasks.argoproj.io    2023-01-30T14:33:46Z
workfloweventbindings.argoproj.io      2023-01-30T14:33:46Z
workflows.argoproj.io                  2023-01-30T14:33:46Z
workflowtaskresults.argoproj.io        2023-01-30T14:33:46Z
workflowtasksets.argoproj.io           2023-01-30T14:33:46Z
workflowtemplates.argoproj.io          2023-01-30T14:33:46Z
```

**Comment by Freia3** [comment]
Here are some benefits listed of installing argo workflows in mulitiple namespaces: https://pipekit.io/blog/how-to-install-argo-workflows-in-multiple-namespaces

We need a seperate argo server per namespace.

Do you have any other suggestions on how to install argo workflows in multiple namespaces then? Is there a way to install only the CRD in one namespace and the deployments in other namespaces?

**Comment by vladlosev** [comment]
As a workaround, you can try to install the second Argo instance with `crds.install=false`. As a general fix, the chart should stop generating the CRDs from the templates and put them into the `crds` directory, allowing Helm to manage them directly.
