### ISSUE TITLE
When the EKS cluster uses the AWS certificate manager to configure SSL, the host and hosts values of Ingress cannot be set correctly

### ISSUE THREAD

**Issue by qingfengfenga** [argoproj/argo-helm#1824]
### Describe the bug

When I use the AWS certificate manager, I can't get the specific key to create the secret, but use the Ingress annotation to call.

In this case, I cannot configure the host of Ingress through Values. If there is no host, Ingress will be redirected to the root directory by default, thus affecting all Ingress.

If I manually modify the created Ingress configuration, it will be overwritten every time I update Helm.

Logs
```
helm upgrade --history-max=5 --install=true --namespace=argo-dev --timeout=10m0s --values=/home/shell/helm/values-argo-workflows-0.22.9.yaml --version=0.22.9 --wait=true argo-workflows-0-1675665450 /home/shell/helm/argo-workflows-0.22.9.tgz
--
Mon, Feb 6 2023 5:34:36 pm | Error: UPGRADE FAILED: template: argo-workflows/templates/server/server-ingress.yaml:30:30: executing "argo-workflows/templates/server/server-ingress.yaml" at <.Values.server.ingress.hosts>: range can't iterate over xxx.xxx.com

```

### Related helm chart

argo-workflows

### Helm chart version

argo-workflows:0.22.9

### To Reproduce

1. Start the EKS cluster and configure the Ingress and AWS certificate manager
2. Install argo-workflows: 0.22.9

### Expected behavior

Set the host and hosts of Ingress correctly without adding a secret

**Comment by yu-croco** [comment]
Hi @qingfengfenga, can you please give me the values.yaml you tried?

*If you are using [aws-loadbalancer-controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/), you can use [Certificate Discovery](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/cert_discovery/) and omit adding ACM to ingress directly. So this may help you? 🤔
