### ISSUE TITLE
Resources not being applied to wait container

### ISSUE THREAD

**Issue by elia-zakeke** [argoproj/argo-helm#1837]
### Describe the bug

How do you configure wait containers resources (request/limit)? 

I'm using the latest helm chart for argo-workflows and I'm getting this error:
`The node was low on resources: ephemeral storage. Container wait was using 68Ki, which exceeds it's request of 0.`

I set the following values:
`executor:
  resources:
    requests:
      ephemeral-storage: 100Mi`

Wait container it's being deployed with no resource defined.

### Related helm chart

argo-workflows

### Helm chart version

latest

### To Reproduce

I'm using docker dind to create container images. The issue is triggered when doing many parallel tasks.

### Expected behavior

Wait container should be deployed with resource parameters from the values file I submitted.

**Comment by vladlosev** [comment]
Please post your chart version, the values you use, and the generated controller configmap.

**Comment by elia-zakeke** [comment]
Chart version: 0.22.11

Values:
```
executor:
  resources:
    limits:
      ephemeral-storage: 1Gi
    requests:
      ephemeral-storage: 10Mi
```

Controller ConfigMap:
executor:
  imagePullPolicy: Always
  resources:
    limits:
      ephemeral-storage: 1Gi
    requests:
      ephemeral-storage: 10Mi
nodeEvents:
  enabled: true

**Comment by vladlosev** [comment]
Hmm I am not sure what is happening here. The chart is apparently generating a correct configmap, but it's not being acted upon by the workflow controller.

**Comment by elia-zakeke** [comment]
should I open an issue in Argo Workflows?

**Comment by vladlosev** [comment]
I am not sure. Without a more detailed context, it's hard to say. The best course of action is probably to ask in their Slack.
