### ISSUE TITLE
Progressive Rollout feature not working

### ISSUE THREAD

**Issue by adrianmiron** [argoproj/argo-helm#1838]
### Describe the bug

When reading the feature PR : https://github.com/argoproj/argo-cd/pull/10048. and the new documentation page for it :
https://argo-cd.readthedocs.io/en/stable/proposals/2022-07-13-appset-progressive-rollout-strategy/#use-case-1 , we should see the applicationset CRD having  a new block named `rollingUpdate` , but  that is not the case, only `rollingSync` is present. (this issue is actually related to the main app documentation, not the chart itself) 

That being said, i cannot get `rollingSync` to work either . The chart mentions this attribute : applicationsetcontroller.enable.progressive.syncs, but enabling it does nothing to trigger a progressive sync ( the attribute is not used). 

What is used is `applicationsetcontroller.enable.progressive.rollouts`, which gets put into ARGOCD_APPLICATIONSET_CONTROLLER_ENABLE_PROGRESSIVE_SYNCS ( but `applicationsetcontroller.enable.progressive.rollouts` is not documented inside the chart).

Manually adding the attribute works, but a fix ( on both project and chart) is needed .

Thanks,
Adrian

### Related helm chart

argo-cd

### Helm chart version

5.20.3

### To Reproduce

Try to implement Progressive rollouts

### Expected behavior

Progressive rollouts work ( rollouts do not actually exist, jut syncs and they do not work in the current default config)

**Comment by pdrastil** [comment]
I was changed to `applicationsetcontroller.enable.progressive.syncs` in the upstream prior 2.6 release and config can be found documented in `configs.params` section.

Ref: https://github.com/argoproj/argo-cd/blob/3f143c9307f99a61bf7049a2b1c7194699a7c21b/docs/operator-manual/argocd-cmd-params-cm.yaml#L168

**Comment by adrianmiron** [comment]
I agree, however the deployment file  sets the required env var based on `applicationsetcontroller.enable.progressive.rollouts`
https://github.com/argoproj/argo-helm/blob/c08fc230d75c85b2c9a07138c5c7b7bc957b98df/charts/argo-cd/templates/argocd-applicationset/deployment.yaml#L139

**Comment by pdrastil** [comment]
Now I see :) thanks for pointing this out. I've created PR with fix for this issue.
