### ISSUE TITLE
Argo CD Helm Chart not generating valid yaml  when slack bot enabled

### ISSUE THREAD

**Issue by oisin88** [argoproj/argo-helm#1850]
### Describe the bug

When slack bot is enabled:

  bots:
    slack:
      # -- Enable slack bot
      ## You have to set secret.notifiers.slack.signingSecret
      enabled: true. <---- set this to true
      
      
      This yaml is generated
      
             affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-
        
        
        The line app.kubernetes.io/name: argocd- is not valid as it ends with underscore.
        
        
        Possibly related to:
        
        https://github.com/argoproj/argo-helm/commit/51386c69be246d233d106ca97d33fda6b63b0caa#diff-63ba55fbc3755b63887cfdd659c44aa46bfc7c70c7ad0c1cf5c0c98149ea4a5fR88
        
        
      
        
        
      
   
      
      

### Related helm chart

argo-cd

### Helm chart version

5.22.1

### To Reproduce

To recreate in values file:

  bots:
    slack:
      # -- Enable slack bot
      ## You have to set secret.notifiers.slack.signingSecret
      enabled: true. <---- set this to true
      
      
    run 
    
    helm template
    
    The out of affinity section looks like this:
    
    
    
       affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-
              topologyKey: kubernetes.io/hostname
      dnsPolicy: ClusterFirst
    
    
Note this not a valid  label as it end with underscore.

app.kubernetes.io/name: argocd-

Adding a "name" to kind of helps:

   bots:
      slack:
        name: slack-bot
        
        
But this is not in value file and the the match labels not match selector labels do not match.  

### Expected behavior

The default chart generated valid yaml when slack bot is enabled.

**Comment by pdrastil** [comment]
Hi @oisin88 - thank you for reporting this. I'll prepare a fix.

**Comment by pdrastil** [comment]
Hi @oisin88 - was this component working at all before affinity change? I've been checking upstream manifests and seems that there is no support for `bot` command for notification controller. This deployment was moved as-is in the past when notifications were still experimental feature and original [source code](https://github.com/argoproj-labs/argocd-notifications) is archived and not under any development. So I'm more inclined to remove bot deployment completely as it's not in upstream / actively developed.

**Comment by oisin88** [comment]
Hi @pdrastil ,

The resources where valid yaml  before the affinity change. I have been able to get it working again by using chart version 5.21.1. However I am not sure if the created resources actually did anything.

However the main issue here is that the yaml is invalid. So even if the resources are not used it will fail linter checks and crash CI/CD pipelines. 

I guess if you can confirm the  resources created in the "bot"  section don't do anything it makes sense to remove and updates your values.yaml.  However  if the resources do something but have been superseded by "notifications" I guess you could do a release and just flag up that you are removing support for "bots". Your call though :) 

Thanks,
Oisin

**Comment by pdrastil** [comment]
I'm refering to this old documentation https://argocd-notifications.readthedocs.io/en/latest/bots/slack-bot/ which is the component you have enabled. I think that this is no longer working and I'll propose a removal.
