### ISSUE TITLE
Upgrading ArgoCD Chart from 4.x to the latest 5.22.1 don't upgrade to kubernetes 1.23 because PodSecurityPolicy

### ISSUE THREAD

**Issue by lfdominguez** [argoproj/argo-helm#1851]
### Describe the bug

When I upgraded my helm deployment, the deployment process works great, but any of the deployments or statefulset allow deploying pods because for example on `sts` `argocd-application-controller`:

```
  Warning  FailedCreate      6m3s (x9 over 55m)  statefulset-controller  create Pod argocd-application-controller-3 in StatefulSet argocd-application-controller failed error: pods "argocd-application-controller-3" is forbidden: 
PodSecurityPolicy: 
unable to admit pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/application-controller]: 
Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/application-controller]: 
Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/application-controller]: 
Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/application-controller]: 
Forbidden: seccomp may not be set spec.volumes[0]: Invalid value: "emptyDir": emptyDir volumes are not allowed to be used pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/application-controller]: 
Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/application-controller]:
Forbidden: seccomp may not be set]
```

### Related helm chart

argo-cd

### Helm chart version

5.22.1

### To Reproduce

1 - `helm upgrade --namespace argocd --values values.yaml --version 5.22.1 argocd argo/argo-cd`
2 - `kubectl  describe sts -n argocd argocd-application-controller`

### Expected behavior

All deployments, statefulsets, pods upgraded to new version.

### Additional context

The current ArgoCD (2.3.1) was running on the same cluster with kubernetes 1.20 (rke2), so I updated the cluster to `v1.23.15+rke2r1`. The ArgoCD currently is working OK, but I need to upgrade it to the latest version, so I applied the new changes to my old `values.yaml` file and tried to do the helm upgrade. Seems that the new changes to the Pod Security of 1.22 & 1.23 is not taken in account on the helm deploy.

**Comment by pdrastil** [comment]
PodSecurityPolicy (PSP) was never present in this Helm chart in any of our components so you must have something on your cluster that creates such rules. Regarding the upgrade latest chart requires K8s 1.22+ as it uses seccomp profile in security context and PSP is deprecated from K8s 1.21+ and will be removed in 1.25.

**Comment by lfdominguez** [comment]
I think that the migration from 1.20 to 1.23 left that PSP rules, here you can see that my cluster:
```
$ kg psp -A 
                                                                                                                                                                                                     
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                   SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
global-unrestricted-psp   true    *                      RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
longhorn-psp              true    SYS_ADMIN              RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            configMap,downwardAPI,emptyDir,secret,projected,hostPath
netdata-psp               true    SYS_PTRACE,SYS_ADMIN   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
rancher-backup-psp        false                          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            persistentVolumeClaim,secret
system-unrestricted-psp   true    *                      RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
```
There is something on the helm chart that I can tell to the deployment that not use these PSP?

**Comment by pdrastil** [comment]
PSP rules are cluster-level resources for admission controller which means they will validate every pod and it's security context running in your cluster. I believe that what this is complaining about is seccomp profile in Argo CD security context that was originally configured in PSP via annotations like this:

```yml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: global-restricted-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
```

You can try this as a workaround but I would recommend to get rid of PSP if possible. You can also take a look to this article for more information about PSP.

Ref: https://medium.com/coryodaniel/kubernetes-assigning-pod-security-policies-with-rbac-2ad2e847c754

**Comment by lfdominguez** [comment]
Good, works for all except `argocd-server` but you give to me a path to go, thanks.

**Comment by lfdominguez** [comment]
If someone needs a workaround for this particular case, need to create a new PSP and ClusterRoleBinding to join:
```
k apply -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/policy/privileged-psp.yaml
k create clusterrole privileged-psp --verb use --resource podsecuritypolicies.policy --resource-name privileged
k create -n argocd rolebinding disable-psp --clusterrole privileged-psp --group system:serviceaccounts:argocd
```
