### ISSUE TITLE
Allow for insecure transport setting on email notifications

### ISSUE THREAD

**Issue by aleckjohnson1** [argoproj/argo-helm#1859]
### Is your feature request related to a problem?

Currently unable to specify non tls transfer for email notification communication as it is not required for current implementation.

### Related helm chart

argo-cd

### Describe the solution you'd like

An exposed parameter in the override file to utilize as a flag to turn secure transfer on and off for email notifications.

**Comment by pdrastil** [comment]
Hi @aleckjohnson1 - I'm not aware that such configuration feature exists. Maybe this should be ask for upstream repository https://github.com/argoproj/argo-cd ?
