### ISSUE TITLE
Resource customisation support

### ISSUE THREAD

**Issue by TapTap21** [argoproj/argo-helm#1872]
### Describe the bug

Resource customisation support was removed in [v1.0 of the chart release ](https://github.com/argoproj/argo-helm/pull/129/files#diff-9eb59d56febda5e405748483497dfdc0c2dfbe9b4f386a12f0180c98d99051e0)

This is an issue, since to add health assessment of apps, [one needs to set a custom health check](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/).

### Related helm chart

argo-cd

### Helm chart version

5.23.5

### To Reproduce

Just install the chart, there is no value to add resource customisations

### Expected behavior

There is an option to add this

**Comment by rrednaxela** [comment]
thanks a lot for your replies. Adding it like
```
configs:
  cm:
    resource.customizations:
```
worked for me.
