### ISSUE TITLE
Update entrypoints after argo pr 12707

### ISSUE THREAD

**Issue by gczuczy** [argoproj/argo-helm#1883]
### Is your feature request related to a problem?

The entrypoint change in https://github.com/argoproj/argo-cd/pull/12707 is another step for making a distroless image possible.
Currently the argocd helm chart does not make it possible to remove the entrypoint.sh from the manifests for using tini directly instead.

Once the PR is merged, `entrypoint.sh` can be removed from the manifests, and all services started directly with `args`. Please see the first comment in the PR for details and kubernetes docs on the topic.

### Related helm chart

argo-cd

### Describe the solution you'd like

Removing the dependency on any kind of shell, so there's one less blocker for a distroless image.

### Describe alternatives you've considered

I'm not sure there are a lot of alternatives, tini is pretty much accepted as the de-facto standard for container entrypoints.

**Comment by yu-croco** [comment]
This issue seems resolved.
