### ISSUE TITLE
Add namespaceOverride in values.yaml

### ISSUE THREAD

**Issue by Mathie01** [argoproj/argo-helm#1884]
### Is your feature request related to a problem?

The chart is installed in the default namespace. It is not possible for us to install the chart where we want

### Related helm chart

argo-cd

### Describe the solution you'd like

Add namespaceOverride in the values.yaml

**Comment by pdrastil** [comment]
Hi @Mathie01 all charts are installed into configured namespace in `~/.kube/config`. If you need different one you can either reconfigure context or use `helm install --namespace argocd` to place it somewhere else. Templating namespace in every resource do not bring any benefit and is not possible for external dependencies such as redis-ha that doesn't support this.

**Comment by pdrastil** [comment]
Hi @Mathie01, same rule with context applies to dependencies that are also placed in desired namespace.

**Comment by robinliubin** [comment]
in my case, Argo-workflow is one sub-chart among 10s other sub-charts.
I want argo goes into argo namespace, while 10s other sub-charts goes into own namespace individually.
argo-workflow -> namespace: argo
postgres -> namespace: postgres
minio -> namespace: minio
redis -> namespace: redis
(...)

postgres/minio/redis etc. we used the helm chart from [bitnami ](https://github.com/bitnami/charts/blob/b03da4d3d3c700815be1619b05e6af141d260488/bitnami/minio/values.yaml#L28)
so we can properly place them, while argo now is the issue.

argo would follow the helm release namespace, so if we do `helm install --namespace argocd`, argo will be deployed in `argocd`, however argocd is one sub-chart that we dont want it follow the umbrella helm chart release.

would you please cover this scenario by adding `namespaceOverride`
