### ISSUE TITLE
Support for additional fields in argocd-secret

### ISSUE THREAD

**Issue by munavirch** [argoproj/argo-helm#1888]
### Is your feature request related to a problem?

We are setting up OIDC with AzureAD which requires to update argocd-secret with client secret. We are deploying argo via terraform helm_release. This makes the secret update impossible without any cleaner solution. If we set `createSecret` and setup the secret via terraform, it'll remove the other keys added by other parties. For e.g., server key. If secret was created by argo helm, this can not be update via terraform. 

### Related helm chart

argo-cd

### Describe the solution you'd like

We would like a value in the helm chart to pass custom key-value for the argocd-secret while installing the helm chart.

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by mkilchhofer** [comment]
It should be possible for a relatively long time:
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-configs/argocd-secret.yaml#L44-L46

-> Use the parameter `configs.secret.extra` for that.
