### ISSUE TITLE
Server metrics port inconsistent with documentation 

### ISSUE THREAD

**Issue by ShimonOhayon** [argoproj/argo-helm#1910]
### Describe the bug

The documentation points out that the server metric port is `8083` in several places
[Ref 1](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/server-commands/argocd-server.md?plain=1#LL44C2-L44C97)
[Ref 2](https://argo-cd.readthedocs.io/en/stable/operator-manual/metrics/#api-server-metrics)

And the Helm chart by default execute the server command with the port `8082` by default.
[here](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L1576)

### Related helm chart

argo-cd

### Helm chart version

v2.6.5

### To Reproduce

1. Deploy the helm chart withe `server.metrics: enabled`
2. notice the metric port.
3. compare to documentation 

### Expected behavior

the metric server should listen to port `8083` by default

**Comment by mkilchhofer** [comment]
You are right, its a bug introduced in
- https://github.com/argoproj/argo-helm/pull/1788
- details https://github.com/argoproj/argo-helm/pull/1788/files#diff-1817bb061b5ceed1dabf4e30ac6445a132baa3884c3278be3e97d166a25e3a3bL294

I will fix it

**Comment by pdrastil** [comment]
@mkilchhofer Please do - probably copy & paste issue when I've taken the values from here:

https://github.com/argoproj/argo-cd/blob/3c058ea732f620459e6d7f60e72bf46c483d2d3f/common/common.go#L50
