### ISSUE TITLE
SOCKS proxy for charts

### ISSUE THREAD

**Issue by jcpunk** [argoproj/argo-helm#1912]
### Is your feature request related to a problem?

My local test deployment of argo-cd has direct access to various internet repos, but requires a proxy to access my internal repos.

My company development argo-cd has direct access to my internal repos, but requires a proxy for internet access.

Rather than having different definitions for the applications I'm checking out, I'd like to define my proxys at install time.

### Related helm chart

argo-cd

### Describe the solution you'd like

Some way to set the proxy env vars (http, https, socks) at installation time via helm.

### Describe alternatives you've considered

Manually injecting the env vars

### Additional context

This may be particularly handy for folks with strong network policy on egress.

**Comment by mkilchhofer** [comment]
There are different approaches for setting the proxy. We at @swisspost also have a very restricted environment and Argo CD cannot reach the internet.

Our main deployment periphery systems like container registry, helm repository, git repo (bitbucket) etc. are hosted on-premise and therefore Argo CD does not need to communicate for around 90% of the apps.
But some apps are developed from external companies/orgs and hosts their stuff on GitHub. The proxy can also be configured on repository or credentialTemplate level, @swisspost / @the-technat contributed this:
- https://github.com/argoproj/argo-cd/pull/11422
- https://github.com/argoproj/argo-cd/pull/11425

If your main stuff is hosted in the internet, then I'd set the proxy via 
- `repoServer.env` or `repoServer.envFrom`
- `server.env` / `server.envFrom` 

The main component to reach the repositories is "repo-server" but sometimes "server" (the Argo CD API Server) tries to reach the repos to check if there is something new in it before it pings the repo-server to do its work.
