### ISSUE TITLE
Chart requires version >=1.22.0-0, running v1.23.16 but error message claims v1.20.0

### ISSUE THREAD

**Issue by TheShahin** [argoproj/argo-helm#1936]
### Describe the bug

Rendering or install chart fails with the error message:

```sh
Error: chart requires kubeVersion: >=1.22.0-0 which is incompatible with Kubernetes v1.20.0
```

`kubectl version --short` output:

```sh
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.23.16-eks-48e63af
```

`helm version` output:

```sh
v3.11.2+gv3.11.2
```

### Related helm chart

argo-cd

### Helm chart version

5.27.4

### To Reproduce

`helm template argo-cd /path/to/argo-cd`

### Expected behavior

Rendered Kubernetes manifests.

**Comment by mkilchhofer** [comment]
So you only have issues with the helm template subcommand?

Remember that helm template does not contact any kubernetes cluster. The version helm thinks the cluster will have is embedded in helm sourcecode. You can inject your cluster version with the `--kube-version string` option, eg. `helm template argo-cd argoproj/argo-cd --kube-version 1.23.16`

**Comment by kbreit-insight** [comment]
@mkilchhofer  How do we do this since, as far as I can tell, helm is built into the Argo container images.

**Comment by mkilchhofer** [comment]
> @mkilchhofer  How do we do this since, as far as I can tell, helm is built into the Argo container images.

@kbreit-insight Argo CD passes the real cluster data via the mentioned parameters to the helm binary.
You can see this in the logs of the repo-server component:

> time="2024-07-23T19:51:36Z" level=info msg="helm template . --name-template hubble-ui --namespace kube-system **--kube-version 1.28** --api-versions acme.cert-manager.io/v1 --api-versions acme.cert-manager.io/v1/Challenge --api-versions acme.cert-manager.io/v1/Order --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1/MutatingWebhookConfiguration --api-versions admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1/CustomResourceDefinition --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1/APIService --api-versions apps/v1 --api-versions apps/v1/ControllerRevision --api-versions apps/v1/DaemonSet --api-versions apps/v1/Deployment --api-versions apps/v1/ReplicaSet --api-versions apps/v1/StatefulSet --api-versions aquasecurity.github.io/v1alpha1 --api-versions aquasecurity.github.io/v1alpha1/ClusterComplianceReport --api-versions aquasecurity.github.io/v1alpha1/ClusterConfigAuditReport --api-versions aquasecurity.github.io/v1alpha1/ClusterInfraAssessmentReport --api-versions aquasecurity.github.io/v1alpha1/ClusterRbacAssessmentReport --api-versions aquasecurity.github.io/v1alpha1/ClusterSbomReport --api-versions aquasecurity.github.io/v1alpha1/ClusterVulnerabilityReport --api-versions aquasecurity.github.io/v1alpha1/ConfigAuditReport --api-versions aquasecurity.github.io/v1alpha1/ExposedSecretReport --api-versions aquasecurity.github.io/v1alpha1/InfraAssessmentReport --api-versions aquasecurity.github.io/v1alpha1/RbacAssessmentReport --api-versions aquasecurity.github.io/v1alpha1/SbomReport --api-versions aquasecurity.github.io/v1alpha1/VulnerabilityReport --api-versions argoproj.io/v1alpha1 --api-versions argoproj.io/v1alpha1/AppProject --api-versions argoproj.io/v1alpha1/Application --api-versions argoproj.io/v1alpha1/ApplicationSet --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2 --api-versions autoscaling/v2/HorizontalPodAutoscaler --api-versions batch/v1 --api-versions batch/v1/CronJob --api-versions batch/v1/Job --api-versions bitnami.com/v1alpha1 --api-versions bitnami.com/v1alpha1/SealedSecret --api-versions cert-manager.io/v1 --api-versions cert-manager.io/v1/Certificate --api-versions cert-manager.io/v1/CertificateRequest --api-versions cert-manager.io/v1/ClusterIssuer --api-versions cert-manager.io/v1/Issuer --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1/CertificateSigningRequest --api-versions cilium.io/v2 --api-versions cilium.io/v2/CiliumClusterwideNetworkPolicy --api-versions cilium.io/v2/CiliumEndpoint --api-versions cilium.io/v2/CiliumExternalWorkload --api-versions cilium.io/v2/CiliumIdentity --api-versions cilium.io/v2/CiliumNetworkPolicy --api-versions cilium.io/v2/CiliumNode --api-versions cilium.io/v2alpha1 --api-versions cilium.io/v2alpha1/CiliumCIDRGroup --api-versions cilium.io/v2alpha1/CiliumL2AnnouncementPolicy --api-versions cilium.io/v2alpha1/CiliumLoadBalancerIPPool --api-versions cilium.io/v2alpha1/CiliumNodeConfig --api-versions cilium.io/v2alpha1/CiliumPodIPPool --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1/Lease --api-versions dex.coreos.com/v1 --api-versions dex.coreos.com/v1/AuthCode --api-versions dex.coreos.com/v1/AuthRequest --api-versions dex.coreos.com/v1/Connector --api-versions dex.coreos.com/v1/DeviceRequest --api-versions dex.coreos.com/v1/DeviceToken --api-versions dex.coreos.com/v1/OAuth2Client --api-versions dex.coreos.com/v1/OfflineSessions --api-versions dex.coreos.com/v1/Password --api-versions dex.coreos.com/v1/RefreshToken --api-versions dex.coreos.com/v1/SigningKey --api-versions discovery.k8s.io/v1 --api-versions discovery.k8s.io/v1/EndpointSlice --api-versions eventing.keda.sh/v1alpha1 --api-versions eventing.keda.sh/v1alpha1/CloudEventSource --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1/Event --api-versions external-secrets.io/v1alpha1 --api-versions external-secrets.io/v1alpha1/ClusterSecretStore --api-versions external-secrets.io/v1alpha1/ExternalSecret --api-versions external-secrets.io/v1alpha1/PushSecret --api-versions external-secrets.io/v1alpha1/SecretStore --api-versions external-secrets.io/v1beta1 --api-versions external-secrets.io/v1beta1/ClusterExternalSecret --api-versions external-secrets.io/v1beta1/ClusterSecretStore --api-versions external-secrets.io/v1beta1/ExternalSecret --api-versions external-secrets.io/v1beta1/SecretStore --api-versions flowcontrol.apiserver.k8s.io/v1beta2 --api-versions flowcontrol.apiserver.k8s.io/v1beta2/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta2/PriorityLevelConfiguration --api-versions flowcontrol.apiserver.k8s.io/v1beta3 --api-versions flowcontrol.apiserver.k8s.io/v1beta3/FlowSchema --api-versions flowcontrol.apiserver.k8s.io/v1beta3/PriorityLevelConfiguration --api-versions generators.external-secrets.io/v1alpha1 --api-versions generators.external-secrets.io/v1alpha1/ACRAccessToken --api-versions generators.external-secrets.io/v1alpha1/ECRAuthorizationToken --api-versions generators.external-secrets.io/v1alpha1/Fake --api-versions generators.external-secrets.io/v1alpha1/GCRAccessToken --api-versions generators.external-secrets.io/v1alpha1/GithubAccessToken --api-versions generators.external-secrets.io/v1alpha1/Password --api-versions generators.external-secrets.io/v1alpha1/VaultDynamicSecret --api-versions generators.external-secrets.io/v1alpha1/Webhook --api-versions helm.cattle.io/v1 --api-versions helm.cattle.io/v1/HelmChart --api-versions helm.cattle.io/v1/HelmChartConfig --api-versions k3s.cattle.io/v1 --api-versions k3s.cattle.io/v1/Addon --api-versions k3s.cattle.io/v1/ETCDSnapshotFile --api-versions k3s.cattle.io/v1/ListenerConfig --api-versions keda.sh/v1alpha1 --api-versions keda.sh/v1alpha1/ClusterTriggerAuthentication --api-versions keda.sh/v1alpha1/ScaledJob --api-versions keda.sh/v1alpha1/ScaledObject --api-versions keda.sh/v1alpha1/TriggerAuthentication --api-versions kyverno.io/v1 --api-versions kyverno.io/v1/ClusterPolicy --api-versions kyverno.io/v1/GenerateRequest --api-versions kyverno.io/v1/Policy --api-versions kyverno.io/v1alpha2 --api-versions kyverno.io/v1alpha2/AdmissionReport --api-versions kyverno.io/v1alpha2/BackgroundScanReport --api-versions kyverno.io/v1alpha2/ClusterAdmissionReport --api-versions kyverno.io/v1alpha2/ClusterBackgroundScanReport --api-versions kyverno.io/v1beta1 --api-versions kyverno.io/v1beta1/UpdateRequest --api-versions kyverno.io/v2 --api-versions kyverno.io/v2/AdmissionReport --api-versions kyverno.io/v2/BackgroundScanReport --api-versions kyverno.io/v2/CleanupPolicy --api-versions kyverno.io/v2/ClusterAdmissionReport --api-versions kyverno.io/v2/ClusterBackgroundScanReport --api-versions kyverno.io/v2/ClusterCleanupPolicy --api-versions kyverno.io/v2/PolicyException --api-versions kyverno.io/v2/UpdateRequest --api-versions kyverno.io/v2alpha1 --api-versions kyverno.io/v2alpha1/GlobalContextEntry --api-versions kyverno.io/v2beta1 --api-versions kyverno.io/v2beta1/CleanupPolicy --api-versions kyverno.io/v2beta1/ClusterCleanupPolicy --api-versions kyverno.io/v2beta1/ClusterPolicy --api-versions kyverno.io/v2beta1/Policy --api-versions kyverno.io/v2beta1/PolicyException --api-versions metallb.io/v1alpha1 --api-versions metallb.io/v1alpha1/AddressPool --api-versions metallb.io/v1beta1 --api-versions metallb.io/v1beta1/AddressPool --api-versions metallb.io/v1beta1/BFDProfile --api-versions metallb.io/v1beta1/BGPAdvertisement --api-versions metallb.io/v1beta1/BGPPeer --api-versions metallb.io/v1beta1/Community --api-versions metallb.io/v1beta1/IPAddressPool --api-versions metallb.io/v1beta1/L2Advertisement --api-versions metallb.io/v1beta1/ServiceL2Status --api-versions metallb.io/v1beta2 --api-versions metallb.io/v1beta2/BGPPeer --api-versions monitoring.coreos.com/v1 --api-versions monitoring.coreos.com/v1/ServiceMonitor --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1/Ingress --api-versions networking.k8s.io/v1/IngressClass --api-versions networking.k8s.io/v1/NetworkPolicy --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1/RuntimeClass --api-versions policy/v1 --api-versions policy/v1/PodDisruptionBudget --api-versions projectcontour.io/v1 --api-versions projectcontour.io/v1/HTTPProxy --api-versions projectcontour.io/v1/TLSCertificateDelegation --api-versions projectcontour.io/v1alpha1 --api-versions projectcontour.io/v1alpha1/ContourConfiguration --api-versions projectcontour.io/v1alpha1/ContourDeployment --api-versions projectcontour.io/v1alpha1/ExtensionService --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1/ClusterRole --api-versions rbac.authorization.k8s.io/v1/ClusterRoleBinding --api-versions rbac.authorization.k8s.io/v1/Role --api-versions rbac.authorization.k8s.io/v1/RoleBinding --api-versions reports.kyverno.io/v1 --api-versions reports.kyverno.io/v1/ClusterEphemeralReport --api-versions reports.kyverno.io/v1/EphemeralReport --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1/PriorityClass --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1/CSIDriver --api-versions storage.k8s.io/v1/CSINode --api-versions storage.k8s.io/v1/CSIStorageCapacity --api-versions storage.k8s.io/v1/StorageClass --api-versions storage.k8s.io/v1/VolumeAttachment --api-versions v1 --api-versions v1/ConfigMap --api-versions v1/Endpoints --api-versions v1/Event --api-versions v1/LimitRange --api-versions v1/Namespace --api-versions v1/Node --api-versions v1/PersistentVolume --api-versions v1/PersistentVolumeClaim --api-versions v1/Pod --api-versions v1/PodTemplate --api-versions v1/ReplicationController --api-versions v1/ResourceQuota --api-versions v1/Secret --api-versions v1/Service --api-versions v1/ServiceAccount --api-versions wgpolicyk8s.io/v1alpha2 --api-versions wgpolicyk8s.io/v1alpha2/ClusterPolicyReport --api-versions wgpolicyk8s.io/v1alpha2/PolicyReport --include-crds" dir=/tmp/_argocd-repo/d73ea43e-8a6c-472c-8963-270a33b8e328/umbrella-charts/cilium-hubble-ui execID=800b4
