### ISSUE TITLE
More flexible secrets

### ISSUE THREAD

**Issue by pbecotte** [argoproj/argo-helm#194]
**Is your feature request related to a problem? Please describe.**
Setting up LDAP on Argocd, there is a nice feature where argo can use secrets to merge withthe config file. As the docs say

> `Any values which start with '$' will look to a key in argocd-secret of the same name (minus the $), to obtain the actual value. This allows you to store the clientSecret as a kubernetes secret.`

However, the helm chart doesn't actually give us any way to put any extra secrets in there (BIND_PASSWORD in my case).

**Describe the solution you'd like**
The argocd-secret needs to be more flexible. It should either just be a `toYaml` block of `secret:`, a `range` block of key/value pairs, or adding a configurable custom block at the end of the existing stuff.

**Comment by seanson** [comment]
Exposed via `configs.secret.extra` in https://github.com/argoproj/argo-helm/commit/4b22128b4cf10bbab9ccab56051a05e98363817a
