### ISSUE TITLE
Unclear pre-requisites for argo-workflows

### ISSUE THREAD

**Issue by cippaciong** [argoproj/argo-helm#1943]
### Is your feature request related to a problem?

Hello, I'm updating my argo-workflow deployment from chart version 0.13.1 to the latest 0.22.15 but I think the [pre-requisite section](https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows#pre-requisites) section in the chart documentation might be out of date.

That section mentions that:
1. The chart uses an install hook to configure the CRD definition
2. Users are supposed to manually create a ServiceAccount in the Namespace in which the release will be deployed w/ appropriate bindings and set the `serviceAccountName` field in the Workflow spec

I tried to search in the templates but didn't find any helm hook to configure the CRDs. Also, it's not clear what the `serviceAccountName` should be defined. It used to be set using `init.serviceAccount` but that changed a long time ago between 0.2.9 and 0.2.10 (see #834)

### Related helm chart

argo-workflows

### Describe the solution you'd like

The question at this point is if the pre-requisites are still valid.

If yes, I think they should be more explicit about how to create the rbac resource and how/where to set the `serviceAccountName` field.

If they're not required anymore, they should probably be removed. 

### Additional context

I noticed the issue because my configuration came from an old setup where `init.serviceAccount` was still set. We kept updating the helm chart without really taking care of it and I noticed it only now.

**Comment by yu-croco** [comment]
Hi @cippaciong , thank you for raising issue.

> The question at this point is if the pre-requisites are still valid.

The answer is no. I will update README.

**Comment by cippaciong** [comment]
That's great! Thanks for the clarification and for updating the docs @yu-croco
