### ISSUE TITLE
[argo-rollouts] Ability to trust private CAs

### ISSUE THREAD

**Issue by stavrospieros1** [argoproj/argo-helm#1957]
### Is your feature request related to a problem?

We need to reach out a private custom application from inside Argo Rollouts pods.
Right now when we try to reach it we receive `x509: certificate signed by unknown authority`
The ca is known and we just need somehow to trust it from inside Argo Rollouts.

### Related helm chart

argo-rollouts

### Describe the solution you'd like

I found out the following issue where a similar problem in argo-cd is solved by mounting the ca-store
[argoproj/argo-cd#6477](https://github.com/argoproj/argo-cd/issues/6477)
But argo rollouts chart does not allow us to add volumes and volumeMounts
https://github.com/argoproj/argo-helm/blob/main/charts/argo-rollouts/templates/controller/deployment.yaml

So if the argo rollouts chart  allows us to add volumes and volumeMounts we can address the problem for argo-rollouts too. 

Of course maybe the community has a better idea. 

### Describe alternatives you've considered

I have not something else in mind, but any approach that could make possible to trust additional ca inside argo-rollouts is more than welcome.

**Comment by jmeridth** [comment]
@stavrospieros1 is this similar?  Was closed by https://github.com/argoproj/argo-helm/pull/1965

**Comment by stavrospieros1** [comment]
Hi @jmeridth , yes  #1965 covers my request.
Thanks a lot !
