### ISSUE TITLE
Helm 3 compatibility for argo chart

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo-helm#196]
**Is your feature request related to a problem? Please describe.**
#169 made the argo-cd chart compatible with both Helm 2 and Helm 3. I'd expect the same setup to work with the argo (workflows) chart.

**Additional context**
I'm happy to make the PR if there's agreement that it's worth doing 😄

**Comment by stefansedich** [comment]
This should have been resolved in #229 so closing this issue off.
