### ISSUE TITLE
Failure to upgrade to version 5.29.0

### ISSUE THREAD

**Issue by igitcode** [argoproj/argo-helm#1961]
### Describe the bug

I realize 5.29.0 was just released in the past few hours, but needed to upgrade so I tried latest version available.

I just attempted to upgrade my ArgoCD instance from 5.13.8 to 5.29.0 and received the below error. I then upgraded from 5.13.8 to 5.28.2 successfully. When trying to upgrade from 5.28.2 to 5.29.0, I ran into the same error below.

```
│ Error: template: argo-cd/templates/argocd-configs/cluster-secrets.yaml:7:24: executing "argo-cd/templates/argocd-configs/cluster-secrets.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
│ 
│   with module.argocd.helm_release.argo-cd,
│   on ../../../modules/argocd/main.tf line 15, in resource "helm_release" "argo-cd":
│   15: resource "helm_release" "argo-cd" {

```

### Related helm chart

argo-cd

### Helm chart version

5.29.0

### To Reproduce

1. Install some recent version of ArgoCD (I was on 5.13.8)
2. Upgrade to 5.29.0
3. Receive error mentioned above.

### Expected behavior

I expected ArgoCD to upgrade to version 5.29.0 successfully.

**Comment by De1taE1even** [comment]
This same issue hit me as well, we had to downgrade back to 5.28.2 in the mean time.
