### ISSUE TITLE
Failed to update to 5.28.3

### ISSUE THREAD

**Issue by OlivierJavaux** [argoproj/argo-helm#1962]
### Describe the bug

Hello,

5.28.3 helm chart fails to install.
Problem is in templates/argocd-configs/repository-secret.yaml and templates/argocd-configs/repository-credentials-secret.yaml files.
Please, replace ".Release.Namespace" with "$.Release.Namespace" as we are in range section.

Thanks for your help

### Related helm chart

argo-cd

### Helm chart version

5.28.3

### To Reproduce

1. helm template -f ....

### Expected behavior

helm template is working correctly

**Comment by mkilchhofer** [comment]
I think you mean version 5.29.0 as 5.28.3 is not a valid release ;-)

Duplicate of #1961 and will be fixed with PR:
- #1963

**Comment by OlivierJavaux** [comment]
You are right, 5.29.0.
Many thanks for the quick fix! (5.29.1 solves the problem)
