### ISSUE TITLE
Setting additional account password using helm cli causes error

### ISSUE THREAD

**Issue by quintonn** [argoproj/argo-helm#1985]
### Describe the bug

When I run a helm install/upgrade command and setting the 'configs.secret.extra.accounts.alice.password' value, I get the error:

> Error: UPGRADE FAILED: template: argo-cd/templates/argocd-configs/argocd-secret.yaml:46:26: executing "argo-cd/templates/argocd-configs/argocd-secret.yaml" at <b64enc>: wrong type for value; expected string; got map[string]interface {}

In another project where I use AWS CDK code, I set the same account password using "cluster.addHelmChart" and provide the same values, and it works fine.

### Related helm chart

argo-cd

### Helm chart version

5.29.1

### To Reproduce

Run:
`helm upgrade --repo https://argoproj.github.io/argo-helm argo-cd argo-cd -n argocd -f ./scripts/argocd/values.yaml --create-namespace --set 'configs.secret.argocdServerAdminPassword=$2y$10$puvrMR6Q/FDCXfKy255cs.mFCAcBwkfiwSHaZYMH/pi9ptOCZPK3u' --set configs.secret.extra.accounts.alice.password=xxxxx --install`

### Expected behavior

A successful install of Argo using Helm

**Comment by mkilchhofer** [comment]
Hi @quintonn can you check if it's related to this issue here?
- https://github.com/argoproj/argo-helm/issues/785

**Comment by quintonn** [comment]
Hi @mkilchhofer , I don't think so, but I'm not 100% sure.
When a value is set using the `--set` flag, is it different to using a values.yaml file?
Also, I am setting `argocdServerAdminPassword` and that is working correctly.

Based on argocd-secret.yaml and the error and some testing I've done, it seems to me like I can't set the `configs.secret.extra`  part the way I am.

If I try with `configs.secret.extra.test=password` it succeeds, but that's not the correct value and probably won't do anything.
