### ISSUE TITLE
Nothing happens select cluster name option in Destination Tab when creating an application.

### ISSUE THREAD

**Issue by gomgomshrimp** [argoproj/argo-helm#2065]
### Describe the bug

When creating an application, cannot select as the name of the cluster on the Destination tab.

### Related helm chart

argo-cd

### Helm chart version

5.33.3

### To Reproduce

1. Click New APP.
2. In Destination tab, select Name instead of URL option.
3. Nothing happens.

### Expected behavior

Changed to a list of names of registered clusters, not cluster URLs

### Screenshots

* URL List
![스크린샷 2023-05-19 08 39 19](https://github.com/argoproj/argo-helm/assets/12162614/c7b834e1-b3c6-4a3f-8793-5a57205dc3ef)
* Change to Name, but noting happens.
![스크린샷 2023-05-19 08 32 30](https://github.com/argoproj/argo-helm/assets/12162614/d6861b41-edd1-4939-95b4-b5661013e5be)

**Comment by yu-croco** [comment]
Hi @gomgomshrimp ,
this repo is for Helm Chart, not Argo CD itself.
So please open an issue at upstream https://github.com/argoproj/argo-cd. 🙏
