### ISSUE TITLE
Help discovery of online argo openapi schema within a description of argo CRDs 

### ISSUE THREAD

**Issue by gberche-orange** [argoproj/argo-helm#2105]
### Is your feature request related to a problem?

As an argo CR author
In order to get completion into my preferred IDE when authoring argo CR such as WorkflowTemplate
I need CRDs to include openapiv3 schemas

They are currently empty
https://github.com/argoproj/argo-helm/blob/783439b71482bdf68ecefa92a349f337e6f2491f/charts/argo-workflows/templates/crds/argoproj.io_workflowtemplates.yaml#L25-L41

### Related helm chart

argo-cd, argo-events, argo-rollouts, argo-workflows, argocd-image-updater, argocd-apps

### Describe the solution you'd like

Possibly include or reference the argo json schema, eg. https://github.com/argoproj/argo-workflows/blob/b07de995f3d2a7a38fddb29386fc3e844fb5f30c/api/jsonschema/schema.json#L4046-L4065

Likely blocked by too large default argo schema, and require smaller schema: https://github.com/argoproj/argo-workflows/issues/8190#issuecomment-1101955858

### Additional context

Workaround: Directly point the IDE to the argo workflow json schema, possibly from schema store (https://github.com/argoproj/argo-workflows/issues/11022)

![argo-schema](https://github.com/argoproj/argo-helm/assets/4748380/6e0ee3cd-c66a-4209-ba0a-d3aba7add191)

Or within the K8S settings https://argoproj.github.io/argo-workflows/ide-setup/#jetbrains-ides-community-ultimate-editions-kubernetes-plugin

**Comment by gberche-orange** [comment]
The current workaround is easy enough and sufficient. 

Only its discovery from the current CRDs might be improved. 

Adding a comment into the CRDs schema description stating `no schema are defined because of size limitations, as a workaround direct your IDE to argo schema available in schema store or https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json` would be sufficient

**Comment by joebowbeer** [comment]
By the way, another workaround is to add a file-level declaration:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json
```
