### ISSUE TITLE
Add label app.kubernetes.io/version to all argocd deployments

### ISSUE THREAD

**Issue by psimms-r7** [argoproj/argo-helm#2118]
### Is your feature request related to a problem?

Could we add the app.kubernetes.io/version label to all the pod deployments for the argocd helm chart deployments please?

This would allow us to track argocd versions

### Related helm chart

argo-cd

### Describe the solution you'd like

Add the label app.kubernetes.io/version with value of appVersion/tag to all deployments pods in order to track versioning 

### Describe alternatives you've considered

Adding the label ourselves under global.podLabels

**Comment by psimms-r7** [comment]
@yu-croco thank you

**Comment by sathieu** [comment]
@psimms-r7 What is your usecase? Why aren't you using `spec.containers[].image` ?

NB: this caused a regression: https://github.com/argoproj/argo-helm/pull/2122#issuecomment-1623422552
