### ISSUE TITLE
Support Argo Workflow v2.5.0

### ISSUE THREAD

**Issue by nicorikken** [argoproj/argo-helm#217]
With Argo Workflow v2.5.0 the deployment seems to have changed drastically: https://github.com/argoproj/argo/tree/master/manifests

Some changes I see:

- UI is now part of the controller, so a single deployment is needed.
- Argo should be able to deal with Role instead of ClusterRole for single-namespace deployment (although the current ClusterRole can be kept for now)
- The option of a database (MySQL or PostgreSQL) for storage can be added. This can be a dependent chart like for Minio (connection parameters are added to the configmap, so no real logic is required in the chart).
- Parameters for a namespaced deploy seems to have moved from environment variable to a commandline flag.

Personally I'm thinking of switching to the Kustomize way of working, as that seems to be the supported/recommended way of deploying Argo Workflow. But as I already have a Helm template, having an upgrade path is nice.

**Comment by paguos** [comment]
I think this PR #258 solves at least a majority of your points.  Maybe Open a separate issue for integrating it with the MySql and Postgres charts?

**Comment by stefansedich** [comment]
@nicorikken did #258 solve this issue for you? happy to close off this issue?

**Comment by nicorikken** [comment]
Whow, this issue is still open. I assumed it would have been closed. Yeah it did solve it for me. Maybe specific features might come up, but that can always be contributed in other issues. Thanks @paguos for your work!
