### ISSUE TITLE
[argo-cd] SAML login broken when using cert-manager

### ISSUE THREAD

**Issue by ShimiTaNaka** [argoproj/argo-helm#2171]
### Describe the bug

When creating a Certrificate resource for the ingress, and configuring okta (for example)
SAML get broken.
In the SAML configuration, the dexURL (according to the docs) is https://ui.argocd.yourorganization.net/api/dex/callback ([ref](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/okta/))
The URL actually points to the external endpoint of ArgoCD server, which is secured with SSL on the Ingress.
This creates an issue since the `argocd-dex-server-tls` mount to argocd-server is using a static secret name.
If we create a Certificate, we need to also modify the secretName for dex server accordingly

### Related helm chart

argo-cd

### Helm chart version

5.31.0

### To Reproduce

1. Install ArgoCD with certificate enable with private issuer
2. Configure Okta SAML using https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/okta/
3. Login

### Expected behavior

Login should be successful without x.509 SSL error

**Comment by mkilchhofer** [comment]
Can you explain where do you see this x.509 erorr?
please send a screenshot or log output
