### ISSUE TITLE
Argo Workflows chart 0.32.0 is missing changes in CRDs

### ISSUE THREAD

**Issue by cmontemuino** [argoproj/argo-helm#2179]
### Describe the bug

According to the diff in argo-workflows project, the chart 0.32.0 is missing changes in CRDs.

### Related helm chart

argo-workflows

### Helm chart version

0.32.0

### To Reproduce

Check the diff: https://github.com/argoproj/argo-workflows/compare/v3.4.9...master

Affected files:

- argoproj.io_clusterworkflowtemplates.yaml
- argoproj.io_cronworkflows.yaml
- argoproj.io_workflows.yaml
- argoproj.io_workflowtasksets.yaml
- argoproj.io_workflowtemplates.yaml

`forceFinalizerRemoval` in `artifactGC` is especially important.

### Expected behavior

CRDs are the same as in https://github.com/argoproj/argo-workflows repo

**Comment by jmeridth** [comment]
@cmontemuino The changes you're speaking of:

- [manifests/base/crds/full/argoproj.io_clusterworkflowtemplates.yaml](https://github.com/argoproj/argo-workflows/compare/v3.4.9...master#diff-04ff8e52e376bec1aa80014a94e86a71fb528aa0f32808490d094d05705fa947)
- [manifests/base/crds/full/argoproj.io_cronworkflows.yaml](https://github.com/argoproj/argo-workflows/compare/v3.4.9...master#diff-2151831845240445dde0fdea426b86ae62c8d2cb5f859f590d03048692686b85)
- [manifests/base/crds/full/argoproj.io_workflows.yaml](https://github.com/argoproj/argo-workflows/compare/v3.4.9...master#diff-8d25cbf1d36d3757ca1352d836cf87610c72c2ebdbadae87ec160dee7eb39223)
- [manifests/base/crds/full/argoproj.io_workflowtasksets.yaml](https://github.com/argoproj/argo-workflows/compare/v3.4.9...master#diff-fae81078b92ae59798db704f2c2007e888bde25d87961f64a1af16547ea783f8)
- [manifests/base/crds/full/argoproj.io_workflowtemplates.yaml](https://github.com/argoproj/argo-workflows/compare/v3.4.9...master#diff-b7f9550bc7f03cc03d0d11d2b36c4439a0b75914f4f475ff0c3047c755a0c0e0)

Were all made to the full CRDs.  Our argo-workflows helm chart CRDs are the minimal CRDs [here](https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows/templates/crds) which match the minimal CRDs upstream [here](https://github.com/argoproj/argo-workflows/tree/master/manifests/base/crds/minimal).  They are the same.

<details>
  <summary>Local diff showing only diff is what we have at the top in the annotations</summary>
  
   ```
    ➜  argo-workflows git:(3.4.9) diff manifests/base/crds/minimal/argoproj.io_clusterworkflowtemplates.yaml ~/code/argo-helm/charts/argo-workflows/templates/crds/argoproj.io_clusterworkflowtemplates.yaml                       
    0a1,2
    > {{- if .Values.crds.install }}
    > {{- if or (.Values.server.clusterWorkflowTemplates.enabled) (.Values.controller.clusterWorkflowTemplates.enabled) }}
    4a7,13
    >   annotations:
    >     {{- if .Values.crds.keep }}
    >     "helm.sh/resource-policy": keep
    >     {{- end }}
    >     {{- with .Values.crds.annotations }}
    >       {{- toYaml . | nindent 4 }}
    >     {{- end }}
    36a46,47
    > {{- end }}
    > {{- end }}
    ➜  argo-workflows git:(3.4.9) diff manifests/base/crds/minimal/argoproj.io_cronworkflows.yaml ~/code/argo-helm/charts/argo-workflows/templates/crds/argoproj.io_cronworkflows.yaml                                             7:30:03
    0a1
    > {{- if .Values.crds.install }}
    4a6,12
    >   annotations:
    >     {{- if .Values.crds.keep }}
    >     "helm.sh/resource-policy": keep
    >     {{- end }}
    >     {{- with .Values.crds.annotations }}
    >       {{- toYaml . | nindent 4 }}
    >     {{- end }}
    40a49
    > {{- end }}
    ➜  argo-workflows git:(3.4.9) diff manifests/base/crds/minimal/argoproj.io_workflows.yaml ~/code/argo-helm/charts/argo-workflows/templates/crds/argoproj.io_workflows.yaml                                                     7:30:35
    0a1
    > {{- if .Values.crds.install }}
    4a6,12
    >   annotations:
    >     {{- if .Values.crds.keep }}
    >     "helm.sh/resource-policy": keep
    >     {{- end }}
    >     {{- with .Values.crds.annotations }}
    >       {{- toYaml . | nindent 4 }}
    >     {{- end }}
    55a64
    > {{- end }}
    ➜  argo-workflows git:(3.4.9) diff manifests/base/crds/minimal/argoproj.io_workflowtasksets.yaml ~/code/argo-helm/charts/argo-workflows/templates/crds/argoproj.io_workflowtasksets.yaml                                       7:30:58
    0a1
    > {{- if .Values.crds.install }}
    4a6,12
    >   annotations:
    >     {{- if .Values.crds.keep }}
    >     "helm.sh/resource-policy": keep
    >     {{- end }}
    >     {{- with .Values.crds.annotations }}
    >       {{- toYaml . | nindent 4 }}
    >     {{- end }}
    41a50
    > {{- end }}
    ➜  argo-workflows git:(3.4.9) diff manifests/base/crds/minimal/argoproj.io_workflowtemplates.yaml ~/code/argo-helm/charts/argo-workflows/templates/crds/argoproj.io_workflowtemplates.yaml                                     7:31:18
    0a1
    > {{- if .Values.crds.install }}
    4a6,12
    >   annotations:
    >     {{- if .Values.crds.keep }}
    >     "helm.sh/resource-policy": keep
    >     {{- end }}
    >     {{- with .Values.crds.annotations }}
    >       {{- toYaml . | nindent 4 }}
    >     {{- end }}
    35a44
    > {{- end }}
  ```
</details>

Those changes have no where to go.  I did state this in the description of my PR for the upgrade [here](https://github.com/argoproj/argo-helm/pull/2175#issue-1814312444).

Are you experiencing an error?  A bug?

**Comment by cmontemuino** [comment]
@jmeridth thanks for the clarification. I couldn't find a mention that minimal CRDs are included in the chart, but if that's the case, then this is not a bug.
I'm closing it.

**Comment by jmeridth** [comment]
@cmontemuino that is a fair point. Us mentioning that in the README is a good idea.

**Comment by demian711** [comment]
Hello. 
Adding me to the thread as "forceFinalizerRemoval" would be useful. 
We are facing a case where Workflows are not being deleted because of the finalizer, despite there are no pods nor nothing that should block the deletion of it
