### ISSUE TITLE
argocd - configurable number of replicas and optional addition of autoscalers for the deployments

### ISSUE THREAD

**Issue by TomHellier** [argoproj/argo-helm#218]
**Is your feature request related to a problem? Please describe.**
I have a need to increase the number of replicas for the deployments in the argocd helm chart, because the deployments I have manage a lot of different clusters and Applications.

**Describe the solution you'd like**
I'd like the replicas to be configurable, and the ability to define autoscalers for the deployments.

**Describe alternatives you've considered**
I use argocd to manage argocd, so would like to be able to tune this using gitops, this forces me to make this templatable.

**Additional context**
n/a

I'm happy to work on this, but won't be able to until this evening.

**Comment by gpaul** [comment]
https://github.com/argoproj/argo-helm/pull/240
