### ISSUE TITLE
[argocd-apps]  unknown field "spec.syncOptions" in 1.4.0

### ISSUE THREAD

**Issue by babykart** [argoproj/argo-helm#2180]
### Describe the bug

Updating to argo-apps-1.4.0, the applications hang in 'OutOfSync' state with this warning in application-controller

```
W0722 14:53:56.772166       2 warnings.go:70] unknown field "spec.syncOptions"
```

### Related helm chart

argocd-apps

### Helm chart version

1.4.0

### To Reproduce

Update to argo-apps-1.4.0

### Expected behavior

Normal sync whithout warning in the application-controller logs.

**Comment by yu-croco** [comment]
Hi @babykart , thank you for raising issue.
We added `syncOptions` in [this PR](https://github.com/argoproj/argo-helm/pull/2176) but looks that indent was wrong (not `spec. syncOptions` but `spec.syncPolicy.syncOptions` ). 😇 

I will fix soon.

<img width="795" alt="image" src="https://github.com/argoproj/argo-helm/assets/30188755/154c4fd5-ea52-461d-9b9f-02594d670543">
