### ISSUE TITLE
Argo Workflows default namespace in the sidebar filter always "undefined" when opening the page for the first time

### ISSUE THREAD

**Issue by steffenneyt** [argoproj/argo-helm#2187]
### Describe the bug

When you log into argo workflows and go to the workflows tab the sidebar always has "undefined" as filter until you change it otherwise. Is there any way that i can set this to another namespace. I have not been able to find something concerning this in the helm values.yaml. This issue has confused a lot of our devs.

### Related helm chart

argo-workflows

### Helm chart version

0.30.0

### To Reproduce

1. Log into Argo Workflows
2. Open the workflows tab
3. The sidebar filter has defaulted to the "undefined" namespace

### Expected behavior

A line in the values.yaml that allows me to specify the default namespace that the filter uses

**Comment by agilgur5** [comment]
Argo Workflows does try to choose a default namespace based [on the user and configuration](https://github.com/argoproj/argo-workflows/blob/1709f96306a2f2f9dbc70cd91e005c667a140e00/ui/src/app/shared/utils.ts#L120).

> A line in the values.yaml that allows me to specify the default namespace that the filter uses

As mentioned above, Argo Workflows itself does not expose such a configuration, so the Helm Chart has no way of configuring this.
If you have a specific request for how the default namespace should be chosen per user, please open an [enhancement request upstream](https://github.com/argoproj/argo-workflows/issues/new?assignees=&labels=enhancement&projects=&template=enhancement_proposal.md).
