### ISSUE TITLE
Unintuitive (bad?) default for automountServiceAccountToken

### ISSUE THREAD

**Issue by komapa** [argoproj/argo-helm#2189]
### Describe the bug

I can see that you are not really encouraging the service account for the `redis` server but at the same time if I create the ServiceAccount, I am 100% sure I want it to be mounted in the Pod so this default is not intuitive and I think is probably causing time wasted to figure out why things are not working: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L1327

Would it be possible to change it to default to `true` instead and leave the rest as is?

Thank yoU!

### Related helm chart

argo-cd

### Helm chart version

2.7.9

### To Reproduce

```
        serviceAccount:
          create: true
          name: argocd-redis
```

### Expected behavior

With the above config, I would expect the service account to be mounted by default.

**Comment by mkilchhofer** [comment]
> Would it be possible to change it to **default to `true`** instead and leave the rest as is?

No that's an anti-pattern in term of security. Do you know [CIS benchmarks](https://www.cisecurity.org/benchmark/kubernetes)?

CIS rule 5.1.6 makes a recommendation:
> Ensure that Service Account Tokens are only mounted where necessary"
