### ISSUE TITLE
Allow to specify services as ClusterIP:None

### ISSUE THREAD

**Issue by komapa** [argoproj/argo-helm#2190]
### Is your feature request related to a problem?

We want to be able to set the `service` as `ClusterIP` but then set the `ClusterIP: None` to effectively make it headless. Currently the helm chart does not allow for that.

### Related helm chart

argo-cd

### Describe the solution you'd like

Be able to set `ClusterIP: None` for all argo-cd `service:` helm chart values.

**Comment by Gab-Menezes** [comment]
This config also makes sense for argowkflows, since headless configuration is recommended when using multiple controllers for metrics scraping. [Doc](https://argoproj.github.io/argo-workflows/metrics/#metrics-endpoint)
