### ISSUE TITLE
ArgoCD notifications processes apps only in namespace where ArgoCD is installed.

### ISSUE THREAD

**Issue by bawk3** [argoproj/argo-helm#2203]
### Describe the bug

I use paradigm app-of-apps. Parent apps located in namespace where argocd helm chart is installed. Child apps are generated in other namespaces.
Due to logs ArgoCD notification controller processes only apps in argocd namespace. Child apps are not processed.

### Related helm chart

argo-cd

### Helm chart version

5.36.1

### To Reproduce

1. Create argocd notification with any destination, for example on successful deploy.
2. Deploy ArgoCD app in argocd namespace - notification received.
3. Deploy ArgoCD app in namespace different from argocd NS - notification not received.

### Expected behavior

Receive notification from apps from all namespaces.

**Comment by yu-croco** [comment]
Hi @bawk3 , this issue is related to Argo CD's feature, so can you please open an issue on https://github.com/argoproj/argo-cd ?
*argo-helm handles Helm Chart.

**Comment by bawk3** [comment]
Okay, thanks
