### ISSUE TITLE
mulesoft rtf install not work service account not found

### ISSUE THREAD

**Issue by calvinShan** [argoproj/argo-helm#2216]
### Describe the bug

Hello,

Whe I install rtf mulesoft on EKS by using the helm, it works well based on this document:
https://docs.mulesoft.com/runtime-fabric/2.3/install-helm

however, I put the chart on Gitlab and create Argocd App to install rtf-agent based on the gitlab chart,
It does not work, the installation is blocked during the joob hook : pre-helm-upgrade-install-hook

The error is that : rtf-agent service account is not found

When I changed the pre-upgrade hook to post-upgrade hook, i got another error during the creation of po : PriorityClass not found

Are there any dependency issues when running hooks in ArgoCD

Thanks

### Related helm chart

other

### Helm chart version

2.3.34

### To Reproduce

argo app create

### Expected behavior

rtf deployed

**Comment by pdrastil** [comment]
Hi, please check the documentation for Helm hooks that are translated to Argo CD resource hooks. Behaviour might be different from what you expect as most of the resources with Helm hooks are usually deleted after the sync.

Ref:
- https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks
- https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/

**Comment by mkilchhofer** [comment]
In addition to the info provided by @pdrastil, I also think the issue here is not related to our helm charts provided to install Argoproj products.

--> So I suggest to ask for support via the Mulesoft / Runtime Fabric support.

**Comment by calvinShan** [comment]
@mkilchhofer @pdrastil in the mulesoft rtf chart, we have pre-delete which is not supported by argocd and a pre-upgrade job, the pre-upgrade is executed during the installation, i think the problem is that it cannot identity pre-install and pre-upgrade in Argocd? when I run the installation, the job should not be executed?

**Comment by mkilchhofer** [comment]
@calvinShan you're talking about an arbitrary chart which isn't related to the project here. This repository is responsible for the following charts only:
- argo-cd
- argo-events
- argo-rollouts
- argo-workflows
- argocd-apps
- argocd-image-updater

Mulesoft seems to be an enterprise product and I assume that they also have enterprise support channels to talk about this behavior.

If you have questions for Argo CD itself, you should join the CNCF Slack on `#argo-cd`. Or open a discussion over there: https://github.com/argoproj/argo-cd/discussions
