### ISSUE TITLE
ArgoCD 2.8.0 dropped feature CM based ConfigManagementPlugin

### ISSUE THREAD

**Issue by sspreitzer** [argoproj/argo-helm#2218]
### Describe the bug

ArgoCD 2.8.0 dropped ConfigMap based ConfigManagementPlugin configuration in favor of CustomResourceDefinition ConfigManagementPlugin. 

The `argo-cd` Helm Chart is (5.43.3 of today) is missing `CustomResourceDefinition/ConfigManagementPlugin`.

### Related helm chart

argo-cd

### Helm chart version

5.43.3

### To Reproduce

Update to version 5.43.3 and have a plugin configured.

### Expected behavior

Install the CRD for ConfigManagementPlugin.

**Comment by pdrastil** [comment]
Can you point me where do you see such resource? Upstream do not have it anywhere in their CRDs
Ref: https://github.com/argoproj/argo-cd/tree/v2.8.0/manifests/crds

**Comment by pdrastil** [comment]
If you are mentioning this https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#write-the-plugin-configuration-file then it's not a CRD. It's a file inside your plugin container that is used for plugin discovery.

**Comment by sspreitzer** [comment]
@pdrastil 
https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.7-2.8/#support-dropped-for-argocd-cm-plugins
https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#migrating-from-argocd-cm-plugins
https://github.com/argoproj/argo-cd/blob/f7bfb3f15b7d3e7524c705e6cf3d18659d14186e/pkg/apis/application/v1alpha1/types.go#L2531

**Comment by sspreitzer** [comment]
> If you are mentioning this https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#write-the-plugin-configuration-file then it's not a CRD. It's a file inside your plugin container that is used for plugin discovery.



> If you are mentioning this https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#write-the-plugin-configuration-file then it's not a CRD. It's a file inside your plugin container that is used for plugin discovery.

If I understand you correctly, the Kubernetes Manifest lookalike is not to be applied in the ArgoCD namespace, but a configuration file placed somewhere in the reposerver container? Is there a more specific migration documentation?

**Comment by sspreitzer** [comment]
I will close this bug, as it merely seems like a misconfiguration than an ArgoCD bug. Thank you for the clarification!

**Comment by pdrastil** [comment]
@sspreitzer It's little confusing but yes it's the same format as other K8s resources. FYI you can also use this configuration option if you want to mount this file externally to your sidecar container.

Ref: https://github.com/argoproj/argo-helm/blob/a64615414d61500835a3de0723a8a9e099540ade/charts/argo-cd/values.yaml#L362
