### ISSUE TITLE
argo-cd: dex is included but not configured

### ISSUE THREAD

**Issue by gtaylor** [argoproj/argo-helm#222]
**Describe the bug**
In following the instructions in the [upstream docs](https://argoproj.github.io/argo-cd/operator-manual/sso/), I prepared a `server.confg` `dex.config` section, similar to the functioning `server.config` `oidc.config`. Upon updating and restarting Argo, I noticed that the login screen was not showing the OIDC auth button as it was with `oidc.config` set (instead of `dex.config`). On digging further, I noticed that no config was being passed into dex.

To provide further context, I am attempting to use GitLab with Argo+Dex. I had used GitLab with Argo directly against GitLab's OIDC provider, but they don't return groups in their id_token. Hence my wanting to pull in Dex.

Dex appears to not be getting configuration, or there is some way to make this work that is not documented.

**To Reproduce**
1. Set your values in `server.config.dex.config`.
2. Restart/reload argo-cd
3. Note that the oidc login button no longer shows.

**Expected behavior**
1. Dex picks up configs from `server.config.dex.config` or by some other means.
2. Some documentation exists somewhere that shows how to make this work.

Thanks, folks!

**Comment by seanson** [comment]
As we currently pass everything under `server.config` as a YAML map to the ConfigMap, this should entirely be configured as `server.config.dex\.config`, where the key name is `dex.config` and not an object `dex` with key `config`.
