### ISSUE TITLE
ArgoCD CM server.insecure

### ISSUE THREAD

**Issue by sass1997** [argoproj/argo-helm#2224]
### Describe the bug

Unfortunatly the configmap option server.insecure isn' enough to disable tls on the argocd server. What do you think to add the extraArg `--insecure`if the server.insecure option is actived?

### Related helm chart

argo-cd

### Helm chart version

all

### To Reproduce

1. add configs.cm.server.insecure option
2. Install helm chart
3. Check Access via Port Forward an Logs of Container

### Expected behavior

If I enable insecure I want to have tls disabled in the argocd server

**Comment by mkilchhofer** [comment]
The insecure config is done via the `params` ConfigMap, not the normal `argocd-cm` ConfigMap.
So you will need to inject it like this:

```yaml
configs:
  params:
    server.insecure: true
```

**Comment by pdrastil** [comment]
Closing as feature works as expected.
