### ISSUE TITLE
[argo-cd] Provide global of Toleration and Affinity for redis-ha

### ISSUE THREAD

**Issue by vumdao** [argoproj/argo-helm#2241]
### Related helm chart

argo-cd

### Describe the solution you'd like

Add following to `redis-ha`

```
  # -- [Tolerations] for use with node taints
  # @default -- `[]` (defaults to global.tolerations)
  tolerations: []

  # -- Assign custom [affinity] rules to the deployment
  # @default -- `{}` (defaults to global.affinity preset)
  affinity: {}
```

**Comment by FernandoMiguel** [comment]
we just had a similar issue and had to chase down the subchart to pass along the expected values

**Comment by pdrastil** [comment]
We don't control / own the redis-ha subchart so this functionality cannot be added.
