### ISSUE TITLE
Inconsistency in RoleBinding namespace templates

### ISSUE THREAD

**Issue by andrewconnors** [argoproj/argo-helm#2242]
### Describe the bug

I am deploying argocd along with argocd-image-updater in my cluster using these helm charts and noticed that the argocd-image-updater RoleBinding doesn't show up in the defined namespace when the chart is deployed. This causes issues when authenticating the updater using a ServiceAccount because the required RoleBinding is placed in the "default" namespace instead of the desired one. 

I believe this can be traced to the following line in the rbac.yaml template for argocd-image-updater: https://github.com/argoproj/argo-helm/blob/main/charts/argocd-image-updater/templates/rbac.yaml#L49

Notice there is no "| quote" in the other rolebinding templates. Ex: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-repo-server/rolebinding.yaml#L16

Happy to put up a PR if it would help but I'm new to K8s so I wanted to be sure.

### Related helm chart

argocd-image-updater

### Helm chart version

0.9.1

### To Reproduce

1. deploy argocd-image-updater in a custom namespace (not default)
2. kubectl get rolebindings
3. notice the image-updater isn't there
4. kubectl get rolebindings -A
5. notice it is in a different namespace

### Expected behavior

All resources get deployed to the specified namespace in the values.yaml file

**Comment by yu-croco** [comment]
Hi @andrewconnors ,
I checked below and argocd-image-updater Rolebinding was created in foo namespace.
I tested with Helm Chart v0.9.1 and I didn't override values.yaml.

Did I miss something? 🤔 

```shell
$ k create ns foo-bar
namespace/foo-bar created
$ helm install argocd-image-updater . -n foo-bar
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/aikawa/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/aikawa/.kube/config
NAME: argocd-image-updater
LAST DEPLOYED: Sun Sep  3 22:05:31 2023
NAMESPACE: foo-bar
STATUS: deployed
REVISION: 1
TEST SUITE: None
$ k get rolebindings -A
NAMESPACE     NAME                                                ROLE                                                  AGE
foo-bar       argocd-image-updater                                Role/argocd-image-updater                             9s
kube-public   kubeadm:bootstrap-signer-clusterinfo                Role/kubeadm:bootstrap-signer-clusterinfo             9m16s
kube-public   system:controller:bootstrap-signer                  Role/system:controller:bootstrap-signer               9m18s
kube-system   kube-proxy                                          Role/kube-proxy                                       9m16s
kube-system   kubeadm:kubelet-config                              Role/kubeadm:kubelet-config                           9m18s
kube-system   kubeadm:nodes-kubeadm-config                        Role/kubeadm:nodes-kubeadm-config                     9m18s
kube-system   system::extension-apiserver-authentication-reader   Role/extension-apiserver-authentication-reader        9m18s
kube-system   system::leader-locking-kube-controller-manager      Role/system::leader-locking-kube-controller-manager   9m18s
kube-system   system::leader-locking-kube-scheduler               Role/system::leader-locking-kube-scheduler            9m18s
kube-system   system:controller:bootstrap-signer                  Role/system:controller:bootstrap-signer               9m18s
kube-system   system:controller:cloud-provider                    Role/system:controller:cloud-provider                 9m18s
kube-system   system:controller:token-cleaner                     Role/system:controller:token-cleaner                  9m18s
```
