### ISSUE TITLE
ARGOCD - Application creation | Paths not displaying

### ISSUE THREAD

**Issue by MichaelSitotaw** [argoproj/argo-helm#2246]
### Describe the bug

- We've installed ARGOCD using Helm charts on our EKS Cluster with GitHub OAUTH SSO for authentication and default Admin role for all users. However, we're facing an issue where the Helm repository paths aren't recognized while creating applications in ARGOCD, 
- While creating the application inside the argocd, The paths are not empty and not being recognised

![Screenshot 2023-09-01 at 12 27 58 AM](https://github.com/argoproj/argo-helm/assets/85827977/92ec6ff5-13fc-4cf0-a750-6f1f3140e863)

```console
# Config Map
apiVersion: v1
data:
  controller.log.format: text
  controller.log.level: info
  controller.operation.processors: "10"
  controller.repo.server.timeout.seconds: "60"
  controller.self.heal.timeout.seconds: "5"
  controller.status.processors: "20"
  otlp.address: ""
  redis.server: argocd-redis:6379
  repo.server: argocd-repo-server:8081
  reposerver.log.format: text
  reposerver.log.level: info
  reposerver.parallelism.limit: "0"
  server.basehref: /argo
  server.dex.server: http://argocd-dex-server:5556
  server.disable.auth: "false"
  server.enable.gzip: "false"
  server.insecure: "false"
  server.log.format: text
  server.log.level: info
  server.rootpath: /argo
  server.staticassets: /shared/app
  server.x.frame.options: sameorigin
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-08-30T15:47:21Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.6.0
  name: argocd-cmd-params-cm
  namespace: argocd
  resourceVersion: "361045"
  uid: 0f2fc681-887a-eeee-a688e-7015df6d3525
```
```console
apiVersion: v1
data:
  admin.enabled: "false"
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: "      connectors:\n        - type: github\n          id: github\n          name:
    GitHub\n          config:\n            clientID: clientidxx\n            clientSecret:
    clientsecretxx\n            orgs:\n              - name:
    githuborgxx\n                teams:\n                                - teamxx\n
    \               "
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  timeout.hard.reconciliation: "0"
  timeout.reconciliation: 180s
  url: https://xx.xx.com/argo
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-08-30T15:47:21Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.6.0
  name: argocd-cm
  namespace: argocd
  resourceVersion: "361044"
  uid: 0080dce0-67f4-ssws2-8aa7-c72ed5a169bb
```

### Related helm chart

argo-cd, other

### Helm chart version

5.45.0

### To Reproduce

- The Helm chart - https://github.com/argoproj/argo-helm/tree/main/charts is being used and can be added to reproduce along with the config map added above to the description
- NOTE: We have added additional helm chart - Redis Adding below for reference

```console
# chart.yaml
apiVersion: v2
appVersion: 7.0.4
description: This Helm chart provides a highly available Redis implementation with
  a master/slave configuration and uses Sentinel sidecars for failover management
home: http://redis.io/
icon: https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Redis_Logo.svg/1200px-Redis_Logo.svg.png
keywords:
- redis
- keyvalue
- database
maintainers:
- email: salimsalaues@gmail.com
  name: ssalaues
- email: aaron.layfield@gmail.com
  name: dandydeveloper
name: redis-ha
sources:
- https://redis.io/download
- https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha
- https://github.com/oliver006/redis_exporter
version: 4.22.2

```
- Im happy to share any additional missing informations here to reproduce this issue

### Expected behavior

- Helm Repo must be detected and Application path must be displayed while creating ARGOCD Application

> NOTE: ARGOCD can able to read the repo as branches are being visible while adding the Repo only the paths are displayed as blank, So Unable to add the values.yml

![Screenshot 2023-09-01 at 12 27 58 AM](https://github.com/argoproj/argo-helm/assets/85827977/92ec6ff5-13fc-4cf0-a750-6f1f3140e863)

### Screenshots

![Screenshot 2023-09-01 at 12 27 58 AM](https://github.com/argoproj/argo-helm/assets/85827977/92ec6ff5-13fc-4cf0-a750-6f1f3140e863)

**Comment by mkilchhofer** [comment]
Did you have a look into the logs of repo-server?

**Comment by MichaelSitotaw** [comment]
@mkilchhofer I dont anything strange on the repo server logs, Adding for reference

> Path was showing nil in the logs

`time="2023-09-05T17:08:07Z" level=info msg="cache hit: git@github.com:orgname/reponame.git/HEAD"
time="2023-09-05T17:08:07Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListApps grpc.service=repository.RepoServerService grpc.start_time="2023-09-05T17:08:07Z" grpc.time_ms=242.422 span.kind=server system=grpc
time="2023-09-05T17:08:07Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListRefs grpc.service=repository.RepoServerService grpc.start_time="2023-09-05T17:08:07Z" grpc.time_ms=260.55 span.kind=server system=grpc
time="2023-09-05T17:08:18Z" level=info msg="app details cache miss: b9cee7627701c39c3becb25293a428e9f93da972/&ApplicationSource{RepoURL:git@github.com:orgname/reponame.git,Path:.,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,}"
time="2023-09-05T17:08:18Z" level=info msg="git fetch origin --tags --force" dir=/tmp/_argocd-repo/58ee13b7-8dfc-4589-bc94-b280a64f0e07 execID=88d4d
time="2023-09-05T17:08:18Z" level=info msg=Trace args="[git fetch origin --tags --force]" dir=/tmp/_argocd-repo/58ee13b7-8dfc-4589-bc94-b280a64f0e07 operation_name="exec git" time_ms=335.760799
time="2023-09-05T17:08:18Z" level=info msg="git checkout --force b9cee7627701c39c3becb25293a428e9f93da972" dir=/tmp/_argocd-repo/58ee13b7-8dfc-4589-bc94-b280a64f0e07 execID=24f89
time="2023-09-05T17:08:18Z" level=info msg=Trace args="[git checkout --force b9cee7627701c39c3becb25293a428e9f93da972]" dir=/tmp/_argocd-repo/58ee13b7-8dfc-4589-bc94-b280a64f0e07 operation_name="exec git" time_ms=5.241904000000001
time="2023-09-05T17:08:18Z" level=info msg="git clean -fdx" dir=/tmp/_argocd-repo/58ee13b7-8dfc-4589-bc94-b280a64f0e07 execID=ddad7
time="2023-09-05T17:08:18Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/_argocd-repo/58ee13b7-8dfc-4589-bc94-b280a64f0e07 operation_name="exec git" time_ms=4.292528
time="2023-09-05T17:08:18Z" level=info msg="git rev-parse HEAD" dir=/tmp/_argocd-repo/58ee13b7-8dfc-4589-bc94-b280a64f0e07 execID=ac212
time="2023-09-05T17:08:18Z" level=info msg=Trace args="[git rev-parse HEAD]" dir=/tmp/_argocd-repo/58ee13b7-8dfc-4589-bc94-b280a64f0e07 operation_name="exec git" time_ms=3.003073
time="2023-09-05T17:08:18Z" level=info msg="app details cache miss: b9cee7627701c39c3becb25293a428e9f93da972/&ApplicationSource{RepoURL:git@github.com:orgname/reponame.git,Path:.,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,}"
time="2023-09-05T17:08:18Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetAppDetails grpc.service=repository.RepoServerService grpc.start_time="2023-09-05T17:08:18Z" grpc.time_ms=803.656 span.kind=server system=grpc`
