### ISSUE TITLE
Argo-events values.yaml is missing config section for Kafka based event bus

### ISSUE THREAD

**Issue by aisac-clearstreet** [argoproj/argo-helm#2248]
### Describe the bug

values.yaml is missing the `configs` section for kafka (currently only has has the settings for NATS and Jetstream).
https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/values.yaml#L61

### Related helm chart

argo-events

### Helm chart version

2.4.1

### To Reproduce

1. Open up charts/argo-events/values.yaml
2. Look at line 61 and notice `kafka` configuration is missing

### Expected behavior

charts/argo-events/values.yaml should contain a section for kafka so resulting template yaml does not have references to NAT/Jetstreeam. At the minimum , should be able to specify 
```
configs:
  kafka:
  
```
with defaults taken from the EventBus yaml

**Comment by jmeridth** [comment]
https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/templates/argo-events-controller/config.yaml is the template that would need to be updated

**Comment by pdrastil** [comment]
I'm not sure if this request is valid as there is no support in upstream repository for this.
Ref: https://github.com/argoproj/argo-events/blob/master/manifests/base/controller-manager/controller-config.yaml

If we are talking about Kafka event source see the specification for event source:
Ref: https://github.com/argoproj/argo-events/blob/master/api/event-source.md#kafkaeventsource
Ref: https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/kafka.yaml
