### ISSUE TITLE
Awrgo workflows chart doesn't add correct auth-mode argument to sever with sso.enabled=true

### ISSUE THREAD

**Issue by alhimik45** [argoproj/argo-helm#2281]
### Describe the bug

Setting `server.sso.enabled: true` and other sso params is not enough to enable SSO. It is needed to pass `--auth-mode sso` argument to server through `server.extraArgs`.

### Related helm chart

argo-workflows

### Helm chart version

0.33.3

### To Reproduce

1. Install chart with `server.sso.enabled: true`
2. Open Argo Server UI
3. Try to login through SSO
4. Get blank screen with 501 http error

### Expected behavior

Chart automatically adds `--auth-mode sso` to server params if SSO is enabled.

**Comment by jmeridth** [comment]
https://github.com/argoproj/argo-helm/issues/2277#issuecomment-1725389694

**Comment by alhimik45** [comment]
As I see, mention of auth mode in Readme was removed [here](https://github.com/argoproj/argo-helm/commit/5fb6688bcbeef2b7b1e1ed8a96d4eb7d172e5c1d#diff-ae43f5e6f178ecd373138fca9474e039d7f21240118df02ec01de5619add5c75L305)
