### ISSUE TITLE
Some maintainers are removed unintentionally from argo-helm

### ISSUE THREAD

**Issue by yu-croco** [argoproj/argo-helm#2287]
### Describe the bug

I got an email that I was removed from argo-helm maintainer.
It seems that many of maintainers are removed accidentally. 🤔 

[CODEOWNERS](https://github.com/argoproj/argo-helm/blob/main/CODEOWNERS) has some errors.

<img width="676" alt="image" src="https://github.com/argoproj/argo-helm/assets/30188755/8373f60f-cfcd-4b07-ab40-e3b850960706">

### Related helm chart

other

### Helm chart version

N/A

### To Reproduce

N/A

### Expected behavior

Let maintainers give permission.

**Comment by yu-croco** [comment]
@mkilchhofer @jmeridth @vladlosev @tico24 @pdrastil @mbevc1

Hi all, let me share the current situation in case. 🙏

**Comment by jmeridth** [comment]
I believe this is a result of https://github.com/argoproj/argoproj/pull/245

**Comment by jmeridth** [comment]
@yu-croco I have resent invites for @mbevc1 @pdrastil @vladlosev and yourself.  I will communicate with the argoproj folks necessary to get this figured out.  I bet they are hesitant to make so many new approvers.  That's gonna be an issue.  Thank you for your patience.

**Comment by yu-croco** [comment]
@jmeridth 
Thank you for your quick action! 👍 🚀

**Comment by mbevc1** [comment]
Cheers @jmeridth

**Comment by terrytangyuan** [comment]
This was simply a "mistake" I did. I removed all outside collaborators since many of them were invited for security reviews and no longer need access. I didn't expect that folks in argo-helm are not yet a member of the GitHub organization yet.

We can probably close this for now.

**Comment by yu-croco** [comment]
Thank you all for the quick action. 👍
