### ISSUE TITLE
ApplicationSet ClusterRole Resource

### ISSUE THREAD

**Issue by reedjosh** [argoproj/argo-helm#2293]
### Is your feature request related to a problem?

I'm trying to implement Application Sets from any namespace.

But then I need a ClusterRole for the application set controller much like that already available for other controllers.

https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/#cluster-scoped-argo-cd-installation

### Related helm chart

argo-cd

### Describe the solution you'd like

Please add a ClusterRole for the applicationset controller that matches the format of the other controller clusterrole options.

### Describe alternatives you've considered

I think for now I'll attempt to use the additionalresources field.

**Comment by spirkaa** [comment]
Also interested
