### ISSUE TITLE
CRD of argorollouts are outdated

### ISSUE THREAD

**Issue by Wojciech-Chilinski** [argoproj/argo-helm#2316]
### Describe the bug

Chart version `2.32.1` of argo-rollout with argo-rollout version 1.6.0 Contains old version of CRDs
[argo-rollouts repo](https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/analysis-template-crd.yaml) vs [argo-helm repo](https://github.com/argoproj/argo-helm/blob/main/charts/argo-rollouts/templates/crds/analysis-template-crd.yaml)

### Related helm chart

argo-rollouts

### Helm chart version

2.32.1

### To Reproduce

just compare

### Expected behavior

same version

**Comment by abdolence** [comment]
@tico24 this issue wasn't completely fixed.
This is the PR to fix it:
https://github.com/argoproj/argo-helm/pull/2361
