### ISSUE TITLE
redis.hardAntiAffinity not working

### ISSUE THREAD

**Issue by wolfdate25** [argoproj/argo-helm#2321]
### Describe the bug

redis-ha deploy configuration not following the values.yaml.

### Related helm chart

argo-cd

### Helm chart version

5.49.0

### To Reproduce

See manifest code.
https://github.com/argoproj/argo-helm/blob/4f5c75fbc7513d0359e11208e24df51474493686/charts/argo-cd/templates/redis/deployment.yaml#L127

### Expected behavior

make softer the antiaffinity rules.

**Comment by vumdao** [comment]
Each time I upgrade ArgoCD, I have to patch the deployment/statefulset again for Affinity
