### ISSUE TITLE
Add an additional ingress for argo-cd for webhook purposes

### ISSUE THREAD

**Issue by yannayh** [argoproj/argo-helm#2325]
### Is your feature request related to a problem?

Hey there.
My team works with ArgoCD to deploy our applications on K8s.
Our cluster has two ingress-nginx installations, one internal (for our dev team, accessible via VPN), and one external, accessible to the internet.
We exposed the ArgoCD UI with the internal ingress for security purposes, but we want to enable incoming webhooks from github in order to make our deployments quicker.
The issue here is that the helm chart supports only one ingress.

### Related helm chart

argo-cd

### Describe the solution you'd like

The optimal way would be to enable an additional ingress, allowing only the /api/webhook route, which will be accessible to the internet with a pre-shared secret.
It would be great if the helm chart would support configuring an additional ingress for the webhook, or rather a list of ingresses, and I would configure two for different routes using different ingress classnames.

Would love to hear what you think of this use-case and if it would be possible to implement.
Thanks,
Yannay

**Comment by mkilchhofer** [comment]
Did you have a look into the extraObjects option?

https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/extra-manifests.yaml

**Comment by yannayh** [comment]
It is a possibility to use that, but I would prefer not to, as I would need to add labels myself, connect the ingress to the relevant service without being able to use the helpers and so on. It will also be more likely to break between versions.
What I'm looking for is a more integrated way to add those ingress.
