### ISSUE TITLE
[argo-events] - CRDS are not up to date

### ISSUE THREAD

**Issue by ArieLevs** [argoproj/argo-helm#2337]
### Describe the bug

argo events helm chart version is not aligned with the CRDs,

for example chart version `2.4.1` has crds with version `1.7.0` https://github.com/argoproj/argo-helm/tree/argo-events-2.4.1/charts/argo-events/templates/crds
while should be `1.8.1` https://github.com/argoproj/argo-helm/blob/argo-events-2.4.1/charts/argo-events/Chart.yaml#L2

is there a "real" source of troth for the CRDs we can install them from?
the above issue raised since there is no [jetstreamExotic](https://argoproj.github.io/argo-events/eventbus/jetstream/#exotic) definition anywhere, but its already part of the documentation.

### Related helm chart

argo-events

### Helm chart version

2.4.1

### To Reproduce

install argo events chart version 2.4.1, app verion 1.8.1, the jetstreamExotic key is missing

### Expected behavior

documentation / helm app version should match crds version

**Comment by yu-croco** [comment]
>is there a "real" source of troth for the CRDs we can install them from?

We follow upstreams' CRD. In Argo Event's case, we follow below.
https://github.com/argoproj/argo-events/tree/v1.8.1/manifests/base/crds

It looks CRD is not changed for a few years in upstream... 🤔 
<img width="1901" alt="image" src="https://github.com/argoproj/argo-helm/assets/30188755/f51888a4-ba65-44e6-bd21-cb5676e56234">

**Comment by yu-croco** [comment]
@ArieLevs 
> the above issue raised since there is no [jetstreamExotic](https://argoproj.github.io/argo-events/eventbus/jetstream/#exotic) definition anywhere, but its already part of the documentation.

Do you get any errors when you deploy the resources in k8s ?

**Comment by ArieLevs** [comment]
@yu-croco yes, error returned:
```
admission webhook "webhook.argo-events.argoproj.io" denied the request: invalid spec: either "nats", "jetstream", or "kafka" needs to be specified
```
I'm using the manifest from this [example](https://argoproj.github.io/argo-events/eventbus/jetstream/#exotic)

**Comment by yu-croco** [comment]
@ArieLevs 
Thank you for the info.
Since we are following the upsteam's CRD, so I wonder it's better to ask in upsteam... 🤔 

@pdrastil @jmeridth @tico24
Do you have any ideas about this...? 🤔

**Comment by jmeridth** [comment]
@ArieLevs This feature was added to the code 2 weeks ago with https://github.com/argoproj/argo-events/pull/2878.  Release 1.8.1 was released before that.  The docs are showing features available to `master`.  You can see this by the `ValidateEventBus.go` that has `jetstreamExotic` now [here](https://github.com/argoproj/argo-events/blob/413ed5267df55e1630c948a0ed571db8a0dcde3a/controllers/eventbus/validate.go#L12).

Once argo-events does a new release, we will also release a new chart.

You may want to ping the argo-events folks in CNCF slack #argo-events about when a new release is expected.  Cheers.

**Comment by jmeridth** [comment]
We have a upstream issue in argo-workflows for showing/allowing selections of versioned docs [here](https://github.com/argoproj/argo-workflows/issues/11390).  We need to do the same with argo-events.

**Comment by ArieLevs** [comment]
great! thanks a lot @yu-croco and @jmeridth 🚀

**Comment by yu-croco** [comment]
Hi @ArieLevs ,
This PR ( https://github.com/argoproj/argo-helm/pull/2417 ) will resolve this issue. 🚀 
`jetstreamExotic` is added In https://github.com/argoproj/argo-events/compare/v1.8.1...v1.9.0 .
