### ISSUE TITLE
argo-cd: 5.51.4 - file argocd-cm.yaml is empty

### ISSUE THREAD

**Issue by batazor** [argoproj/argo-helm#2355]
### Describe the bug

config file is empty

### Related helm chart

argo-cd

### Helm chart version

5.51.4

### To Reproduce

1. helm dependencies update

### Expected behavior

5.51.3 - save correct config file

**Comment by tico24** [comment]
Can you please describe both the issue and the reproduction steps in a way that we can understand please? At this point in time the issue is very unclear.

**Comment by batazor** [comment]
hmm, very strange, yesterday the problem was that the `argocd-cm.yaml` file was empty in the chart when downloading, today everything went fine and the file is not empty, maybe yesterday there was some problem when downloading the chart? Anyway it is working now.
