### ISSUE TITLE
Add documentation for migrating Config Management Plugins from argocd-cm ConfigMap

### ISSUE THREAD

**Issue by kzap** [argoproj/argo-helm#2359]
### Is your feature request related to a problem?

ArgoCD removed support for Config Management Plugins (CMP) in the `argocd-cm` ConfigMap in v2.8 [[link](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.7-2.8/#support-dropped-for-argocd-cm-plugins)]

Support for CMP sidecar plugins was added to the Helm Chart
- https://github.com/argoproj/argo-helm/pull/1865 and released in https://github.com/argoproj/argo-helm/releases/tag/argo-cd-5.26.0
- and documentation in https://github.com/argoproj/argo-helm/pull/1747 released in https://github.com/argoproj/argo-helm/releases/tag/argo-cd-5.16.14
- ArgoCD version in Helm chart was updated to 2.8.0 in https://github.com/argoproj/argo-helm/releases/tag/argo-cd-5.43.0

Still as someone migrating from a previous version of the helm chart it is not obvious all the requirements to move from the old configMap style config to the new method in this helm chart 

While the [ArgoCD CMP migration guide](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#migrating-from-argocd-cm-plugins) has all the details, it has no examples of how to migrate if you are using the Helm Chart.

### Related helm chart

argo-cd

### Describe the solution you'd like

I would like to propose we update the README with notes on the `5.26.0` version of this helm chart on how to upgrade and what fields might be of interest to someone using the previous `argocd-cmp

**Comment by yu-croco** [comment]
Hi @kzap , thank you for opening issue.

> I would like to propose we update the README with notes on the 5.26.0 version of this helm chart on how to upgrade and what fields might be of interest to someone using the previous `argocd-cmp

We always welcome PR. :)
