### ISSUE TITLE
[argo-rollouts] - CRDs are not up to date

### ISSUE THREAD

**Issue by Sven1410** [argoproj/argo-helm#2377]
### Describe the bug

"rollout-crd.yaml" misses the field "scaleDown" in "workloadRef"
(see upstream file:  [argo-rollouts master](https://github.com/argoproj/argo-rollouts/blob/1305129da1c4c6251251952a1d377b07fc2475cc/manifests/crds/rollout-crd.yaml#L3400C26-L3400C27) )

### Related helm chart

argo-rollouts

### Helm chart version

2.32.6

### To Reproduce

compare files:
https://github.com/argoproj/argo-helm/blob/main/charts/argo-rollouts/templates/crds/rollout-crd.yaml
and:
https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/rollout-crd.yaml

search for "scaleDown:"

### Expected behavior

documentation / helm app version should match crds version

**Comment by yu-croco** [comment]
Hi @Sven1410 ,
We follow version tags, not `master` branch.
[v1.6.3](https://github.com/argoproj/argo-rollouts/blob/v1.6.3/manifests/crds/rollout-crd.yaml) doesn't have `scaleDown`, so I think CRD is not out dated. :)

**Comment by yu-croco** [comment]
It's ok, please feel free to open issues ! :)
