### ISSUE TITLE
Cannot create an application from the UI with values.yaml file in parent directory of the chart

### ISSUE THREAD

**Issue by cviktorov** [argoproj/argo-helm#242]
**Describe the bug**
Cannot create a application in the UI with values.yaml file which is placed in parent directory of the chart

**To Reproduce**
1. Create helm chart in github repo
2. Put your values.yaml file in the parent directory of the chart
3. Create an application from the UI, and add in "VALUES FILES" field: "../values.yaml"

**Expected behavior**
Expected behavior is to be created an application. This works with the argocd command line

**Screenshots**
![Screenshot 2020-02-14 at 15 21 21](https://user-images.githubusercontent.com/3735031/74535961-bd8eae80-4f3f-11ea-968f-5d03563ee27d.png)

**Additional context**
In the helm template command is to configure to search the file in the parent description. This is the error:
Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in helm/extension-service-product-cf-hcp: rpc error: code = Unknown desc = `helm template . --name s4-dev --namespace cveti-demo --kube-version 1.16` failed exit status 1: Error: render error in "s4hana-extension-service/templates/service.yaml": template: s4hana-extension-service/templates/service.yaml:11:18: executing "s4hana-extension-service/templates/service.yaml" at <.Values.service.type>: nil pointer evaluating interface {}.typecd

**Comment by seanson** [comment]
This repository is for managing and maintaining the community Helm charts for installing Argo components. Issues with ArgoCD can be raised here: https://github.com/argoproj/argo-cd
