### ISSUE TITLE
Helm Chart - Check prometheus CRD availability before creating ServiceMonitor resources

### ISSUE THREAD

**Issue by cmontemuino** [argoproj/argo-helm#2427]
### Is your feature request related to a problem?

This is a guardrail to prevent installing enabling the `telemetryConfig` and not having Prometheus installed. If that's the case, then Helm will fail because of missing Prometheus CRDs.

### Related helm chart

argo-workflows

### Describe the solution you'd like

Wrap the content of:
`charts/argo-workflows/templates/controller/workflow-controller-servicemonitor.yaml`

with: `{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}`

### Describe alternatives you've considered

None

**Comment by cmontemuino** [comment]
I can contribute with a PR if that helps.

**Comment by yu-croco** [comment]
We always welcome PR :)

**Comment by cmontemuino** [comment]
> We always welcome PR :)
> 
> Argo CD has same kind of condition for ServiceMonitor, so it sounds reasonable to adopt the same style. https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/servicemonitor.yaml#L1

Perfect!
Here it is: https://github.com/argoproj/argo-helm/pull/2430

**Comment by cmontemuino** [comment]
There's still an open pr associated to this issue. Removing the stale label.
