### ISSUE TITLE
Argocd cannot sync itself when a healthcheck is removed from the values file

### ISSUE THREAD

**Issue by perlinger** [argoproj/argo-helm#2455]
### Describe the bug

This bug may be related to issue #2450.
We are wondering if argocd supports making changes to health checks without restarting argocd.

### Related helm chart

argo-cd

### Helm chart version

v5.14.1

### To Reproduce

To reproduce the issue, please follow these steps:
1. Have a cluster running with a lua health check in the values file.
2. Remove the health check.
3. We are finding that argocd starts to hang.
4. When we delete all the argocd pods and when the pods reinstall then argocd starts to sync again and the change takes affect.

### Expected behavior

After removing the health check, expect argocd to sync itself

**Comment by perlinger** [comment]
Is it the case that ArgoCD restarts on a change to the configmap named argocd-cmd-params-cm.
- Reference: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/deployment.yaml#L29
- Healthchecks, on the other hand, are in the configmap named argocd-cm.

**Comment by pdrastil** [comment]
@crenshaw-dev Hi Michael - if I remember right `argocd-cm` was watched ConfigMap with hot reload. Can you confirm that that is the correct assumption or we are just missing checksum to restart controllers on config change.

**Comment by yu-croco** [comment]
FYI 
I found the same question in the past. Below is the answer.
https://github.com/argoproj/argo-helm/discussions/1664#discussioncomment-4631802

**Comment by perlinger** [comment]
This values file entry worked for us
```
global:
  podAnnotations:
    "argocdcm": "argocd-cm updated 01/26/2024. This is a short term manual fix"
```

**Comment by yu-croco** [comment]
which means Argo CD server doesn't watch some of the data in argocd-cm CM.... 👀

**Comment by pdrastil** [comment]
Seems like it - as simple fix we can add another checksum for components that use that ConfigMap.
