### ISSUE TITLE
helm: argocd-apps chart should support templatePatch 2.10 feature

### ISSUE THREAD

**Issue by jwitko** [argoproj/argo-helm#2463]
### Is your feature request related to a problem?

In upcoming release 2.10 a new parameter inside applicationSets is being created called `templatePatch`.  The argocd-apps helm chart allows for templating applicationSets and so it should also handle this new feature.

### Related helm chart

argocd-apps

### Describe the solution you'd like

Helm chart supports `.templatePatch` templating inside applicationSet resources

### Describe alternatives you've considered

N/A

**Comment by pdrastil** [comment]
Feature available in PR https://github.com/argoproj/argo-helm/issues/2463

**Comment by jwitko** [comment]
> Feature available in PR #2463

That seems to link to this issue

**Comment by pdrastil** [comment]
@jwitko You are right - anyway 5.55.0 / 6.x version already have CRDs and Argo CD 2.10.x so it can be implemented.
