### ISSUE TITLE
Missing Liveness and Readiness probes for redis HA proxy component

### ISSUE THREAD

**Issue by ashishkamat2791** [argoproj/argo-helm#2464]
### Is your feature request related to a problem?

We ran into problem during resilency testing for redis HA network loss and network delay
while we perform chaos testing with injection of network loss/delay script, redis HA proxy pods going into CrashLoopBackOff and also causing scaling of repo server upto 21 and then also causing them crash loopback off after certian interval.

after investgation why repo server got scaled up found that redis HA proxy caches the repo's content and unavailablity of same hitting hard to repo server

we have checked helm chart templates https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/redis/deployment.yaml and found that the section we asked for is missing.

currently for current version we have added this section manually, however sine we are proxying github repositories to check latest version if available.
Hence during next upgrade if requirement specifed does not fulfill we can run into issues and need to manually add those probes since open source version which we are proxying still does not have this section.

Please add this section on priorty in upcoming releases.

### Related helm chart

argo-cd

### Describe the solution you'd like

Add Liveness and readiness probes for redis HA proxy with default values such as
`# readiness and livensess Probes
    livenessProbe: 
        initialDelaySeconds: 25
        timeoutSeconds: 2
        periodSeconds: 25
        successThreshold: 1
       failureThreshold: 6
    readinessProbe: 
        initialDelaySeconds: 15
        timeoutSeconds: 2
        periodSeconds: 15
        successThreshold: 1
       failureThreshold: 6

**Comment by yu-croco** [comment]
Hi @ashishkamat2791 , thank you for opening issue.
Does https://github.com/argoproj/argo-helm/pull/2400 resolve this issue?

**Comment by ashishkamat2791** [comment]
@yu-croco Yes it has similar changes we are looking for.
Please merge the PR soon

**Comment by Farfaday** [comment]
Hi,
#2400 would be for "redis" (single node deployment) and not for redis-ha.
@ashishkamat2791 wich redis are you using ?

**Comment by ashishkamat2791** [comment]
We require this liveness readiness probes basically for all components.
We are using redis and redis HA both.
For redis HA We need this fix on priority.

**Comment by ashishkamat2791** [comment]
Hi 
any ETA or updates by when the said PR will be merged to main for changes
