### ISSUE TITLE
Argo events JetStream EventBus cannot be deployed with limits

### ISSUE THREAD

**Issue by antoinetran** [argoproj/argo-helm#2469]
### Describe the bug

In a Kubernetes cluster with resourceQuota policy, which prevents any pods to be launched without limits (cpu + memory), I cannot deploy EventBus JetStream.

### Related helm chart

argo-events

### Helm chart version

2.4.2

### To Reproduce

```
helm upgrade --install my-argo-events argo/argo-events --version 2.4.2 --namespace argo-events
```
Then apply
```
# https://argoproj.github.io/argo-events/eventbus/jetstream/
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  template:
    container:
      resources:
        # kubectl top pods -n argo-events eventbus-default-js-0
        # NAME                    CPU(cores)   MEMORY(bytes)
        # eventbus-default-js-0   8m           101Mi
        requests:
          cpu: 8m
          memory: 101Mi
        limits:
          cpu: 80m
          memory: 512Mi
```

### Expected behavior

Like Argo Sensors, EventSource, etc., they can be deployed with limits. Eg for EventSource:
```
#https://raw.githubusercontent.com/argoproj/argo-events/v1.7.6/examples/event-sources/nats.yaml$
apiVersion: argoproj.io/v1alpha1$
kind: EventSource$
metadata:$
  name: nats$
  namespace: argo-events$
spec:$
  template:$
    container:$
      resources:$
        # kubectl top pods -n argo-events nats-eventsource-m5d8x-55986dd6c7-nzh74$
        # NAME                                      CPU(cores)   MEMORY(bytes)$
        # nats-eventsource-m5d8x-55986dd6c7-nzh74   6m           14Mi$
        requests:$
          cpu: 6m$
          memory: 14Mi$
        limits:$
          cpu: 60m$
          memory: 50Mi
```

### Additional context

```
argo-events   2m51s       Warning   SyncError           pod/eventbus-default-js-0                                                               Error syncing to physical cluster: pods "eventbus-default-js-0-x-argo-events-x-my-vcluster" is forbidden: failed quota: default-lrfmh: must specify limits.cpu for: main,metrics,reloader; limits.memory for: main,metrics,reloader
```

**Comment by antoinetran** [comment]
Of course I can deploy NATS, with limits, with its helm charts as a workaround. But I am struggling to make Argo Events works with a NATS JetStream cluster without tls. Because Argo Events requires secured connection. Also, it would be great to just have it working like the other Argo Events resources.

**Comment by pdrastil** [comment]
Hi @antoinetran this seems more like ask for upstream repository https://github.com/argoproj/argo-events. The Helm chart in this repo provides deployment for a argo-events controller without any event source / bus specific configuration that should be supplied by the user. Is my understanding correct and this relates only to how `EventBus` resource behaves?

**Comment by antoinetran** [comment]
> Hi @antoinetran this seems more like ask for upstream repository https://github.com/argoproj/argo-events. The Helm chart in this repo provides deployment for a argo-events controller without any event source / bus specific configuration that should be supplied by the user. Is my understanding correct and this relates only to how `EventBus` resource behaves?

Hi, oohhh you're right!! Sorry, I mixed the two repos. Closing it in favor of opening in upstream repository.

**Comment by antoinetran** [comment]
See https://github.com/argoproj/argo-events/issues/1988 for example, it works!
