### ISSUE TITLE
Add app versions to READMEs

### ISSUE THREAD

**Issue by jsolbrig** [argoproj/argo-helm#247]
**Is your feature request related to a problem? Please describe.**
Currently, when viewing readmes for the various apps, it is difficult to determine which version of the app a given chart version corresponds to. This is also true when looking at the charts from hub.helm.com.

**Describe the solution you'd like**
Add version numbers to the chart-level READMEs and maintain the number in the future.

**Comment by sebastien-prudhomme** [comment]
The app version is displayed on the Helm Hub. I don't see the problem.

**Comment by seanson** [comment]
We took this out of the argo-cd chart because it was consistently being forgotten with version bumps. Let's find a way to put this back in programmatically from the `Chart.yaml`.

**Comment by cabrinha** [comment]
I believe this project adds the chart version to the README it generates: https://github.com/norwoodj/helm-docs

**Comment by seanson** [comment]
> I believe this project adds the chart version to the README it generates: https://github.com/norwoodj/helm-docs

It does but it would require some additional templating and some extra value annotations to maintain the documentation. Some extra work but definitely a good idea!
