### ISSUE TITLE
Argo-CD Role/ClusterRole templates are rendered according to undocumented and confusing Values

### ISSUE THREAD

**Issue by cdemarco-drw** [argoproj/argo-helm#2470]
### Describe the bug

Re: the Argo-CD chart:
Several Role/ClusterRole templates--I count at least application-controller, argocd-server, argocd-reposerver, but there may be others--are rendered if the `clusterAdminAccess` value is (set AND true) OR (absent AND createClusterRoles is true). At least one of these (repoServer) sets full privs on *.* clusterwide if this is set to true.

None of this behavior is documented in the values.yaml, leaving the implementor to puzzle through the template logic and trial-and-error to get a reasonably-least-access permission scope.

This needs to be more easily-configured, and documented.

### Related helm chart

argo-cd

### Helm chart version

v5.53.8

### To Reproduce

Render the chart with various values, attempt to grok the template logic.

### Expected behavior

Documentation exists. Config options aren't mutually-referenced; there is a single way to enable/disable a given atom of functionality.

**Comment by pdrastil** [comment]
Hi @cdemarco-drw, the undocumented features such as `clusterAdminAccess` were intentionally removed from values.yaml when they were deprecated 1 year ago and complex logic you see in templates is a fallback behaviour that is going to be fully removed in https://github.com/argoproj/argo-helm/pull/2407. If we need to document something specific that will be kept afterward or fix permissions let us know.

**Comment by cdemarco-drw** [comment]
That sounds like the right path forward.
Will the change be called out via clear language in the CHANGELOG? Users will need to refactor values.

**Comment by pdrastil** [comment]
Hi @cdemarco-drw - released version 6.x removed all undocumented flags so I'll close this ticket. If you find anything that is missing or needs enhancement let us know.
