### ISSUE TITLE
`.Values.applicationSet.webhook.ingress.enabled` has no default value and errors if not provided

### ISSUE THREAD

**Issue by myoung34** [argoproj/argo-helm#2482]
### Describe the bug

If you set `metrics.enabled` to `true` then `templates/argocd-applicationset/networkpolicy.yaml` will error out for a missing value on `.applicationSet.webhook.ingress.enabled` since there is no default value

### Related helm chart

argo-cd

### Helm chart version

6.0.2

### To Reproduce

```
✗ cat kustomization.yaml| yq '.helmCharts[0].valuesInline.applicationSet'
metrics:
  enabled: true
```
```
✗ kustomize build --enable-helm . >/dev/null

Error: Error: template: argo-cd/templates/argocd-applicationset/networkpolicy.yaml:1:128: executing "argo-cd/templates/argocd-applicationset/networkpolicy.yaml" at <.Values.applicationSet.webhook.ingress.enabled>: nil pointer evaluating interface {}.ingress

Use --debug flag to render out invalid YAML
: unable to run: 'helm template argocd --namespace argocd /home/myoung/repos/github/homelab/k8s/argo/charts/argo-cd --values /tmp/kustomize-helm-2559191084/argo-cd-kustomize-values.yaml --include-crds' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-2559191084/helm HELM_CACHE_HOME=/tmp/kustomize-helm-2559191084/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-2559191084/helm/.data] (is 'helm' installed?)
~                                                                                                                                                                       
```

It will work as expected only if you provide a value:

```
✗ cat kustomization.yaml| yq '.helmCharts[0].valuesInline.applicationSet'
webhook:
  ingress:
    enabled: false
metrics:
  enabled: true
```
```
✗ kustomize build --enable-helm . >/dev/null
```
```
✗ echo $?
0
```

### Expected behavior

There should be a default value for the `.applicationSet.webhook.ingress.enabled` in Values.yaml

**Comment by pdrastil** [comment]
@myoung34 This was moved to `applicationSet.ingress` - there is no `webhook` subkey anymore

**Comment by myoung34** [comment]
@pdrastil Then I made the wrong fix for [this](https://github.com/argoproj/argo-helm/blob/5f2f0edad09d73e388d3a66b153b4eaff4312034/charts/argo-cd/templates/argocd-applicationset/networkpolicy.yaml#L1) which **does** reference a webhook causing this error

**Comment by pdrastil** [comment]
@myoung34 Good catch - issue is really in NetworkPolicy. Fix on the way:
https://github.com/argoproj/argo-helm/pull/2484
