### ISSUE TITLE
Unclear default value for `application.instanceLabelKe`

### ISSUE THREAD

**Issue by soupdiver** [argoproj/argo-helm#249]
**Describe the bug**
I'm coming from: https://github.com/argoproj/argo-cd/pull/3148
The default value for `application.instanceLabelKe` in this repo differs from the default hardcoded value at https://github.com/argoproj/argo-cd/blob/6592773a35af39de3a223b1eda41fd51bc117d8f/common/common.go#L95.
This could cause a little confusion.
I think the default value should be consistent across all related repositories.

**To Reproduce**
1. Deploy `argo-helm` with default values.

**Expected behavior**
Value for `application.instanceLabelKe` should be as described in the docs: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml#L199.

**Comment by seanson** [comment]
Looking at the documentation it looks like the current value was the old value before it changed. I'd like to see someone test the impact of changing the key, especially anyone using ArgoCD to manage itself.

**Comment by soupdiver** [comment]
> especially anyone using ArgoCD to manage itself.

Actually I'm doing exactly this.
What exactly you want to test/see?
When I changed the label and pushed to git, ArgoCD picked up the label change in the App diff but I did not notice much else. But I'm quite new to Argo...so happy to help if have some more detailed instructions.

**Comment by seanson** [comment]
Current default value is set to the recommended documentation default in https://argoproj.github.io/argo-cd/faq/#why-is-my-app-out-of-sync-even-after-syncing

>We recommend that you use argocd.argoproj.io/instance.
