### ISSUE TITLE
Automatically created workflow role does not allow to list or create workflows

### ISSUE THREAD

**Issue by sli720** [argoproj/argo-helm#2491]
### Describe the bug

I expected that I can list and create workflows through the created service account when I specify this for the Argo Workflows helm chart:

    workflow:
      serviceAccount:
        create: true
        name: argo-cli
      rbac:
        create: true

But I can not run e.g. argo list, just get this error:

`rpc error: code = PermissionDenied desc = workflows.argoproj.io is forbidden: User "system:serviceaccount:argo:argo-cli" cannot list resource "workflows" in API group "argoproj.io" in the namespace "argo" `

When I additionally add workflows to the resources in the automatically created role, it works. I don't think that's the expected behavior or? I suppose this role should be able to list and create workflows but it only contains these rules by default:

    rules:
      - apiGroups: ["argoproj.io"]
        resources:
          - "workflowtaskresults.argoproj.io"
          - "workflowartifactgctasks.argoproj.io"
          - "workflowtasksets.argoproj.io"
          - "workflowartifactgctasks.argoproj.io/status"
          - "workflowtasksets.argoproj.io/status"
        verbs:
          - "get"
          - "list"
          - "watch"
          - "create"
          - "patch"
          - "delete"
      - apiGroups: [""]
        resources:
          - "pods"
          - "pods/log"
          - "pods/exec"
        verbs:
          - "get"
          - "list"
          - "watch"
          - "create"
          - "patch"

### Related helm chart

argo-workflows

### Helm chart version

0.40.10

### To Reproduce

Install the helm chart in the namespace argo specifying these additional values:

      controller:
        workflowNamespaces:
          - argo
      workflow:
        serviceAccount:
          create: true
          name: argo-cli
        rbac:
          create: true

### Expected behavior

The default workflow role should be able to list, create and patch workflows as described here: https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows.

**Comment by yu-croco** [comment]
Hi @sli720 ,
If you mean that you used the ServiceAccount/rbac for executing argo cli, then it's a wrong use case.
The ServiceAccount/rbac is for assigning to Workflow, not for executing CLI.
Ref: https://github.com/argoproj/argo-helm/tree/main/charts/argo-workflows#serviceaccount-for-workflow-spec

**Comment by sli720** [comment]
This means I have to create the role, rolebinding and service account by myself?
