### ISSUE TITLE
ArgoCD Repo Server does not restart when `argocd-ssh-known-hosts-cm` changes

### ISSUE THREAD

**Issue by lusu007** [argoproj/argo-helm#2493]
### Describe the bug

ArgoCD Repo Server does not restart when `argocd-ssh-known-hosts-cm` changes

### Related helm chart

argo-cd

### Helm chart version

6.0.5

### To Reproduce

1. Install ArgoCD
2. Change `configs.ssh.knownHosts`

### Expected behavior

The ArgoCD repo server should restart and load the newly added keys

**Comment by mkilchhofer** [comment]
Maybe we should discuss it here rather than in the PR

> Are we sure that this is needed? I mean known-hosts can also be updated via Argo CD ui and then repo-server will use it in the next few seconds/minutes (the delay of Kubernetes updating the mounted file inside repo-server)
> ![image](https://github.com/argoproj/argo-helm/assets/7290987/2107eb65-9200-4218-963b-f4bcb690f047)
> _Source: https://github.com/argoproj/argo-helm/pull/2495#pullrequestreview-1874326251_

Did you see an issue or did you just observe that repo-server doesn't restart upon change?

**Comment by lusu007** [comment]
I did test it again. And ArgoCD automatically reloads known hosts when k8s synced the Configmap into the pod. Perhaps I was too fast while testing it yesterday.

I will close this issue and the related PR (#2495). Thanks for pointing it out @mkilchhofer! 😊
