### ISSUE TITLE
ArgoCD chart upgrade > 6 removes local users

### ISSUE THREAD

**Issue by ck250186** [argoproj/argo-helm#2509]
### Describe the bug

When we upgrade to the latest version of argo it removes our user accounts described under the .Values.server.config section in the values file.

Seems to be related to the change made to the _helpers.tpl 6 days ago -- https://github.com/argoproj/argo-helm/pull/2407/files#diff-3ab72d238c59822cae0278af9e926c7c1e61f5eb2c1cada7bfe57e6eecb67768

### Related helm chart

argo-cd

### Helm chart version

> 6.0.0

### To Reproduce

1.
--Chart.yaml--
apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: "6.0.9" #check here for updates: https://github.com/argoproj/argo-helm/releases
    repository: https://argoproj.github.io/argo-helm
2.
--Values.yaml--
argo-cd:
  server:
    config:
       accounts.xyz: login
       accounts.abc: login
       accounts.qwe: login
       admin.enabled: "false"

### Expected behavior

To be able to use the values file to add all the required users.

**Comment by pdrastil** [comment]
Hi @ck250186 this is not a bug, the `server.config` section was deprecated more than 1 year ago and fallback logic was completely removed in 6.x release along with all other deprecated features.

**Comment by ck250186** [comment]
Yeah I just read through all the docs and updated to use the new section and it worked for us.  Thank you for the quick response. Closing out this bug
