### ISSUE TITLE
ability to provide a custom CA to validate HTTPS repositories

### ISSUE THREAD

**Issue by chrpinedo** [argoproj/argo-helm#2521]
### Is your feature request related to a problem?

Our git server has a SSL/TLS certificate signed by a custom CA. We cannot validate the SSL/TLS certificate for HTTPS repositories. The only solution is to skip the validation of the SSL/TLS certificate.

### Related helm chart

argo-cd

### Describe the solution you'd like

Provide a values field to provide the Custom CA for the HTTP repositories.

**Comment by pdrastil** [comment]
Hi @chrpinedo - this should be already supported here: https://github.com/argoproj/argo-helm/blob/ba20d9518291fba3b7fc218957cea145d9d2bcdd/charts/argo-cd/values.yaml#L351

**Comment by chrpinedo** [comment]
thanks @pdrastil I did not notice it, it could solve my issue. Thanks,
