### ISSUE TITLE
 Path order in AWS Ingress with gRPC is incorrect 

### ISSUE THREAD

**Issue by fulcrum29** [argoproj/argo-helm#2532]
### Describe the bug

Due to [HTTP/S path](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/aws/ingress.yaml#L31) being first in AWS Ingress declaration gRPC path is never evaluated beacause of ALB Listener Rules prioritization.
Basically host header is always set to same value so ALB Listener rule pointing to standard HTTP endpoint is always hit regardless whether _Contnet-Type_ is set to _application/grpc_ as it has higher priority due to path order in Ingress declaration (see screenshot below)

### Related helm chart

argo-cd

### Helm chart version

from 6.0.0

### To Reproduce

Create Ingress with gRPC endpoint using AWS controller

### Expected behavior

gRPC rule evaluated first

### Screenshots

![argocd-ingress](https://github.com/argoproj/argo-helm/assets/35672150/07fb1e76-4801-49c8-91bd-05064294e90c)

**Comment by pdrastil** [comment]
Closed via https://github.com/argoproj/argo-helm/pull/2531
