### ISSUE TITLE
Introduce support for dynamic cluster sharding

### ISSUE THREAD

**Issue by oscrx** [argoproj/argo-helm#2537]
### Is your feature request related to a problem?

We are running into some scaling issues with our application controllers. I read that there is a new sharding system implemented in ArgoCD.

It was lightly discussed in https://github.com/argoproj/argo-helm/pull/2318 already.
Since it is now released I'd like to give it a go.

This issue is the notification that I will start working on this.

### Related helm chart

argo-cd

### Describe the solution you'd like

I'd like this chart to support dynamic sharding of clusters among the application controllers.

### Additional context

Here is the upstream documentation: https://argo-cd.readthedocs.io/en/stable/operator-manual/dynamic-cluster-distribution/
It goes into the inner workings and health checks being performed.

**Comment by pdrastil** [comment]
Hi @oscrx - thanks for letting us know that you would like to create PR for this. If I may ask in advance - can you please copy & paste current STS into deployment.yaml and do this as second implementation that is hidden behind feature toggle like `controller.experimental: true`? I've intentionally didn't port this as upstream contains warning this is still alpha feature and might have breaking changes. Also some env variables are different from the current set used by STS and it would be easier to merge / port changes in both implementations independently. Thank you

**Comment by oscrx** [comment]
Hey @pdrastil
I just noticed your message. I think my implementation is basically what you suggested anyway.
Let me know what you think!

**Comment by pdrastil** [comment]
Hey @oscrx, yes it is. Thanks again for the PR.
