### ISSUE TITLE
PROGRESSIVE-SYNC status panel is not getting gadded 

### ISSUE THREAD

**Issue by ravindraprasad85** [argoproj/argo-helm#2543]
### Describe the bug

In ARGOCD UI PROGRESSIVE-SYNC panel is not getting added in argocd ui. i can login into the argocd server container and can see below which is even for metrics only and its added. While progressive sync is not there even inside the argocd server container
argocd@ccid-argo-cd-argocd-server-857fd47746-zlczn:~$ ls -ltr /tmp/extensions/resources/extension-Metrics.js/
total 528
-rw-r--r-- 1 1000 1000 540642 Feb 22 18:34 extensions-Metrics.js

### Related helm chart

argo-cd

### Helm chart version

v2.10.1

### To Reproduce

  extensions:
    # -- Enable support for Argo CD extensions
    enabled: true

    ## Argo CD extension installer image
    image:
      # -- Repository to use for extension installer image
      repository: "quay.io/argoprojlabs/argocd-extension-installer"
      # -- Tag to use for extension installer image
      tag: "v0.0.1"
      # -- Image pull policy for extensions
      # @default -- `""` (defaults to global.image.imagePullPolicy)
      imagePullPolicy: ""

    # -- Extensions for Argo CD
    # @default -- `[]` (See [values.yaml])
    ## Ref: https://github.com/argoproj-labs/argocd-extension-metrics#install-ui-extension
    extensionList:
      - name: extension-metrics
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension.tar.gz
          - name: EXTENSION_CHECKSUM_URL
            value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension_checksums.txt
          **- name: EXTENSION_URL_PROGRESS
            value: https://github.com/alexymantha/argocd-progressive-sync-extension/releases/download/v1.0.0/extension.tar.gz
          - name: EXTENSION_CHECKSUM_URL_PROGRESS
            value: https://github.com/alexymantha/argocd-progressive-sync-extension/releases/download/v1.0.0/checksum.txt**

### Expected behavior

PROGRESSIVE-SYNC PANEL SHOULD BE ADDED IN ARGOCD UI PORTAL

### Additional context

Panel is not added there in argocd ui

**Comment by yu-croco** [comment]
Hi @ravindraprasad85 ,
argo-helm support extensions to add argocd-server's initContainer, but it's too hard to handle debugs for specifications except for k8s manifest itself because we are not familiar with them.
So can you please ask at [upstream](https://github.com/argoproj-labs/argocd-extension-metrics) ?

**Comment by ravindraprasad85** [comment]
@yu-croco : Since, this issue is belongs to argocd helm based deployment only, so it should be consider here as a bug if others are also facing the same. 

I have not tried with vm based deployment as mentioned above in upstream link , so raising bug there would not be fine.

i would request all if anyone can help me to installed the argocd extensions (progressive-sync, metrics, others) using helm , would be great 😊 
Thanks
