### ISSUE TITLE
Chart value for NodePort port

### ISSUE THREAD

**Issue by Tazminia** [argoproj/argo-helm#255]
**Problem**
Unable to specify port for argocd server nodeport Service.
The chart allows to set server.service.type to NodePort. However, we do not choose the port that will be used on each node to run this service.
If we want a reverse proxy or a loadbalancer to point to the argocd, we have to change the port every time we redeploy argocd.

**Possible solution**
Create a value, for example: server.service.nodeport.port

**Other solutions**
Maybe using argocd behind a reverse proxy or a loadbalancer is not a good pattern. If so, I am interested in knowing why so ?

**Comment by seanson** [comment]
If this feature is still needed, please feel free to open a pull request with the appropriate changes.

**Comment by mkilchhofer** [comment]
Hi @Tazminia, I think this is implemented now with this PR: https://github.com/argoproj/argo-helm/pull/515. If so, can you please close this issue?
