### ISSUE TITLE
Ingress tls "true" fail - require map

### ISSUE THREAD

**Issue by danilo-patrucco** [argoproj/argo-helm#2551]
### Describe the bug

Hello,

In the value file, if server.ingress.tls is set to true the deployment of the helm chart will fail with the following error: 
 
invalid type for io.k8s.api.netowrking.v1.IngressSpec.tls: got "boolean", expected "map"

It seems to have problems deploying the certs attached to the ingress specifically

### Related helm chart

argo-cd

### Helm chart version

1.6.2

### To Reproduce

deploy the helm chart and add the certificate secrets  `--set server.ingress.enabled=true --set server.ingress.tls=true --set server.certificateSecret.enabled=true --set server.certificateSecret.key=${TLSKEY} --set server.certificateSecret.crt=${TLSCRT}` 

where TLSKEY and TLSCRT are the tls keys and certificates that I manually generated (I have a private issuer)

### Expected behavior

create the ingress and the secrets (that are created properly)

**Comment by pdrastil** [comment]
Hi @danilo-patrucco it seems you are using new values with old version of the chart. The boolen flag is present in `6.x` release.

**Comment by danilo-patrucco** [comment]
> Hi @danilo-patrucco it seems you are using new values with old version of the chart. The boolen flag is present in `6.x` release.

yep, that did it....thank you very much
