### ISSUE TITLE
[argo-cd] `aws.backendProtocolVersion` should be `GRPC`

### ISSUE THREAD

**Issue by mikutas** [argoproj/argo-helm#2552]
### Describe the bug

Target health status of target group corresponding to [this service](https://github.com/argoproj/argo-helm/blob/2f82fb5992fe1e390d1ebdbc4be6d5d6c6549a37/charts/argo-cd/templates/argocd-server/aws/service.yaml#L1) becomes unhealthy because the value `server.ingress.aws.backendProtocolVersion` is `HTTP2` (i.e. the target group's protocol version is `HTTP2`).
It causes argocd-server pod's "not ready" status in environment which benefit from [pod readiness gate](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/deploy/pod_readiness_gate/).

Target health status become healthy after setting `server.ingress.aws.backendProtocolVersion` to `GRPC`.

![image](https://github.com/argoproj/argo-helm/assets/23391543/bdd853f8-1035-4f5b-9d59-33efa442043b)

![image](https://github.com/argoproj/argo-helm/assets/23391543/92b53e0c-230b-448c-aa39-b6b64e387de0)

AWS docs:
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html#health-check-settings
  - <img width="921" alt="image" src="https://github.com/argoproj/argo-helm/assets/23391543/1f2408db-3bf5-446d-81f3-e9271a5c2c53">
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#target-group-protocol-version

### Related helm chart

argo-cd

### Helm chart version

6.4.1

### To Reproduce

- Use [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller/) to expose argocd-server
- Set following values to argo-cd chart:
  - `server.ingress.enabled`: true
  - `server.ingress.controller`: aws

### Expected behavior

Health check for target group is successful

### Additional context

My guess is `alb.ingress.kubernetes.io/backend-protocol-version` need not be configurable?

related issue: https://github.com/argoproj/argo-cd/issues/8067

**Comment by yu-croco** [comment]
It's just my guess, but the default value is from sample in upstream, which means there's no deep meaning behind it
*I forgot where the doc was, but the values were the same as argo-helm's one.
And proper guide is explained [here](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#aws-application-load-balancer).

Anyway I think it's reasonable to change the default value of `.server.ingress.aws.backendProtocolVersion` and  `.server.ingress.aws.serviceType` .
I will make PR for this.

**Comment by yu-croco** [comment]
> *I forgot where the doc was, but the values were the same as argo-helm's one.

it's [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode), referred in [README](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#aws-application-load-balancer).

**Comment by yu-croco** [comment]
The purpose of the default value is https://github.com/argoproj/argo-helm/pull/2553#discussion_r1506008766 .

**Comment by mikutas** [comment]
just making sure :memo:) `serviceType` doesn't matter with this issue

**Comment by yu-croco** [comment]
> just making sure 📝) serviceType doesn't matter with this issue

Thank you for correcting! 🙏
