### ISSUE TITLE
helm argo-rollouts CRDS don't match manifests in argo-rollouts repo

### ISSUE THREAD

**Issue by dodwmd** [argoproj/argo-helm#2578]
### Describe the bug

Noticed that the CRDS that are installed as part of the helm install don't match the manifests in the argo-rollouts repo. Currently debugging a issue where rollouts 'timeout' but the replica sets show healthy.

### Related helm chart

argo-rollouts

### Helm chart version

2.34.3

### To Reproduce

Install the helm chart with default settings:

`kubectl diff -f https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/crds/rollout-crd.yaml`

### Expected behavior

No/little difference shown

**Comment by yu-croco** [comment]
Hi @dodwmd ,

>Noticed that the CRDS that are installed as part of the helm install don't match the manifests in the argo-rollouts repo. 
>kubectl diff -f https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/crds/rollout-crd.yaml

You checked the diff from `master` in upstream, but we follow specific version. Can you please check the diff with specific version?
