### ISSUE TITLE
Allow creating projects declaratively 

### ISSUE THREAD

**Issue by aqeelat** [argoproj/argo-helm#2597]
### Is your feature request related to a problem?

I'm using argo to control two clusters under two separate projects. It would be great if I can create the new project using helm in an ergonomic way.

### Related helm chart

argo-cd

### Describe the solution you'd like

A way to create new projects more natively, similar to clusterCredentials. 

### Describe alternatives you've considered

Creating the project by passing it to extraObjects

**Comment by pdrastil** [comment]
Hi @aqeelat take a look into argocd-apps chart [here](https://github.com/argoproj/argo-helm/blob/e248b6b3166491e187f7cdf499b28fb9fbf70408/charts/argocd-apps/values.yaml#L48). The deployment of Argo CD will never support this as we render CRDs as templates and it's not technically possible to provision resources that you are about to install.
