### ISSUE TITLE
dandydeveloper/redis-ha does not add expected labels that argocd cli expects to exist

### ISSUE THREAD

**Issue by rdelpret** [argoproj/argo-helm#2621]
### Describe the bug

When deploying Argo CD with this helm chart, running the following Argo CD CLI command yields the following error:
```
argocd admin cluster stats
FATA[0002] cannot find pod with selector: [app.kubernetes.io/name=argocd-redis-ha-haproxy app.kubernetes.io/name=argocd-redis] - use the --{component}-name flag in this command or set the environmental variable (Refer to https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables), to change the Argo CD component name in the CLI
```

This is because the upstream redis-ha chart dependency used by this repo does not include `app.kubernetes.io/name` labels on its workloads. It is not possible to work around this by providing a new value to the cli for the label because the key itself does not exist.

Conversely, the kustomize manifests provided by argoproj/argo-cd does use these labels on the redis workloads. 

Chart: https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/redis-haproxy-deployment.yaml#L26

Kustomize: https://github.com/argoproj/argo-cd/blob/master/manifests/base/redis/argocd-redis-deployment.yaml#L5

This could probably be addressed in the CLI codebase as well. 

### Related helm chart

argo-cd

### Helm chart version

[argo-cd-6.7.8](https://github.com/argoproj/argo-helm/releases/tag/argo-cd-6.7.8)

### To Reproduce

Run the following command after deploying an argo cd instance with this helm chart
```
argocd admin cluster stats
FATA[0002] cannot find pod with selector: [app.kubernetes.io/name=argocd-redis-ha-haproxy app.kubernetes.io/name=argocd-redis] - use the --{component}-name flag in this command or set the environmental variable (Refer to https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables), to change the Argo CD component name in the CLI
```

### Expected behavior

The command works as expected because the label key exists.

**Comment by mkilchhofer** [comment]
Maybe you can try adding this:
```diff
diff --git a/charts/argo-cd/ci/ha-static-values.yaml b/charts/argo-cd/ci/ha-static-values.yaml
index ad5efd35..fa5ecd51 100644
--- a/charts/argo-cd/ci/ha-static-values.yaml
+++ b/charts/argo-cd/ci/ha-static-values.yaml
@@ -4,6 +4,9 @@ crds:

 redis-ha:
   enabled: true
+  haproxy:
+    labels:
+      app.kubernetes.io/name: argocd-redis

 server:
   replicas: 2
```

If this works, we can add it to our default values 🙋‍♂️

**Comment by mkilchhofer** [comment]
6.7.9 should contain the fix 👍
