### ISSUE TITLE
Argocd Upgrade from 1.3.2 

### ISSUE THREAD

**Issue by reggie-k** [argoproj/argo-helm#269]
Hi,
I have argocd 1.3.2 installed, it was installed from plain yamls, as instructed in official argocd doc.
Now I want to upgrade to the latest with helm chart.
How can I perform such an upgrade?
Do I have to uninstall the existing argocd in order to install the chart?

**Comment by seanson** [comment]
This is entirely up to your local Kubernetes setup and it is generally best practice to uninstall older resources if switching to a Helm maintained chart.
