### ISSUE TITLE
upgrade issue (redis-ha crashs)

### ISSUE THREAD

**Issue by davkar3n** [argoproj/argo-helm#2693]
### Describe the bug

we are having issue with ArgoCD upgrade.

for example if you try to upgrade 5.53.6 ==> 5.53.7  redis-ha start crashing.
after 3rd instace it creates again terminates all pods even argo-server , dex, controller.

any type of changes that redis chart has make this issue happans .

If you install 5.53.7 from scretch it will work, but upgrade to another verion where were redis changes , it crashs.

### Related helm chart

argo-cd

### Helm chart version

5.53.7

### To Reproduce

upgrade 5.53.6 to 5.53.7

### Expected behavior

redis-ha crashs after creating 3rd pod

**Comment by pdrastil** [comment]
Hi @davkar3n do you run something like dynatrace on the cluster? I've seen similar issue with recent version that was crash looping for me after switch to alpine image.

See: https://github.com/DandyDeveloper/charts/issues/268
