### ISSUE TITLE
Installation fails with "CRD already exists" error

### ISSUE THREAD

**Issue by mikeraimondi** [argoproj/argo-helm#27]
This is on version 0.3.1

`helm install` fails with the following error: 
`Error: release argo failed: customresourcedefinitions.apiextensions.k8s.io "workflows.argoproj.io" already exists`

I have verified that the CRD is not present with `kubectl get crd` prior to running `helm install`.

**Comment by alexmt** [comment]
Tried to run `helm install` on fresh minikube and could not reproduce the issue. I'm pretty sure chart don't include CRD definition twice. 

Can you double-check if your cluster has workflow CRD installed? You also might run `helm install argo/argo --no-crd-hook` to skip any CRD installation.

**Comment by mikeraimondi** [comment]
I double and triple-checked that my cluster didn't have the workflow CRD installed. In fact, I manually deleted the workflow CRD, then ran `helm install` and got the same error about the CRD already existing.

Yep, we're using `--no-crd-hook` as a workaround. Very puzzled by this.

If it helps to correlate with other bug reports, the environment is GKE, version 1.10.6-gke.11.

**Comment by bbhoss** [comment]
Just ran into this myself using Docker for Mac/Kubernetes for Mac, stable channel (2.0.0.0-mac81 (29211)). Kubernetes  v1.10.3

**Comment by harshal-shah** [comment]
This happened to me with helm version 2.12.0 but does not happen in 2.11. I ran into this with jaeger-operator.

**Comment by bclermont** [comment]
still happens on helm 2.13

**Comment by chriskolenko** [comment]
Work around:

Delete custom definitions 
```
kubectl delete customresourcedefinition/applications.argoproj.io -n argocd --force=true --grace-period=0 
kubectl delete customresourcedefinition/appprojects.argoproj.io -n argocd --force=true --grace-period=0
```

Then reinstall. :'(

**Comment by rehevkor5** [comment]
Deleting the CRDs worked for one deploy, but now the problem is back again :( with:

```
    * module.argo.helm_release.argo_workflows: 1 error occurred:
    * helm_release.argo_workflows: rpc error: code = Unknown desc = object is being deleted: customresourcedefinitions.apiextensions.k8s.io "workflows.argoproj.io" already exists
```

**Comment by bclermont** [comment]
I wanted to use argo for ci/cd but as it's not ready to deploy on k8s I abandon that thought

I'll take a look again in 6 months

**Comment by mattmelgard** [comment]
This issue also shows up when trying to install argo in two separate namespaces. It looks like the name for the CRD is hardcoded... Please re-open, this is still an issue.

**Comment by alexec** [comment]
Can anyone who is experienceding this issue have time to fix this please?

**Comment by mattmelgard** [comment]
I might be able to work on this this weekend.

**Comment by mattmelgard** [comment]
@alexec seems I had the issue I was seeing confused with another one. This actually seems to work just fine for me using helm 1.12. Sorry for the mixup!

**Comment by okunc** [comment]
nope, still not fixed, I'm on helm 2.12.1 and had to apply the fix by @chriskolenko - dropping the crds helped..

**Comment by xiaoluwwwxiaolu** [comment]
have the same error,version v2.14.3

**Comment by yann-soubeyrand** [comment]
Hi,

Not sure if everyone's use case is the same, but if the use case is to install several Argo CD instances, each in its own namespace, you'll have to use Helm's --no-crd-hook option for all but the first installation. This is normal, CRD can't be installed multiple times.
