### ISSUE TITLE
ArgoCD upgrade from 6.9.3->6.10.0 not working

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [argoproj/argo-helm#2707]
### Describe the bug

When upgrading from 6.9.3 to 6.10.0, I am getting this error on my controllers:
```
Warning  Failed     108s (x12 over 4m2s)  kubelet            Error: secret "argocd-redis" not found
```
First of all, I never had a secret called: `argocd-redis`, so in the 6.10.0 upgrade docs it says to remove it.   Since I don't have it, I attempted the upgrade anyway.  Half of the controllers failed complaining about `argocd-redis` not found.  Am I missing something?  

### Related helm chart

argo-cd

### Helm chart version

6.10.0

### To Reproduce
```
kubectl delete secret argocd-redis -n argocd # I don't have this, nor anything like it.
helm upgrade argocd argo/argo-cd --reuse-values --wait
kubectl rollout restart deployment argo-cd-redis-ha-haproxy -n argocd
rollout restart statefulset argo-cd-redis-ha-server -n argocd
kubectl rollout restart deployment argo-cd-argocd-server argo-cd-argocd-repo-server argo-cd-argocd-applicationset-controller -n argocd
```
None of the existing pods will start correctly, they all fail with:
```
Error: secret "argocd-redis" not found
```

I confirmed that I never had a `argocd-redis` secret in my `argocd` namespace. 

I reverted my deployment back to 6.9.3, and all is well.

### Expected behavior

The upgrade to work

**Comment by yu-croco** [comment]
Hi @rsavage-nozominetworks 
I wonder changelog helps you?
https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#6100

**Comment by mkilchhofer** [comment]
Okay the section [How to rotate Redis secret?](https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#how-to-rotate-redis-secret) may confuse you. This is not a howto for the upgrade but a howto if you want to replace the random secret at a later time (some organization have requirements to rotate static credentials).

When you ran the helm upgrade command to version 6.10.0, did you saw a Pod (controlled by a Kubernetes Job) with the name `argocd-redis-secret-init-<hash>`?

This Pod will create the secret, not the helm chart itself. If it fails (and I hope it doesn't), the Secret will not be there.

**Comment by rsavage-nozominetworks** [comment]
Thanks. I did not see that job, but I will try again and report back with confirmation or not.

**Comment by roeldev** [comment]
I have the same problem. When I install ArgoCD on a new cluster `argocd/argocd-redis-secret-init-<hash>` errors:

```
Checking for initial Redis password in secret argocd/argocd-redis at key auth.                                                                                                                                
Argo CD Redis secret state confirmed: secret name argocd-redis.                                                                                                                                              
time="2024-05-22T19:28:23Z" level=fatal msg="key auth doesn't exist in secret argocd-redis. \n"
```

**Comment by rsavage-nozominetworks** [comment]
Update from my side.  I tried the upgrade again, I can confirm do not see the job which creates the secret.  


What I do see is these pods go into error during the upgrade:

```

NAMESPACE           NAME                                                              READY   STATUS                            RESTARTS       AGE
argocd              argo-cd-argocd-application-controller-2                           0/1     CreateContainerConfigError        0              2m5s
argocd              argo-cd-argocd-repo-server-7bb9c5f8c6-nfb69                       0/1     CreateContainerConfigError        0              2m47s
argocd              argo-cd-argocd-server-c97874978-97thj                             0/1     CreateContainerConfigError        0              2m37s
argocd              argo-cd-redis-ha-haproxy-cd884696-2hn4v                           0/1     CreateContainerConfigError        0              3m17s
argocd              argo-cd-redis-ha-server-2                                         0/3     Init:CreateContainerConfigError   0              76s
```

```
kubectl logs pod/argo-cd-argocd-application-controller-2 -n argocd
Error from server (BadRequest): container "application-controller" in pod "argo-cd-argocd-application-controller-2" is waiting to start: CreateContainerConfigError
```

```
kubectl logs pod/argo-cd-argocd-repo-server-7bb9c5f8c6-nfb69 -n argocd
Defaulted container "repo-server" out of: repo-server, copyutil (init)
Error from server (BadRequest): container "repo-server" in pod "argo-cd-argocd-repo-server-7bb9c5f8c6-nfb69" is waiting to start: CreateContainerConfigError
```
```
kubectl logs pod/argo-cd-argocd-server-c97874978-97thj -n argocd
Error from server (BadRequest): container "server" in pod "argo-cd-argocd-server-c97874978-97thj" is waiting to start: CreateContainerConfigError
```

```
kubectl logs pod/argo-cd-redis-ha-haproxy-cd884696-2hn4v -n argocd
Defaulted container "haproxy" out of: haproxy, config-init (init)
Error from server (BadRequest): container "haproxy" in pod "argo-cd-redis-ha-haproxy-cd884696-2hn4v" is waiting to start: CreateContainerConfigError

kubectl logs pod/argo-cd-redis-ha-haproxy-cd884696-2hn4v -n argocd -c config-init
10.REDACTED     argo-cd-redis-ha-announce-0.argocd.svc.cluster.local  argo-cd-redis-ha-announce-0.argocd.svc.cluster.local argo-cd-redis-ha-announce-0
10.REDACTED    argo-cd-redis-ha-announce-1.argocd.svc.cluster.local  argo-cd-redis-ha-announce-1.argocd.svc.cluster.local argo-cd-redis-ha-announce-1
10.REDACTED    argo-cd-redis-ha-announce-2.argocd.svc.cluster.local  argo-cd-redis-ha-announce-2.argocd.svc.cluster.local argo-cd-redis-ha-announce-2
```

```
kubectl logs pod/argo-cd-redis-ha-server-2 -n argocd
Defaulted container "redis" out of: redis, sentinel, split-brain-fix, config-init (init)
Error from server (BadRequest): container "redis" in pod "argo-cd-redis-ha-server-2" is waiting to start: PodInitializing

kubectl logs pod/argo-cd-redis-ha-server-2 -n argocd -c sentinel
Error from server (BadRequest): container "sentinel" in pod "argo-cd-redis-ha-server-2" is waiting to start: PodInitializing

kubectl logs pod/argo-cd-redis-ha-server-2 -n argocd -c split-brain-fix
Error from server (BadRequest): container "split-brain-fix" in pod "argo-cd-redis-ha-server-2" is waiting to start: PodInitializing

kubectl logs pod/argo-cd-redis-ha-server-2 -n argocd -c config-init
Error from server (BadRequest): container "config-init" in pod "argo-cd-redis-ha-server-2" is waiting to start: CreateContainerConfigError
```

Additionally, I had a check based on the info from @roeldev regarding `externalRedis.username`, mine is set to `""`.  The strange thing is, I have never had a problem upgrading ArgoCD, so I am either missing something or perhaps there's something inherited from prior upgrade potentially causing this issue.

FWIW Here's a screenshot
![image](https://github.com/argoproj/argo-helm/assets/108539282/fd20d152-2678-4eec-b2f8-5d9a7484219b)

Additionally, I am upgrading via terraform.  Kinda of stumped right now.

**Comment by mkilchhofer** [comment]
@rsavage-nozominetworks 

Can you share the Terraform code you are using? I also use Terraform to deploy the helm chart:
https://github.com/mkilchhofer/k8s-gitops-services/blob/886cbac2c3c1955a50aed0354e4583760f45ad3e/k3s-bootstrap/argocd.tf#L31-L35

Do you use `resource "helm_release" "argocd" {..}` or do you use Terraform to only render the manifests into a TF data source with `data "helm_template" "argocd" {..}` ?

**Comment by rsavage-nozominetworks** [comment]
@mkilchhofer I do use `resource "helm_release" "argocd" {..}`.   Here's my terraform code snipit: 

```hcl
resource "helm_release" "argo_cd" {
  name             = "argo-cd"
  namespace        = "argocd"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argo-cd"
  create_namespace = true
  version          = "6.10.0"
  values           = [local.argocd_values]
  wait             = false
  max_history      = 20
  disable_webhooks = true
  timeout          = 600
}
```

**Comment by mkilchhofer** [comment]
Thanks for sharing @rsavage-nozominetworks 
Now it is clear why it doesn't work:

> ![image](https://github.com/argoproj/argo-helm/assets/7290987/87e5a79b-a2af-42c4-9d24-0af7c218bc5c)
> Ref: https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#disable_webhooks

Can you try to unset this option?

**Comment by rsavage-nozominetworks** [comment]
@mkilchhofer yep, I'll give it a try and report back, thank you.

**Comment by rsavage-nozominetworks** [comment]
@mkilchhofer that worked.  Thanks much!!!

**Comment by sambo2021** [comment]
> Thanks for sharing @rsavage-nozominetworks Now it is clear why it doesn't work:
> 
> > ![image](https://private-user-images.githubusercontent.com/7290987/332980918-87e5a79b-a2af-42c4-9d24-0af7c218bc5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTQxNjAsIm5iZiI6MTcyODY1Mzg2MCwicGF0aCI6Ii83MjkwOTg3LzMzMjk4MDkxOC04N2U1YTc5Yi1hMmFmLTQyYzQtOWQyNC0wYWY3YzIxOGJjNWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMTMzNzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGNkYzRmNTU5YWEwNzBhZGM0ZGJmYTZjYWY5YzM1ZTU5ZDJiM2EwOTdhNTQ4YzUzYTViMTk1MDJjYzQ0MmRiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.sIDZVX0WgtwZFRkOSFIKHlhSB1Dj6DWrXpKGGJxWbmc)
> > Ref: https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#disable_webhooks
> 
> Can you try to unset this option?

the same while helm template th argo-cd chart needs --validate against the cluster to render the redis-secret-init application
