### ISSUE TITLE
argo-cd: argocd-cmp-cm is created but not mounted by deployment

### ISSUE THREAD

**Issue by damoshushu** [argoproj/argo-helm#2723]
### Describe the bug

![image](https://github.com/argoproj/argo-helm/assets/24828250/f2b541c4-673d-4579-8cee-66ce0155a750)

the argocd-cmp-cm is created, but it is not mounted 

### Related helm chart

argo-cd

### Helm chart version

argo-cd 6.11.1

### To Reproduce

1. add plugin values.yaml

    configs:
      cmp:
          create: true
          plugins:
            kustomized-helm:
            .....

2. deploy helm
3. check config map is created
4. check plugin is not mounted

### Expected behavior

the plugin in the config map is mounted to plugins folder

**Comment by damoshushu** [comment]
volumes: []
  #  - name: argocd-cmp-cm
  #    configMap:
  #      name: argocd-cmp-cm

**Comment by florianspk** [comment]
Hello @damoshushu 
Why did you close your PR ?  I think it could be an improvement to mount the configmap argocd-cmp-cm in the repo-server when .Values.configs.cmp.create is enabled
Can you reopen your issues and remove the bug label? I'd suggest a PR along these way
@NIXKnight  any thoughts on this ?

**Comment by florianspk** [comment]
I didn't say anything, but if you practice integrating plugins into argocd a little more, they can be mounted differently depending on the module.

**Comment by NIXKnight** [comment]
@florianspk You need to create the sidecar containers and mount the configuration of your plugins in them. You can find an example [here](https://github.com/argoproj/argo-helm/pull/1865) in my PR.
