### ISSUE TITLE
RBAC not getting applied namespaces based

### ISSUE THREAD

**Issue by ravindraprasad85** [argoproj/argo-helm#2732]
### Describe the bug

I do have my (PROD) ArgoCD cluster deployed in Kubernetes cluster using helm, ArgoCD Version 2.9.3 . It running in HA mode with redis HA . Its controlling more than 10 clusters (Prod/Dev/UAT) currently & 10 Repos. I do have more than 100 Apps running in that cluster. Now i needs to control the different teams in Dev cluster and their namespace wise. They should be able to perform anything in their namespace only where the applicationsets/applications running. Client application installed in Argocd cluster Namespace: "ccid-argocd"

Dev Cluster --> Team: A & namespace: A
Dev Cluster --> Team: B & namespace: B

I have tried to write the RBAC policies by following
https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/

currently ARGOCD is integrated with SSO and scope is "group", i have tried below but not working as expected

p, role:team-qa, applicationsets, get, aam-qa-perf-us-east/*, allow
p, role:team-qa, applicationsets, get, *, allow
p, role:team-qa, clusters, get, uat-east1-sa-eks, allow
g, teamnonprod, role:team-qa
g, my-org:teamnonprod, role:team-qa
-Thanks

### Related helm chart

argo-cd

### Helm chart version

v3.15.1

### To Reproduce

Modify the role-rbac-cm

### Expected behavior

RBAC should applied and working as expected

### Additional context

Namespace based RBAC need to be configured in ARGOCD

**Comment by yu-croco** [comment]
Hi @ravindraprasad85 , since it's related to Argo CD itself, can you please open an issue in [upstream](https://github.com/argoproj/argo-cd) ?
*argo-helm manages Helm Chart, not Argo CD itself.

Thanks.

**Comment by ravindraprasad85** [comment]
Okay

**Comment by yu-croco** [comment]
Let us close this for now. Please feel free to open an issue when it comes to Helm Chart. :)
