### ISSUE TITLE
Argo Rollouts Dashboard Stuck in Loading

### ISSUE THREAD

**Issue by sdoncila** [argoproj/argo-helm#2747]
### Describe the bug

After installing Argo-Rollouts Helm Chart, the screen is stuck in loading.

It happens in both of these scenarios:

- when I do port-forwarding of the dashboard pod or service
- when I enable ingress for dashboard and create a AWS application load balancer.

Logs from dashboard pod:

```
time="2024-06-06T08:53:15Z" level=info msg="Argo Rollouts starting" version=v1.6.6+737ca89
time="2024-06-06T08:53:15Z" level=info msg="Creating event broadcaster"
time="2024-06-06T08:53:15Z" level=info msg="Setting up event handlers"
time="2024-06-06T08:53:15Z" level=info msg="Setting up experiments event handlers"
time="2024-06-06T08:53:15Z" level=info msg="Setting up analysis event handlers"
time="2024-06-06T08:53:15Z" level=info msg="Leaderelection get id argocd-rollouts-argo-rollouts-8477d4b6f9-4twdj_a5f1908f-5e0b-4c1c-b0b6-90737114d99a"
time="2024-06-06T08:53:15Z" level=info msg="Starting Metric Server at 0.0.0.0:8090"
time="2024-06-06T08:53:15Z" level=info msg="Starting Healthz Server at 0.0.0.0:8080"
time="2024-06-06T08:53:15Z" level=info msg="attempting to acquire leader lease argo-rollouts/argo-rollouts-controller-lock...\n"
time="2024-06-06T08:53:16Z" level=info msg="New leader elected: argocd-rollouts-argo-rollouts-868546b4bc-8dccz_835bab9e-d1eb-4b47-828e-5c2d8070d3f7"
time="2024-06-06T08:53:32Z" level=info msg="successfully acquired lease argo-rollouts/argo-rollouts-controller-lock\n"
time="2024-06-06T08:53:32Z" level=info msg="New leader elected: argocd-rollouts-argo-rollouts-8477d4b6f9-4twdj_a5f1908f-5e0b-4c1c-b0b6-90737114d99a"
time="2024-06-06T08:53:32Z" level=info msg="I am the new leader: argocd-rollouts-argo-rollouts-8477d4b6f9-4twdj_a5f1908f-5e0b-4c1c-b0b6-90737114d99a"
time="2024-06-06T08:53:32Z" level=info msg="Starting Controllers"
time="2024-06-06T08:53:32Z" level=info msg="invalidated cache for resource in namespace: argo-rollouts with the name: argo-rollouts-notification-configmap"
time="2024-06-06T08:53:32Z" level=info msg="Waiting for controller's informer caches to sync"
time="2024-06-06T08:53:32Z" level=info msg="Started controller"
time="2024-06-06T08:53:32Z" level=info msg="Starting Service workers"
time="2024-06-06T08:53:32Z" level=info msg="Starting Ingress workers"
time="2024-06-06T08:53:32Z" level=info msg="Started Service workers"
time="2024-06-06T08:53:32Z" level=info msg="Started Ingress workers"
time="2024-06-06T08:53:32Z" level=info msg="Starting analysis workers"
time="2024-06-06T08:53:32Z" level=warning msg="Controller is running."
time="2024-06-06T08:53:32Z" level=info msg="Starting Rollout workers"
time="2024-06-06T08:53:32Z" level=info msg="Started rollout workers"
time="2024-06-06T08:53:32Z" level=info msg="Started 30 analysis workers"
time="2024-06-06T08:53:32Z" level=info msg="Starting Experiment workers"
time="2024-06-06T08:53:32Z" level=info msg="Started Experiment workers"
time="2024-06-06T09:08:32Z" level=info msg="invalidated cache for resource in namespace: argo-rollouts with the name: argo-rollouts-notification-configmap"
time="2024-06-06T09:23:32Z" level=info msg="invalidated cache for resource in namespace: argo-rollouts with the name: argo-rollouts-notification-configmap"
time="2024-06-06T09:38:32Z" level=info msg="invalidated cache for resource in namespace: argo-rollouts with the name: argo-rollouts-notification-configmap"
```

Image from Load Balancer:

<img width="1710" alt="Screenshot 2024-06-06 at 12 44 47" src="https://github.com/argoproj/argo-helm/assets/139113647/6614838c-e2cf-4dc3-a027-71a776a3bfd9">

I have tested lower versions of the chart also. Thank you

### Related helm chart

argo-rollouts

### Helm chart version

1.6.6

### To Reproduce

1. Install the helm chart for Argo-Rollouts and enabled the dashboard
2. Port-forward the dashboard pod

Chart.yaml

apiVersion: v2
name: argocd-rollouts
version: 1.0.0
appVersion: v1.6.6
description: A Helm chart for Argo Rollouts
maintainers:
- name: plx
dependencies:
  - name: argo-rollouts
    version: "2.35.3"
    repository: https://argoproj.github.io/argo-helm
type: application

values.yaml

argo-rollouts:
  serviceAccount:
    create: true
  controller:
    replicas: 1
    nodeSelector:
      nodegroup: tools
    resources:
    limits:
      cpu: 150m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  dashboard:
    enabled: true
    nodeSelector:
      nodegroup: tools
    resources:
    limits:
      cpu: 150m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

### Expected behavior

The dashboards should be visible, not stuck in loading.
I deployed also a blue/green Rollouts yaml, and it is still stuck like that.

### Screenshots

<img width="1710" alt="Screenshot 2024-06-06 at 12 44 47" src="https://github.com/argoproj/argo-helm/assets/139113647/470e0d61-acfd-4dc2-b666-bd842e250aeb">

<img width="1302" alt="Screenshot 2024-06-06 at 12 55 10" src="https://github.com/argoproj/argo-helm/assets/139113647/fa020abf-3492-40a2-9903-de6b00167c0d">

**Comment by sdoncila** [comment]
<img width="1701" alt="Screenshot 2024-06-07 at 09 03 58" src="https://github.com/argoproj/argo-helm/assets/139113647/4b570811-d1a4-48f7-b92b-5e2960b1de12">

**Comment by yu-croco** [comment]
Hi @sdoncila, thank you for opening the issue.
Since argo-helm manages Helm Chart  and not so familiar with the specific behaviors, can you please open an issue/discussion in [upstream](https://github.com/argoproj/argo-rollouts) ?

**Comment by sdoncila** [comment]
@yu-croco Thank you, I opened an issue there and closing here.
Best regards,
Sergiu
