### ISSUE TITLE
HA for application and applicationset controller 

### ISSUE THREAD

**Issue by BarAshkenazi** [argoproj/argo-helm#2758]
### Is your feature request related to a problem?

Following closed issue:
https://github.com/argoproj/argo-helm/issues/1246
This is still missing

### Related helm chart

argo-cd

### Describe the solution you'd like

Implement and describe high availability of the application-/applicationset controller.
https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-application-controller

**Comment by pdrastil** [comment]
Hi @BarAshkenazi there is no HA support for application controller. As stated in values.yaml if you use more replicas it will shard the load between StatefulSets. The ApplicationSet controller supports leader election if you deploy more replicas via values.
