### ISSUE TITLE
Argo server role should allow Pod delete for retry

### ISSUE THREAD

**Issue by kristofarkas** [argoproj/argo-helm#277]
The argo server role needs to be able to delete pods, as this is how the Retry button works.

https://github.com/argoproj/argo-helm/blob/805371544d5ff408e0da4b10a97b61002729959c/charts/argo/templates/server-cluster-role.yaml#L23-L30

**Comment by stefansedich** [comment]
With #278 merged this should be fixed! thanks @kristofarkas
