### ISSUE TITLE
argo-events values.yaml missing Jetstream versions

### ISSUE THREAD

**Issue by burkaman** [argoproj/argo-helm#2787]
### Describe the bug

The direct Argo Events installation method includes a number of explicitly defined Jetstream versions here: https://github.com/argoproj/argo-events/blob/master/manifests/install.yaml#L333.

The Helm installation only has a single `latest` version: https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/values.yaml#L98

This contradicts the documentation, which correctly says "Do NOT use "latest" but a specific version in your real deployment": https://argoproj.github.io/argo-events/eventbus/jetstream/

I know I can sort of override this with `configs.jetstream.versions[0].version` etc., but is there a reason to not include all the versions from install.yaml in values.yaml here? I can open a PR if there are no objections.

### Related helm chart

argo-events

### Helm chart version

2.4.6

### To Reproduce

1. Install Argo Events using the Helm chart
2. Deploy a Jetstream EventBus with a specified version, e.g. 2.10.10
3. See the error `failed to get jetstream version, err: unsupported version "2.10.10", supported versions: "latest"`
4. Check the `argo-events-controller-manager` ConfigMap, see that `latest` is the only Jetstream version

### Expected behavior

All Jetstream versions available through the kubectl installation method should be available through Helm as well.

**Comment by yu-croco** [comment]
Hi @burkaman , this is because we follow `[manifests/base](https://github.com/argoproj/argo-events/tree/master/manifests/base)` and we don't usually focus other files.
I think it's reasonable to reflect versions in upstream.

**Comment by burkaman** [comment]
Thanks @yu-croco! Really appreciate the quick turnaround here.
