### ISSUE TITLE
Add egress NetworkPolicies

### ISSUE THREAD

**Issue by dan-m8t** [argoproj/argo-helm#2807]
### Is your feature request related to a problem?

By default we deploy default-deny ingress/egress rules into our namespaces. This means when I deploy Argo CD into a namespace with NetworkPolicies enabled it won't work because Argo CD is missing these egress rules. For example argocd-application-controller egress repo-server port to the argocd-repo-server. Only ingress rules are created.

### Related helm chart

argo-cd

### Describe the solution you'd like

A configurable helm value that allows the creation of egress rules when needed or wanted.

### Describe alternatives you've considered

For now I disabled our default deny egress rule.

**Comment by omerap12** [comment]
I can help with that :)
