### ISSUE TITLE
CRD upgrade found in read me doesn't work

### ISSUE THREAD

**Issue by CameronMukherjee** [argoproj/argo-helm#2827]
### Describe the bug

When attempting to run:
`kubectl apply -k "https://github.com/argoproj/argo-cd/manifests/crds?ref=argo-cd-7.3.6"`

You are met with:
```
error: failed to run '/usr/local/bin/git fetch --depth=1 https://github.com/argoproj/argo-cd argo-cd-7.3.6': fatal: couldn't find remote ref argo-cd-7.3.6
: exit status 128
```

### Related helm chart

argo-cd

### Helm chart version

7.3.6

### To Reproduce

1. Have a previous version of ArgoCD installed.
2. Attempt to upgrade (in my case I completely deleted the namespace for argocd).
3. Attempt to re-install, in my case via Terraform:
```
variable "namespace" {
  type = string
}

resource "helm_release" "argocd" {
  name       = "argocd"
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
  version = "7.3.6"
  namespace  = var.namespace
  values = [
    file("${path.module}/helm-values.yaml")
  ]
}
```

Found this while attempting to fix the following issue - was told to check the README for the path:
│ Error: Unable to continue with install: ClusterRole "argocd-application-controller" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "argocd"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "dev"
│ 
│   with module.dev.module.argocd.helm_release.argocd,
│   on dev/argocd/main.tf line 5, in resource "helm_release" "argocd":
│    5: resource "helm_release" "argocd" {
│ 

### Expected behavior

CRDs would be upgraded and bug would go away.

**Comment by yu-croco** [comment]
Hi @CameronMukherjee ,

>When attempting to run:
kubectl apply -k "https://github.com/argoproj/argo-cd/manifests/crds?ref=argo-cd-7.3.6"
>
>You are met with:
>
>error: failed to run '/usr/local/bin/git fetch --depth=1 https://github.com/argoproj/argo-cd argo-cd-7.3.6': fatal: couldn't find remote ref argo-cd-7.3.6
: exit status 128

As you can see it's upstream's url, not argo-helm's one, which means version should be same as one of [upstream's versions](https://github.com/argoproj/argo-cd/releases).

**Comment by CameronMukherjee** [comment]
Ah thank you very much @yu-croco. Apologises for not realising this earlier.
