### ISSUE TITLE
Add way to make tls secrets volumes non-optional

### ISSUE THREAD

**Issue by rgl** [argoproj/argo-helm#2840]
### Is your feature request related to a problem?

While trying to bootstrap a talos linux cluster by placing argocd in a talos cluster inlineManifest and at the same time create the argocd certificates with cert-manager, due to races at bootstrap times, argocd ends up starting before the certificate secret is actually created, so I end up with a broken argocd, one which has bogus certificates.

### Related helm chart

argo-cd

### Describe the solution you'd like

Some kind of chart variable to make all the tls related volumes as non-optional.

For example, a way to modify the `optional: true` at:

https://github.com/argoproj/argo-helm/blob/argo-cd-7.3.9/charts/argo-cd/templates/argocd-server/deployment.yaml#L493-L512

From what I understood, that would prevent argo from being started until the, e.g., argocd-server-tls, secret exists.

**Comment by yu-croco** [comment]
Hi @rgl , thank you for opening an issue.
argo-helm follows [upstreams' manifest](https://github.com/argoproj/argo-cd/tree/master/manifests). The values you mention are optional in [upstream](https://github.com/argoproj/argo-cd/blob/master/manifests/base/server/argocd-server-deployment.yaml#L109-L114), so changing default config is not reasonable.

On the other hand, I think it makes sense to add attributes in values.yaml to override the `optional` flag. 🤔

**Comment by pdrastil** [comment]
Hi @rgl - for race conditions or pod restarts on change in secret / configmaps I can also recommend [Reloader](https://github.com/stakater/Reloader) project that solves this and is applicable for other things inside of the cluster.

**Comment by rgl** [comment]
I'm also using reloader. But in this case, since reloader is also in the race. It did not work. Changing the optional to false did work thou.
