### ISSUE TITLE
argo-events crd install redundancy

### ISSUE THREAD

**Issue by shaunofneuron** [argoproj/argo-helm#285]
**Describe the bug**
Might be my inexperience with helm but during the chart install helm states that the eventsources CRD is already installed. I am doing this on a clean install and noticed that there are definitions in `crds/` (which will be picked up automatically by Helm) _and_ definitions in `templates/` that will conditionally be installed with the `installCRD` flag. Instead of submitting a pr that removes either of these (which I can totally do) I wanted to bubble this up as setting `installCRDS` to false allows me to work around this. Please also correct me if I am doing something wrong!

**To Reproduce**
1. Install argo-events chart 0.7.2

**Expected behavior**
Install of chart without collision between crd definitions.

**Additional context**
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: eventsources.argoproj.io

**Comment by papanito** [comment]
Steps to reproduce:

1.  Install chart
    ```
    helm install argo-events remote/argo-events -n argo-events -f argo-events/values.dev.yaml
    Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: eventsources.argoproj.io
    ```
1. Check `CustomResourceDefinition  `
    ```bash
    $ kubectl get CustomResourceDefinition | grep argo
    applications.argoproj.io                          2019-03-29T18:57:32Z
    appprojects.argoproj.io                           2019-03-29T18:57:32Z
    eventsources.argoproj.io                          2020-06-08T05:37:56Z
    gateways.argoproj.io                              2020-06-08T04:47:13Z
    sensors.argoproj.io                               2020-06-08T04:47:13Z
    workflows.argoproj.io                             2019-04-09T09:34:02Z
    ```
1.  Delete `eventsources.argoproj.io`
    ```bash
    kubectl delete CustomResourceDefinition  eventsources.argoproj.io
    customresourcedefinition.apiextensions.k8s.io "eventsources.argoproj.io" deleted
    ```
1.  Install chart again, ends with the same error
    ```
    helm install argo-events remote/argo-events -n argo-events -f argo-events/values.dev.yaml
    Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: eventsources.argoproj.io
    ```

**Comment by norbjd** [comment]
Just faced the same issue, but, as documented :

https://github.com/argoproj/argo-helm/tree/02f9725f770d02e0900a0cf7a2ace1136d5340c3/charts/argo-events#notes-on-crd-installation

> Some users would prefer to install the CRDs outside of the chart. You can disable the CRD installation of this chart by using --set installCRD=false when installing the chart.

Running :

```
helm install argo-events argo/argo-events --set installCRD=false
```

succeeds for me.
