### ISSUE TITLE
Failed to compare desired state to live state

### ISSUE THREAD

**Issue by atalakey4work** [argoproj/argo-helm#2866]
### Describe the bug

Application Sync stuck with status unknown and ComparisonError.

### Related helm chart

argo-cd

### Helm chart version

7.4.0

### To Reproduce

Upgrade ArgoCD to version 7.4.0 on Kubernetes version 1.24

### Expected behavior

Application Sync with no issues

### Additional context

Error message:

Failed to compare desired state to live state: failed to perform pre-diff normalization: error building typed results: error creating typedLive: .status: field not declared in schema

Note that it is working fine after rolling back to version 7.3.11

**Comment by yu-croco** [comment]
Hi @atalakey4work , since it's about Argo CD itself, you can open issue in [upstream](https://github.com/argoproj/argo-cd).

**Comment by pdrastil** [comment]
Hi I would say it's 1.24 K8s version. Minimum supported / tested version is 1.25 based on [upstream docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/tested-kubernetes-versions/). The version contain is also enforced since 7.4.0 of helm chart.
