### ISSUE TITLE
Support reloading argo workflows Deployments when ConfigMap changes

### ISSUE THREAD

**Issue by bdun1013** [argoproj/argo-helm#2890]
### Is your feature request related to a problem?

I have noticed that changes to the argo workflows controller ConfigMap, which is consumed by both the server and controller Deployments, is not picked up.

### Related helm chart

argo-workflows

### Describe the solution you'd like

Add a checksum to the argo workflows controller and server Deployment's pod spec to restart the Deployments when the ConfigMap changes: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

**Comment by agilgur5** [comment]
Duplicate of #2622
