### ISSUE TITLE
Helm chart for 1.15

### ISSUE THREAD

**Issue by musabmasood** [argoproj/argo-helm#292]
Any ideas when this will be available?

**Comment by virtrixke** [comment]
Also the current helm chart is a v1. You guys will bump it up to v2 (helm3)?

**Comment by seanson** [comment]
As there is a significant userbase still using Helm v2 I believe we will keep the Helm API version at v1 for at least until ArgoCD itself no longer supports Helm.
@musabmasood - Is there a particular 1.15 deprecation you're talking about? The only one I'm aware of is the coming 1.16 Deployment version deprecation?

**Comment by musabmasood** [comment]
@seanson no, I was just wondering when the helm chart for Argo's own installation would be available for ArgoCD v1.15. At the time I created this requested, the ArgoCD helm chart was pointing to an older version of the app. This has now been resolved 11 days ago, so I will close the issue.

https://github.com/argoproj/argo-helm/blob/0eb0730abb54f9cc45e94256855fb7e845fb7df3/charts/argo-cd/values.yaml#L13

https://github.com/argoproj/argo-helm/blob/0eb0730abb54f9cc45e94256855fb7e845fb7df3/charts/argo-cd/Chart.yaml#L2
