### ISSUE TITLE
FR: Add JSON Schema validation for charts

### ISSUE THREAD

**Issue by thiagowfx** [argoproj/argo-helm#2927]
### Related helm chart

argo-cd, argo-events, argo-rollouts, argo-workflows, argocd-image-updater, argocd-apps

### Describe the solution you'd like

Introduce a values.schema.json file for all helm charts

Docs: https://helm.sh/docs/topics/charts/#schema-files

### Describe alternatives you've considered

Defining the schemas downstream

**Comment by SoldierFace** [comment]
download
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by mkilchhofer** [comment]
Xref:
- https://github.com/argoproj/argo-helm/issues/2157

**Comment by agilgur5** [comment]
Closing as duplicate of #2157
