### ISSUE TITLE
Can't deploy Helm Chart using ".Capabilities.APIVersions.Has" function

### ISSUE THREAD

**Issue by leandrok** [argoproj/argo-helm#2948]
### Describe the bug

Hello, I'm trying to deploy the [Helm Chart for Zabbix](https://github.com/zabbix-community/helm-zabbix) but ArgoCD shows the following "Sync Error":
 
`The Kubernetes API could not find version "v1beta1" of batch/CronJob for requested resource zabbix/infra-zabbix-nodesclean. Version "v1" of batch/CronJob is installed on the destination cluster.`

The template referenced above is [located here](https://github.com/zabbix-community/helm-zabbix/blob/master/charts/zabbix/templates/job-init-db-schema.yaml) and contains this code:

```
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
```

I have an EKS cluster running version 1.29. Therefore, the API version for cronjobs is "batch/v1". But for some reason is trying to deploy the v1beta1 version.

As a workaround, I tried to provide to ArgoCD the right k8s version and API version used in my cluster, by configuring the following settings in the ArgoCD Helm Chart:

```
kubeVersionOverride: "1.29.3"

apiVersionOverrides:
  cronJob: "cronjob/v1"
```

However that didn't work. By the way, I'm not sure if I'm configuring these settings correctly. Where can I find some documentation (at least a recent example) of how to use them?

Is there any way to solve this?

Thank you very much in advance!

### Related helm chart

argo-cd

### Helm chart version

7.6.5

### To Reproduce

1. Try to deploy the Zabbix helm chart https://github.com/zabbix-community/helm-zabbix
2. Try to synchronize the application. ArgoCD will show "Sync Failed"
3. The reason/message is shown in the "Describe the bug" section

### Expected behavior

1. I'm expecting that the Zabbix Helm Chart is deployed (correctly detects that the version of my EKS cluster uses the cronjob/v1 API version, not the cronjob/v1beta1 version)

**Comment by yu-croco** [comment]
Hi @leandrok , I think you are using wrong way. I am not sure how you manage the Zabbix  chart but if you set `.Values.apiVersionOverrides.xxxx` , it will be passed to argo-cd Helm Chart, not Zabbix.
It is for internal resources, not for out side of Helm Chart. So I think your use case doesn't suite for the value.

**Comment by leandrok** [comment]
Got it thanks!
