### ISSUE TITLE
Bump image-updater

### ISSUE THREAD

**Issue by black-snow** [argoproj/argo-helm#2956]
### Is your feature request related to a problem?

I've just felt a bit stupid to see I'm running 0.11.0 of argocd-image-updater and there's a 0.14.0 already plus 0.11.0 is from Oct 27, 2021! It's almost 3 years old now.

So I went on artifacthub and noticed ... 0.11.0 is the latest version there ...

Is there a specific reason it's still sitting at 0.11.0?

### Related helm chart

argocd-image-updater

### Describe the solution you'd like

Bump to 0.14.0 + find 0.11.x, 0.12.* and 0.13.* on artifacthub.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by yu-croco** [comment]
Hi @black-snow 
I wonder you might misunderstand the meaning of version. The Helm Chart version is `0.11.0` but the appVersion is `0.14.0`, which is [the latest version](https://github.com/argoproj-labs/argocd-image-updater/releases).
Ref: https://github.com/argoproj/argo-helm/blob/main/charts/argocd-image-updater/Chart.yaml#L5-L6

**Comment by black-snow** [comment]
Haha, you're right - I'm stupid. Thanks!
