### ISSUE TITLE
dragonfly

### ISSUE THREAD

**Issue by Nello-Angelo** [argoproj/argo-helm#2967]
### Related helm chart

argo-cd

### Describe the solution you'd like

ability to choose between redis and dragonfly

### Describe alternatives you've considered

dragonfly

**Comment by Nello-Angelo** [comment]
https://github.com/dragonflydb/dragonfly

**Comment by mkilchhofer** [comment]
Hi @Nello-Angelo,
This project here only provides a helm chart for the upstream Kustomize manifests of Argo CD. Can you open a feature request in the upstream GitHub? https://github.com/argoproj/argo-cd/issues/new/choose
