### ISSUE TITLE
Add liveness probe to application-controller deployment and statefulset templates

### ISSUE THREAD

**Issue by ReeseGarth** [argoproj/argo-helm#2973]
### Is your feature request related to a problem?

Likely a niche case, but we wanted to deploy a "test" argo-cd instance using our main argo-cd instance to test SSO in our staging environment. Because it is missing liveness probe config from the deployment/statefulset and we have gatekeeper requiring it the deployment fails. We could work around using kustomize or creating a gatekeeper exception, but feel that it would be a nice to have regardless.

I am happy to write a PR to address this. I wanted to create this issue first though in the case excluding liveness was a conscious decision.

### Related helm chart

argo-cd

### Describe the solution you'd like

liveness probe can be configured for the application-controller deployment and statefulset.

### Describe alternatives you've considered

- patch the template using kustomize
- make gatekeeper exception

**Comment by yu-croco** [comment]
Hi @ReeseGarth , regarding the reason why application-controller doesn't have livenessProbe, [this comment](https://github.com/argoproj/argo-helm/pull/2978#pullrequestreview-2365969120) helps you to know the situation. Though I made a PR for this issue, I ended up that it's not worth to add at argo-helm without fixing the issue at upstream, so I closed it. 🫠 

So if you have motivation to improve this, can you please open an issue at upstream as well?

**Comment by ReeseGarth** [comment]
@yu-croco ah, thanks for the context. I'll close.
