### ISSUE TITLE
Add SSO in the helm chart

### ISSUE THREAD

**Issue by user-name-is-taken** [argoproj/argo-helm#298]
**Describe the solution you'd like**

I should be able to [configure SSO](https://argoproj.github.io/argo-cd/operator-manual/user-management/#existing-oidc-provider) from the helm chart. The helm chart already includes the [configmap](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-configs/argocd-cm.yaml) used for SSO configuration, so adding SSO should be straight forward.

**Describe alternatives you've considered**

I'm configuring SSO by manually overwriting the configmap after installing the helm chart. This is not good because it will get overwritten on helm upgrade etc.

**Comment by tylerauerbeck** [comment]
I've started working on this a bit (specifically for OpenShift Authentication), but think this could probably apply a bit more broadly (and then have OpenShift outlier pieces). The way that I was going about this was relying a bit heavily on new 3.1.X functionality (specifically the `lookup` function), but I was thinking along the lines of "if certain SSO values aren't provided, go ahead and go look them up, but if they are provided... use them", which would allow for compatability across the board.

I'm open to feedback here as I don't want to go too far down the wrong path if others disagree, but would be happy to add what I have here.

**Comment by seanson** [comment]
This is currently configurable via the Helm chart by providing values to `server.config` in https://github.com/argoproj/argo-helm/blob/c2d9c8125863a5290d1715e14c2fbff7fd3886d2/charts/argo-cd/values.yaml#L458

Is there something missing from this functionality?
