### ISSUE TITLE
No Chart containing ArgoCD v2.12.7

### ISSUE THREAD

**Issue by YaronL16** [argoproj/argo-helm#3066]
### Is your feature request related to a problem?

I want to install the latest ArgoCD v2.12.x release, which which would be v2.12.7, however the latest version I could find in a chart is v2.12.6, which is Included with the argocd-7.6.12 chart.
And in later charts, the app version jumps to v2.13.x.
I think this is a problem for people who want to have the most recent and updated patch.

### Related helm chart

argo-cd

### Describe the solution you'd like

I don't know much about the release process- I see the version bump is generally done by a bot, but in this case it did not happen.
I would love to manually push a PR of a 7.6.13 chart containing app version v2.12.6, please let me know if that would be okay or not

thanks

**Comment by yu-croco** [comment]
It's explained in https://github.com/argoproj/argo-helm/pull/3068#issuecomment-2515854143
