### ISSUE TITLE
Redis-HA OpenShift SecurityContext

### ISSUE THREAD

**Issue by mathianasj** [argoproj/argo-helm#324]
**Describe the bug**
I am trying to deploy redis-ha to openshift and it currently requires the security context to be set.  I would rather this be removed or optional so it can run out of the box on openshift.

**To Reproduce**
1. Deploy chart with redis-ha on OpenShift
1. StatefulSet fails to launch with `1000 is not an allowed group spec.initContainers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000570000, 1000579999] `

**Expected behavior**
The application should deploy without the need for custom SecurityContexts

**Comments**
We should be able to modify the redis-ha chart to follow the same deployment model as in the standard redis as part of the chart.

**Comment by johnkost** [comment]
Migrating from v2.2.16 to v.2.6.0, we are experiencing this issue

**Comment by johnkost** [comment]
Looking into this, this is the commit that causes issues on OCP: https://github.com/argoproj/argo-helm/commit/9b80bd95e4d599b93a4af91fb3e1d1aa49d26270 as it sets the user to run as
