### ISSUE TITLE
Workflow-controller namespaced

### ISSUE THREAD

**Issue by alk-rniveau** [argoproj/argo-helm#328]
Hi team,

If I well understand the argo documentation https://github.com/argoproj/argo/blob/master/docs/managed-namespace.md
We need to run `--namespaced` on argo-server AND workflow-controller to namespaced workflows.

It's possible to add this argument with server.extraArgs but it seems impossible for the workflow-controller.

In my test, I can run workflow in every workspaces (unexpected) and I can't see them in the UI (expected).

BTW, it seems `controller.workflowNamespaces` is useless due to this "bug".

Are you ok with my description or did I miss something ?

**Describe the solution you'd like**
The capability to namespaced workflow-controller with extraArgs as for the server

**Comment by stefansedich** [comment]
Hello @alk-rniveau this one should be getting tackled over https://github.com/argoproj/argo-helm/pull/263 and once that goes in namespaced support should be good to go!
