### ISSUE TITLE
A Helm Chart that combines argo workflow as well as prometheus setup

### ISSUE THREAD

**Issue by arshadansari27** [argoproj/argo-helm#351]
Argo setup for newbies would be a lot easier if argo can be setup with prometheus. 

A single command installation via helm to setup argo as well as prometheus based monitoring

Have tried diong installing the argo and prometheus wit separate charts and it is very daunting to have them work well with each other, especially with different namespace.

**Comment by seanson** [comment]
Prometheus is a different project and application and so should not be combined.
