### ISSUE TITLE
[argo] Allow Server RBAC creation to be skipped

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo-helm#366]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the Hybrid authentication mode to allow a read only UI for logged out users with the ability to log in to perform actions that actually modify workflows (create, update, delete).

**Describe the solution you'd like**

Something like

```yaml
server:
  rbac:
    create: false
```

Which would allow me to provide my own ClusterRole/ClusterRoleBinding separately with the exact privileges that I want.

**Comment by stefansedich** [comment]
@dcherman what version of Helm are you using?

**Comment by dcherman** [comment]
dherman$ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

**Comment by stefansedich** [comment]
> dherman$ helm version
> version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Ah I need to wake up properly, I read that as `CRD` which is why I asked helm version :smile:, sounds like what you are saying would be a welcome change to enable disabling the OOTB RBAC items.

**Comment by dcherman** [comment]
Exactly

**Comment by jacek-jablonski** [comment]
@dcherman would you mind sharing read-only role for argo server?
