### ISSUE TITLE
PodSecurityPolicy support for argo workflow CRD deploy

### ISSUE THREAD

**Issue by ibexmonj** [argoproj/argo-helm#401]
**Is your feature request related to a problem? Please describe.**

Firstly, thank you for supporting and maintaining these argo helm charts. These are super helpful to me as i begin my argo workflow testing. 

As for the issue, I tried to search for open and closed issues related to this but was unable to find any info. Do we have any guidance on supporting `PodSecurityPolicy` for these helm charts ?

**Describe the solution you'd like**

List out a `PodSecurityPolicy` and tie it to a `ClusterRole` to ensure the `argo-server` and `argo-workflow-controller` serviceaccounts can use the PSP.

**Describe alternatives you've considered**

I am working on testing this install on a cluster that has PSP enabled. Will report on findings in this issue. Just wanted to get some community feedback here.

**Comment by andyfeller** [comment]
If you’re using Helm 3.1+ and didn’t want to bake this into the Helm charts, you could leverage [post renderers](https://helm.sh/docs/topics/advanced/) to mutate the Helm charts before installed.

**Comment by FrediWeber** [comment]
We use pretty restrictive PSPs in our cluster and ArgoCD performs pretty well. The only problem was, that the standard redis image runs as root. I'm changing this now.

**Comment by ibexmonj** [comment]
@FrediWeber the `workflow-controller` and `argo-server` seem to require `runasroot` permissions as well. What redis image are you referring to ? The CRD and controller install for Argo workflows don't have a redis image, do they ?

**Comment by FrediWeber** [comment]
Sorry I thought you refered to ArgoCD. Wrong Project.

Ibexmonj <notifications@github.com> schrieb am Di. 14. Juli 2020 um 17:32:

**Comment by ibexmonj** [comment]
No worries. I saw your PR for argo-cd and figured that out :) Not too familiar with argo-cd `yet` :)
