### ISSUE TITLE
Use a non-root redis image

### ISSUE THREAD

**Issue by FrediWeber** [argoproj/argo-helm#404]
**Is your feature request related to a problem? Please describe.**
The current redis image runs the container as root user.

**Describe the solution you'd like**
We should use a image that doesn't run as root.

**Describe alternatives you've considered**
Allow the container to run as root via a PSP.

**Additional context**
The "main" issue is: https://github.com/argoproj/argo-cd/issues/3933

**Comment by ErikLundJensen** [comment]
This change breaks deployment at OpenShift where a specific user should not be used. As in the remaining of the Argo CD chart the securityContext must be empty set {} and it is the responsibility of the users for the chart to setup the securityContext as it is platform/environment specific.

**Comment by spencergilbert** [comment]
> This change breaks deployment at OpenShift where a specific user should not be used. As in the remaining of the Argo CD chart the securityContext must be empty set {} and it is the responsibility of the users for the chart to setup the securityContext as it is platform/environment specific.

Can you open a new issue for this?

**Comment by ErikLundJensen** [comment]
Opened new issue #441 as this fix does not work at OpenShift.
