### ISSUE TITLE
argocd-notifications: Failing to install chart on Helm2

### ISSUE THREAD

**Issue by kagkarlsson** [argoproj/argo-helm#425]
**Describe the bug**
Since the chart uses `apiVersion: v2` I am unable to install it in my cluster where I currently have not upgraded to helm3. Is this by accident or intended? Is it possible to make it compatible with helm2 also?

**Error**
```
apiVersion 'v2' is not valid. The value must be "v1"
```

**Comment by kagkarlsson** [comment]
cc @andyfeller

**Comment by andyfeller** [comment]
Hey @kagkarlsson, the use of `v2` was intentional when I originally created and contributed the chart given the [helm v2 deprecation](https://helm.sh/blog/helm-v2-deprecation-timeline/) set by the community:

> We recognize that rolling out a major version change in production requires time. The Helm maintainers committed to providing bugfixes for Helm v2 until May 2020 (which they extended to August 2020) and security patches for Helm v2 until November 2020. And now the bugfix window is closing; Helm v2.16.10 will be the final bugfix release and 2.17.0 will follow with the download location updated.
>  
> What does this mean for Helm users?
> 
> After August 13, 2020, you will see these changes:
> 
> If you’re still using Helm v2, you will want to migrate to Helm v3 now. Helm 3.2.4 is widely used and production-ready. While largely backwards-compatible, there are specific changes you’ll want to be aware of when carrying out your migration.
> Starting now, ongoing support of Helm v2 is limited to the next three months of security patches. That means we will no longer be accepting pull requests for anything but verified security issues.
> The stable and incubator repos will be de-listed from the Helm Hub, introduced in December 2018. Find your preferred repositories on Helm Hub to add them to your configs, and track the migration of charts to their new decentralized locations.
> After November 13, 2020, you will see these changes:
> 
> No further Helm v2 releases (even for security patches)
> No further updates to Helm v2 documentation, which will remain available for the present time but may be discontinued
> Existing and new issues/PRs that are v2-specific will be closed
> Transitioning Helm release and chart hosting ownership to CNCF

I'm open to ideas of how to facilitate those still working to migrate from Helm v2 to v3 but I'm unaware of a happy compromise that straddles both; hence erring on the side of moving things forward.

Thoughts?

**Comment by andyfeller** [comment]
In all seriousness, I am sorry this is a problem :(

**Comment by kagkarlsson** [comment]
Ok, I was not aware of the details regarding EOL of Helm2. I see your point 👍. 
Not a very fluent helm-user so I unfortunately do not have any suggestions either, sorry. 
Let's leave it the way it is. I will create the resources myself and migrate to the chart when we have updated to helm3
