### ISSUE TITLE
argo-cd: Update CRD's to latest in source

### ISSUE THREAD

**Issue by jdfalk** [argoproj/argo-helm#429]
**Describe the bug**
The argocd team changed the CRD's but did not change the version, the current version in the helm repo is outdated and should be updated.

**To Reproduce**
1. Deploy argocd via helm chart

**Expected behavior**
CRD version should match the CRD version upstream

**Additional context**
It is understood that the current argocd crd's have fields that are only relevant to v1.7.0-rc1 and the current chart uses v1.6.x, but if a user wishes to manually specify the new container in order to resolve the myriad of issues in 1.6.x their CRD's will be overwritten. One easy way to address this issue in the future is to version CRD's.

**Comment by jdfalk** [comment]
I've created a PR to resolve this: https://github.com/argoproj/argo-helm/pull/430

**Comment by cabrinha** [comment]
It'd be great if there were a way to automate this.

**Comment by RichiCoder1** [comment]
@cabrinha It'd be a bit of work, but could make do a cron GitHub Workflow that checks upstreams, diffs against crds, and then submits a PR if they're outta sync. Lot of manual work though.
