### ISSUE TITLE
2.6.2 templating issue

### ISSUE THREAD

**Issue by sadoMasupilami** [argoproj/argo-helm#434]
**Describe the bug**
allow custom paths for ingress leads to teplating issues with my values which are not changed from 2.6.1

**To Reproduce**
update from 2.6.1 useing values like this:
server:
  extraArgs:
    - --insecure
  ingressGrpc:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
    hosts:
      - argocd.example.com
    tls:
      - secretName: argocd-secret
        hosts:
          - argocd.example.com

this leads to the followig template error:

Wait helm template failed. Error: render error in "argo-cd/templates/argocd-server/ingress-grpc.yaml": template: argo-cd/templates/argocd-server/ingress-grpc.yaml:36:20: executing "argo-cd/templates/argocd-server/ingress-grpc.yaml" at <.Values.server.ingressGrpc.extraPaths>: can't evaluate field Values in type interface {} : exit status 1

**Expected behavior**
update works

**Comment by sadoMasupilami** [comment]
i guess a if around the extraPaths woul catch that?

**Comment by ekarademir** [comment]
I think we are hitting the same bug that #435 is fixing

**Comment by sadoMasupilami** [comment]
Thank you for your effort! Sadly I had no time to fix it.
