### ISSUE TITLE
Use a non-root redis image without setting securityContext as default

### ISSUE THREAD

**Issue by ErikLundJensen** [argoproj/argo-helm#441]
**Describe the bug**
Issue #404 introduced an error when deploying at OpenShift.
OpenShift does not expect runAsUser and runAsGroup to be set to fixed values as OpenShift assigns "random" userId by default.

The securityContext should therefore not be specified by the values.yaml in the chart. See also the other components in Argo CD where runAsUser neither is set.

**To Reproduce**
1. Deploy Argo CD Helm Chart to OpenShift

**Expected behavior**
Deploy to OpenShift without having to override the redis.securityContext with an empty set.

**Additional context**
Error from OpenShift
Error creating: pods "argo-argocd-redis-67f6fs7f8-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000820000, 1000829999]]

**Comment by seanson** [comment]
If Redis is the only component with this issue then any issue regarding default values would belong to the upstream https://github.com/helm/charts/tree/master/stable/redis-ha.
