### ISSUE TITLE
Argo-CD v0.12.0 needs Redis?

### ISSUE THREAD

**Issue by davidholsgrove** [argoproj/argo-helm#45]
I've been using the [Helm Chart](https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd) for v0.11.2 version of Argo-CD, and attempted to update all image tags to v0.12.0 but getting an error on the application controller;
```
2019/03/25 04:22:44 cache: Get key="app|managed-resources|<appname>|0.12.0" failed: dial tcp: lookup argocd-redis on 172.20.0.10:53: no such host
```
Do we have a new requirement which should be added to a `requirements.yaml`?

**Comment by alexmt** [comment]
You are right. Redis was introduced in v0.12. Chart has to be updated.
