### ISSUE TITLE
[argo-cd] missing gpg configmap

### ISSUE THREAD

**Issue by travisghansen** [argoproj/argo-helm#457]
**Describe the bug**
I get errors about a missing configmap when I navigate to configuration->gnupg keys

`Unable to load data: configmap "argocd-gpg-keys-cm" not found`

Should this be included/managed by the chart?

Thanks!

**Comment by travisghansen** [comment]
Configuration->projects gives the same error/message

**Comment by mssanjay** [comment]
I too see the same error. I am using 1.7.6

**Comment by exu** [comment]
I have the same error
In our deployment Argo stopped working at all after upgrade to `1.7.6` 
It wants now to delete all manifests - looks like Argo cant get manifests from git repo.

**Comment by mssanjay** [comment]
I was able to fix this by creating configmap "argocd-gpg-keys-cm"
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-gpg-keys-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-gpg-keys-cm

**Comment by travisghansen** [comment]
Sure we can fix it. It’s more a question of being managed by the chart like ssh keys etc.

**Comment by abdennour** [comment]
same issue even after upgrading to the latest version

**Comment by travisghansen** [comment]
Is there something that's preventing this from being implemented/fixed?

**Comment by jeff51419** [comment]
if you use helm instal argo-cd, there is no argocd-gpg-keys-cm configMap.
![image](https://user-images.githubusercontent.com/18411883/115647020-bb9b5900-a355-11eb-9976-77d7dcf36089.png)

if you use the install.sh, there is a argocd-gpg-keys-cm file.
![image](https://user-images.githubusercontent.com/18411883/115647147-e5ed1680-a355-11eb-9178-0e75c78cc66a.png)
