### ISSUE TITLE
Getting 504 for api/v1/workflow-events/?listOptions... URL

### ISSUE THREAD

**Issue by mseiwald** [argoproj/argo-helm#462]
## Summary 

Getting this error message on the Argo UI a few seconds after loading the page:

<img width="1552" alt="Screenshot 2020-09-30 at 09 08 46" src="https://user-images.githubusercontent.com/619827/94654000-b8c71100-02fc-11eb-921e-90251ed31281.png">

Looking at the developer console I can see a 504 error for a `api/v1/workflow-events/?listOptions...` URL:

<img width="1792" alt="Screenshot 2020-09-30 at 09 06 55" src="https://user-images.githubusercontent.com/619827/94653935-a220ba00-02fc-11eb-9f3c-c21954cde7e2.png">

## Diagnostics

What version of Argo Workflows are you running?

v2.11.0

This happens on an empty install of Argo (using helm chart version 0.12.1) and the logs of the argo-server don't show anything interesting during the error. It's as if the argo-server completely ignores this request and then nginx-ingress runs into a timeout.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by meurig** [comment]
I'm seeing similar issues (not sure if they're related) upon upgrading to v2.11:
https://github.com/argoproj/argo/issues/4231

I've created a new issue since I feel it's suitable different, but I'm not sure if they'll prove to have the same underlying cause.

**Comment by willgleich** [comment]
This is probably rooted in the missing eventbindings CRD, so those API endpoints don't exist. Should've been fixed in the helm 0.13.0 refresh for v2.11.3 but I'm still seeing it. Ill PR something in.

**Comment by mseiwald** [comment]
@willgleich Thanks, this seems to solve the issue for us. Just to understand the root cause, does this mean that helm won't discover newly added CRDs in the `crds` folder? Or why would a regular helm upgrade not fixe the issue automatically?

**Comment by mseiwald** [comment]
I'm actually getting a different error now every few minutes. Should I open a new issue?

<img width="1792" alt="Screenshot 2020-10-13 at 11 05 14" src="https://user-images.githubusercontent.com/619827/95840228-300c9400-0d44-11eb-9757-48f21fcb9e13.png">
