### ISSUE TITLE
CRD "workflows.argoproj.io" incorrectly rendered?

### ISSUE THREAD

**Issue by muwon** [argoproj/argo-helm#483]
**Describe the bug**
When CRD "workflows.argoproj.io" is created, the "spec.additionalPrinterColumns" became part of "spec.versions"

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2020-10-29T21:31:03Z"
  generation: 1
  name: workflows.argoproj.io
  resourceVersion: "610788391"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/workflows.argoproj.io
  uid: 110646a6-297e-42d6-a7e0-42cb13e4a1b1
spec:
  conversion:
    strategy: None
  group: argoproj.io
  names:
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    shortNames:
    - wf
    singular: workflow
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status of the workflow
      jsonPath: .status.phase
      name: Status
      type: string
    - description: When the workflow was started
      format: date-time
      jsonPath: .status.startedAt
      name: Age
      type: date
    name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    shortNames:
    - wf
    singular: workflow
  conditions:
  - lastTransitionTime: "2020-10-29T21:31:03Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-10-29T21:31:03Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
```

See the correct definition of CRD "workflows.argoproj.io" https://github.com/argoproj/argo-helm/blob/master/charts/argo/templates/workflow-crd.yaml#L10 and https://github.com/argoproj/argo-helm/blob/master/charts/argo/crds/workflow-crd.yaml#L9

**To Reproduce**
1.  'git clone git@github.com:argoproj/argo-helm.git'
2. Run 'helm install --debug --namespace argo --name argo ./argo --set controller.containerRuntimeExecutor=k8sapi'
3. Run 'kubectl get crd/workflows.argoproj.io -o yaml'
4. Look for "additionalPrinterColumns"

**Expected behavior**
"additionalPrinterColumns" should be a spec of the CRD, not a version.

**Screenshots**

**Additional context**

**Comment by lamroger** [comment]
FWIW, it seems like `apiVersion: apiextensions.k8s.io/v1` forces a different schema than `apiVersion: apiextensions.k8s.io/v1beta1`. I'm assuming workflows CRD existed in 1.15 and you upgraded to 1.16 which deprecates `v1beta1` but converted it to `v1`. (bc that's what happened to us)
