### ISSUE TITLE
Argo Rollouts Pod Annotations on wrong place

### ISSUE THREAD

**Issue by ghost** [argoproj/argo-helm#487]
**Describe the bug**
**.Values.podAnnotations** is being applied on the Deployment metadata instead of the Deployment spec template metadata annotations

**To Reproduce**
1. define some podAnnotations on a values file
2. run helm template (referencing the values file)
2. see that the podAnnotations are defined on the deployment metadata annotations instead of the deployment spec template metadata

**Expected behavior**
podAnnotations should be on the deployment spec.template.metadata.annotations

**Comment by amit-handda** [comment]
+1. we want to add the prometheus annotations to the rollout pod, but unable to do it. thanks
