### ISSUE TITLE
helm upgrade does not increment "App Version" 

### ISSUE THREAD

**Issue by emcay** [argoproj/argo-helm#489]
**Describe the bug**
When modifying the image.tag in values.yaml such as from v1.7.6, to v1.7.8, and then performing a helm upgrade, the "App Version" value returned with "helm list" does not reflect the correct version(incorrectly shows v1.7.6), while a "kubectl describe pod" shows argo pods running the correct version (v1.7.8)

**To Reproduce**
1. Modify any/all image.tag parameters to increment the version (such as from v1.7.6 to v1.7.8)
2. Perform a "Helm upgrade"
3. View incorrect "App Version" value with "helm list"
4. View correct image version with "kubectl describe image"

**Expected behavior**
That the "App Version" value would be incremented when the version of the image deployed changes.

**Comment by KrustyHack** [comment]
Ay,

I don't think it's a bug. It's how Helm works. To update "app version" you need to update it in Chart.yaml file. It's not related to image used in your values or templates. The chart maintainer should change it manually when upgrading its chart.

**Comment by clementlecorre** [comment]
I fix here : https://github.com/argoproj/argo-helm/pull/494

**Comment by KrustyHack** [comment]
Ay,

I don't know how maintainers want to handle `appVersion` field. We need to ask them I think.
