### ISSUE TITLE
argo-cd: cannot log into gRPC host

### ISSUE THREAD

**Issue by Nuru** [argoproj/argo-helm#491]
**Describe the bug**
Attempting to log in via the CLI fails with and HTTP/2.0 status 404 error

**To Reproduce**
1. Deploy argo-cd using [helm file](https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd) version 2.9.5, setting both `ingress` and `ingressGrpc` `enabled: true`
1. Verify installation by going to website URL and logging in with `admin` and password
1. Attempt to login with `argocd` CLI v1.7.8: `argocd login grpc.argocd.example.com --insecure`

After entering username and password, get
```
FATA[0012] rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain; charset=utf-8" 
```

**Expected behavior**
Expected to be able to log into server

**Additional context**
Nginx reports connection attempt:
```
"POST /session.SessionService/Create HTTP/2.0" 404 19
```

**Comment by zmingxie** [comment]
I just ran into this error, then I realized I didn't update my `ingress-nginx-controller` flag as mentioned here:
 
>`nginx.ingress.kubernetes.io/ssl-passthrough` annotation requires that the `--enable-ssl-passthrough` flag be added to the command line arguments to ingress-nginx-controller

Hope this will fix your issue too
