### ISSUE TITLE
Workflows CRD should be installed as a `post-install` rather than `pre-install` step

### ISSUE THREAD

**Issue by wookasz** [argoproj/argo-helm#5]
This is probably a niece use-case that most won't run into, but before the changes to install CRD along with the rest of that chart were merged, we were installing/upgrading using our own chart, with the CRD one of the resources installed.

When switching over to the new official 0.1.1 chart, ~helm ran the `pre-install` hook, "creating" the already existing CRD, then proceeded to delete as part of the cleanup.~ the `pre-install` hook did not run because it was an upgrade.

Running this as a `post-upgrade` hook would seemingly have solved the problem. The CRD should be applied as part of a `post-install` and `post-upgrade` hook so that it is correctly updated should anything change.

**Comment by jessesuen** [comment]
We now use the helm crd-install hook
