### ISSUE TITLE
existing application shows 'groupVersion shouldn't be empty' after upgrading to latest argocd

### ISSUE THREAD

**Issue by tonythomasm** [argoproj/argo-helm#507]
I had argocd deployed with v1.5.4. I installed latest argocd (v1.7.6) using helm. In this, the application chart which was working in v1.5.4 seems not working with v1.7.6. It shows a comparison error  - 'groupVersion shouldn't be empty'. Please help to figure out what is the reason for this issue.

**Comment by iorlov1** [comment]
Have the same issue. 
Please advise

**Comment by salla2** [comment]
Hi any workaround available for this issue?

**Comment by holinnn** [comment]
In my case someone forgot the `apiVersion` in one of the resources deployed in their application. 
Setting the `apiVersion` for that resource fixed the issue, and ArgoCD was able to sync all the resources.

**Comment by igorcezar** [comment]
There is a workaround suggested in https://github.com/argoproj/argo-cd/issues/5334#issuecomment-768175349 where you should set the Application to use Helm v3 to render charts.

**Comment by ryancastle** [comment]
This can happen with zealous Helm whitespace chomping. For example, you can lose `apiVersion` into a preceding comment.

```
# Some thoughtful comment
{{- $root := .Values -}}
apiVersion: argoproj.io/v1alpha1
...
```

**Comment by fr4nkR** [comment]
> In my case someone forgot the `apiVersion` in one of the resources deployed in their application.
> Setting the `apiVersion` for that resource fixed the issue, and ArgoCD was able to sync all the resources.

Worked for me, thank you!

**Comment by StepanKuksenko** [comment]
> There is a workaround suggested in [argoproj/argo-cd#5334 (comment)](https://github.com/argoproj/argo-cd/issues/5334#issuecomment-768175349) where you should set the Application to [use Helm v3 to render charts](https://argoproj.github.io/argo-cd/user-guide/helm/#helm-version).

worked for me thank you
