### ISSUE TITLE
argo-cd: helm notes ingress configuration differs from README

### ISSUE THREAD

**Issue by arndt-s** [argoproj/argo-helm#526]
**Describe the bug**
The helm notes are showing `service.ingress.enabled` to enable ingress, which differs from `server.ingress.enabled` as stated in the README of the chart

**To Reproduce**
Install helm chart and check notes log after a successful install.

**Expected behavior**
configuration keys should match

**Comment by mkilchhofer** [comment]
Hi @arndt-s,
I think your PR #527 is merged and this issue can be closed?
