### ISSUE TITLE
[argo-cd] Change "redis-ha" chart source from stable channel to something available

### ISSUE THREAD

**Issue by onyxet** [argoproj/argo-helm#528]
Hello guys!

Currently `stable` repo for helm charts isn't available so in order to use `redis-ha` setup with argocd we need to change chart dependency

I believe [redis-cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster) from Bitnami repo could be suitable

If everybody is OK regarding bitnami chart I'd happy to contribute this feature request

**Comment by AndriiOmelianenko** [comment]
I think this PR https://github.com/argoproj/argo-helm/pull/502 already implements it
