### ISSUE TITLE
Use quote for annotations

### ISSUE THREAD

**Issue by chulkilee** [argoproj/argo-helm#532]
**Describe the bug**

Using "5.0" for redis image tag results in bad annotation then crash, because the integer-like string is not quoted as string, thus it's incorrect type for annotation values.

**To Reproduce**

Use following values

```yaml
redis:
  enabled: true
  image:
    tag: "5.0"
```

Then get following error:

```
Error: unable to build kubernetes objects from release manifest: unable to decode "": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Name: Labels: ReadString: expects " or n, but found 5, error found in #10 byte of ...|version":5,"helm.sh/|..., bigger context ...|io/part-of":"argocd","app.kubernetes.io/version":5,"helm.sh/chart":"argo-cd-2.11.0"},"name":"argocd-|...
```

**Expected behavior**

version should be `"5"`, not `5` in yaml.

**Additional context**

The problematic line:

https://github.com/argoproj/argo-helm/blob/182ef88c67c1ac58d0a922b7101a23e2f91ab2f5/charts/argo-cd/templates/redis/deployment.yaml#L14

See also [Quote Strings, Don't Quote Integers](https://helm.sh/docs/howto/charts_tips_and_tricks/#quote-strings-dont-quote-integers)

```yaml
name: {{ .Values.MyName | quote }}
```

**Comment by yianniBantes** [comment]
Is there any working example? 

I am trying to set this value: 
- name: >-
          ingress.web.annotations.nginx\.ingress\.kubernetes\.io\/proxy‑read‑timeout
  value: "1800" 

, But it always comes with a single quote or no quotes at all. I've tried forceString, it places a single quote too. 

Has anyone managed to place double quotes around an integer?

Thanks
