### ISSUE TITLE
(argo)Argo bump to 2.12

### ISSUE THREAD

**Issue by willgleich** [argoproj/argo-helm#540]
**Is your feature request related to a problem? Please describe.**
Currently argo helm chart is configured for appVersion: v2.11.7

**Describe the solution you'd like**
Update argo helm chart to v2.12.3 (or current latest)

**Additional context**
Wondering if anyone is slated for this work? Looks to be a smaller set of changes to argo/manifests/install.yaml

**Comment by TimoWillemsen** [comment]
I'll pick it up tonight :)

**Comment by willgleich** [comment]
https://github.com/argoproj/argo-helm/pull/554 https://github.com/argoproj/argo-helm/pull/541 Looks like this one got completed with these.
