### ISSUE TITLE
Error installing argocd via helm

### ISSUE THREAD

**Issue by medkbadri** [argoproj/argo-helm#543]
Hello,

Following the latest change to crd-application.yaml, I'm receiving this error while trying to install argocd via Helm :

Error: failed to install CRD crds/crd-application.yaml: CustomResourceDefinition.apiextensions.k8s.io "applications.argoproj.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required.

++

**Comment by medkbadri** [comment]
Error while applying the crd:
k apply -f https://raw.githubusercontent.com/argoproj/argo-helm/master/charts/argo-cd/crds/crd-application.yaml
error: error validating "https://raw.githubusercontent.com/argoproj/argo-helm/master/charts/argo-cd/crds/crd-application.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false

It's related to the apiVersion  being changed from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1

**Comment by dnskr** [comment]
The commit https://github.com/argoproj/argo-helm/commit/391c439de69073a74b38571b96d37ff56f996b81#diff-de9dc82041c1bfb559e1ca8ef6f43d634793cb77453a354af5c89b3e28a02f0a broke it
File `charts/argo-cd/crds/crd-project.yaml` 
```
apiVersion: apiextensions.k8s.io/v1beta1
apiVersion: apiextensions.k8s.io/v1
```

@vladlosev Could you please check it?

**Comment by dnskr** [comment]
Previous chart version works fine but warning messages:
`helm install argocd argo/argo-cd -f argocd.yaml --version 2.11.0 --wait`
```
W0112 23:05:40.085090    6044 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0112 23:05:40.103090    6044 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0112 23:05:42.124301    6044 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0112 23:05:42.133301    6044 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0112 23:05:42.365887    6044 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0112 23:05:42.581332    6044 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME: argocd
LAST DEPLOYED: Tue Jan 12 23:05:42 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
....................
```

**Comment by vladlosev** [comment]
#545 fixes the CRD definitions.

**Comment by abhinavkhanna-sf** [comment]
@vladlosev @dnskr is there an ETA on when the fix will be merged? Can you suggest whats the last good version I can use?

**Comment by vladlosev** [comment]
The project maintainers need to approve and merge the PR now, as only they can do that.
