### ISSUE TITLE
Argo Rollouts chart is not compatible with version v0.10.2

### ISSUE THREAD

**Issue by MarkSRobinson** [argoproj/argo-helm#548]
**Describe the bug**

Using the argo rollouts helm chart with v0.10.2 creates an installation that is broken.  Specifically, Argo Rollouts installed this way will not be able to rollout deployments and will get permanently stuck in the setup phase of a rollout.

**To Reproduce**
1. Install to Kubernetes v1.17
2. Use version `0.10.2` instead of the default of `0.8.0`
3. Following the Argo Rollouts getting Started guideline, do a rollout
4. Watch rollout using kubectl argo rollouts get ro rollouts-demo --watch
5. Rollout is locked in setup state

**Expected behavior**
Argo Rollouts is installed in a working state such that the getting started manual works.

**Screenshots**

**Additional context**
 I believe the default configuration has changed in AR recently going by their PRs.  I think it's related to the security and permission changes they have made recently.

**Comment by sergeyshaykhullin** [comment]
Manifest fix https://github.com/argoproj/argo-helm/pull/552

**Comment by cabrinha** [comment]
fixed in #552
