### ISSUE TITLE
Can not get admin psw via kubectl

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-helm#55]
Can not get psw via kubectl in:

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/NOTES.txt

kubectl get pods -n argocd -l app.kubernetes.io/name={{ include "argo-cd.name" . }}-server -o name | cut -d'/' -f 2

error: name cannot be provided when a selector is specified

USE:
kubectl get pod -n argocd -l app.kubernetes.io/name=argo-cd-server -o jsonpath="{.items[0].metadata.name}"

or

kubectl get pod -n argocd -l app.kubernetes.io/name=argo-cd-server -o name | cut -d'/' -f 2

**Comment by alexec** [comment]
It does look like the docs maybe incorrect. Can you try this and tell me if it works:

https://argoproj.github.io/argo-cd/getting_started/#4-login-using-the-cli
