### ISSUE TITLE
[Release] Helm charts for deploying ArgoCD CRDs

### ISSUE THREAD

**Issue by sbose78** [argoproj/argo-helm#550]
Given that Helm doesn't "upgrade" CRDs in `/crds`, we might want to consider maintaining two charts per release. 

1) One chart which has the CRDs in `/templates`
2) Another chart that references (1).

Happy to hear what the community thinks.

**Comment by sbose78** [comment]
( sorry, this isn't a bug per se )

**Comment by hawksight** [comment]
I like the sound of this idea @sbose78 and matches exactly the recommendations made [here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) by helm project.

I am facing this issue as I have one instance or argo for all our clusters, regularly upgrading it. But as the CRDs are evolving.. I can't make use of all the features. currently.

I am interested to see how everyone else is getting around the issue of updating the crds when helm installed. Is everyone else just getting the yaml files and updating?

**Comment by jppitout** [comment]
I think this is a great idea. Right now CRDs can't even be installed at all: 
```
Steps to reproduce the behavior:
  1. $ kubectl apply -f https://github.com/argoproj/argo-cd/blob/master/manifests/crds/application-crd.yaml 
error: error parsing https://github.com/argoproj/argo-cd/blob/master/manifests/crds/application-crd.yaml: error converting YAML to JSON: yaml: line 92: mapping values are not allowed in this context

  2. $ kubectl apply -f https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/crds/crd-project.yaml
error: error parsing https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/crds/crd-project.yaml: error converting YAML to JSON: yaml: line 92: mapping values are not allowed in this context
```
Tried logging a bug but for some reason not able to.

**Comment by jppitout** [comment]
What is the best way to automate updating CRDs since they aren't part of the Helm chart anymore?

**Comment by jppitout** [comment]
Thanks for the info! 

Our ArgoCD is deployed through a CI/CD pipeline which means manual steps aren't easily handled but any breaking changes should be picked up in our sandbox environment when ArgoCD is deployed there. Based on this use case I think a dependency chart would  be great! Also it would help us to tie specific chart versions to CRD versions. 

Is there a way to check which CRD versions should be paired with each chart version?

**Comment by jppitout** [comment]
bump

**Comment by jppitout** [comment]
For anyone stumbling across this issue in the future... CRD manifests are now tagged with chart version numbers (since 3.x.x) our solution for deploying ArgoCD via CI/CD pipelines was to add this to our code:
```
curl -L -O "https://raw.githubusercontent.com/argoproj/argo-helm/argo-cd-${ARGOCD_CHART_VERSION}/charts/argo-cd/crds/crd-application.yaml"
curl -L -O "https://raw.githubusercontent.com/argoproj/argo-helm/argo-cd-${ARGOCD_CHART_VERSION}/charts/argo-cd/crds/crd-project.yaml"

kapp deploy --app kapp-argocd-crds \
    --wait-timeout 5m \
    --namespace argocd \
    --yes \
    --file crd-application.yaml \
    --file crd-project.yaml
```
