### ISSUE TITLE
Can't install argo rollouts

### ISSUE THREAD

**Issue by utkarsh-pro** [argoproj/argo-helm#555]
**Describe the bug**
Trying to install argo-rollouts using helm v3.5.0 results in the following error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]
```

**To Reproduce**
1. Run `helm repo add argo https://argoproj.github.io/argo-helm`
2. Run `helm repo update`
3. Run `helm install argo-release argo/argo-rollouts`

**Expected behavior**
argo-rollouts should get installed without any errors.

**Additional Details**
Kubernetes Version: 1.19.1
helm Version: v3.5.0
Argo-Rollouts Chart Version: 0.4.0 and 0.4.1
OS: Manjaro Linux

**Comment by templarfelix** [comment]
erros:

`error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]`

**Comment by omegion** [comment]
Same error here:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.s
pec): unknown field "additionalPrinterColumns" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError
(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec,
ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDef
initionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomR
esourceDefinitionSpec]
```

**Comment by Xtigyro** [comment]
Same here - with the difference that it errors out on Helm v2.17.0 with:

```
  Error: release argo-rollouts-helm2 failed: CustomResourceDefinition.apiextensions.k8s.io "rollouts.argoproj.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
```

**Comment by cabrinha** [comment]
Did this fix it? https://github.com/argoproj/argo-helm/pull/589

**Comment by utkarsh-pro** [comment]
@cabrinha, not sure if #589 fixed it but issue seems to be resolved now. Thanks for the help! Closing the issue now :smile:
