### ISSUE TITLE
Syntax error when deploying argo-cd helm chart

### ISSUE THREAD

**Issue by gabrielcalderon** [argoproj/argo-helm#56]
When deployment argo-cd the following error shows up:

Helm template failed. Error: parse error in "argo-cd/templates/argocd-server-service.yaml: template: argo-cd/templates/argocd-server-service.yaml:13: unexpected {{end}} : exit status 1

**Comment by alexec** [comment]
@e-mon is this related to your change in https://github.com/argoproj/argo-helm/pull/53?

**Comment by alexec** [comment]
@gabrielcalderon can you try deleting the `{{ end }}` on that line and see if it works please?

**Comment by gabrielcalderon** [comment]
@alexec I can confirm that removing the {{end}} makes the error go away.

[https://github.com/gabrielcalderon/argo-helm/blob/master/charts/argo-cd/templates/argocd-server-service.yaml](url)
