### ISSUE TITLE
Notifications: argocd-notifications-cm ConfigMap Template Blocks v1.0.0+ Upgrade

### ISSUE THREAD

**Issue by booleanbetrayal** [argoproj/argo-helm#560]
**Describe the bug**

The `argocd-notifications/templates/configmap.yaml` Helm template blocks `argocd-notifications:v1.0.0` and above.
The `ConfigMap` expectations have been updated in the image for 1.0.0+, but the Helm template has not been updated to accomodate the new `ConfigMap` format. 

The Helm template cannot be toggled off via a value switch, but it can still be overridden manually in a project that imports the argocd Helm package by producing duplicate definitions.

This however results in a Warning if deploying to ArgoCD as managed by ArgoCD.

**To Reproduce**
1. Use latest Helm charts release, as according to the [install instructions](https://argocd-notifications.readthedocs.io/en/latest/#helm-v3-getting-started)
2. Update `image.tag` to `v1.0.0`
3. Observe that the `ConfigMap` is generated with the legacy structure and that there is no value switch to toggle it off

**Expected behavior**
The Helm charts should be updated to support the new argocd-notifications `ConfigMap` expectations.
As a hot-fix, providing a value to toggle the `ConfigMap` off entirely prior to this refactor being implemented, would be helpful.

**Screenshots**
An example of bundling an alternative `argocd-notifications-cm` `ConfigMap` to support v1.0.0+, without any capability of disabling the packaged version.

<img width="1473" alt="Screen Shot 2021-01-27 at 6 58 47 PM" src="https://user-images.githubusercontent.com/981825/106079032-b2417e00-60d1-11eb-9b81-ef3b764f1dee.png">

**Additional context**
In lieu of the appropiate support, a hot-fix value toggle could go a long way, perhaps with a note in the Argo CD Notifications > Overview section indicating that full support is forthcoming.

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo-helm/pull/567 . Thanks to @georgekaz !
