### ISSUE TITLE
Helm charts not respecting namespace flag (when using helm template)

### ISSUE THREAD

**Issue by nabadger** [argoproj/argo-helm#566]
**Describe the bug**

The helm chart definitions should respect namespaces that are passed in when using `helm template`.

**To Reproduce**

```
 helm template charts/argo-cd --namespace foo
```

**Expected behavior**

I would expect all the workloads (deployments etc) to get deployed to namespace `foo` - it looks like only the RBAC rules get this.

Instead ,there is no namespace information in the generated manifests, which means they always get deployed to `default` namespace.

I have a feeling this may be a change between helm2 / helm3 (I was using helm3).

I belive the correct fix is to use ` namespace: {{ .Release.Namespace }}` in the chart templates, which gets set when using `helm template`.

**Comment by vladlosev** [comment]
This is a controversial issue (see https://github.com/helm/helm/issues/5465), but the chart as is is actually adhering to the Helm authors' recommendations.

**Comment by perezjasonr** [comment]
The problem is that due to this we cannot tell it which namespace to go to, as nabadger stated it will go to default everytime. Even in the basic "getting started" argocd docs they put everything in argocd namespace with kubectl -n argocd.

helm --namespace argocd does not reflect this result.

**Comment by perezjasonr** [comment]
actually I take that back, I just used this chart with namespace argocd and everything, pods, deployment, service was in argocd not default. I'm not sure why we got different results. As long as all this stuff does go to the namespace in the namespace arg  than not having it actually in templates should be fine.
