### ISSUE TITLE
[argocd] Cannot pass metadata.finalizers to Project AppProject resource .Values.server.additionalProjects

### ISSUE THREAD

**Issue by abdennour** [argoproj/argo-helm#587]
**Is your feature request related to a problem? Please describe.**
The current helm chart of argocd does not give a way to pass extra metadata for project resources.

**Describe the solution you'd like**
it would be great to have `.Values.server.additionalProjects.finalizers` with default value :

```yaml
  finalizers:
  - resources-finalizer.argocd.argoproj.io 
```

**Describe alternatives you've considered**
or at least:  having `.Values.server.additionalProjects.additionalMetadata`

**Additional context**

https://github.com/argoproj/argo-cd/issues/4369#issuecomment-695074427

**Comment by mkilchhofer** [comment]
Adding the finalizer by default could be dangerous, right?

**Comment by abdennour** [comment]
any news about this issue? 
it was reported before the GA of v2.x

**Comment by mkilchhofer** [comment]
Not stale
