### ISSUE TITLE
argocd chart does not include ClusterRole and ClusterRoleBinding for argocd-server.

### ISSUE THREAD

**Issue by denniswebb** [argoproj/argo-helm#61]
**Describe the bug**
Chart does not include the ClusterRole/argocd-server or ClusterRoleBinding/argocd-server as is found in https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

**To Reproduce**
1. Install from chart
2. Deploy any application to the default cluster to a new namespace
3. Click on pod and you can not see manifest or logs

**Expected behavior**
If the ClusterRole and  ClusterRoleBinding are present, manifest and logs will be readable.

**Additional context**
This is a quick fix I will try to PR later this weekend.

**Comment by rocketspacer** [comment]
@alexec This bug re-appeared on master (Chart version 1.7.3)
