### ISSUE TITLE
Dex-Server metrics not working with prometheus

### ISSUE THREAD

**Issue by crevillo** [argoproj/argo-helm#615]
**Describe the bug**
Hello. Sorry I'm quite newbie to this. i'm trying to setup metrics for the `dex-server`. According to the doc it looks those metrics are exposed in port `5558`. But I no see metrics there. Not sure if I miss anything. If you can point me to the right solution that'll be great

**To Reproduce**
1. Install the helm chart with a values.yaml file containing 
```
  dex:
    metrics:
      enabled: true
    podAnnotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '5558'
```
2. Having prometheus up go to see the targets there. 
3. Check dex-server target. Is that UP or down? 
4. For us is down
![image](https://user-images.githubusercontent.com/306215/110340989-299bf300-802a-11eb-83b8-ab5248d2c89a.png)

**Expected behavior**
Target should be up

**Screenshots**
We can see this services with that config 
![image](https://user-images.githubusercontent.com/306215/110342730-07a37000-802c-11eb-9dc1-a4ccb1993ba3.png)

i can do port-forward to the port 5558 to look for the metrics but instead i get errors
```
kubectl -n argo-cd port-forward svc/argo-cd-argocd-dex-server 9000:5558
Forwarding from 127.0.0.1:9000 -> 5558
Forwarding from [::1]:9000 -> 5558
Handling connection for 9000
E0308 16:34:45.698946   86787 portforward.go:400] an error occurred forwarding 9000 -> 5558: error forwarding port 5558 to pod ba36adc2891c7c0d55e8225f30446cdacf28312c3e1e919df9b099f294ea5ebb, uid : exit status 1: 2021/03/08 15:34:45 socat[23228] E connect(5, AF=2 127.0.0.1:5558, 16): Connection refused
Handling connection for 9000
E0308 16:34:49.337534   86787 portforward.go:400] an error occurred forwarding 9000 -> 5558: error forwarding port 5558 to pod ba36adc2891c7c0d55e8225f30446cdacf28312c3e1e919df9b099f294ea5ebb, uid : exit status 1: 2021/03/08 15:34:49 socat[23285] E connect(5, AF=2 127.0.0.1:5558, 16): Connection refused
```

```
curl http://127.0.0.1:9000/metrics
curl: (52) Empty reply from server
```

Let me know if anything is wrong with my config. Thanks.

**Comment by aslafy-z** [comment]
This issue should be reopened. Dex metrics are still not reachable.

**Comment by ksaio** [comment]
I experience same issue

**Comment by hughhm** [comment]
Also having the same issue. Portforward shows that the Dex server itself is not posting any metrics

**Comment by mkilchhofer** [comment]
I cannot reproduce this in my setup:
```console
$ kubectl port-forward argocd-dex-server-8d7b75c6f-bk7dn 5558:5558
Forwarding from 127.0.0.1:5558 -> 5558
Forwarding from [::1]:5558 -> 5558

$ curl -s localhost:5558/metrics | head
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 5.4956e-05
go_gc_duration_seconds{quantile="0.25"} 6.5832e-05
go_gc_duration_seconds{quantile="0.5"} 0.000181204
go_gc_duration_seconds{quantile="0.75"} 0.100093906
go_gc_duration_seconds{quantile="1"} 0.100093906
go_gc_duration_seconds_sum 0.100395898
go_gc_duration_seconds_count 4
# HELP go_goroutines Number of goroutines that currently exist
```

Can you share with us what dex version and chart version you are using?

**Comment by hughhm** [comment]
Interesting, thanks for reopening, details below:

Chart version: `3.25.2`

Dex version:
```
  image:
    repository: ghcr.io/dexidp/dex
    tag: v2.30.0
    imagePullPolicy: IfNotPresent
```
Running port-forward without k9s shows this connection refused error which i think means nothing is listening on that port in the container:

```
 $  kubectl port-forward argocd-dex-server-87c8cdf86-q7vmh 5558:5558
Forwarding from 127.0.0.1:5558 -> 5558
Forwarding from [::1]:5558 -> 5558
Handling connection for 5558
E1112 08:52:47.063095   34721 portforward.go:400] an error occurred forwarding 5558 -> 5558: error forwarding port 5558 to pod 41dc905c6500582bf58716329fda73055bf289e2f46d2f1857773145d654427f, uid : exit status 1: 2021/11/11 22:22:47 socat[30750] E connect(5, AF=2 127.0.0.1:5558, 16): Connection refused

$  ~  curl -s localhost:5558/metrics | head
```

The container certainly has the port open, as does the service:
```
    image: ghcr.io/dexidp/dex:v2.30.0
    imagePullPolicy: IfNotPresent
    name: dex-server
    ports:
    - containerPort: 5556
      name: http
      protocol: TCP
    - containerPort: 5557
      name: grpc
      protocol: TCP
    - containerPort: 5558
      name: metrics
      protocol: TCP
```

**Comment by hughhm** [comment]
I think i may have been mistaken about the role of the dex server. Having reviewed this a bit further and seeing the log `dex is not configured` i realised it is used for OpenID auth which we do not have setup. Can i ask why the server is enabled by default, does it serve another purpose other than OpenID auth or can we safely disable if using the local login?

Apologies for the confusion.

**Comment by mkilchhofer** [comment]
Ahh that might be the case when no dex config is specified inside the ConfigMap, right.

It is enabled by default since our intent is that the upstream kustomize and the helm default installation should match.

But when you use an external OIDC auth provider directly, you could disable the dex server.

**Comment by janpieper** [comment]
Using the following config, I can disable deploying the dex server:

```yaml
dex:
  enabled: false
```

But what about the argocd-server? When disabling dex, the `--dex-server` flag gets removed from the argocd-server Deployment, but this makes the argocd-server to fall back to the default dex server address:

https://github.com/argoproj/argo-cd/blob/17c6daa9ea897936bb5f472455b520c1de41fc2b/cmd/argocd-server/commands/argocd_server.go#L169

I expect the argocd-server to still try to use the dex server that is not available anymore. Is there any way to tell the argocd-server that it should not (try to) use the dex server? :thinking:

**Comment by mkilchhofer** [comment]
This `--dex-server` tells the Argo API Server to run a reverse proxy for dex:
https://github.com/argoproj/argo-cd/blob/122ecefc3abfe8b691a08d9f3cecf9a170cc8c37/server/server.go#L746

But it only starts the reverse proxy if Dex (`dex.config`) or SSO (`oidc.config`) is configured:
https://github.com/argoproj/argo-cd/blob/v2.2.1/server/server.go#L773-L788

This might be optimised as it also starts the reverse proxy when SSO is configured, but it does not bother that much. It only produces these log lines when someone tries to access `https://<argocd-url>/api/dex`
```log
2021/12/20 18:00:54 http: proxy error: dial tcp: lookup argocd-dex-server on 10.43.0.10:53: no such host
2021/12/20 18:04:59 http: proxy error: dial tcp: lookup argocd-dex-server on 10.43.0.10:53: no such host
```
