### ISSUE TITLE
[argo] Move to minio operator

### ISSUE THREAD

**Issue by tsunamishaun** [argoproj/argo-helm#639]
**Is your feature request related to a problem? Please describe.**
Per the [minio deprecation notice](https://helm.min.io/) it is recommended to move to the [minio operator ](https://github.com/minio/operator).

**Describe the solution you'd like**
Modify argo chart to have a conditional dependency on minio-operator and also optionally install a minio cr to match the current usage.

**Describe alternatives you've considered**
Not upgrading and continue to use deprecated minio chart.

**Additional context**
After the recent argo chart reference fix to the minio chart [#455](https://github.com/argoproj/argo-helm/issues/455) we realized it would be deprecated next week.

**Comment by oliverbaehler** [comment]
Hi @tsunamishaun, thanks for your input. I tried to implement your suggested changes. Would you mind taking a look into it and give some feedback, if that's what you are looking for? It would also be super cool if you could realize the use case, so we could maybe have some more realistic default values.

I am happy to talk about any change :)
