### ISSUE TITLE
Defning a a custom health check not possible

### ISSUE THREAD

**Issue by arnarg** [argoproj/argo-helm#64]
**Is your feature request related to a problem? Please describe.**
According to the [documentation](https://argoproj.github.io/argo-cd/operator-manual/health/#way-1-define-a-custom-health-check-in-argocd-cm-configmap) you should be able to add `resource.customizations` to `argocd-cm` to define a custom resource health checks. The helm chart does not allow this.

**Describe the solution you'd like**
Add the option in config in `values.yaml` to add resource customizations. This will be rendered in `argocd-cm` like the other options do.

**Describe alternatives you've considered**
Patching `argocd-cm` from kubectl, not an option imo.

**Comment by TapTap21** [comment]
@alexec it seems like this functionality was removed in chart version 5.7.0 when the argocd-cm was moved to `configs.cm`.

It seems to me that it is not possible to set `resource.customizations` for a custom health check in the current version. Should this issue be reopened?

**Comment by pdrastil** [comment]
@TapTap21 @alexec This functionality is still there. `config.cm` is equivalent to `server.config` (and there is still fallback to old section for compatibility reasons). You just need to define your own health check.

```yaml
configs:
  cm:
    # Custom health check
    resource.customizations.health.certmanager.k8s.io-Certificate: |
      hs = {}
      if obj.status ~= nil then
        if obj.status.conditions ~= nil then
          for i, condition in ipairs(obj.status.conditions) do
            if condition.type == "Ready" and condition.status == "False" then
              hs.status = "Degraded"
              hs.message = condition.message
              return hs
            end
            if condition.type == "Ready" and condition.status == "True" then
              hs.status = "Healthy"
              hs.message = condition.message
              return hs
            end
          end
        end
      end
      hs.status = "Progressing"
      hs.message = "Waiting for certificate"
      return hs
```
