### ISSUE TITLE
[argo] Ability to configure default path for ingress

### ISSUE THREAD

**Issue by gcalmettes** [argoproj/argo-helm#640]
**Is your feature request related to a problem? Please describe.**
While Argo Workflow is compatible with being served on a subpath, the current ingress provided in the chart does not allow for passing a custom subpath.
Note that this option is available on other argo charts, like argo-cd for exemple (https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L505) 

**Describe the solution you'd like**
The option of passing a custom path for the ingress would be great.
Proposal in #641 

**Describe alternatives you've considered**
Right now, to serve Argo Workflow on a subpath, the chart ingress has to be disabled and a custom ingress object has to be deployed alongside the chart.

**Comment by mkilchhofer** [comment]
Close as PR https://github.com/argoproj/argo-helm/pull/641 is closed now. @gcalmettes said that a new PR/issue is created if the migrated chart still misses this feature.
