### ISSUE TITLE
ArtifactHub Verified Publisher

### ISSUE THREAD

**Issue by oliverbaehler** [argoproj/argo-helm#651]
**Is your feature request related to a problem? Please describe.**

We should mark this repository as verified Publisher Repository on Artifacthub. This way User's will know, that the charts they are downloading are published from here.

**Describe the solution you'd like**

We need someone that has control over the artifacthub repository, to add the following file to the `gh-pages` branch:

  * [https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml)

And that's basically it. Maybe that's something you could do @alexec, i believe you have that power.. :D 

**Describe alternatives you've considered**

To not become verified Publisher

**Additional context**
-

**Comment by mkilchhofer** [comment]
Who can help from the argoproj team? @alexec , @alexmt , @jessesuen , @jannfis  ? This repository here seems to be owned by a individual and not an organization: https://artifacthub.io/packages/search?page=1&repo=argo

If this individual account is owned by someone of the argoproj team, we could easily transfer it to a newly created Org. Also if this is not owned by someone of argoproj, we can create a new Org an claim ownership easily: https://artifacthub.io/docs/topics/repositories/#ownership-claim

**Comment by alexec** [comment]
I'm not sure where the owner is listed?

**Comment by mkilchhofer** [comment]
So you are the owner?

**Comment by jessesuen** [comment]
Sorry for late response. I didn't see this mention until today. So I've just:

1. created an `argoproj` organization in artifacthub.io. I'm not sure how to add others as members of that org, but I'd like to add other project leads.
2. committed an `artifacthub-repo.yml` into the gh-pages to prove ownership
3. initiated the ownership claims process of the `argo` artifacthub.io repository through artifacthub.io

I think after step 3, something else needs to happen in the artifacthub.io side of things because it doesn't yet appear in the repositories list, and the option to claim ownership of `argo` is now greyed out.

Let's wait and see what happens next

**Comment by mkilchhofer** [comment]
Oh, this is cool :-)
Did you already tried by pressing the "CLAIM OWNERSHIP" button?
![image](https://user-images.githubusercontent.com/7290987/133744625-8b2775dd-ff63-4512-9985-c617957ac0a1.png)

**Comment by jessesuen** [comment]
Correct. I did this:
![image](https://user-images.githubusercontent.com/12677113/133829367-a4b82dc6-f644-4e27-9c79-80a67e977058.png)

I was able to click claim ownership once, but now the option is greyed out, as if it is in the middle of the process.

**Comment by mkilchhofer** [comment]
Hmm from the public side it looks like the repo is already transfered:
![image](https://user-images.githubusercontent.com/7290987/133830284-da98b18c-fd98-4bc4-b9cc-8c0e8a26d820.png)

Before you did your things, there was "ORG: Helm"

**Comment by mkilchhofer** [comment]
@jessesuen Do you see the id now? If so, could you please proceed and update the gh-pages branch? :-)

**Comment by jessesuen** [comment]
Yup. Looks like something changed on artifacthub and I am able to see the repo after logging in to artifacthub. I committed the repositoryID to the artifacthub-repo.yml. I think this issue should be able to be closed once we see the badge.
