### ISSUE TITLE
[argocd-notifications] Chart's metrics.enabled.false setting not obeyed 

### ISSUE THREAD

**Issue by pentago** [argoproj/argo-helm#653]
Installed the latest version of the chart this morning and noticed that even though I have `metrics.enabled.false` configured, pod startup logs say that metrics are active: https://i.imgur.com/Mfb8etx.png

**Comment by mkilchhofer** [comment]
You are viewing logs of the container. There is no option to disable the metrics listener. But the resources which belongs to metrics are not deployed:
- https://github.com/argoproj/argo-helm/blob/master/charts/argocd-notifications/templates/service-metrics.yaml#L1
- https://github.com/argoproj/argo-helm/blob/master/charts/argocd-notifications/templates/servicemonitor.yaml#L1

I close this, as it works as designed.
