### ISSUE TITLE
secrets "argocd-initial-admin-secret" not found on reinstall

### ISSUE THREAD

**Issue by williamcodes** [argoproj/argo-helm#684]
**Describe the bug**
The "argocd-initial-admin-secret" secret does not exist when the chart is reinstalled.

**To Reproduce**
1. `helm install argocd charts/argocd --create-namespace --namespace argocd --wait`
2. `PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)`
3. `argocd login localhost:8080 --name admin --password "${PASSWORD}"`
4. `helm uninstall argocd`
5. `helm install argocd charts/argocd --create-namespace --namespace argocd --wait`
6. `PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)`
7. `argocd login localhost:8080 --name admin --password "${PASSWORD}"`

**Expected behavior**
Login should work

**Actual behavior**
```
Error from server (NotFound): secrets "argocd-initial-admin-secret" not found
```

**Comment by NiniiGit** [comment]
(Hope this will help others)
okay, so now I learned the hard way that for argo-cd installation via helm,
new password of the ArgoCD will be your argocd api-server pod name with the numbers at the end name (kubectl -n argocd get po >> to find pod name) for example, the entire name of your pod-like: argocd-server-xxxxxxxx would be your initial password

**Comment by hghtwr** [comment]
Gonna leave this here for future people searching for this problem: 
https://argo-cd.readthedocs.io/en/release-2.0/faq/#i-forgot-the-admin-password-how-do-i-reset-it
