### ISSUE TITLE
[workflows]: Add Helm-Docs Support

### ISSUE THREAD

**Issue by oliverbaehler** [argoproj/argo-helm#696]
**Is your feature request related to a problem? Please describe.**
Currently we don't document values in the README.md for each chart. This since the charts are mostly very complex and they get out of sync very fast. 

**Describe the solution you'd like**
[Helm-Docs](https://github.com/norwoodj/helm-docs) synces README content based on values files. If we could add helm-docs to our github workflows we could simply document all values.

**Describe alternatives you've considered**

**Additional context**

**Comment by chgl** [comment]
https://github.com/kubepack/chart-doc-gen is pretty neat as well. It's effectively the same as helm-docs but doesn't require a custom prefix for comments (although I tried making this configurable but haven't succeeded yet https://github.com/norwoodj/helm-docs/issues/67 ...). I'm using it in my chart repo over at https://github.com/chgl/charts.

**Comment by mkilchhofer** [comment]
not stale
