### ISSUE TITLE
ArtifactHub Helm Annotations

### ISSUE THREAD

**Issue by 300481** [argoproj/argo-helm#735]
Hello,

**Is your feature request related to a problem? Please describe.**
When I'm looking for the Argo Helm Charts on Artifact Hub,
I'm missing two very important facts:

- Used Container Images and their versions --> to easily get CVE information
- Changelog to see, what is changed between the Chart-Versions

I need this information to decide if it is a major risk deploying a new version, or not.
Currently I must investigate this with a lot of effort.

**Describe the solution you'd like**
Please just add as much as possible Artifact Hub Helm Annotations in the Chart.yaml:
https://artifacthub.io/docs/topics/annotations/helm/

**Describe alternatives you've considered**
An alternative regarding the Changelog could be a CHANGELOG.md within the chart,
but having this directly on Artifact Hub is better.
Regarding the CVE scan results I have no alternative idea for the moment.

Thank you very much for your work!

**Comment by 300481** [comment]
Great, the Artifact Hub [commit](https://github.com/artifacthub/hub/commit/783f2b1eb03e40a9cbd686981353b36010974297) from before 8 hours will now enable it to extract the images from the manifests from a dry-run install using the the default.yaml described as in the [documentation](https://artifacthub.io/docs/topics/security_report/#helm-charts)

Anyway, extending the Argo Helm Charts with the annotations would be very helpful in any case.
Especially the changelog stays interesting for me.

**Comment by oliverbaehler** [comment]
@300481 Understandable, it's also difficult to have an overview since this is just community maintained. A first improvement we have done is expanding the lint workflow, so that the charts are always installed on a pr (via. #685). We will address your issue with a guideline for Changelog definition.

**Comment by 300481** [comment]
@oliverbaehler this sounds good and should solve the issue.
Thank you!
