### ISSUE TITLE
Argo-Rollouts 1.0 support

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-helm#740]
**Is your feature request related to a problem? Please describe.**
Upgrade to support argo-rollouts 1.0.

It was just released today.

thank you

**Comment by DanTulovsky** [comment]
FYI, the CRDs as they currently exist here do not work for 1.0.

**Comment by derjust** [comment]
If someone could outline how this upgrade would work out I'm happy to take a shot at it.
Like where do the original CRDs come from to be placed into the chart?

**Comment by DanTulovsky** [comment]
They would come from: https://github.com/argoproj/argo-rollouts/releases/download/v1.0.0/install.yaml
