### ISSUE TITLE
Allow Setting of Image Pull Policy 

### ISSUE THREAD

**Issue by igobypenn** [argoproj/argo-helm#75]
**Problem**: I ran into a situation in which we would like to leverage the Argo helm chart in an air gapped environment. The machine we will be deploying to do not have external connections and are unable to pull images. Instead the images are pre-loaded on the the nodes. 

**Solution**: 
[See](https://github.com/argoproj/argo-helm/pull/74): Enable imagePullPoicy consistently across all helm charts.

**Comment by alexec** [comment]
Fixed?
