### ISSUE TITLE
[argo-workflows] Helm .Capabilities not representing k8s cluster

### ISSUE THREAD

**Issue by marekadare** [argoproj/argo-helm#753]
**Describe the bug**
In one of the latest changes to argo-workflows argo-workflows/templates/_helpers.tpl was added. The helper argo-workflows.ingress.apiVersion is using .Capabilities.KubeVersion.Version but that is not representing the current k8s cluster version.

If you use argocd to deploy your Helm Chart the .Capabilities.KubeVersion.Version is v1.20.0 but the actual k8s cluster version is v1.18.0

This leads to an unusable Helm Chart, because I don't know any way to configure that version.
Updating the k8s cluster is not an option at the moment due to production usage.

**To Reproduce**
1. Install v1.18.0 Kubernetes cluster
1. Install argocd
2. Create new app for argo-workflows in argocd
3. Sync

**Expected behavior**
I don't know how but argocd or the argoworkflow Helm Chart helpers should check the k8s-cluster version beforehand.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16648900/119487140-4b6b6300-bd59-11eb-911a-1b4593f20443.png)

**Comment by kulinskyvs** [comment]
Looks, I have similar behavior with Helmfile. 

```yaml
server:
  ingress:
    enabled: true
    hosts:
      - myhost.mydomain.com
```

I have K8s cluster version 1.19 and with the values.yaml listed above I'm facing the following issue

```
STDERR:
  Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend

COMBINED OUTPUT:
  Release "argo-workflows" does not exist. Installing it now.
  Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend
```

**Comment by mkilchhofer** [comment]
We recently added a new value to workaround this in `argo-cd`: https://github.com/argoproj/argo-helm/pull/704

Related issues:
- `argo-cd` chart: #703 
- argo-cd bug: https://github.com/argoproj/argo-cd/issues/3594

**Comment by mkilchhofer** [comment]
https://github.com/argoproj/argo-cd/issues/5833 is implemented now. let's see if this helps as soon as this fix got released.

**Comment by marekadare** [comment]
Thanks for your reply.
I'll give it a try as soon as possible.

**Comment by naimo84** [comment]
I also have to say thank you for the fast fix 👍
