### ISSUE TITLE
NameOverride and fullnameOverride support

### ISSUE THREAD

**Issue by IvanovOleg** [argoproj/argo-helm#754]
Hello. It would be great to have a possibility to override the name of resources.

**Comment by mkilchhofer** [comment]
Hello @IvanovOleg,
Could you please provide the name of the chart you are having this issue with?

**Comment by IvanovOleg** [comment]
@mkilchhofer argo-rollouts

**Comment by weisjohn** [comment]
@mkilchhofer is this possible for argo-workflows as well?

**Comment by weisjohn** [comment]
> @mkilchhofer is this possible for argo-workflows as well?

oops, looks like https://github.com/argoproj/argo-helm/pull/759 already covers this

**Comment by weisjohn** [comment]
Actually, it looks like the chart allows you to specify `fullname`, but this still includes the `.Release.Name`. It'd be nice if the chart supported `fullnameOverride` to shrink overly pod names.

**Comment by mkilchhofer** [comment]
> Actually, it looks like the chart allows you to specify `fullname`, but this still includes the `.Release.Name`. It'd be nice if the chart supported `fullnameOverride` to shrink overly pod names.

Filed a PR for the workflows chart: https://github.com/argoproj/argo-helm/pull/769
