### ISSUE TITLE
Add keyPrefix option in artifactRepository.s3

### ISSUE THREAD

**Issue by donaldrauscher** [argoproj/argo-helm#76]
Per [this documentation](https://github.com/argoproj/argo/blob/master/ARTIFACT_REPO.md), you can specify a keyPrefix for your artifacts.  Requesting we simply add some logic for this in `workflow-controller-config-map.yaml`.  Thanks!

**Comment by alexec** [comment]
This would be a great community submission if you fancy raising a PR?

**Comment by donaldrauscher** [comment]
Just submitted PR

**Comment by donaldrauscher** [comment]
Merged
