### ISSUE TITLE
Complete migration CircleCI -> Github Actions

### ISSUE THREAD

**Issue by mkilchhofer** [argoproj/argo-helm#776]
The initial intent was: https://github.com/argoproj/argo-cd/pull/3677

With these PRs, we migrated the chart related workflows to GitHub Actions:
- Linting: https://github.com/argoproj/argo-helm/pull/685
- Releasing: https://github.com/argoproj/argo-helm/pull/741
- ?? (.argo directory): https://github.com/argoproj/argo-helm/pull/770

Before we drop the `.circleci` folder in the repository root, we need to 
1) disable current Merge checks:
  a) ci/circleci: lint
  b) ci/circleci: publish
2) enable a new merge check:
   - chart-test

![image](https://user-images.githubusercontent.com/7290987/120238847-59d7e400-c25d-11eb-8733-6bcf73eb2214.png)

Could you implement that @jessesuen, @alexec, @alexmt or @jannfis?

**Comment by alexec** [comment]
Done. Try now.

**Comment by mkilchhofer** [comment]
> Done. Try now.

Looks good, thank you. I'll file a PR to remove the CircleCI `config.yaml`

**Comment by mkilchhofer** [comment]
After merging #780 I now see:
![image](https://user-images.githubusercontent.com/7290987/120354506-c527c180-c302-11eb-91fd-593c5db92370.png)
![image](https://user-images.githubusercontent.com/7290987/120354627-e12b6300-c302-11eb-9e03-8c658cf0d7dc.png)

Is it possible, that CircleCI needs to be removed in the GitHub settings also, @alexec ?

**Comment by alexmt** [comment]
Disabled Circle CI builds for this repo. Next PR/commit should be good

**Comment by alexec** [comment]
Try now,.

**Comment by mkilchhofer** [comment]
Looks good 🥳  thank you so much.
