### ISSUE TITLE
[argocd-notifications] Add configmap and secret names override

### ISSUE THREAD

**Issue by sergeyshaykhullin** [argoproj/argo-helm#779]
**Is your feature request related to a problem? Please describe.**
Add secret and configmap names override after new controller version released

**Describe the solution you'd like**

https://github.com/argoproj-labs/argocd-notifications/issues/295#issuecomment-852184767

**Describe alternatives you've considered**

**Additional context**

**Comment by mkilchhofer** [comment]
not stale
