### ISSUE TITLE
question(argocd): Migrate from YAML to Helm Release

### ISSUE THREAD

**Issue by Bhuppi9753** [argoproj/argo-helm#789]
I have just started learning helm. I had installed Agrocd version 1.6 from the official YAML file now want to upgrade to the latest version through this helm chart, 
just need a confirmation like can I directly install this helm chart in my env or do I need to change anything in it?

Thanks for your support!

**Comment by oliverbaehler** [comment]
Hi @Bhuppi9753 I would recommend to install a new instance with helm and migrate your date from the old instance. For the helm chart you will need to disable the deployment of CRDs  (`helm .... --skip-crds`). And you should deploy it into a different namespace, if possible.

**Comment by Bhuppi9753** [comment]
is it possible to migrate data from yaml install argocd to helm install argocd
