### ISSUE TITLE
argo-workflow: Ingress templating is misbehaving for <1.19 clusters

### ISSUE THREAD

**Issue by Byh0ki** [argoproj/argo-helm#794]
**Describe the bug**
Since https://github.com/argoproj/argo-helm/pull/747, the `Ingress` templating will not work properly on <1.19 K8s clusters (tested on 1.18.8). The ingress manifest is generated with `networking.k8s.io/v1` API but it's not available until 1.19 for `Ingress`. I'm not sure about older clusters than 1.18, the problem seems to be that when `networking.k8s.io/v1` is available on the cluster, either for `Ingress` or for anything else, the template will generate a `networking.k8s.io/v1` Ingress.

**To Reproduce**
1. Install the chart on a <1.19 cluster
2. The install will fail with a validation error

**Expected behavior**
The `Ingress` manifest should be generated for `networking.k8s.io/v1beta1` API.

**Comment by mkilchhofer** [comment]
Duplicates #753
