### ISSUE TITLE
Add Support For ALB Ingress Controller

### ISSUE THREAD

**Issue by toneill818** [argoproj/argo-helm#803]
**Is your feature request related to a problem? Please describe.**
When using AWS ALB ingress controller a new service needs to be created for GRPC.

**Describe the solution you'd like**
Add a flag to the ingress to specify you are going to use an ALB. Then create the service described [here](https://argoproj.github.io/argo-cd/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode) and create the ingress. 

**Describe alternatives you've considered**
Using the kustomize install or creating the service outside of the helm chart. 

**Additional context**
The key here is the `alb.ingress.kubernetes.io/conditions.argogrpc: [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]` annotation on the server ingress. This will create a second rule in the ALB listener so the additional GRPC ingress would not be needed if using an ALB for the ingress.

**Comment by emanuelflp** [comment]
@toneill818 this is great and it works here. The only issue is because you have defined the type of the `service-grpc` as `ClusterIP` and the AWS ingress controller needs this parameter as `NodePort`. I will send a PR to fix this.

**Comment by toneill818** [comment]
@emanuelflp What version of the ALB ingress controller are you using. It is able to work with the service type of `ClusterIP` and is set to `ClusterIP` in the official documentation. 
https://argoproj.github.io/argo-cd/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode

**Comment by toneill818** [comment]
Fixed in #862 and #909

**Comment by agaudreault-jive** [comment]
@toneill818 I have been trying to make thing works with HTTP2, but it seems I always have a `FATA[0005] rpc error: code = Internal desc = transport: received the unexpected content-type "text/html"` exception from the CLI. When I look at the specific Target Group for HTTP2 in AWS, the instance does not appear as Healthy. They do with the HTTP1 target group. Did you make it work with an ALB ?
![image](https://user-images.githubusercontent.com/47184027/141830981-fadeccd8-8bdc-4c19-91c4-6a2d2fd43893.png)
![image](https://user-images.githubusercontent.com/47184027/141831051-6ad73a4b-8e11-43b6-93b5-066bc4a1896d.png)
![image](https://user-images.githubusercontent.com/47184027/141831077-7a267184-7ca0-4cb5-a7a8-83b32a02ab2f.png)

**Comment by wmiller112** [comment]
Anyone that comes across this, I found the grpc services described [here](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode) has the annotation 
`alb.ingress.kubernetes.io/backend-protocol-version: HTTP2` and I found that the grpc service health check would fail. Changing it to `GRPC` resolved the issue

**Comment by innovia** [comment]
its doesnt solve the healthchecks codes

``` ValidationError: Health check matcher GRPC code '200' must be within '0-99' inclusive```

**Comment by innovia** [comment]
Actually,  just make sure not to specify the status code  in the annotations so that the target groups auto-detect it

<img width="2590" alt="image" src="https://user-images.githubusercontent.com/112025/198396226-ee8abaa3-24d8-4d72-b2eb-0d66523a8752.png">

<img width="2582" alt="image" src="https://user-images.githubusercontent.com/112025/198396314-0d110b06-c9ef-4374-bbaf-938b252d0c19.png">
