### ISSUE TITLE
[Argocd-ApplicationSet] Possible CRD install validation error

### ISSUE THREAD

**Issue by unb9rn** [argoproj/argo-helm#825]
Hello!
I'm trying to install applicationset with Terraform and Helm provider.
While applying new state there is an error:
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "applicationsets.argoproj.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "argocd-4039"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "argocd"`
But the CRD is installed anyway and exluding it on a second run with installCRDs="false" deploys application set without an error...

**Comment by soleares** [comment]
@mkilchhofer I'm seeing this same error while updating Helm chart 4.9.14 -> 5.4.0. Is this a new bug?

**Comment by mkilchhofer** [comment]
@soleares Did you read the upgrading section in charts README?
-> notes on version 5.2 is relevant for you

**Comment by soleares** [comment]
I went through the releases but didn’t make the connection at the time. Thanks for pointing me in the right direction!
