### ISSUE TITLE
image updater chart

### ISSUE THREAD

**Issue by bitgandtter** [argoproj/argo-helm#826]
**Describe the solution you'd like**
I like to use a helm chart for image updater project

**Describe alternatives you've considered**
installing the component using terraform its hard to maintain

**Comment by mkilchhofer** [comment]
Related to:
- https://github.com/argoproj-labs/argocd-image-updater/issues/221
- https://github.com/argoproj/argo-helm/pull/477
- https://github.com/argoproj/argo-helm/pull/475
