### ISSUE TITLE
[argo-cd] Support enabling hostNetwork to Pods

### ISSUE THREAD

**Issue by abdennour** [argoproj/argo-helm#836]
**Is your feature request related to a problem? Please describe.**
In some kubernetes clusters with a specific networking environment, you need to add `hostNetwork: true` to your pods , so pods can connect to internet.
In my case, the initContainer of argocd-repo-server need to download some argo plugins.
Accordingly, i need to run the repo-server pod with `hostNetwork: true`

On the other hand, there is no way to inject this value using the current helm chart

**Describe the solution you'd like**
Support one of the following ( or even both of them):
-  `.Values.global.hostNetwork`
- `.Values. repoServer.hostNetwork`

**Describe alternatives you've considered**
For now, i can patch the deployment of repo-server, but this violate the immutable infra : 

```sh
kubectl patch deployment argocd-repo-server -p '{...... "hostNetwork": true..}'

```
**Additional context**
- affected chart version: 3.9.0  ( git commit 9227990  )

**Comment by qgervacio** [comment]
I don't think this is implemented no?
