### ISSUE TITLE
Allow global labels for Argo-CD chart at pod level

### ISSUE THREAD

**Issue by Karlah28** [argoproj/argo-helm#852]
We would like to have the ability to add custom labels in the deployment files in the argo-cd chart, so we can pass them as parameters at a global level and only having to set once (for example --set global.podLabels="" to set the labels on all pods within the argo-cd chart, instead of defining them individually at the controller, dex, redis level).

We have internal policies that require certain labels are defined on our deployments within Kubernetes. 

The workaround (short term solution) so far has been to copy the argo-helm project and manually update the manifest files and rebuild the charts, in order to make it compliant for deployment on our cluster.

**Comment by vladlosev** [comment]
This repository defines 6 charts. Which one is the issue about?

**Comment by Karlah28** [comment]
We are particularly using argo-cd and argo-rollouts but none of the support this feature.

**Comment by Karlah28** [comment]
Is there a particular reason why each pod within the argo-cd chart has unique label configurations? For example server.podLabels and repoServer.podLabes vs having a global variable ex: global.podLabels to add labels to all pods in the chart? This is more of where my request was going. Wanted to gauge the interest from the argo team from accepting such modification. This would also apply to having a global setting for environmental variables.

**Comment by pdrastil** [comment]
I concur that this feature would be useful. We have similar use case where each pod on our cluster needs to have 2 extra labels for Splunk log collection and it would be helpful to define them just once on global level instead of copy & pasting the value everywhere.
