### ISSUE TITLE
Update CRD's

### ISSUE THREAD

**Issue by atze234** [argoproj/argo-helm#856]
The installed crds with the helm chart are not up2date. 
https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/crds/crd-application.yaml

differs from 
https://github.com/argoproj/argo-cd/blob/master/manifests/crds/application-crd.yaml

I have an issue that i cannot use jqPathExpressions in ignoreDifferences

**Comment by emanuelflp** [comment]
I believe that this occur because master branch in argo-cd repo points to RC(latest) version(2.1) and argo-helm only works with stable versions(2.0.5).

**Comment by atze234** [comment]
Ah sorry...you're right

**Comment by mqxter** [comment]
Hi guys, would appretiate ur help here, 
is there a way to install the helm chart with support for jqPathExpression?
or do i have to install the manifests directly?
