### ISSUE TITLE
Helm charts are pending release

### ISSUE THREAD

**Issue by logicfox** [argoproj/argo-helm#86]
**Describe the bug**
The helm charts are pending release. Argo chart v 0.5.0 was merged to master 15 days ago. Is there a CI pipeline releasing these charts?

**To Reproduce**
1. Add Argo-helm charts repo. `helm repo add argo https://argoproj.github.io/argo-helm`
2. Run `helm update`
3. Install Argo chart. Features like `containerRuntimeExecutor` were merged to master a month ago is not available.

**Expected behavior**
Charts must be released on schedule to mirror chart versions in master.

**Comment by se-jaeger** [comment]
Would be great if someone could release the chart. - Thanks in advance!

**Comment by alexec** [comment]
try now?

**Comment by se-jaeger** [comment]
Works for me, thanks a lot!

**Comment by alexec** [comment]
np
