### ISSUE TITLE
[argo-rollouts] Add ingress support for dashboard

### ISSUE THREAD

**Issue by sergeyshaykhullin** [argoproj/argo-helm#868]
**Is your feature request related to a problem? Please describe.**
argo-rollouts 2.0 released https://github.com/argoproj/argo-helm/releases/tag/argo-rollouts-2.0.0

**Describe the solution you'd like**
Add ingress section to helm chart for dashboard

**Describe alternatives you've considered**

**Additional context**
Reuse existing from argo-cd?

WIP: https://github.com/argoproj/argo-helm/pull/870

**Comment by sergeyshaykhullin** [comment]
@mkilchhofer I opened pr for this

**Comment by mkilchhofer** [comment]
Sorry. I thought that this issue is in the upstream repo here: https://github.com/argoproj/argo-rollouts
From my side I only approve your pr #870 if the upstream project accept an ingress in their kustomize manifests.

**Comment by sergeyshaykhullin** [comment]
Not stale
