### ISSUE TITLE
Argo-Workflows: singleNamespace flag is ignored in workflow-role/rb/sa.yaml because of typo

### ISSUE THREAD

**Issue by SebastianGoeb** [argoproj/argo-helm#876]
### Describe the bug

Hi guys, I noticed a typo in workflow-role/rb/sa.yaml that causes it to not respect the singleNamespace flag. It should be `singleNamespace` but is `singeNamespace` (missing the "l").

I also don't understand the intended effect though. If `singleNamespace=false`, then workflow-role/rb/sa.yaml generate one role/rb/sa for each managed namespace, or for "default" if none are configured. If `singleNamespace=true`, then they generate a role/rb/sa for namespace ""? How does that make sense? Shouldn't it still be the managed namespace, or `{{ .Release.Namespace }}` if not configured? Something like that?

### To Reproduce

1. `helm template argo/argo-workflows --set singleNamespace=false`
1. observe (intended) `namespace: <whatever namespace is currently configured in kubeconfig>`
1. `helm template argo/argo-workflows --set singleNamespace=true`
1. observe (not intended) `namespace: <whatever namespace is currently configured in kubeconfig>`
1. `helm template argo/argo-workflows --set singeNamespace=true`, notice typo "singe"
1. observe (as intended) `namespace: ""`

### Expected behavior

should respect `singleNamespace` flag, but respects `singeNamespace` flag instead (which shouldn't really exist).

**Comment by mkilchhofer** [comment]
Introduced in PR https://github.com/argoproj/argo-helm/pull/824. @reinvantveer could you answer the issue authors question? :-)

**Comment by reinvantveer** [comment]
I must admit that I do not fully comprehend the intended behaviour of the singleNamespace option - it's there not by my design unfortunately. I expected the singleNamespace to be in a specified namespace for the namespace indeed, but it may be for some historical reason.

I take responsibity for the typo, my apologies for this.

**Comment by SebastianGoeb** [comment]
Apologies for the wall of text. It got longer and longer the more I fleshed out my thoughts on the singleNamespace situation. I hope it's reasonably coherent:

> I must admit that I do not fully comprehend the intended behaviour of the singleNamespace option - it's there for some historical reason? I expected the singleNamespace to be in a specified namespace for the release indeed.

So my understanding is that `singleNamespace` more or less translates to argo's own `--namespaced` flag, which switches between a cluster-scoped and namespace-scoped argo installation. Maybe it would be good to rename `singleNamespace` to `namespaced` to clarify that it does this, and also that multiple managed namespaces are allowed. It seems that `--namespaced` and `--managed-namespace` are mostly (or fully?) independent of each other.

Now onto what `--namespace` argo expects and what the current manifests provide:

### For the Server/Controller:
This requires switching from ClusterRole/Binding to Role/Binding, according to [the docs](https://argoproj.github.io/argo-workflows/managed-namespace/), which is exactly what `singleNamespace` does for the server and controller manifests. 

However, it then installs Role, SA, and RB into `{{ .Release.Namespace }}`. Doesn't this mean that the server/controller are only able to manage their own namespace, not another? I haven't tried this out yet (I will shortly), but the way I understand it is that to manage a different namespace you need either

1. a ServiceAccount in the source namespace, a ClusterRole, and a RoleBinding (not Cluster) in each target namespace
2. a ServiceAccount in the source namespace, a Role _and_ RoleBinding in each target namespace

Presumably, without `--namespaced` we should be using the first option, and with `--namespaced` we should be using the second option. I feel like the current singleNamespace setup with Role/Binding _only_ in the source namespace should be broken, but I'll try it out as well and see how it goes.

### For the Workflows:
The executor requires to be able to observe / make changes to its own pod (which is obviously in its own namespace). Here the `singleNamespace` flag does not have the effect of switching between ClusterRole and Role (it's always Role), but between which list of namespaces will receive Roles/Bindings. For `singleNamespace=true` it's the strange `namespace: ""` behavior, and for `singleNamespace=false` it's `[managedNamespace1, ... managedNamespaceN, {{.Release.Namespace}}]`.

Both options seem odd to me. presumably with `--namespaced` it should be

- only `{{ .Release.Namespace }}` (if no managed namespaces are specified)
- only `[managedNamespace1, ... managedNamespaceN]`, but not `{{ .Release.Namespace }}` (if some managed namespaces are specified)

I would expect that, if I configure managed namespaces, then the controller is forbidden from managing Workflows in its own namespace unless the controller-namespace is also explicitly listed as managed (i.e. I would expect the list of managed namespaces to completely describe what the controller can do, instead of having `{{ .Release.Namespace }}` tacked onto the end).

Then without `--namespaced` (cluster scoped argo) I would assume that the controller may manage Workflows anywhere (ClusterRoleBinding). I'm not sure if it's also intended to restrict a cluster-scoped argo installation to only some managed namespaces. As far as I can tell the distinction `--namespaced`, or not, is primarily to distinguish between per-cluster and per-namespace installations or Argo itself, because the latter can't tolerate having ClusterRoles. I wouldn't want to forbid the use case of having a cluster-scoped argo + managed namespaces (say you want 1 argo for all users, but want to forbid installing workflows into kube-system).

### How I Think the Permissions Should Be Structured:

I feel like the permission matrix for server/controller should be something like this:

| | `--namespaced` (namespace-scope) | no `--namespaced` (cluster-scope) |
|---|---|---|
|`managedNamespaced=null`| 1 Role, 1 RoleBinding, both in argo-namespace (argo can only install workflows in its own namespace) | 1 ClusterRole, 1 ClusterRoleBinding (argo can install workflows anywhere) |
|`managedNamespaced=[m1, ... mN]`| N Roles, N RoleBindings, both in [m1, ... mN] (argo can only install workflows in managed namespaces, not even its own unless also explicitly permitted) | 1 ClusterRole, N RoleBindings (role exists globally, but argo can only install workflows in certain namespaces) |

and for workflows themselves (executor, really) it should be something like this:

| | `--namespaced` (namespace-scope) | no `--namespaced` (cluster-scope) |
|---|---|---|
|`managedNamespaced=null`| 1 Role, 1 RoleBinding, 1 ServiceAccount, all in argo-namespace (executor can only manage pods in its own namespace, which is also the argo namespace) | Not sure how this is supposed to work at all. ServiceAccounts are namespace-scoped, so we would have to install a ServiceAccount in every namespace, regardless of whether we use ClusterRole or Role, or elevate the privileges of the default service account. I don't think the list of all namespaces is known in helm, and it could also change afterwards. |
|`managedNamespaced=[m1, ... mN]`| N Roles, N RoleBindings, N ServiceAccounts, all in [m1, ... mN] (executor can only manage pods in its own namespace, which is one of the managed namespaces). The ServiceAccounts should also all have the same name, so argo can assign the same `serviceAccountName` by default and expect it to work in any managed namespace | 1 ClusterRole, N RoleBindings (role exists globally, but workflows can only manage pods in their own namespaces). This should work because the list of managed namespaces is known.|

**Comment by SebastianGoeb** [comment]
Oh and also, I think what is currently called the workflow-sa/rb/role.yaml should be executor-sa/rb/role.yaml, because it's the executor (init, wait) that cares about having `pod/patch` privileges, not usually the main container. Sure, it would be good to provide a default workflow ServiceAccount, but the `pod/patch` privilege listed in workflow-role.yaml is really what the executor expects by default.

The generated ServiceAccount is also not used anywhere. I had to specify
```
controller:
  workflowDefaults:
    spec:
      executor:
        serviceAccountName: <contents of workflow.serviceAccount.name>
```
myself. Maybe there should be 2 sets of SA/R/RB, one for the workflow, one for the executor, with only the executor being optional, and both setting the appropriate properties in workflowDefaults?

**Comment by reinvantveer** [comment]
Wow, thanks for the elaborate explanation @SebastianGoeb, I'll have to let that sink over a night's sleep I think! I'll just open a PR for the typo tomorrow, I think, and leave the restructuring of the RBAC for another time/person.

**Comment by reinvantveer** [comment]
https://github.com/argoproj/argo-helm/pull/881
