### ISSUE TITLE
argocd version v2.1.0 breaks repo-server deployment

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [argoproj/argo-helm#882]
### Describe the bug

There is a change in repo server docker image. Previous to v2.1.0, the entrypoint references a file called uid_entrypoint.sh, which is hardcoded in the argocd [helm chart](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L44). 
New reposerver docker image, changes the arg entrypoint file to [entrypoint.sh](https://github.com/argoproj/argo-cd/blob/master/entrypoint.sh).
This prevents using the reposerver with the v2.1.0 image.

### To Reproduce

change global image tag to v2.1.0

### Expected behavior

repo server should be able to start

**Comment by kjvellajr** [comment]
Related PR for ArgoCD v2.1.0 image: https://github.com/argoproj/argo-cd/pull/6998
