### ISSUE TITLE
[argo-workflows] Argo UI silently defaults to authentication since chart 0.4.0

### ISSUE THREAD

**Issue by reinvantveer** [argoproj/argo-helm#895]
### Describe the bug

Since argo-workflows chart v0.4.0, the user interface to Argo server requires authentication by default (probably since introduction of a 3.0.7+ version of `appVersion`. I think I traced this to commit https://github.com/argoproj/argo-helm/commit/04cbf217aebe9ce3e847b277ecb4c25eb95fbf2d, before then, I was able to access the web UI without any kind of authentication.

Since our gateway handles the authentication part, I have no need for additional authentication layers. But I haven't been able to find the documentation on how to disable something that was disabled by default before.

The behaviour can be disabled by adding
```yaml
server:
  extraArgs:
    - --auth-mode=server
```
to the configured values. If this is no longer the desired default, this should ideally be documented.

### To Reproduce

1. Install argo-workflows helm chart v0.3.0 
2. Visit http://{your_domain/and/any/subpaths}/argo. You have immediate access to the UI
3. Deploy argo-workflows helm chart v0.4.0
4. Visit http://{your_domain/and/any/subpaths}/argo again, you get a login screen (see below)

### Expected behavior

I'd like access to the web UI without authentication please

### Screenshots

![image](https://user-images.githubusercontent.com/9550733/130623570-b0c812a5-6a3d-4b6e-b47d-b7b3ed00c14a.png)

### Additional context
Added the pod manifest as deployed locally on my machine
[argo-server.zip](https://github.com/argoproj/argo-helm/files/7039757/argo-server.zip)

**Comment by reinvantveer** [comment]
Added the pod manifest as deployed locally on my machine
[argo-server.zip](https://github.com/argoproj/argo-helm/files/7039727/argo-server.zip)

**Comment by reinvantveer** [comment]
I'm more than willing to submit a fix for this, but the question is rather what the default behavior of the Argo server application should be

**Comment by yriveiro** [comment]
SSO login implies some external dependencies and non-trivial configurations. If the UI is not exposed in a public network deploy and access Argo should be straightforward.

I expend 2h trying to disable the login once I don't wanna deploy a Keycloak service or configure SSO from my cloud provider to explore Argo.

IMO the default should be no login and for extra security configure SSO or RBAC if available.

**Comment by reinvantveer** [comment]
@mkilchhofer This asks for directions from the argo-helm maintainers I believe. Can you please advise?

**Comment by mkilchhofer** [comment]
Hmm I don't use workflows, therefore I cannot assist here.
But from what I see in their CHANGELOG.md, this is a normal behavior
> ## v3.1.0-rc1 (2021-05-12)
>
 > * (..)
 > * [01d310235](https://github.com/argoproj/argo-workflows/commit/01d310235a9349e6d552c758964cc2250a9e9616) chore(server)!: Required authentication by default. Resolves #5206 (#5211)

xref:
- https://github.com/argoproj/argo-workflows/issues/5206
- https://github.com/argoproj/argo-workflows/pull/5211

**Comment by yriveiro** [comment]
Ok,auth is required as the default, my question is, we authenticate against what? Dex?

**Comment by mkilchhofer** [comment]
Did you read the operator manual? :)
https://argoproj.github.io/argo-workflows/argo-server-auth-mode/

There are 3 modes.
If you want to use the "sso" mode: Yes, dex is supported: https://argoproj.github.io/argo-workflows/argo-server-sso-argocd/

**Comment by yriveiro** [comment]
I see ..., by design, Argo UI doesn't work without an external dependency. 

For people that don't know the tech will be a barrier to play with Argo Workflows out of the box but if Argo's team did the change should be a reasoning behind it.

**Comment by reinvantveer** [comment]
> I see ..., by design, Argo UI doesn't work without an external dependency.
Well, fortunately it does with `--auth-mode=server`, but it I think it calls for just a little more documentation on the helm side.

**Comment by reinvantveer** [comment]
Had some trouble finding the time for this, but here it is

**Comment by reinvantveer** [comment]
For future visitors of this issue: in the linked PR this entry was added to the workflows chart README: https://github.com/argoproj/argo-helm/tree/master/charts/argo-workflows#workflow-server-authentication

**Comment by dberardo-com** [comment]
is there a more explicit answer as of version 3.5 ? 

the question is: IS IT POSSIBLE TO DISABLE AUTH ENTIRELY when in dev mode ?

cheers

**Comment by philippeflorent** [comment]
trying this

```
argo server --auth-mode=server
time="2025-06-04T12:54:09.283Z" level=warning msg="RegisterStackDumper is not supported on windows - noop"
time="2025-06-04T12:54:09.284Z" level=info msg="not enabling pprof debug endpoints"
time="2025-06-04T12:54:09.289Z" level=info authModes="[server]" baseHRef=/ managedNamespace= namespace=default secure=true ssoNamespace=default
time="2025-06-04T12:54:09.290Z" level=info msg="Generating Self Signed TLS Certificates for Secure Mode"
time="2025-06-04T12:54:09.291Z" level=warning msg="You are running without client authentication. Learn how to enable client authentication: https://argo-workflows.readthedocs.io/en/latest/argo-server-auth-mode/"
time="2025-06-04T12:54:09.292Z" level=info msg="SSO disabled"
time="2025-06-04T12:54:09.304Z" level=fatal msg="configmaps \"workflow-controller-configmap\" not found"
```

I get the same page but with an error

![Image](https://github.com/user-attachments/assets/6a24ee84-bcff-4dd7-865e-80519a5b826b)

I created a token
```
kubectl -n argo create token argo-server
```
it works with argo CLI

**but it does not work as I paste it in the web page textarea**

**Comment by philippeflorent** [comment]
ok I found I had to 

kubectl patch deployment argo-server --namespace argo --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/args", "value": ["server","--auth-mode=server"]}]'
