### ISSUE TITLE
[argo-cd] Support Argo CD Core

### ISSUE THREAD

**Issue by donovanmuller** [argoproj/argo-helm#910]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Support for installing [Argo CD Core](https://blog.argoproj.io/argo-cd-v2-1-first-release-candidate-is-ready-c1aab7795638#826b) released in 2.1 via this Chart, would be great.

### Describe alternatives you've considered

There are manual installation options currently as well as Kustomize but would be nice to continue to use this Chart to install Argo CD Core.

### Additional context

None

**Comment by peterwhitesell** [comment]
This would be helpful for me too. Please reopen

**Comment by fhera** [comment]
This would be helpful for me too. Please reopen 2

**Comment by juanmbellini** [comment]
This would be helpful for me too. Please reopen 3

**Comment by patrickshan** [comment]
/reopen
Please
