### ISSUE TITLE
Argo workflow details & logs not coming on UI  for namespaced managed installation

### ISSUE THREAD

**Issue by kriskrishna** [argoproj/argo-helm#940]
### Describe the bug

Argo workflow details & logs not coming on UI  for namespaced managed using manifest fikes based installation, postGres being on backend

### To Reproduce

Manifest file used: postgres based yaml file

### Expected behavior

Workflow details & logs should show up on UI

**Comment by vladlosev** [comment]
We see similar issue when Argo is accessed over a proxy like [Teleport](https://github.com/gravitational/teleport). Teleport is trying to buffer requests and ends up preventing data returned over [eventsource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) requests.

But I don't think the issue resides with the chart.

**Comment by vladlosev** [comment]
The Teleport issue has been fixed in the version [7.2.0](https://github.com/gravitational/teleport/releases/tag/v7.2.0) and [8.0.0](https://github.com/gravitational/teleport/releases/tag/v8.0.0).
