### ISSUE TITLE
Support deploying the Argo CD Extensions Controller with argo-cd

### ISSUE THREAD

**Issue by cooperbenson-qz** [argoproj/argo-helm#971]
### Is your feature request related to a problem?

The [Argo CD Extensions Controller](https://github.com/argoproj-labs/argocd-extensions) provides a method to extend the ArgoCD UI with custom functionality (like a [UI for displaying Argo Rollout states](https://github.com/argoproj-labs/rollout-extension)). However because it requires adding a container to the ArgoCD server deployment, it cannot be installed on Helm installations of ArgoCD.

### Related helm chart

argo-cd

### Describe the solution you'd like

It would be great if there was a value to enable the ArgoCD Extension Controller as a part of the chart

### Describe alternatives you've considered

The official installation process for the ArgoCD Extension Controller requires the use of Kustomize since it needs to patch the argocd-server deployment to add a container.

**Comment by yq314** [comment]
The extension container can be added in `server.extraContainers`, but it requires the crd to be created for it to run successfully. Guess the simplest approach is to add the extension crd into the crds folder

**Comment by mubarak-j** [comment]
Im curious how can i leverage the support for extensions in #1050 to install [rollout-extension](https://github.com/argoproj-labs/rollout-extension)? Do I need to install the extension separately as a [yaml manifest](https://github.com/argoproj-labs/rollout-extension/blob/master/manifests/install.yaml) after deploying argocd-extensions via helm chart?

**Comment by yq314** [comment]
> Im curious how can i leverage the support for extensions in #1050 to install [rollout-extension](https://github.com/argoproj-labs/rollout-extension)? Do I need to install the extension separately as a [yaml manifest](https://github.com/argoproj-labs/rollout-extension/blob/master/manifests/install.yaml) after deploying argocd-extensions via helm chart?

just uncomment [this line](https://github.com/argoproj/argo-helm/blob/7033883914e07f9248eba1cf5a208084394318bc/charts/argo-cd/values.yaml#L1294)  will do
