### ISSUE TITLE
Instillation fails with "Error: no available release name found"

### ISSUE THREAD

**Issue by zmunro** [argoproj/argo-helm#98]
I am following the instillation guide here: [link](https://argoproj.github.io/argo-events/installation/)
But when I run `helm install argo/argo-events` I get the error:
`Error: no available release name found`

**Comment by paguos** [comment]
Maybe an obvious suggestion. But did you run `helm repo add argo https://argoproj.github.io/argo-helm` before?

**Comment by jbehling** [comment]
@zmunro have you had an chance to verify that you have the argo chart repository correctly setup?

**Comment by jbehling** [comment]
Have not heard back from the issue reporter, so closing
