### ISSUE TITLE
When argocd manages argocd argocd-secret is wiped when no webhooks config is provided

### ISSUE THREAD

**Issue by arnarg** [argoproj/argo-helm#99]
**Describe the bug**
When we set up argocd to manage itself through an application with helm it quickly stops working altogether as it wipes out `admin.password`, `admin.passwordMtime` and `server.secretKey` (along with all other keys).

This is because when no webhooks configuration is provided in `values.yaml` [this](https://github.com/argoproj/argo-helm/blob/db30d36879d9122714291ad4f161be9a986fde27/charts/argo-cd/templates/argocd-secret.yaml) template is rendered as this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels: 
    ...
type: Opaque
data:
```

Meaning, here data is null can't be diffed with existing secret by Kubernetes and completely replaces data. Changing it to simply an empty object (`data: {}`) works fine.

For some reason this didn't use to be a problem in version `0.2.2` (Argo-CD 0.12).

A possible workaround is to put fake webhook secret so that data isn't null.

**Expected behavior**
Argocd should take over itself fine.

**Additional context**

**Comment by seanson** [comment]
Resolved in #102
