### ISSUE TITLE
Argo Workflows controller RBAC missing workflowtasksets resources

### ISSUE THREAD

**Issue by wsams** [argoproj/argo-helm#997]
### Describe the bug

The workflow controller when run at the cluster scope is missing the ability to watch or list `WorkflowTaskSets`. This may also be the case namespaced.

### Related helm chart

argo-workflows

### To Reproduce

Deploy the latest v0.8.0 Helm Chart for Argo Workflows. View the logs of the workflows controller.

### Expected behavior

The workflow controller can watch `WorkflowTaskSets` as well as list them. I would expect to see `workflowtasksets` and possibly `workflowtasksets/finalizers` in `charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml`.

### Additional context

Here is one of the lines in the workflow controller logs:

```
pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/reflector.go:167: Failed to watch *v1alpha1.WorkflowTaskSet: failed to list *v1alpha1.WorkflowTaskSet: workflowtasksets.argoproj.io is forbidden:  │
│ User "system:serviceaccount:argons:argo-workflows-tst-workflow-controller" cannot list resource "workflowtasksets" in API group "argoproj.io" at the cluster scope
```

Note, my Helm release is named `argo-workflows-tst`.

**Comment by MichielDeMey** [comment]
Good catch, currently running into the same RBAC issue. 👍
